#!/usr/bin/env python3
import os
import re

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "tab_erf.rs")).read()


def table(name):
    m = re.search(r"static %s: [^=]*= \[(.*?)\n\];" % name, src, re.S)
    return m.group(1)


def pairs(body):
    return [float(a) for a, _ in re.findall(r"\[([-0-9.e+]+), ([-0-9.e+]+)\]", body)]


e0 = pairs(table("ERF_E0"))
q = pairs(table("ERF_Q"))
off = [int(x) for x in re.search(r"static ERF_OFF: [^=]*= \[([^\]]*)\]", src).group(1).split(",") if x.strip()]
assert len(e0) == 97 and len(off) == 98
out = [
    "//! Compact erf rows for the binary32 function (generated by gen_compact.py from tab_erf.rs; do not edit).",
    "#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]",
    "",
    "/// [erf(k/16) high part, q_0 .. q_7 high parts]: erf(k/16 + h) = row[0] + h (row[1] + h row[2] + ...).",
    "pub(super) static ERF8: [[f64; 9]; 97] = [",
]
for k in range(97):
    row = [e0[k]] + [q[off[k] + i] if off[k] + i < off[k + 1] else 0.0 for i in range(8)]
    out.append("    [" + ", ".join(repr(v) for v in row) + "],")
out.append("];")
open(os.path.join(here, "tab_erf8.rs"), "w").write("\n".join(out) + "\n")


src = open(os.path.join(here, "tab_gamma.rs")).read()
f0 = pairs(table("LG_F0"))
q = pairs(table("LG_Q"))
off = [int(x) for x in re.search(r"static LG_OFF: [^=]*= \[([^\]]*)\]", src).group(1).split(",") if x.strip()]
assert len(f0) == 125 and len(off) == 126
out = [
    "//! Compact lgamma rows for the binary32 function (generated by gen_compact.py from tab_gamma.rs; do not edit).",
    "#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]",
    "",
    "/// [F0 high part, q_0 .. q_11 high parts] of node k = i + 4 (x0 = k/8): lgamma(x0 + h) = row[0] + h (row[1] + h row[2] + ...).",
    "pub(super) static LG12: [[f64; 13]; 125] = [",
]
for i in range(125):
    row = [f0[i]] + [q[off[i] + j] if off[i] + j < off[i + 1] else 0.0 for j in range(12)]
    out.append("    [" + ", ".join(repr(v) for v in row) + "],")
out.append("];")
open(os.path.join(here, "tab_lg12.rs"), "w").write("\n".join(out) + "\n")
