#!/usr/bin/env python3
import os
import re
from fractions import Fraction
from math import comb

ROWS = 51
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "tab_bessel.rs")).read()


def coeffs(name):
    m = re.search(r"pub\(super\) static " + name + r": \[\[f64; 2\]; \d+\] = \[(.*?)\n\];", src, re.S)
    pairs = re.findall(r"\[([^\],]+), ([^\]]+)\]", m.group(1))
    return [Fraction(float(h)) + Fraction(float(l)) for h, l in pairs]


def lit(v):
    return repr(float(v))


def row(a, j):
    c = Fraction(j, 128)
    g = [sum(comb(m, k) * a[m] * c ** (m - k) for m in range(k, len(a))) for k in range(6)]
    out = []
    for k in (0, 1):
        h = Fraction(float(g[k]))
        out += [lit(h), lit(g[k] - h)]
    out += [lit(g[k]) for k in range(2, 6)]
    return "[" + ", ".join(out) + "]"


print("// Generated by gen_yrows.py; do not edit.")
for name, tab in (("Y0E_ROWS", "Y0_E"), ("Y1E_ROWS", "Y1_E")):
    print()
    print(f"/// E(u) Taylor rows of {tab} at u = j/128, j = 0..={ROWS - 1}: [g0 hi, g0 lo, g1 hi, g1 lo, g2, g3, g4, g5].")
    print(f"pub const {name}: [[f64; 8]; {ROWS}] = [")
    a = coeffs(tab)
    for j in range(ROWS):
        print("    " + row(a, j) + ",")
    print("];")
