#!/usr/bin/env python3
import math
import os
import sys
from fractions import Fraction as Fr

here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, here)
import mp
import cheb

DEG = 8
W = Fr(1, 32)


def gamma(x):
    return mp.fn("gamma", x)


rows = []
worst = 0.0
for k in range(33):
    x0 = 1 + Fr(k, 16)
    c = [float(v) for v in cheb.cheb_fit(gamma, x0, W, DEG)]
    for j in range(65):
        h = -W + 2 * W * j / 64
        v = sum(Fr(c[i]) * h**i for i in range(DEG + 1))
        worst = max(worst, float(abs(v / gamma(x0 + h) - 1)))
    rows.append(c)
print("worst relative error of the rows: 2^%.1f" % math.log2(worst), file=sys.stderr)
assert worst < 2.0**-52

out = [
    "//! Gamma rows for the binary32 tgammaf (generated by gen_gamma16.py; do not edit).",
    "#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]",
    "",
    "/// Row k: Gamma(1 + k/16 + h) = sum of row[i] h^i for |h| <= 1/32 (relative error below 2^-52).",
    "pub(super) static GAMMA16: [[f64; %d]; 33] = [" % (DEG + 1),
]
for c in rows:
    out.append("    [" + ", ".join(repr(v) for v in c) + "],")
out.append("];")
open(os.path.join(here, "tab_gamma16.rs"), "w").write("\n".join(out) + "\n")
