#!/usr/bin/env python3
from fractions import Fraction
from math import comb, factorial

ROWS = 51
M = 60


def series(kind):
    if kind == 0:
        return [Fraction((-1) ** m, factorial(m) ** 2) for m in range(M)]
    return [Fraction((-1) ** m, factorial(m) * factorial(m + 1)) for m in range(M)]


def taylor(a, c, k):
    return sum(comb(m, k) * a[m] * c ** (m - k) for m in range(k, M))


def lit(v):
    return repr(float(v))


def row(a, j):
    c = Fraction(j, 128)
    g = [taylor(a, c, k) for k in range(6)]
    out = []
    for k in (0, 1):
        h = Fraction(float(g[k]))
        out += [lit(h), lit(g[k] - h)]
    out += [lit(g[k]) for k in range(2, 6)]
    return "[" + ", ".join(out) + "]"


print("// Generated by gen_jrows.py; do not edit.")
for kind, name in ((0, "J0_ROWS"), (1, "J1_ROWS")):
    print()
    print(f"/// {'J' if kind == 0 else 'K'}(u) Taylor rows at u = j/128, j = 0..={ROWS - 1}: [g0 hi, g0 lo, g1 hi, g1 lo, g2, g3, g4, g5].")
    print(f"pub const {name}: [[f64; 8]; {ROWS}] = [")
    a = series(kind)
    for j in range(ROWS):
        print("    " + row(a, j) + ",")
    print("];")
