#!/usr/bin/env python3
from fractions import Fraction

import mp
from math import comb, factorial

ROWS = 51
M = 60


TWO_OVER_PI = 2 / mp.fn("const_pi")


def series(kind):
    if kind == 0:
        return [TWO_OVER_PI * Fraction((-1) ** m, factorial(m) ** 2) for m in range(M)]
    return [TWO_OVER_PI * Fraction((-1) ** m, factorial(m) * factorial(m + 1)) for m in range(M)]


def taylor(a, c, k):
    return sum(comb(m, k) * a[m] * c ** (m - k) for m in range(k, M))


def lit(v):
    return repr(float(v))


def row(a, j):
    c = Fraction(j, 128)
    g = [taylor(a, c, k) for k in range(7)]
    out = []
    for k in (0, 1):
        h = Fraction(float(g[k]))
        out += [lit(h), lit(g[k] - h)]
    out += [lit(g[k]) for k in range(2, 7)]
    return "[" + ", ".join(out) + "]"


def coeffs(kind, n):
    out = []
    for m in range(n):
        c = Fraction((-1) ** m, 4 ** m * factorial(m) * factorial(m + kind))
        h = Fraction(float(c))
        out.append(f"[{lit(h)}, {lit(c - h)}]")
    return out


print("// Generated by gen_jrows.py; do not edit.")
for kind, name in ((0, "J0P_ROWS"), (1, "J1P_ROWS")):
    print()
    print(f"/// (2/pi) {'J' if kind == 0 else 'K'}(u) Taylor rows at u = j/128, j = 0..={ROWS - 1}: [g0 hi, g0 lo, g1 hi, g1 lo, g2, g3, g4, g5, g6].")
    print(f"pub const {name}: [[f64; 9]; {ROWS}] = [")
    a = series(kind)
    for j in range(ROWS):
        print("    " + row(a, j) + ",")
    print("];")

for kind, name, n in ((0, "JS0_C", 12), (1, "JS1_C", 11)):
    print()
    print(f"/// The power series of {'j0(x)' if kind == 0 else '2 j1(x) / x'} in w = x^2, m = 0..{n - 1}: [hi, lo] of (-1)^m / (4^m m! (m + {kind})!).")
    print(f"pub const {name}: [[f64; 2]; {n}] = [")
    for c in coeffs(kind, n):
        print("    " + c + ",")
    print("];")
