#!/usr/bin/env python3
import sys
import os
from fractions import Fraction

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mp
import cheb

HERE = os.path.dirname(os.path.abspath(__file__))
TOL = Fraction(1, 2**113)


def lit(v):
    r = repr(float(v))
    if r in ("inf", "-inf", "nan"):
        raise ValueError(v)
    return r


def dd(q):
    hi, lo = mp.to_dd(q)
    return "[%s, %s]" % (lit(hi), lit(lo))


def td(q):
    hi, mid, lo = mp.to_td(q)
    return "[%s, %s, %s]" % (lit(hi), lit(mid), lit(lo))


def const_pi():
    p = mp.MP()
    mp._lib.mpfr_const_pi(p.p(), mp.RNDN)
    return p.frac()


def const_ln2():
    p = mp.MP()
    mp._lib.mpfr_const_log2(p.p(), mp.RNDN)
    return p.frac()


def const_euler():
    p = mp.MP()
    mp._lib.mpfr_const_euler(p.p(), mp.RNDN)
    return p.frac()


def header(name, what):
    return "//! %s (generated by gen_tables.py %s; do not edit).\n#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]\n\n" % (what, name)


def array(name, rows, doc, ty="[f64; 2]"):
    s = "/// %s\npub(super) static %s: [%s; %d] = [\n" % (doc, name, ty, len(rows))
    for r in rows:
        s += "    %s,\n" % r
    return s + "];\n\n"


def bernoulli(n):
    from math import comb
    b = [Fraction(0)] * (n + 1)
    b[0] = Fraction(1)
    for m in range(1, n + 1):
        b[m] = -sum(comb(m + 1, k) * b[k] for k in range(m)) / (m + 1)
    return b


def gen_base():
    out = header("base", "Base constants of the special functions")
    pi = const_pi()
    ln2 = const_ln2()
    rows = []
    for j in range(64):
        rows.append(dd(mp.fn("exp2", Fraction(j, 64))))
    out += array("EXP2_TAB", rows, "2^(j/64), j = 0..63, as double-double.")
    v = ln2 / 64
    c1 = Fraction(round(v * 2**(36 + 6 + 1)), 2**(36 + 6 + 1))
    r = v - c1
    c2 = Fraction(float(r))
    c3 = float(r - c2)
    out += "pub(super) const LN2_64_C1: f64 = %s;\npub(super) const LN2_64_C2: f64 = %s;\npub(super) const LN2_64_C3: f64 = %s;\n" % (lit(c1), lit(c2), lit(c3))
    out += "pub(super) const INV_LN2_64: f64 = %s; // 64 / ln 2\n" % lit(Fraction(64) / ln2)
    out += "pub(super) const LN2_DD: [f64; 2] = %s;\n" % dd(ln2)
    out += "pub(super) const PI_DD: [f64; 2] = %s;\n" % dd(pi)
    out += "pub(super) const LN_PI_DD: [f64; 2] = %s;\n" % dd(mp.fn("log", pi))
    out += "pub(super) const INV_PI_DD: [f64; 2] = %s;\n" % dd(1 / pi)
    twopi = 2 * pi
    out += "pub(super) const HALF_LN_2PI_DD: [f64; 2] = %s;\n" % dd(mp.fn("log", twopi) / 2)
    sq = mp.fn("sqrt", pi)
    out += "pub(super) const TWO_OVER_SQRT_PI_DD: [f64; 2] = %s;\n" % dd(2 / sq)
    out += "pub(super) const EULER_DD: [f64; 2] = %s;\n\n" % dd(const_euler())
    f = [1]
    for n in range(1, 60):
        f.append(f[-1] * n)
    out += array("INV_FACT", [dd(Fraction(1, f[n])) for n in range(14)], "1/n!, n = 0..13.")
    rows = []
    for k in range(0, 24):
        rows.append(dd(Fraction((-1) ** k) * pi ** (2 * k) / f[2 * k + 1]))
    out += array("SINPI_C", rows, "Coefficients of sin(pi t)/(pi t) as a series in t^2: (-1)^k pi^(2k)/(2k+1)!.")
    B = bernoulli(60)
    rows = []
    for k in range(1, 25):
        rows.append(dd(B[2 * k] / (2 * k * (2 * k - 1))))
    out += array("STIRLING_C", rows, "B_2k / (2k (2k-1)), k = 1..24.")
    fa = [1]
    for n in range(1, 171):
        fa.append(fa[-1] * n)
    out += array("FACT_DD", [dd(Fraction(x)) for x in fa], "n!, n = 0..170 as double-double (exact up to 22!).")
    open(os.path.join(HERE, "tab_base.rs"), "w").write(out)


def sqrtpi():
    return mp.fn("sqrt", const_pi())


def gen_erf():
    out = header("erf", "erf / erfc node tables")
    sp = sqrtpi()
    W = Fraction(1, 32)
    rows_c = []
    off = [0]
    e0s = []
    ec0s = []
    degs = []
    for k in range(0, 97):
        x0 = Fraction(k, 16)
        e0 = mp.fn("erf", x0)
        ec0 = mp.fn("erfc", x0)
        d0 = 2 * mp.fn("exp", -x0 * x0) / sp

        def g(x, x0=x0, e0=e0, d0=d0):
            h = x - x0
            if h == 0:
                return d0
            return (mp.fn("erf", x) - e0) / h

        best = None
        for n in range(6, 40):
            c = cheb.cheb_fit(g, x0, W, n)
            worst = Fraction(0)
            for i in range(0, 33):
                h = W * (Fraction(2 * i, 32) - 1) + Fraction(1, 10**12)
                gv = g(x0 + h)
                e = abs(cheb.horner(c, h) - gv) / abs(gv)
                worst = max(worst, e)
            if worst < TOL:
                best = c
                break
        assert best is not None, k
        degs.append(len(best) - 1)
        for a in best:
            rows_c.append(dd(a))
        off.append(len(rows_c))
        e0s.append(dd(e0))
        ec0s.append(dd(ec0))
        print("erf node", k, "degree", len(best) - 1, file=sys.stderr)
    out += "/// Nodes: x0 = k/16 for k = 0..96; erf(x0 + h) = E0 + h q(h), erfc = EC0 - h q(h), |h| <= 1/32.\n"
    out += array("ERF_E0", e0s, "erf(k/16).")
    out += array("ERF_EC0", ec0s, "erfc(k/16).")
    out += array("ERF_Q", rows_c, "Coefficients q_0..q_n of node k at ERF_OFF[k]..ERF_OFF[k+1].")
    out += "pub(super) static ERF_OFF: [u16; %d] = %s;\n\n" % (len(off), "[" + ", ".join(map(str, off)) + "]")
    W2 = Fraction(1, 4)
    rows_c = []
    off = [0]
    for j in range(0, 44):
        x0 = 6 + Fraction(j, 2)

        def R(x):
            return mp.fn("erfc", x) * mp.fn("exp", x * x)

        best = None
        for n in range(8, 40):
            c = cheb.cheb_fit(R, x0, W2, n)
            worst = Fraction(0)
            for i in range(0, 33):
                h = W2 * (Fraction(2 * i, 32) - 1) + Fraction(1, 10**12)
                gv = R(x0 + h)
                e = abs(cheb.horner(c, h) - gv) / abs(gv)
                worst = max(worst, e)
            if worst < TOL:
                best = c
                break
        assert best is not None, j
        for a in best:
            rows_c.append(dd(a))
        off.append(len(rows_c))
        print("erfc tail node", j, "degree", len(best) - 1, file=sys.stderr)
    out += array("ERFC_TAIL_R", rows_c, "R(x) = erfc(x) exp(x^2) on nodes 6 + j/2: coefficients in h = x - x0.")
    out += "pub(super) static ERFC_TAIL_OFF: [u16; %d] = %s;\n\n" % (len(off), "[" + ", ".join(map(str, off)) + "]")
    open(os.path.join(HERE, "tab_erf.rs"), "w").write(out)


def lgam(x):
    return mp.lgamma(x)[0]


def fit_poly(g, x0, w, nmin, nmax=60, pts=33):
    for n in range(nmin, nmax):
        c = cheb.cheb_fit(g, x0, w, n)
        worst = Fraction(0)
        for i in range(0, pts):
            h = w * (Fraction(2 * i, pts - 1) - 1) + w * Fraction(1, 10**6)
            gv = g(x0 + h)
            e = abs(cheb.horner(c, h) - gv) / abs(gv)
            worst = max(worst, e)
        if worst < TOL:
            return c
    raise RuntimeError("no fit")


def gen_gamma():
    out = header("gamma", "lgamma node tables and negative-side root windows")
    W = Fraction(1, 16)
    f0s = []
    rows = []
    off = [0]
    for k in range(4, 129):
        c = Fraction(k, 8)
        f0 = lgam(c)
        psi = mp.fn("digamma", c)

        def g(x, c=c, f0=f0, psi=psi):
            h = x - c
            if h == 0:
                return psi
            return (lgam(x) - f0) / h

        best = fit_poly(g, c, W, 8)
        for a in best:
            rows.append(dd(a))
        off.append(len(rows))
        f0s.append(dd(f0))
        print("lgamma node", k, "degree", len(best) - 1, file=sys.stderr)
    out += array("LG_F0", f0s, "lgamma(k/8), k = 4..128.")
    out += array("LG_Q", rows, "Coefficients q_0..q_n of node k (index k-4) at LG_OFF[k-4]..LG_OFF[k-3]: lgamma(k/8 + h) = F0 + h q(h), |h| <= 1/16.")
    out += "pub(super) static LG_OFF: [u16; %d] = %s;\n\n" % (len(off), "[" + ", ".join(map(str, off)) + "]")
    roots = []
    for n in range(2, 21):
        for side in (-1, +1):
            if side == +1 and n < 3:
                continue
            lo = Fraction(1, 2**200)
            hi = Fraction(1, 2)
            def val(u):
                return lgam(-n + side * (-u) if False else (-n - u if side < 0 else -n + u))
            assert val(lo) > 0 and val(hi) < 0, (n, side)
            for _ in range(260):
                mid = (lo + hi) / 2
                if val(mid) > 0:
                    lo = mid
                else:
                    hi = mid
            u0 = (lo + hi) / 2
            r = -n - u0 if side < 0 else -n + u0
            roots.append((r, u0))
    roots.sort(key=lambda t: -t[0])
    rr = []
    ws = []
    rows = []
    off = [0]
    for (r, u0) in roots:
        Wd = min(Fraction(1, 2**14), u0 / 512)
        e = 0
        while Fraction(1, 2**(e + 1)) > Wd:
            e += 1
        Wd = Fraction(1, 2**(e + 1))
        psi = mp.fn("digamma", r)

        def g(x, r=r, psi=psi):
            h = x - r
            if h == 0:
                return psi
            return lgam(x) / h

        best = fit_poly(g, r, Wd, 4)
        for a in best:
            rows.append(dd(a))
        off.append(len(rows))
        rr.append(td(r))
        ws.append(lit(Wd))
        print("root", float(r), "u0", float(u0), "W", float(Wd), "degree", len(best) - 1, file=sys.stderr)
    out += array("LG_ROOT_R", rr, "Roots of lgamma below -2 (descending) as triple-doubles.", "[f64; 3]")
    out += array("LG_ROOT_W", ws, "Half-width of the window around each root.", "f64")
    out += array("LG_ROOT_C", rows, "Per root: coefficients s_0..s_n with lgamma(r + d) = d s(d), |d| <= W.")
    out += "pub(super) static LG_ROOT_OFF: [u16; %d] = %s;\n\n" % (len(off), "[" + ", ".join(map(str, off)) + "]")
    open(os.path.join(HERE, "tab_gamma.rs"), "w").write(out)


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "base"
    {"base": gen_base, "erf": gen_erf, "gamma": gen_gamma}[which]()
