use core::ffi::{c_int, c_ushort};
use rusty_libc_core::messages;

#[unsafe(no_mangle)]
pub extern "C" fn __isctype(c: c_int, mask: c_int) -> c_int {
    c_int::from(rusty_libc_ctype::class_of(c)) & mask
}

#[unsafe(no_mangle)]
pub static __fpu_control: c_ushort = 0x037f;

#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static _sys_errlist: messages::ErrPtrs = messages::err_ptrs();
#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static sys_errlist: messages::ErrPtrs = messages::err_ptrs();
#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static _sys_nerr: c_int = 135;
#[allow(non_upper_case_globals)]
#[unsafe(no_mangle)]
pub static sys_nerr: c_int = 135;
#[cfg(feature = "shared")]
core::arch::global_asm!(
    ".text",
    ".globl __newlocale",
    ".type __newlocale, @function",
    "__newlocale:",
    "jmp newlocale",
    ".globl __duplocale",
    ".type __duplocale, @function",
    "__duplocale:",
    "jmp duplocale",
    ".globl __freelocale",
    ".type __freelocale, @function",
    "__freelocale:",
    "jmp freelocale",
    ".globl __nl_langinfo_l",
    ".type __nl_langinfo_l, @function",
    "__nl_langinfo_l:",
    "jmp nl_langinfo_l",
    ".globl __strcoll_l",
    ".type __strcoll_l, @function",
    "__strcoll_l:",
    "jmp strcoll_l",
    ".globl __strxfrm_l",
    ".type __strxfrm_l, @function",
    "__strxfrm_l:",
    "jmp strxfrm_l",
    ".globl __strtod_l",
    ".type __strtod_l, @function",
    "__strtod_l:",
    "jmp strtod_l",
    ".globl __strtof_l",
    ".type __strtof_l, @function",
    "__strtof_l:",
    "jmp strtof_l",
    ".globl __strtold_l",
    ".type __strtold_l, @function",
    "__strtold_l:",
    "jmp strtold_l",
    ".globl __strtol_l",
    ".type __strtol_l, @function",
    "__strtol_l:",
    "jmp strtol_l",
    ".globl __strtoll_l",
    ".type __strtoll_l, @function",
    "__strtoll_l:",
    "jmp strtoll_l",
    ".globl __strtoul_l",
    ".type __strtoul_l, @function",
    "__strtoul_l:",
    "jmp strtoul_l",
    ".globl __strtoull_l",
    ".type __strtoull_l, @function",
    "__strtoull_l:",
    "jmp strtoull_l",
    ".globl __towlower_l",
    ".type __towlower_l, @function",
    "__towlower_l:",
    "jmp towlower_l",
    ".globl __towupper_l",
    ".type __towupper_l, @function",
    "__towupper_l:",
    "jmp towupper_l",
    ".globl __iswctype_l",
    ".type __iswctype_l, @function",
    "__iswctype_l:",
    "jmp iswctype_l",
    ".globl __wctype_l",
    ".type __wctype_l, @function",
    "__wctype_l:",
    "jmp wctype_l",
    ".globl __wcscoll_l",
    ".type __wcscoll_l, @function",
    "__wcscoll_l:",
    "jmp wcscoll_l",
    ".globl __wcsxfrm_l",
    ".type __wcsxfrm_l, @function",
    "__wcsxfrm_l:",
    "jmp wcsxfrm_l",
    ".globl __strftime_l",
    ".type __strftime_l, @function",
    "__strftime_l:",
    "jmp strftime_l",
    ".globl __wcsftime_l",
    ".type __wcsftime_l, @function",
    "__wcsftime_l:",
    "jmp wcsftime_l",
    ".globl __wctrans_l",
    ".type __wctrans_l, @function",
    "__wctrans_l:",
    "jmp wctrans_l",
    ".globl __towctrans_l",
    ".type __towctrans_l, @function",
    "__towctrans_l:",
    "jmp towctrans_l",
    ".globl __strcasecmp_l",
    ".type __strcasecmp_l, @function",
    "__strcasecmp_l:",
    "jmp strcasecmp_l",
    ".globl __strncasecmp_l",
    ".type __strncasecmp_l, @function",
    "__strncasecmp_l:",
    "jmp strncasecmp_l",
    ".globl __wcscasecmp_l",
    ".type __wcscasecmp_l, @function",
    "__wcscasecmp_l:",
    "jmp wcscasecmp_l",
    ".globl __wcsncasecmp_l",
    ".type __wcsncasecmp_l, @function",
    "__wcsncasecmp_l:",
    "jmp wcsncasecmp_l",
    ".globl __wcstod_l",
    ".type __wcstod_l, @function",
    "__wcstod_l:",
    "jmp wcstod_l",
    ".globl __wcstof_l",
    ".type __wcstof_l, @function",
    "__wcstof_l:",
    "jmp wcstof_l",
    ".globl __wcstold_l",
    ".type __wcstold_l, @function",
    "__wcstold_l:",
    "jmp wcstold_l",
    ".globl __wcstol_l",
    ".type __wcstol_l, @function",
    "__wcstol_l:",
    "jmp wcstol_l",
    ".globl __wcstoll_l",
    ".type __wcstoll_l, @function",
    "__wcstoll_l:",
    "jmp wcstoll_l",
    ".globl __wcstoul_l",
    ".type __wcstoul_l, @function",
    "__wcstoul_l:",
    "jmp wcstoul_l",
    ".globl __wcstoull_l",
    ".type __wcstoull_l, @function",
    "__wcstoull_l:",
    "jmp wcstoull_l",
);

#[unsafe(no_mangle)]
pub extern "C" fn __cxa_at_quick_exit(func: Option<extern "C" fn()>, _dso: *mut core::ffi::c_void) -> c_int {
    rusty_libc_stdlib::misc::at_quick_exit(func)
}

