#![allow(missing_docs)]

core::arch::global_asm!(
    ".pushsection .rodata.rl_compat,\"a\",@progbits",
    ".Lrl_op0: .asciz \"QUERY\"",
    ".Lrl_op1: .asciz \"IQUERY\"",
    ".Lrl_op2: .asciz \"CQUERYM\"",
    ".Lrl_op3: .asciz \"CQUERYU\"",
    ".Lrl_op4: .asciz \"NOTIFY\"",
    ".Lrl_op5: .asciz \"UPDATE\"",
    ".Lrl_op6: .asciz \"6\"",
    ".Lrl_op7: .asciz \"7\"",
    ".Lrl_op8: .asciz \"8\"",
    ".Lrl_op9: .asciz \"9\"",
    ".Lrl_op10: .asciz \"10\"",
    ".Lrl_op11: .asciz \"11\"",
    ".Lrl_op12: .asciz \"12\"",
    ".Lrl_op13: .asciz \"13\"",
    ".Lrl_op14: .asciz \"ZONEINIT\"",
    ".Lrl_op15: .asciz \"ZONEREF\"",
    ".popsection",
    ".pushsection .data.rl_compat,\"aw\",@progbits",
    ".globl __rl_cd__res_opcodes",
    ".type __rl_cd__res_opcodes, @object",
    ".size __rl_cd__res_opcodes, 128",
    ".p2align 4",
    "__rl_cd__res_opcodes:",
    ".quad .Lrl_op0, .Lrl_op1, .Lrl_op2, .Lrl_op3, .Lrl_op4, .Lrl_op5, .Lrl_op6, .Lrl_op7",
    ".quad .Lrl_op8, .Lrl_op9, .Lrl_op10, .Lrl_op11, .Lrl_op12, .Lrl_op13, .Lrl_op14, .Lrl_op15",
    ".symver __rl_cd__res_opcodes, _res_opcodes@GLIBC_2.2.5",
    ".popsection",
    ".pushsection .text.rl_compat,\"ax\",@progbits",
    ".p2align 3",
    ".globl __rl_cs___p_secstodate",
    "__rl_cs___p_secstodate:",
    "jmp __p_secstodate",
    ".symver __rl_cs___p_secstodate, __p_secstodate@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs__sethtent",
    "__rl_cs__sethtent:",
    "jmp __rl_sethtent",
    ".symver __rl_cs__sethtent, _sethtent@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs__gethtent",
    "__rl_cs__gethtent:",
    "jmp __rl_gethtent",
    ".symver __rl_cs__gethtent, _gethtent@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs__gethtbyname",
    "__rl_cs__gethtbyname:",
    "jmp __rl_gethtbyname",
    ".symver __rl_cs__gethtbyname, _gethtbyname@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs__gethtbyname2",
    "__rl_cs__gethtbyname2:",
    "jmp __rl_gethtbyname2",
    ".symver __rl_cs__gethtbyname2, _gethtbyname2@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs__gethtbyaddr",
    "__rl_cs__gethtbyaddr:",
    "jmp __rl_gethtbyaddr",
    ".symver __rl_cs__gethtbyaddr, _gethtbyaddr@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs_res_gethostbyname",
    "__rl_cs_res_gethostbyname:",
    "jmp __rl_res_gethostbyname",
    ".symver __rl_cs_res_gethostbyname, res_gethostbyname@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs_res_gethostbyname2",
    "__rl_cs_res_gethostbyname2:",
    "jmp __rl_res_gethostbyname2",
    ".symver __rl_cs_res_gethostbyname2, res_gethostbyname2@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs_res_gethostbyaddr",
    "__rl_cs_res_gethostbyaddr:",
    "jmp __rl_res_gethostbyaddr",
    ".symver __rl_cs_res_gethostbyaddr, res_gethostbyaddr@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs_res_send_setqhook",
    "__rl_cs_res_send_setqhook:",
    "jmp __rl_res_send_setqhook",
    ".symver __rl_cs_res_send_setqhook, res_send_setqhook@GLIBC_2.2.5",
    ".p2align 3",
    ".globl __rl_cs_res_send_setrhook",
    "__rl_cs_res_send_setrhook:",
    "jmp __rl_res_send_setrhook",
    ".symver __rl_cs_res_send_setrhook, res_send_setrhook@GLIBC_2.2.5",
    ".popsection",
);
