#![allow(missing_docs)]

core::arch::global_asm!(
    ".pushsection .text.rl_compat,\"ax\",@progbits",
    ".p2align 3",
    ".globl __adjtimex",
    ".type __adjtimex, @function",
    "__adjtimex:",
    "jmp adjtimex",
    ".p2align 3",
    ".globl __arch_prctl",
    ".type __arch_prctl, @function",
    "__arch_prctl:",
    "jmp arch_prctl",
    ".p2align 3",
    ".globl __bzero",
    ".type __bzero, @function",
    "__bzero:",
    "jmp bzero",
    ".p2align 3",
    ".globl __clone",
    ".type __clone, @function",
    "__clone:",
    "jmp clone",
    ".p2align 3",
    ".globl __close",
    ".type __close, @function",
    "__close:",
    "jmp close",
    ".p2align 3",
    ".globl __connect",
    ".type __connect, @function",
    "__connect:",
    "jmp connect",
    ".p2align 3",
    ".globl __dup2",
    ".type __dup2, @function",
    "__dup2:",
    "jmp dup2",
    ".p2align 3",
    ".globl __endmntent",
    ".type __endmntent, @function",
    "__endmntent:",
    "jmp endmntent",
    ".p2align 3",
    ".globl __fcntl",
    ".type __fcntl, @function",
    "__fcntl:",
    "jmp fcntl",
    ".p2align 3",
    ".globl __ffs",
    ".type __ffs, @function",
    "__ffs:",
    "jmp ffs",
    ".p2align 3",
    ".globl __fork",
    ".type __fork, @function",
    "__fork:",
    "jmp fork",
    ".p2align 3",
    ".globl __getmntent_r",
    ".type __getmntent_r, @function",
    "__getmntent_r:",
    "jmp getmntent_r",
    ".p2align 3",
    ".globl __getpid",
    ".type __getpid, @function",
    "__getpid:",
    "jmp getpid",
    ".p2align 3",
    ".globl __gettimeofday",
    ".type __gettimeofday, @function",
    "__gettimeofday:",
    "jmp gettimeofday",
    ".p2align 3",
    ".globl __gmtime_r",
    ".type __gmtime_r, @function",
    "__gmtime_r:",
    "jmp gmtime_r",
    ".p2align 3",
    ".globl __iswalnum_l",
    ".type __iswalnum_l, @function",
    "__iswalnum_l:",
    "jmp iswalnum_l",
    ".p2align 3",
    ".globl __iswalpha_l",
    ".type __iswalpha_l, @function",
    "__iswalpha_l:",
    "jmp iswalpha_l",
    ".p2align 3",
    ".globl __iswblank_l",
    ".type __iswblank_l, @function",
    "__iswblank_l:",
    "jmp iswblank_l",
    ".p2align 3",
    ".globl __iswcntrl_l",
    ".type __iswcntrl_l, @function",
    "__iswcntrl_l:",
    "jmp iswcntrl_l",
    ".p2align 3",
    ".globl __iswctype",
    ".type __iswctype, @function",
    "__iswctype:",
    "jmp iswctype",
    ".p2align 3",
    ".globl __iswdigit_l",
    ".type __iswdigit_l, @function",
    "__iswdigit_l:",
    "jmp iswdigit_l",
    ".p2align 3",
    ".globl __iswgraph_l",
    ".type __iswgraph_l, @function",
    "__iswgraph_l:",
    "jmp iswgraph_l",
    ".p2align 3",
    ".globl __iswlower_l",
    ".type __iswlower_l, @function",
    "__iswlower_l:",
    "jmp iswlower_l",
    ".p2align 3",
    ".globl __iswprint_l",
    ".type __iswprint_l, @function",
    "__iswprint_l:",
    "jmp iswprint_l",
    ".p2align 3",
    ".globl __iswpunct_l",
    ".type __iswpunct_l, @function",
    "__iswpunct_l:",
    "jmp iswpunct_l",
    ".p2align 3",
    ".globl __iswspace_l",
    ".type __iswspace_l, @function",
    "__iswspace_l:",
    "jmp iswspace_l",
    ".p2align 3",
    ".globl __iswupper_l",
    ".type __iswupper_l, @function",
    "__iswupper_l:",
    "jmp iswupper_l",
    ".p2align 3",
    ".globl __iswxdigit_l",
    ".type __iswxdigit_l, @function",
    "__iswxdigit_l:",
    "jmp iswxdigit_l",
    ".p2align 3",
    ".globl __lseek",
    ".type __lseek, @function",
    "__lseek:",
    "jmp lseek",
    ".p2align 3",
    ".globl __mbrtowc",
    ".type __mbrtowc, @function",
    "__mbrtowc:",
    "jmp mbrtowc",
    ".p2align 3",
    ".globl __nanosleep",
    ".type __nanosleep, @function",
    "__nanosleep:",
    "jmp nanosleep",
    ".p2align 3",
    ".globl __open",
    ".type __open, @function",
    "__open:",
    "jmp open",
    ".p2align 3",
    ".globl __open64",
    ".type __open64, @function",
    "__open64:",
    "jmp open64",
    ".p2align 3",
    ".globl __pipe",
    ".type __pipe, @function",
    "__pipe:",
    "jmp pipe",
    ".p2align 3",
    ".globl __poll",
    ".type __poll, @function",
    "__poll:",
    "jmp poll",
    ".p2align 3",
    ".globl __pread64",
    ".type __pread64, @function",
    "__pread64:",
    "jmp pread64",
    ".p2align 3",
    ".globl __pwrite64",
    ".type __pwrite64, @function",
    "__pwrite64:",
    "jmp pwrite64",
    ".p2align 3",
    ".globl __rawmemchr",
    ".type __rawmemchr, @function",
    "__rawmemchr:",
    "jmp rawmemchr",
    ".p2align 3",
    ".globl __read",
    ".type __read, @function",
    "__read:",
    "jmp read",
    ".p2align 3",
    ".globl __sbrk",
    ".type __sbrk, @function",
    "__sbrk:",
    "jmp sbrk",
    ".p2align 3",
    ".globl __sched_get_priority_max",
    ".type __sched_get_priority_max, @function",
    "__sched_get_priority_max:",
    "jmp sched_get_priority_max",
    ".p2align 3",
    ".globl __sched_get_priority_min",
    ".type __sched_get_priority_min, @function",
    "__sched_get_priority_min:",
    "jmp sched_get_priority_min",
    ".p2align 3",
    ".globl __sched_getparam",
    ".type __sched_getparam, @function",
    "__sched_getparam:",
    "jmp sched_getparam",
    ".p2align 3",
    ".globl __sched_getscheduler",
    ".type __sched_getscheduler, @function",
    "__sched_getscheduler:",
    "jmp sched_getscheduler",
    ".p2align 3",
    ".globl __sched_setscheduler",
    ".type __sched_setscheduler, @function",
    "__sched_setscheduler:",
    "jmp sched_setscheduler",
    ".p2align 3",
    ".globl __sched_yield",
    ".type __sched_yield, @function",
    "__sched_yield:",
    "jmp sched_yield",
    ".p2align 3",
    ".globl __select",
    ".type __select, @function",
    "__select:",
    "jmp select",
    ".p2align 3",
    ".globl __send",
    ".type __send, @function",
    "__send:",
    "jmp send",
    ".p2align 3",
    ".globl __setmntent",
    ".type __setmntent, @function",
    "__setmntent:",
    "jmp setmntent",
    ".p2align 3",
    ".globl __setpgid",
    ".type __setpgid, @function",
    "__setpgid:",
    "jmp setpgid",
    ".p2align 3",
    ".globl __statfs",
    ".type __statfs, @function",
    "__statfs:",
    "jmp statfs",
    ".p2align 3",
    ".globl __strcasecmp",
    ".type __strcasecmp, @function",
    "__strcasecmp:",
    "jmp strcasecmp",
    ".p2align 3",
    ".globl __strcasestr",
    ".type __strcasestr, @function",
    "__strcasestr:",
    "jmp strcasestr",
    ".p2align 3",
    ".globl __strdup",
    ".type __strdup, @function",
    "__strdup:",
    "jmp strdup",
    ".p2align 3",
    ".globl __strerror_r",
    ".type __strerror_r, @function",
    "__strerror_r:",
    "jmp strerror_r",
    ".p2align 3",
    ".globl __strndup",
    ".type __strndup, @function",
    "__strndup:",
    "jmp strndup",
    ".p2align 3",
    ".globl __strsep_g",
    ".type __strsep_g, @function",
    "__strsep_g:",
    "jmp strsep",
    ".p2align 3",
    ".globl __strtod_internal",
    ".type __strtod_internal, @function",
    "__strtod_internal:",
    "jmp strtod",
    ".p2align 3",
    ".globl __strtof128_internal",
    ".type __strtof128_internal, @function",
    "__strtof128_internal:",
    "jmp strtof128",
    ".p2align 3",
    ".globl __strtof_internal",
    ".type __strtof_internal, @function",
    "__strtof_internal:",
    "jmp strtof",
    ".p2align 3",
    ".globl __strtol_internal",
    ".type __strtol_internal, @function",
    "__strtol_internal:",
    "jmp strtol",
    ".p2align 3",
    ".globl __strtold_internal",
    ".type __strtold_internal, @function",
    "__strtold_internal:",
    "jmp strtold",
    ".p2align 3",
    ".globl __strtoll_internal",
    ".type __strtoll_internal, @function",
    "__strtoll_internal:",
    "jmp strtoll",
    ".p2align 3",
    ".globl __strtoul_internal",
    ".type __strtoul_internal, @function",
    "__strtoul_internal:",
    "jmp strtoul",
    ".p2align 3",
    ".globl __strtoull_internal",
    ".type __strtoull_internal, @function",
    "__strtoull_internal:",
    "jmp strtoull",
    ".p2align 3",
    ".globl __strverscmp",
    ".type __strverscmp, @function",
    "__strverscmp:",
    "jmp strverscmp",
    ".p2align 3",
    ".globl __towctrans",
    ".type __towctrans, @function",
    "__towctrans:",
    "jmp towctrans",
    ".p2align 3",
    ".globl __vfork",
    ".type __vfork, @function",
    "__vfork:",
    "jmp vfork",
    ".p2align 3",
    ".globl __vfscanf",
    ".type __vfscanf, @function",
    "__vfscanf:",
    "jmp vfscanf",
    ".p2align 3",
    ".globl __vsnprintf",
    ".type __vsnprintf, @function",
    "__vsnprintf:",
    "jmp vsnprintf",
    ".p2align 3",
    ".globl __vsscanf",
    ".type __vsscanf, @function",
    "__vsscanf:",
    "jmp vsscanf",
    ".p2align 3",
    ".globl __waitpid",
    ".type __waitpid, @function",
    "__waitpid:",
    "jmp waitpid",
    ".p2align 3",
    ".globl __wcstod_internal",
    ".type __wcstod_internal, @function",
    "__wcstod_internal:",
    "jmp wcstod",
    ".p2align 3",
    ".globl __wcstof128_internal",
    ".type __wcstof128_internal, @function",
    "__wcstof128_internal:",
    "jmp wcstof128",
    ".p2align 3",
    ".globl __wcstof_internal",
    ".type __wcstof_internal, @function",
    "__wcstof_internal:",
    "jmp wcstof",
    ".p2align 3",
    ".globl __wcstol_internal",
    ".type __wcstol_internal, @function",
    "__wcstol_internal:",
    "jmp wcstol",
    ".p2align 3",
    ".globl __wcstold_internal",
    ".type __wcstold_internal, @function",
    "__wcstold_internal:",
    "jmp wcstold",
    ".p2align 3",
    ".globl __wcstoll_internal",
    ".type __wcstoll_internal, @function",
    "__wcstoll_internal:",
    "jmp wcstoll",
    ".p2align 3",
    ".globl __wcstoul_internal",
    ".type __wcstoul_internal, @function",
    "__wcstoul_internal:",
    "jmp wcstoul",
    ".p2align 3",
    ".globl __wcstoull_internal",
    ".type __wcstoull_internal, @function",
    "__wcstoull_internal:",
    "jmp wcstoull",
    ".popsection",
);
