#![allow(missing_docs)]

core::arch::global_asm!(
    ".pushsection .text.rl_compat,\"ax\",@progbits",
    ".p2align 3",
    ".globl _IO_fclose",
    "_IO_fclose:",
    "jmp fclose",
    ".p2align 3",
    ".globl _IO_fdopen",
    "_IO_fdopen:",
    "jmp fdopen",
    ".p2align 3",
    ".globl _IO_feof",
    "_IO_feof:",
    "jmp feof",
    ".p2align 3",
    ".globl _IO_ferror",
    "_IO_ferror:",
    "jmp ferror",
    ".p2align 3",
    ".globl _IO_fflush",
    "_IO_fflush:",
    "jmp fflush",
    ".p2align 3",
    ".globl _IO_fgets",
    "_IO_fgets:",
    "jmp fgets",
    ".p2align 3",
    ".globl _IO_fopen",
    "_IO_fopen:",
    "jmp fopen",
    ".p2align 3",
    ".globl _IO_fprintf",
    "_IO_fprintf:",
    "jmp fprintf",
    ".p2align 3",
    ".globl _IO_fputs",
    "_IO_fputs:",
    "jmp fputs",
    ".p2align 3",
    ".globl _IO_fread",
    "_IO_fread:",
    "jmp fread",
    ".p2align 3",
    ".globl _IO_ftell",
    "_IO_ftell:",
    "jmp ftell",
    ".p2align 3",
    ".globl _IO_fwrite",
    "_IO_fwrite:",
    "jmp fwrite",
    ".p2align 3",
    ".globl _IO_getc",
    "_IO_getc:",
    "jmp getc",
    ".p2align 3",
    ".globl _IO_gets",
    "_IO_gets:",
    "jmp gets",
    ".p2align 3",
    ".globl _IO_popen",
    "_IO_popen:",
    "jmp popen",
    ".p2align 3",
    ".globl _IO_printf",
    "_IO_printf:",
    "jmp printf",
    ".p2align 3",
    ".globl _IO_putc",
    "_IO_putc:",
    "jmp putc",
    ".p2align 3",
    ".globl _IO_puts",
    "_IO_puts:",
    "jmp puts",
    ".p2align 3",
    ".globl _IO_setbuffer",
    "_IO_setbuffer:",
    "jmp setbuffer",
    ".p2align 3",
    ".globl _IO_setvbuf",
    "_IO_setvbuf:",
    "jmp setvbuf",
    ".p2align 3",
    ".globl _IO_sprintf",
    "_IO_sprintf:",
    "jmp sprintf",
    ".p2align 3",
    ".globl _IO_sscanf",
    "_IO_sscanf:",
    "jmp sscanf",
    ".p2align 3",
    ".globl _IO_ungetc",
    "_IO_ungetc:",
    "jmp ungetc",
    ".p2align 3",
    ".globl _IO_vfprintf",
    "_IO_vfprintf:",
    "jmp vfprintf",
    ".p2align 3",
    ".globl _IO_vsprintf",
    "_IO_vsprintf:",
    "jmp vsprintf",
    ".p2align 3",
    ".globl _IO_flockfile",
    "_IO_flockfile:",
    "jmp flockfile",
    ".p2align 3",
    ".globl _IO_funlockfile",
    "_IO_funlockfile:",
    "jmp funlockfile",
    ".p2align 3",
    ".globl _IO_ftrylockfile",
    "_IO_ftrylockfile:",
    "jmp ftrylockfile",
    ".p2align 3",
    ".globl _IO_fgetpos",
    "_IO_fgetpos:",
    "jmp fgetpos",
    ".p2align 3",
    ".globl _IO_fgetpos64",
    "_IO_fgetpos64:",
    "jmp fgetpos64",
    ".p2align 3",
    ".globl _IO_fsetpos",
    "_IO_fsetpos:",
    "jmp fsetpos",
    ".p2align 3",
    ".globl _IO_fsetpos64",
    "_IO_fsetpos64:",
    "jmp fsetpos64",
    ".popsection",
);
