core::arch::global_asm!(
    ".text",
    ".globl dlopen",
    ".type dlopen, @function",
    "dlopen:",
    "mov rdx, [rsp]",
    "mov rcx, [rip + environ@GOTPCREL]",
    "mov rcx, [rcx]",
    "jmp [rip + __libc_ldso_dlopen@GOTPCREL]",
    ".size dlopen, .-dlopen",
    ".globl dlmopen",
    ".type dlmopen, @function",
    "dlmopen:",
    "mov rcx, [rsp]",
    "mov r8, [rip + environ@GOTPCREL]",
    "mov r8, [r8]",
    "jmp [rip + __libc_ldso_dlmopen@GOTPCREL]",
    ".size dlmopen, .-dlmopen",
    ".globl dlclose",
    ".type dlclose, @function",
    "dlclose:",
    "jmp [rip + __libc_ldso_dlclose@GOTPCREL]",
    ".size dlclose, .-dlclose",
    ".globl dlsym",
    ".type dlsym, @function",
    "dlsym:",
    "mov rdx, [rsp]",
    "jmp [rip + __libc_ldso_dlsym@GOTPCREL]",
    ".size dlsym, .-dlsym",
    ".globl dlvsym",
    ".type dlvsym, @function",
    "dlvsym:",
    "mov rcx, [rsp]",
    "jmp [rip + __libc_ldso_dlvsym@GOTPCREL]",
    ".size dlvsym, .-dlvsym",
    ".globl dlerror",
    ".type dlerror, @function",
    "dlerror:",
    "jmp [rip + __libc_ldso_dlerror@GOTPCREL]",
    ".size dlerror, .-dlerror",
    ".globl dladdr",
    ".type dladdr, @function",
    "dladdr:",
    "jmp [rip + __libc_ldso_dladdr@GOTPCREL]",
    ".size dladdr, .-dladdr",
    ".globl dladdr1",
    ".type dladdr1, @function",
    "dladdr1:",
    "jmp [rip + __libc_ldso_dladdr1@GOTPCREL]",
    ".size dladdr1, .-dladdr1",
    ".globl dlinfo",
    ".type dlinfo, @function",
    "dlinfo:",
    "mov rcx, [rsp]",
    "jmp [rip + __libc_ldso_dlinfo@GOTPCREL]",
    ".size dlinfo, .-dlinfo",
    ".globl dl_iterate_phdr",
    ".type dl_iterate_phdr, @function",
    "dl_iterate_phdr:",
    "mov rdx, [rsp]",
    "jmp [rip + __libc_ldso_iterate_phdr@GOTPCREL]",
    ".size dl_iterate_phdr, .-dl_iterate_phdr",
    ".globl _dl_find_object",
    ".type _dl_find_object, @function",
    "_dl_find_object:",
    "jmp [rip + __libc_ldso_find_object@GOTPCREL]",
    ".size _dl_find_object, .-_dl_find_object",
    ".weak __libc_ldso_dlopen",
    ".weak __libc_ldso_dlmopen",
    ".weak __libc_ldso_dlclose",
    ".weak __libc_ldso_dlsym",
    ".weak __libc_ldso_dlvsym",
    ".weak __libc_ldso_dlerror",
    ".weak __libc_ldso_dladdr",
    ".weak __libc_ldso_dladdr1",
    ".weak __libc_ldso_dlinfo",
    ".weak __libc_ldso_iterate_phdr",
    ".weak __libc_ldso_find_object",
);
