[workspace]
resolver = "3"
members = ["crates/rusty-libc-mem", "crates/rusty-libc-core", "crates/rusty-libc-malloc", "crates/rusty-libc-stdio", "crates/rusty-libc-ctype", "crates/rusty-libc-stdlib", "crates/rusty-libc-math", "crates/rusty-libc-sys", "crates/rusty-libc-util", "crates/rusty-libc-time", "crates/rusty-libc-wchar", "crates/rusty-libc-regex", "crates/rusty-libc-pthread", "crates/rusty-libc-signal", "crates/rusty-libc-net", "crates/rusty-libc-iconv", "crates/rusty-libc-fortify", "crates/rusty-libc-locale", "crates/rusty-libc-extra", "crates/rusty-libc-ipc", "crates/rusty-libc-rpc", "crates/rusty-libc-cabi"]
exclude = ["crates/rusty-libc-ldso", "crates/rusty-libc-mvec"]

[workspace.package]
edition = "2024"
license = "LGPL-2.1-or-later"

[profile.dev]
panic = "abort"

[profile.dev.package.rusty-libc-math]
opt-level = 3
overflow-checks = false
debug-assertions = false

[profile.release]
panic = "abort"
opt-level = 3

[profile.rt]
inherits = "release"
codegen-units = 256
[profile.rt.package.rusty-libc-stdio]
codegen-units = 16
[profile.rt.package.rusty-libc-math]
codegen-units = 16
[profile.rt.package.rusty-libc-mem]
codegen-units = 16
[profile.rt.package.rusty-libc-malloc]
codegen-units = 16
[profile.rt.package.rusty-libc-core]
codegen-units = 16
[profile.rt.package.rusty-libc-locale]
codegen-units = 256
[profile.release.package.rusty-libc-locale]
codegen-units = 256
