#!/usr/bin/env python3
from fractions import Fraction
import math

P = 2400
ONE = 1 << P


def atan_inv(n):
    x = ONE // n
    n2 = n * n
    s = x
    k = 1
    sign = -1
    while x:
        x //= n2
        k += 2
        s += sign * (x // k)
        sign = -sign
    return s


PI = 4 * (4 * atan_inv(5) - atan_inv(239))


def atan_fp(num, den):
    x = (num * ONE) // den
    h = 0
    for _ in range(5):
        s = math.isqrt(ONE * ONE + x * x)
        x = (x * ONE) // (ONE + s)
        h += 1
    x2 = (x * x) >> P
    term = x
    s = x
    k = 1
    sign = -1
    while term:
        term = (term * x2) >> P
        k += 2
        s += sign * (term // k)
        sign = -sign
    return s << h


def ln2_fp():
    s = 0
    t = ONE
    k = 1
    while t:
        t >>= 1
        s += t // k
        k += 1
    return s


LN2 = ln2_fp()


def to_frac(v):
    return Fraction(v, ONE)


def dd(fr):
    hi = float(fr)
    lo = float(fr - Fraction(hi))
    return hi, lo


def lit(x):
    r = repr(x)
    if 'e' not in r and '.' not in r:
        r += '.0'
    return r


def top_bits(fr, nbits):
    e = 0
    while fr >= 2 ** (e + 1):
        e += 1
    while fr < Fraction(2) ** e:
        e -= 1
    q = Fraction(2) ** (e - nbits + 1)
    return Fraction(math.floor(fr / q)) * q


def cw_split(fr, parts, nbits):
    res = []
    rem = fr
    for _ in range(parts):
        p = top_bits(rem, nbits)
        res.append(p)
        rem -= p
    return res, rem


def out(s=""):
    print(s)


def fact(n):
    return math.factorial(n)


def sgn(k):
    return -1 if k % 2 else 1


out("//! Constant tables for trig.rs. GENERATED by gen_tables.py (same directory) from exact")
out("//! big-integer arithmetic; derived data, nothing copied from another library. Do not edit.")
out("#![allow(clippy::excessive_precision, clippy::unreadable_literal, clippy::approx_constant, dead_code)]")
out()
pio2 = to_frac(PI) / 2
out("/// 2/pi: bits 1..1536 after the binary point, big-endian 64-bit words (Payne-Hanek).")
TWO_OVER_PI = (2 * ONE * ONE) // PI
words = []
for i in range(24):
    words.append((TWO_OVER_PI >> (P - 64 * (i + 1))) & ((1 << 64) - 1))
out("pub const TWO_OVER_PI_WORDS: [u64; 24] = [")
for i in range(0, 24, 3):
    out("    " + ", ".join("0x%016x" % w for w in words[i:i + 3]) + ",")
out("];")
out()
parts, rest = cw_split(pio2, 3, 33)
out("/// pi/2 = P1 + P2 + P3 + P4 with P1..P3 of 33 bits (n*Pi exact for n < 2^20), P4 a double.")
for i, p in enumerate(parts, 1):
    out("pub const PIO2_%d: f64 = %s;" % (i, lit(float(p))))
out("pub const PIO2_4: f64 = %s;" % lit(float(rest)))
out()
h, l = dd(pio2)
out("pub const PIO2: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
pi = to_frac(PI)
h, l = dd(pi)
out("pub const PI: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
h, l = dd(1 / pi)
out("pub const INV_PI: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
h, l = dd(pi / 4)
out("pub const PIO4: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
h, l = dd(3 * pi / 4)
out("pub const PI3O4: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("pub const TWO_OVER_PI: f64 = %s;" % lit(float(2 / pi)))
out()
ln2 = to_frac(LN2)
(l1, l2), l3 = cw_split(ln2, 2, 42)
out("/// ln 2 = LN2_1 + LN2_2 + LN2_3, LN2_1 and LN2_2 of 42 bits (k*LN2_i exact for |k| < 2^11).")
out("pub const LN2_1: f64 = %s;" % lit(float(l1)))
out("pub const LN2_2: f64 = %s;" % lit(float(l2)))
out("pub const LN2_3: f64 = %s;" % lit(float(l3)))
h, l = dd(ln2)
out("pub const LN2: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("pub const LOG2E: f64 = %s;" % lit(float(1 / ln2)))
out()
out("/// atan(k/32), k = 0..=32, as (hi, lo).")
out("pub const ATAN_TAB: [(f64, f64); 33] = [")
for k in range(33):
    if k == 0:
        v = Fraction(0)
    elif k == 32:
        v = pi / 4
    else:
        v = to_frac(atan_fp(k, 32))
    h, l = dd(v)
    out("    (%s, %s)," % (lit(h), lit(l)))
out("];")
out()

h, l = dd(Fraction(-1, 6))
out("pub const SIN_C3: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("/// sin tail: coefficient of z^j in y^5*(...) : (-1)^(j+2)/(2j+5)!, j = 0..9")
out("pub const SIN_TAIL: [f64; 10] = [" + ", ".join(lit(float(Fraction(sgn(j + 2), fact(2 * j + 5)))) for j in range(10)) + "];")
h, l = dd(Fraction(1, 24))
out("pub const COS_C4: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("/// cos tail: coefficient of z^j in z^3*(...) : (-1)^(j+3)/(2j+6)!, j = 0..9")
out("pub const COS_TAIL: [f64; 10] = [" + ", ".join(lit(float(Fraction(sgn(j + 3), fact(2 * j + 6)))) for j in range(10)) + "];")
out()
out("/// atan tail: coefficient of z^j in t^3*(...) : (-1)^(j+1)/(2j+3), j = 0..7")
out("pub const ATAN_TAIL: [f64; 8] = [" + ", ".join(lit(float(Fraction(sgn(j + 1), 2 * j + 3))) for j in range(8)) + "];")
h, l = dd(Fraction(1, 3))
out("pub const THIRD: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("/// atanh tail: coefficient of z^j in s^5*(...) : 1/(2j+5), j = 0..11")
out("pub const ATANH_TAIL: [f64; 12] = [" + ", ".join(lit(float(Fraction(1, 2 * j + 5))) for j in range(12)) + "];")
out("/// atanh tail in double-double (precise path): 1/(2j+5), j = 0..19")
out("pub const ATANH_TAIL_DD: [(f64, f64); 20] = [" + ", ".join("(%s, %s)" % tuple(lit(v) for v in dd(Fraction(1, 2 * j + 5))) for j in range(20)) + "];")
out("/// expm1 tail: coefficient of u^j in u^3*(...) : 1/(j+3)!, j = 0..7")
out("pub const EXPM1_TAIL: [f64; 8] = [" + ", ".join(lit(float(Fraction(1, fact(j + 3)))) for j in range(8)) + "];")
