#!/usr/bin/env python3
from fractions import Fraction
import math

P = 400
ONE = 1 << P


def mul(a, b):
    return (a * b) >> P


def sincos_fp(num, den):
    x = (num * ONE) // den
    x2 = mul(x, x)
    s = 0
    c = 0
    t = x
    k = 1
    while t:
        s += t if (k // 2) % 2 == 0 else -t
        t = mul(t, x2) // ((k + 1) * (k + 2))
        k += 2
    t = ONE
    k = 0
    while t:
        c += t if (k // 2) % 2 == 0 else -t
        t = mul(t, x2) // ((k + 1) * (k + 2))
        k += 2
    return s, c


def atan_inv(n):
    x = ONE // n
    n2 = n * n
    s = x
    k = 1
    sign = -1
    while x:
        x //= n2
        k += 2
        s += sign * (x // k)
        sign = -sign
    return s


PI = 4 * (4 * atan_inv(5) - atan_inv(239))


def atan_fp(num, den):
    x = (num * ONE) // den
    h = 0
    for _ in range(6):
        s = math.isqrt(ONE * ONE + x * x)
        x = (x * ONE) // (ONE + s)
        h += 1
    x2 = mul(x, x)
    term = x
    s = x
    k = 1
    sign = -1
    while term:
        term = mul(term, x2)
        k += 2
        s += sign * (term // k)
        sign = -sign
    return s << h


def frac(v):
    return Fraction(v, ONE)


def dd(fr):
    hi = float(fr)
    lo = float(fr - Fraction(hi))
    return hi, lo


def lit(x):
    r = repr(x)
    if 'e' not in r and '.' not in r:
        r += '.0'
    return r


def out(s=""):
    print(s)


out("//! Constant tables for trig/fast.rs. GENERATED by gen_fast.py (same directory) from exact")
out("//! big-integer arithmetic; derived data, nothing copied from another library. Do not edit.")
out("#![allow(clippy::excessive_precision, clippy::unreadable_literal, clippy::approx_constant, dead_code)]")
out()
N = 64
K = 64
out("/// (sin, cos) of k/64 for k = 0..=63, each as (hi, lo, hi, lo): S_hi, S_lo, C_hi, C_lo.")
out("pub const SINCOS_TAB: [[f64; 4]; %d] = [" % K)
for k in range(K):
    s, c = sincos_fp(k, N)
    sh, sl = dd(frac(s))
    ch, cl = dd(frac(c))
    out("    [%s, %s, %s, %s]," % (lit(sh), lit(sl), lit(ch), lit(cl)))
out("];")


def top_bits(fr, nbits):
    e = 0
    while fr >= 2 ** (e + 1):
        e += 1
    while fr < Fraction(2) ** e:
        e -= 1
    q = Fraction(2) ** (e - nbits + 1)
    return Fraction(math.floor(fr / q)) * q


def sincos_angle(j):
    ang = (j * PI) // 128
    q, r = divmod(j % 256, 64)
    rr = (r * PI) // 128
    x = rr
    x2 = mul(x, x)
    s = 0
    t = x
    k = 1
    while t:
        s += t if (k // 2) % 2 == 0 else -t
        t = mul(t, x2) // ((k + 1) * (k + 2))
        k += 2
    c = 0
    t = ONE
    k = 0
    while t:
        c += t if (k // 2) % 2 == 0 else -t
        t = mul(t, x2) // ((k + 1) * (k + 2))
        k += 2
    for _ in range(q):
        s, c = c, -s
    if r == 0:
        s = [0, ONE, 0, -ONE][q]
        c = [ONE, 0, -ONE, 0][q]
    return s, c


out()
out("/// (sin, cos) of j*pi/128 for j = 0..=255 as [S_hi, S_lo, C_hi, C_lo] (exact zeros where exact).")
out("pub const SINCOS128: [[f64; 4]; 256] = [")
for j in range(256):
    s, c = sincos_angle(j)
    sh, sl = dd(frac(s))
    ch, cl = dd(frac(c))
    out("    [%s, %s, %s, %s]," % (lit(sh), lit(sl), lit(ch), lit(cl)))
out("];")
out()
step = frac(PI) / 128
a1 = top_bits(step, 27)
a2 = top_bits(step - a1, 27)
a3 = step - a1 - a2
out("/// pi/128 = PI128_1 + PI128_2 + PI128_3; the first two have 27 bits (m * PI128_i exact for m < 2^26).")
out("pub const PI128_1: f64 = %s;" % lit(float(a1)))
out("pub const PI128_2: f64 = %s;" % lit(float(a2)))
out("pub const PI128_3: f64 = %s;" % lit(float(a3)))
out("/// tan(e pi/128) for e = -32..31 (index e + 32) as [hi, lo]: the table of the tangent kernels.")
out("pub const TAN64: [[f64; 2]; 64] = [")
for e in range(-32, 32):
    sn, cs = sincos_angle(e % 256)
    t = frac(sn) / frac(cs)
    th, tl = dd(t)
    out("    [%s, %s]," % (lit(th), lit(tl)))
out("];")
out("/// 128/pi.")
out("pub const INV_PI128: f64 = %s;" % lit(float(128 / frac(PI))))
b1 = float(step)
b2 = float(step - Fraction(b1))
b3 = float(step - Fraction(b1) - Fraction(b2))
out("/// pi/128 = PI128_B1 + PI128_B2 + PI128_B3, three non-overlapping doubles (fused-multiply-add reduction).")
out("pub const PI128_B1: f64 = %s;" % lit(b1))
out("pub const PI128_B2: f64 = %s;" % lit(b2))
out("pub const PI128_B3: f64 = %s;" % lit(b3))


from math import comb

DEG = 8


def row_out(g):
    h0, l0 = dd(frac(g[0]))
    h1, l1 = dd(frac(g[1]))
    rest = [float(frac(v)) for v in g[2:DEG + 1]]
    return "[%s, %s, %s, %s, %s]" % (lit(h0), lit(l0), lit(h1), lit(l1), ", ".join(lit(v) for v in rest))


def taylor_from_series(coef_fp, c_fp, mmax):
    pw = [ONE]
    for _ in range(mmax):
        pw.append(mul(pw[-1], c_fp))
    g = []
    for k in range(DEG + 1):
        acc = 0
        for m in range(k, mmax + 1):
            acc += comb(m, k) * mul(coef_fp[m], pw[m - k])
        g.append(acc)
    return g


MM = 260
R_COEF = [(comb(2 * m, m) << P) // (4 ** m * (2 * m + 1)) for m in range(MM + 1)]
Q_COEF = [(comb(2 * m, m) << P) // (8 ** m * (2 * m + 1)) for m in range(MM + 1)]

out()
out("/// asin(x) = x * R(x^2) near u = j/128: rows for j = 0..=32 (u up to 0.25).")
out("pub const ASIN_ROWS: [[f64; 11]; 33] = [")
for j in range(33):
    out("    " + row_out(taylor_from_series(R_COEF, (j << P) // 128, MM)) + ",")
out("];")
out()
out("/// acos(1 - w) = sqrt(2 w) * Q(w) near w = j/128: rows for j = 0..=64 (w up to 0.5).")
out("pub const ACOSQ_ROWS: [[f64; 11]; 65] = [")
for j in range(65):
    out("    " + row_out(taylor_from_series(Q_COEF, (j << P) // 128, MM)) + ",")
out("];")


def atan_taylor(c_num, c_den):
    c = (c_num << P) // c_den
    q0 = ONE + mul(c, c)
    q1 = 2 * c
    G = [(ONE << P) // q0]
    G.append(-((q1 * G[0]) // q0))
    for n in range(2, DEG):
        G.append(-(((q1 * G[n - 1]) >> P) + G[n - 2]) * ONE // q0)
    base = atan_fp(c_num, c_den) if c_num else 0
    g = [base] + [G[n] // (n + 1) for n in range(DEG)]
    return g


out()
out("/// atan(c + d) near c = j/128: rows for j = 0..=128.")
out("pub const ATAN_ROWS: [[f64; 11]; 129] = [")
for j in range(129):
    out("    " + row_out(atan_taylor(j, 128)) + ",")
out("];")



def ln2_fixed():
    s = 0
    t = ONE
    k = 1
    while t:
        t >>= 1
        s += t // k
        k += 1
    return s


LN2F = ln2_fixed()


def exp_fp(x):
    s = ONE
    t = ONE
    n = 1
    while t:
        t = mul(t, x) // n
        s += t
        n += 1
    return s


out()
out("/// [2^(j/128) hi, lo, 2^(-j/128) hi, lo] for j = 0..=127.")
out("pub const EXP128: [[f64; 4]; 128] = [")
for j in range(128):
    x = mul(LN2F, (j << P) // 128)
    e = exp_fp(x)
    ei = (ONE << P) // e
    th, tl = dd(frac(e))
    ih, il = dd(frac(ei))
    out("    [%s, %s, %s, %s]," % (lit(th), lit(tl), lit(ih), lit(il)))
out("];")
step = frac(LN2F) / 128
l1 = top_bits(step, 35)
l2 = top_bits(step - l1, 35)
l3 = step - l1 - l2
out()
out("/// ln2/128 = LN2_128_1 + LN2_128_2 + LN2_128_3 (35 bits each for the first two: m * LN2_128_i exact for m < 2^18).")
out("pub const LN2_128_1: f64 = %s;" % lit(float(l1)))
out("pub const LN2_128_2: f64 = %s;" % lit(float(l2)))
out("pub const LN2_128_3: f64 = %s;" % lit(float(l3)))
out("pub const INV_LN2_128: f64 = %s;" % lit(float(128 / frac(LN2F))))

def bernoulli(nmax):
    B = [Fraction(0)] * (nmax + 1)
    B[0] = Fraction(1)
    for m in range(1, nmax + 1):
        B[m] = -sum(comb(m + 1, k) * B[k] for k in range(m)) / (m + 1)
    return B


BN = bernoulli(40)
tc = []
for n in range(1, 12):
    c = Fraction(2 ** (2 * n) * (2 ** (2 * n) - 1)) * BN[2 * n] / math.factorial(2 * n)
    tc.append(c)
out()
out("/// tanh x = x + x^3 * (TANH_C[0] + TANH_C[1] x^2 + ...): coefficients of x^(2n+1), n = 1..10.")
out("pub const TANH_C: [f64; 10] = [" + ", ".join(lit(float(c)) for c in tc[1:]) + "];")



def atanh_fp(num, den):
    x = (num * ONE) // den
    x2 = mul(x, x)
    t = x
    s = 0
    k = 1
    while t:
        s += t // k
        t = mul(t, x2)
        k += 2
    return s


LN10F = 3 * LN2F + 2 * atanh_fp(1, 9)
LOG2_10 = (LN10F << P) // LN2F
out()
l10 = frac(LN10F)
h, l = dd(l10)
out("pub const LN10_DD: (f64, f64) = (%s, %s);" % (lit(h), lit(l)))
out("/// 128 log2(10).")
out("pub const INV_LOG10_2_128: f64 = %s;" % lit(float(128 * frac(LOG2_10))))
step = frac(LN2F) / frac(LN10F) / 128
a1 = top_bits(step, 35)
a2 = top_bits(step - a1, 35)
a3 = step - a1 - a2
out("/// log10(2)/128 = LOG10_2_128_1 + LOG10_2_128_2 + ... (35 bits each for the first two).")
out("pub const LOG10_2_128_1: f64 = %s;" % lit(float(a1)))
out("pub const LOG10_2_128_2: f64 = %s;" % lit(float(a2)))


out()
out("/// [1/c_j, ln c_j hi, ln c_j lo] for c_j = 1 + j/128, j = -37..=53 (index j + 37).")
out("pub const LOG128: [[f64; 3]; 91] = [")
for j in range(-37, 54):
    cinv = (ONE << P) // (((128 + j) * ONE) // 128)
    ih = float(frac(cinv))
    fr = Fraction(ih)
    num, den = fr.denominator - fr.numerator, fr.denominator + fr.numerator
    if num == 0:
        lc = 0
    elif num > 0:
        lc = 2 * atanh_fp(num, den)
    else:
        lc = -2 * atanh_fp(-num, den)
    lh, ll = dd(frac(lc))
    out("    [%s, %s, %s]," % (lit(ih), lit(lh), lit(ll)))
out("];")


RH_COEF = [(-1) ** m * R_COEF[m] for m in range(MM + 1)]
S_COEF = [(ONE // (2 * m + 1)) for m in range(MM + 1)]
Q2_COEF = [(-1) ** m * Q_COEF[m] for m in range(MM + 1)]
out()
out("/// asinh(x) = x R(-x^2) near u = x^2 = j/128: rows for j = 0..=32.")
out("pub const ASINH_ROWS: [[f64; 11]; 33] = [")
for j in range(33):
    out("    " + row_out(taylor_from_series(RH_COEF, (j << P) // 128, MM)) + ",")
out("];")
out()
out("/// atanh(x) = x S(x^2) near u = x^2 = j/128: rows for j = 0..=32.")
out("pub const ATANH_ROWS: [[f64; 11]; 33] = [")
for j in range(33):
    out("    " + row_out(taylor_from_series(S_COEF, (j << P) // 128, MM)) + ",")
out("];")
out()
out("/// atanh(x) = x S(x^2) near u = x^2 = j/256: rows for j = 0..=185 (x up to 0.85).")
out("pub const ATANH_ROWS_W: [[f64; 11]; 186] = [")
for j in range(186):
    out("    " + row_out(taylor_from_series(S_COEF, (j << P) // 256, MM)) + ",")
out("];")
BN2 = bernoulli(2 * (MM + 1))
T_COEF = []
for n in range(1, MM + 2):
    cn = Fraction(2 ** (2 * n) * (2 ** (2 * n) - 1)) * BN2[2 * n] / math.factorial(2 * n)
    T_COEF.append(int(cn * ONE))
out()
out("/// tanh(x) = x T(x^2) near u = x^2 = j/128: rows for j = 0..=128 (x up to 1).")
out("pub const TANH_ROWS: [[f64; 11]; 129] = [")
for j in range(129):
    out("    " + row_out(taylor_from_series(T_COEF, (j << P) // 128, MM)) + ",")
out("];")
out()
out("/// acosh(1 + t) = sqrt(2 t) Q2(t) near t = j/128: rows for j = 0..=128.")
out("pub const ACOSHQ_ROWS: [[f64; 11]; 129] = [")
for j in range(129):
    out("    " + row_out(taylor_from_series(Q2_COEF, (j << P) // 128, MM)) + ",")
out("];")


def tan_taylor(j, den):
    s, c = sincos_fp(j, den)
    g = [(s * ONE) // c if c else 0]
    g.append(ONE + mul(g[0], g[0]))
    for n in range(1, DEG):
        acc = 0
        for i in range(n + 1):
            acc += mul(g[i], g[n - i])
        g.append(acc // (n + 1))
    return g


out()
out("/// tan(c + d) near c = j/256: rows for j = 0..=200 (Taylor coefficients g0..g8 as in ATAN_ROWS).")
out("pub static TAN_ROWS: [[f64; 11]; 201] = [")
for j in range(201):
    out("    " + row_out(tan_taylor(j, 256)) + ",")
out("];")


INV_PI_FP = (ONE * ONE) // PI
R_PI_COEF = [mul(c, INV_PI_FP) for c in R_COEF]
Q_PI_COEF = [mul(c, INV_PI_FP) for c in Q_COEF]
out()
out("/// asin(x)/pi = x R(x^2)/pi near u = j/128 (ASIN_ROWS divided by pi): rows for j = 0..=32.")
out("pub const ASINPI_ROWS: [[f64; 11]; 33] = [")
for j in range(33):
    out("    " + row_out(taylor_from_series(R_PI_COEF, (j << P) // 128, MM)) + ",")
out("];")
out()
out("/// acos(1 - w)/pi = sqrt(2 w) Q(w)/pi near w = j/128 (ACOSQ_ROWS divided by pi): rows for j = 0..=64.")
out("pub const ACOSPIQ_ROWS: [[f64; 11]; 65] = [")
for j in range(65):
    out("    " + row_out(taylor_from_series(Q_PI_COEF, (j << P) // 128, MM)) + ",")
out("];")
