[package]
name = "rusty-libc-rpc"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
rusty-libc-core = { path = "../rusty-libc-core" }
rusty-libc-mem = { path = "../rusty-libc-mem" }
rusty-libc-malloc = { path = "../rusty-libc-malloc" }
rusty-libc-net = { path = "../rusty-libc-net" }
rusty-libc-sys = { path = "../rusty-libc-sys" }
rusty-libc-time = { path = "../rusty-libc-time" }
rusty-libc-stdio = { path = "../rusty-libc-stdio" }
rusty-libc-stdlib = { path = "../rusty-libc-stdlib" }

[features]
export = []
