use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("AT_NULL", V::Dec(0)),
        ("AT_IGNORE", V::Dec(1)),
        ("AT_EXECFD", V::Dec(2)),
        ("AT_PHDR", V::Dec(3)),
        ("AT_PHENT", V::Dec(4)),
        ("AT_PHNUM", V::Dec(5)),
        ("AT_PAGESZ", V::Dec(6)),
        ("AT_BASE", V::Dec(7)),
        ("AT_FLAGS", V::Dec(8)),
        ("AT_ENTRY", V::Dec(9)),
        ("AT_NOTELF", V::Dec(10)),
        ("AT_UID", V::Dec(11)),
        ("AT_EUID", V::Dec(12)),
        ("AT_GID", V::Dec(13)),
        ("AT_EGID", V::Dec(14)),
        ("AT_PLATFORM", V::Dec(15)),
        ("AT_HWCAP", V::Dec(16)),
        ("AT_CLKTCK", V::Dec(17)),
        ("AT_FPUCW", V::Dec(18)),
        ("AT_DCACHEBSIZE", V::Dec(19)),
        ("AT_ICACHEBSIZE", V::Dec(20)),
        ("AT_UCACHEBSIZE", V::Dec(21)),
        ("AT_IGNOREPPC", V::Dec(22)),
        ("AT_SECURE", V::Dec(23)),
        ("AT_BASE_PLATFORM", V::Dec(24)),
        ("AT_RANDOM", V::Dec(25)),
        ("AT_HWCAP2", V::Dec(26)),
        ("AT_RSEQ_FEATURE_SIZE", V::Dec(27)),
        ("AT_RSEQ_ALIGN", V::Dec(28)),
        ("AT_HWCAP3", V::Dec(29)),
        ("AT_HWCAP4", V::Dec(30)),
        ("AT_EXECFN", V::Dec(31)),
        ("AT_SYSINFO", V::Dec(32)),
        ("AT_SYSINFO_EHDR", V::Dec(33)),
        ("AT_L1I_CACHESHAPE", V::Dec(34)),
        ("AT_L1D_CACHESHAPE", V::Dec(35)),
        ("AT_L2_CACHESHAPE", V::Dec(36)),
        ("AT_L3_CACHESHAPE", V::Dec(37)),
        ("AT_L1I_CACHESIZE", V::Dec(40)),
        ("AT_L1I_CACHEGEOMETRY", V::Dec(41)),
        ("AT_L1D_CACHESIZE", V::Dec(42)),
        ("AT_L1D_CACHEGEOMETRY", V::Dec(43)),
        ("AT_L2_CACHESIZE", V::Dec(44)),
        ("AT_L2_CACHEGEOMETRY", V::Dec(45)),
        ("AT_L3_CACHESIZE", V::Dec(46)),
        ("AT_L3_CACHEGEOMETRY", V::Dec(47)),
        ("AT_MINSIGSTKSZ", V::Dec(51)),
    ]),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

