use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Include("<sys/types.h>"),
    Item::Gate(&[
        Branch { head: "ifdef __USE_LARGEFILE64", items: &[
            Item::Gate(&[
                Branch { head: "ifndef __off64_t_defined", items: &[
                    Item::Consts(&[
                        ("__off64_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("long", "off64_t"),
                ] },
            ], ""),
        ] },
    ], ""),
    Item::Consts(&[
        ("F_GETLK64", V::Dec(5)),
        ("F_SETLK64", V::Dec(6)),
        ("F_SETLKW64", V::Dec(7)),
        ("O_ACCMODE", V::Txt("0003")),
        ("O_RDONLY", V::Txt("00")),
        ("O_WRONLY", V::Txt("01")),
        ("O_RDWR", V::Txt("02")),
        ("O_CREAT", V::Txt("0100")),
        ("O_EXCL", V::Txt("0200")),
        ("O_NOCTTY", V::Txt("0400")),
        ("O_TRUNC", V::Txt("01000")),
        ("O_APPEND", V::Txt("02000")),
        ("O_NONBLOCK", V::Txt("04000")),
        ("O_NDELAY", V::Dec(2048)),
        ("O_SYNC", V::Txt("04010000")),
        ("O_FSYNC", V::Hex(0x101000)),
        ("O_ASYNC", V::Txt("020000")),
        ("F_GETLK", V::Dec(5)),
        ("F_SETLK", V::Dec(6)),
        ("F_SETLKW", V::Dec(7)),
        ("F_OFD_GETLK", V::Dec(36)),
        ("F_OFD_SETLK", V::Dec(37)),
        ("F_OFD_SETLKW", V::Dec(38)),
        ("O_LARGEFILE", V::Dec(0)),
        ("O_DIRECTORY", V::Hex(0x10000)),
        ("O_NOFOLLOW", V::Hex(0x20000)),
        ("O_CLOEXEC", V::Hex(0x80000)),
        ("O_DIRECT", V::Hex(0x4000)),
        ("O_NOATIME", V::Hex(0x40000)),
        ("O_PATH", V::Hex(0x200000)),
        ("O_TMPFILE", V::Hex(0x410000)),
        ("O_DSYNC", V::Hex(0x1000)),
        ("O_RSYNC", V::Hex(0x101000)),
        ("F_DUPFD", V::Dec(0)),
        ("F_GETFD", V::Dec(1)),
        ("F_SETFD", V::Dec(2)),
        ("F_GETFL", V::Dec(3)),
        ("F_SETFL", V::Dec(4)),
        ("F_SETOWN", V::Dec(8)),
        ("F_GETOWN", V::Dec(9)),
        ("F_SETSIG", V::Dec(10)),
        ("F_GETSIG", V::Dec(11)),
        ("F_SETOWN_EX", V::Dec(15)),
        ("F_GETOWN_EX", V::Dec(16)),
        ("F_SETLEASE", V::Dec(1024)),
        ("F_GETLEASE", V::Dec(1025)),
        ("F_NOTIFY", V::Dec(1026)),
        ("F_DUPFD_QUERY", V::Dec(1027)),
        ("F_CREATED_QUERY", V::Dec(1028)),
        ("F_SETPIPE_SZ", V::Dec(1031)),
        ("F_GETPIPE_SZ", V::Dec(1032)),
        ("F_ADD_SEALS", V::Dec(1033)),
        ("F_GET_SEALS", V::Dec(1034)),
        ("F_GET_RW_HINT", V::Dec(1035)),
        ("F_SET_RW_HINT", V::Dec(1036)),
        ("F_GET_FILE_RW_HINT", V::Dec(1037)),
        ("F_SET_FILE_RW_HINT", V::Dec(1038)),
        ("F_DUPFD_CLOEXEC", V::Dec(1030)),
        ("FD_CLOEXEC", V::Dec(1)),
        ("FD_PIDFS_ROOT", V::Dec(-10002)),
        ("F_RDLCK", V::Dec(0)),
        ("F_WRLCK", V::Dec(1)),
        ("F_UNLCK", V::Dec(2)),
        ("F_EXLCK", V::Dec(4)),
        ("F_SHLCK", V::Dec(8)),
        ("LOCK_SH", V::Dec(1)),
        ("LOCK_EX", V::Dec(2)),
        ("LOCK_NB", V::Dec(4)),
        ("LOCK_UN", V::Dec(8)),
        ("LOCK_MAND", V::Dec(32)),
        ("LOCK_READ", V::Dec(64)),
        ("LOCK_WRITE", V::Dec(128)),
        ("LOCK_RW", V::Dec(192)),
        ("DN_ACCESS", V::Txt("0x00000001")),
        ("DN_MODIFY", V::Txt("0x00000002")),
        ("DN_CREATE", V::Txt("0x00000004")),
        ("DN_DELETE", V::Txt("0x00000008")),
        ("DN_RENAME", V::Txt("0x00000010")),
        ("DN_ATTRIB", V::Txt("0x00000020")),
        ("DN_MULTISHOT", V::Hex(0x80000000)),
        ("F_SEAL_SEAL", V::Txt("0x0001")),
        ("F_SEAL_SHRINK", V::Txt("0x0002")),
        ("F_SEAL_GROW", V::Txt("0x0004")),
        ("F_SEAL_WRITE", V::Txt("0x0008")),
        ("F_SEAL_FUTURE_WRITE", V::Txt("0x0010")),
        ("F_SEAL_EXEC", V::Txt("0x0020")),
        ("RWH_WRITE_LIFE_NOT_SET", V::Dec(0)),
        ("RWF_WRITE_LIFE_NOT_SET", V::Dec(0)),
        ("RWH_WRITE_LIFE_NONE", V::Dec(1)),
        ("RWH_WRITE_LIFE_SHORT", V::Dec(2)),
        ("RWH_WRITE_LIFE_MEDIUM", V::Dec(3)),
        ("RWH_WRITE_LIFE_LONG", V::Dec(4)),
        ("RWH_WRITE_LIFE_EXTREME", V::Dec(5)),
        ("FAPPEND", V::Dec(1024)),
        ("FFSYNC", V::Hex(0x101000)),
        ("FASYNC", V::Hex(0x2000)),
        ("FNONBLOCK", V::Dec(2048)),
        ("FNDELAY", V::Dec(2048)),
        ("POSIX_FADV_NORMAL", V::Dec(0)),
        ("POSIX_FADV_RANDOM", V::Dec(1)),
        ("POSIX_FADV_SEQUENTIAL", V::Dec(2)),
        ("POSIX_FADV_WILLNEED", V::Dec(3)),
        ("POSIX_FADV_DONTNEED", V::Dec(4)),
        ("POSIX_FADV_NOREUSE", V::Dec(5)),
        ("SYNC_FILE_RANGE_WAIT_BEFORE", V::Dec(1)),
        ("SYNC_FILE_RANGE_WRITE", V::Dec(2)),
        ("SYNC_FILE_RANGE_WAIT_AFTER", V::Dec(4)),
        ("SYNC_FILE_RANGE_WRITE_AND_WAIT", V::Dec(7)),
        ("SPLICE_F_MOVE", V::Dec(1)),
        ("SPLICE_F_NONBLOCK", V::Dec(2)),
        ("SPLICE_F_MORE", V::Dec(4)),
        ("SPLICE_F_GIFT", V::Dec(8)),
        ("FALLOC_FL_ALLOCATE_RANGE", V::Txt("0x00")),
        ("FALLOC_FL_KEEP_SIZE", V::Txt("0x01")),
        ("FALLOC_FL_PUNCH_HOLE", V::Txt("0x02")),
        ("FALLOC_FL_NO_HIDE_STALE", V::Txt("0x04")),
        ("FALLOC_FL_COLLAPSE_RANGE", V::Txt("0x08")),
        ("FALLOC_FL_ZERO_RANGE", V::Hex(0x10)),
        ("FALLOC_FL_INSERT_RANGE", V::Hex(0x20)),
        ("FALLOC_FL_UNSHARE_RANGE", V::Hex(0x40)),
        ("FALLOC_FL_WRITE_ZEROES", V::Hex(0x80)),
        ("MAX_HANDLE_SZ", V::Dec(128)),
        ("AT_HANDLE_FID", V::Dec(512)),
        ("AT_HANDLE_MNT_ID_UNIQUE", V::Dec(1)),
        ("AT_HANDLE_CONNECTABLE", V::Dec(2)),
        ("AT_EXECVE_CHECK", V::Hex(0x10000)),
        ("OPENAT2_REGULAR", V::Txt("0x100000000ULL")),
        ("RESOLVE_NO_XDEV", V::Txt("0x01")),
        ("RESOLVE_NO_MAGICLINKS", V::Txt("0x02")),
        ("RESOLVE_NO_SYMLINKS", V::Txt("0x04")),
        ("RESOLVE_BENEATH", V::Txt("0x08")),
        ("RESOLVE_IN_ROOT", V::Hex(0x10)),
        ("RESOLVE_CACHED", V::Hex(0x20)),
        ("UTIME_NOW", V::Txt("0x3fffffffL")),
        ("UTIME_OMIT", V::Txt("0x3ffffffeL")),
        ("S_IFMT", V::Hex(0xf000)),
        ("S_IFDIR", V::Hex(0x4000)),
        ("S_IFCHR", V::Hex(0x2000)),
        ("S_IFBLK", V::Hex(0x6000)),
        ("S_IFREG", V::Hex(0x8000)),
        ("S_IFIFO", V::Hex(0x1000)),
        ("S_IFLNK", V::Hex(0xa000)),
        ("S_IFSOCK", V::Hex(0xc000)),
        ("S_ISUID", V::Dec(2048)),
        ("S_ISGID", V::Dec(1024)),
        ("S_ISVTX", V::Dec(512)),
        ("S_IRUSR", V::Dec(256)),
        ("S_IWUSR", V::Dec(128)),
        ("S_IXUSR", V::Dec(64)),
        ("S_IRWXU", V::Dec(448)),
        ("S_IRGRP", V::Dec(32)),
        ("S_IWGRP", V::Dec(16)),
        ("S_IXGRP", V::Dec(8)),
        ("S_IRWXG", V::Dec(56)),
        ("S_IROTH", V::Dec(4)),
        ("S_IWOTH", V::Dec(2)),
        ("S_IXOTH", V::Dec(1)),
        ("S_IRWXO", V::Dec(7)),
        ("R_OK", V::Dec(4)),
        ("W_OK", V::Dec(2)),
        ("X_OK", V::Dec(1)),
        ("F_OK", V::Dec(0)),
        ("SEEK_SET", V::Dec(0)),
        ("SEEK_CUR", V::Dec(1)),
        ("SEEK_END", V::Dec(2)),
        ("AT_FDCWD", V::Dec(-100)),
        ("AT_SYMLINK_NOFOLLOW", V::Hex(0x100)),
        ("AT_REMOVEDIR", V::Hex(0x200)),
        ("AT_SYMLINK_FOLLOW", V::Hex(0x400)),
        ("AT_NO_AUTOMOUNT", V::Hex(0x800)),
        ("AT_EMPTY_PATH", V::Hex(0x1000)),
        ("AT_STATX_SYNC_TYPE", V::Hex(0x6000)),
        ("AT_STATX_SYNC_AS_STAT", V::Txt("0x0000")),
        ("AT_STATX_FORCE_SYNC", V::Hex(0x2000)),
        ("AT_STATX_DONT_SYNC", V::Hex(0x4000)),
        ("AT_RECURSIVE", V::Hex(0x8000)),
        ("AT_EACCESS", V::Hex(0x200)),
        ("F_ULOCK", V::Dec(0)),
        ("F_LOCK", V::Dec(1)),
        ("F_TLOCK", V::Dec(2)),
        ("F_TEST", V::Dec(3)),
    ]),
    Item::Blank,
    Item::Block { head: "struct f_owner_ex ", body: &["", "  int type;", "  pid_t pid;", ""], tail: "" },
    Item::Block { head: "struct flock64 ", body: &["", "  short l_type;", "  short l_whence;", "  long l_start;", "  long l_len;", "  pid_t l_pid;", ""], tail: "" },
    Item::Block { head: "struct file_handle ", body: &["", "  unsigned int handle_bytes;", "  int handle_type;", "  unsigned char f_handle[];", ""], tail: "" },
    Item::Block { head: "struct open_how ", body: &["", "  uint64_t flags;", "  uint64_t mode;", "  uint64_t resolve;", ""], tail: "" },
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

pub static TRAILER: &[Item] = &[
    Item::Gate(&[
        Branch { head: "if __USE_FORTIFY_LEVEL > 0 && defined __fortify_function", items: &[
            Item::Raw(Reason::GlibcMacro, "# define __OPEN_NEEDS_MODE(oflag) (((oflag) & 0100) != 0 || ((oflag) & 0x410000) == 0x410000)"),
            Item::Include("<bits/fcntl-linux-fortify.h>"),
            Item::Include("<bits/fcntl2.h>"),
        ] },
    ], ""),
];
pub const TRAILER_CHOMP: bool = false;
