use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("MAXQUOTAS", V::Dec(3)),
        ("USRQUOTA", V::Dec(0)),
        ("GRPQUOTA", V::Dec(1)),
        ("PRJQUOTA", V::Dec(2)),
        ("SUBCMDMASK", V::Txt("0x00ff")),
        ("SUBCMDSHIFT", V::Dec(8)),
        ("Q_SYNC", V::Hex(0x800001)),
        ("Q_QUOTAON", V::Hex(0x800002)),
        ("Q_QUOTAOFF", V::Hex(0x800003)),
        ("Q_GETFMT", V::Hex(0x800004)),
        ("Q_GETINFO", V::Hex(0x800005)),
        ("Q_SETINFO", V::Hex(0x800006)),
        ("Q_GETQUOTA", V::Hex(0x800007)),
        ("Q_SETQUOTA", V::Hex(0x800008)),
        ("Q_GETNEXTQUOTA", V::Hex(0x800009)),
        ("QFMT_VFS_OLD", V::Dec(1)),
        ("QFMT_VFS_V0", V::Dec(2)),
        ("QFMT_OCFS2", V::Dec(3)),
        ("QFMT_VFS_V1", V::Dec(4)),
        ("QFMT_SHMEM", V::Dec(5)),
        ("QIF_DQBLKSIZE_BITS", V::Dec(10)),
        ("QIF_DQBLKSIZE", V::Dec(1024)),
        ("QIF_BLIMITS", V::Dec(1)),
        ("QIF_SPACE", V::Dec(2)),
        ("QIF_ILIMITS", V::Dec(4)),
        ("QIF_INODES", V::Dec(8)),
        ("QIF_BTIME", V::Dec(16)),
        ("QIF_ITIME", V::Dec(32)),
        ("QIF_LIMITS", V::Dec(5)),
        ("QIF_USAGE", V::Dec(10)),
        ("QIF_TIMES", V::Dec(48)),
        ("QIF_ALL", V::Dec(63)),
        ("IIF_BGRACE", V::Dec(1)),
        ("IIF_IGRACE", V::Dec(2)),
        ("IIF_FLAGS", V::Dec(4)),
        ("IIF_ALL", V::Dec(7)),
        ("DQF_ROOT_SQUASH", V::Dec(1)),
        ("DQF_SYS_FILE", V::Hex(0x10000)),
        ("QUOTA_NL_NOWARN", V::Dec(0)),
        ("QUOTA_NL_IHARDWARN", V::Dec(1)),
        ("QUOTA_NL_ISOFTLONGWARN", V::Dec(2)),
        ("QUOTA_NL_ISOFTWARN", V::Dec(3)),
        ("QUOTA_NL_BHARDWARN", V::Dec(4)),
        ("QUOTA_NL_BSOFTLONGWARN", V::Dec(5)),
        ("QUOTA_NL_BSOFTWARN", V::Dec(6)),
        ("QUOTA_NL_IHARDBELOW", V::Dec(7)),
        ("QUOTA_NL_ISOFTBELOW", V::Dec(8)),
        ("QUOTA_NL_BHARDBELOW", V::Dec(9)),
        ("QUOTA_NL_BSOFTBELOW", V::Dec(10)),
        ("QUOTA_NL_C_MAX", V::Dec(1)),
        ("QUOTA_NL_A_MAX", V::Dec(7)),
        ("MAX_IQ_TIME", V::Dec(604800)),
        ("MAX_DQ_TIME", V::Dec(604800)),
        ("NR_DQHASH", V::Dec(43)),
        ("NR_DQUOTS", V::Dec(256)),
    ]),
    Item::Blank,
    Item::Raw(Reason::GlibcMacro, "#define QCMD(cmd, type) (((cmd) << SUBCMDSHIFT) | ((type) & SUBCMDMASK))"),
    Item::Block { head: "struct if_dqblk ", body: &["", "  uint64_t dqb_bhardlimit;", "  uint64_t dqb_bsoftlimit;", "  uint64_t dqb_curspace;", "  uint64_t dqb_ihardlimit;", "  uint64_t dqb_isoftlimit;", "  uint64_t dqb_curinodes;", "  uint64_t dqb_btime;", "  uint64_t dqb_itime;", "  uint32_t dqb_valid;", ""], tail: "" },
    Item::Block { head: "struct dqblk ", body: &["", "  uint64_t dqb_bhardlimit;", "  uint64_t dqb_bsoftlimit;", "  uint64_t dqb_curspace;", "  uint64_t dqb_ihardlimit;", "  uint64_t dqb_isoftlimit;", "  uint64_t dqb_curinodes;", "  uint64_t dqb_btime;", "  uint64_t dqb_itime;", "  uint32_t dqb_valid;", ""], tail: "" },
    Item::Block { head: "struct if_nextdqblk ", body: &["", "  uint64_t dqb_bhardlimit;", "  uint64_t dqb_bsoftlimit;", "  uint64_t dqb_curspace;", "  uint64_t dqb_ihardlimit;", "  uint64_t dqb_isoftlimit;", "  uint64_t dqb_curinodes;", "  uint64_t dqb_btime;", "  uint64_t dqb_itime;", "  uint32_t dqb_valid;", "  uint32_t dqb_id;", ""], tail: "" },
    Item::Block { head: "struct if_dqinfo ", body: &["", "  uint64_t dqi_bgrace;", "  uint64_t dqi_igrace;", "  uint32_t dqi_flags;", "  uint32_t dqi_valid;", ""], tail: "" },
    Item::Block { head: "struct dqinfo ", body: &["", "  uint64_t dqi_bgrace;", "  uint64_t dqi_igrace;", "  uint32_t dqi_flags;", "  uint32_t dqi_valid;", ""], tail: "" },
    Item::Raw(Reason::GlibcMacro, "#define dqoff(UID) ((long)((UID) * sizeof (struct dqblk)))"),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

