use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("TTYDEF_IFLAG", V::Hex(0x2d22)),
        ("TTYDEF_OFLAG", V::Hex(0x1805)),
        ("TTYDEF_LFLAG", V::Hex(0x8a1b)),
        ("TTYDEF_CFLAG", V::Dec(1440)),
        ("TTYDEF_SPEED", V::Txt("0x2580U")),
        ("CEOF", V::Dec(4)),
        ("CEOL", V::Dec(0)),
        ("CERASE", V::Txt("0177")),
        ("CINTR", V::Dec(3)),
        ("CSTATUS", V::Dec(0)),
        ("CKILL", V::Dec(21)),
        ("CMIN", V::Dec(1)),
        ("CQUIT", V::Txt("034")),
        ("CSUSP", V::Dec(26)),
        ("CTIME", V::Dec(0)),
        ("CDSUSP", V::Dec(25)),
        ("CSTART", V::Dec(17)),
        ("CSTOP", V::Dec(19)),
        ("CLNEXT", V::Dec(22)),
        ("CDISCARD", V::Dec(15)),
        ("CWERASE", V::Dec(23)),
        ("CREPRINT", V::Dec(18)),
        ("CEOT", V::Dec(4)),
        ("CBRK", V::Dec(0)),
        ("CRPRNT", V::Dec(18)),
        ("CFLUSH", V::Dec(15)),
    ]),
    Item::Blank,
    Item::Raw(Reason::GlibcMacro, "#define CTRL(x) ((x) & 037)"),
    Item::Consts(&[
        ("CEOF", V::Txt("CTRL('d')")),
        ("CEOL", V::Txt(r#"'\0'"#)),
        ("CERASE", V::Txt("0177")),
        ("CINTR", V::Txt("CTRL('c')")),
        ("CSTATUS", V::Txt(r#"'\0'"#)),
        ("CKILL", V::Txt("CTRL('u')")),
        ("CMIN", V::Dec(1)),
        ("CQUIT", V::Txt("034")),
        ("CSUSP", V::Txt("CTRL('z')")),
        ("CTIME", V::Dec(0)),
        ("CDSUSP", V::Txt("CTRL('y')")),
        ("CSTART", V::Txt("CTRL('q')")),
        ("CSTOP", V::Txt("CTRL('s')")),
        ("CLNEXT", V::Txt("CTRL('v')")),
        ("CDISCARD", V::Txt("CTRL('o')")),
        ("CWERASE", V::Txt("CTRL('w')")),
        ("CREPRINT", V::Txt("CTRL('r')")),
        ("CEOT", V::Txt("CEOF")),
        ("CBRK", V::Txt("CEOL")),
        ("CRPRNT", V::Txt("CREPRINT")),
        ("CFLUSH", V::Txt("CDISCARD")),
    ]),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

