use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("UTIME_NOW", V::Txt("0x3fffffffL")),
        ("UTIME_OMIT", V::Txt("0x3ffffffeL")),
        ("S_IFMT", V::Hex(0xf000)),
        ("S_IFDIR", V::Hex(0x4000)),
        ("S_IFCHR", V::Hex(0x2000)),
        ("S_IFBLK", V::Hex(0x6000)),
        ("S_IFREG", V::Hex(0x8000)),
        ("S_IFIFO", V::Hex(0x1000)),
        ("S_IFLNK", V::Hex(0xa000)),
        ("S_IFSOCK", V::Hex(0xc000)),
        ("S_ISUID", V::Dec(2048)),
        ("S_ISGID", V::Dec(1024)),
        ("S_ISVTX", V::Dec(512)),
        ("S_IRUSR", V::Dec(256)),
        ("S_IWUSR", V::Dec(128)),
        ("S_IXUSR", V::Dec(64)),
        ("S_IRWXU", V::Dec(448)),
        ("S_IREAD", V::Dec(256)),
        ("S_IWRITE", V::Dec(128)),
        ("S_IEXEC", V::Dec(64)),
        ("S_IRGRP", V::Dec(32)),
        ("S_IWGRP", V::Dec(16)),
        ("S_IXGRP", V::Dec(8)),
        ("S_IRWXG", V::Dec(56)),
        ("S_IROTH", V::Dec(4)),
        ("S_IWOTH", V::Dec(2)),
        ("S_IXOTH", V::Dec(1)),
        ("S_IRWXO", V::Dec(7)),
        ("ACCESSPERMS", V::Dec(511)),
        ("ALLPERMS", V::Dec(4095)),
        ("DEFFILEMODE", V::Dec(438)),
        ("S_BLKSIZE", V::Dec(512)),
        ("STATX_TYPE", V::Txt("0x00000001U")),
        ("STATX_MODE", V::Txt("0x00000002U")),
        ("STATX_NLINK", V::Txt("0x00000004U")),
        ("STATX_UID", V::Txt("0x00000008U")),
        ("STATX_GID", V::Txt("0x00000010U")),
        ("STATX_ATIME", V::Txt("0x00000020U")),
        ("STATX_MTIME", V::Txt("0x00000040U")),
        ("STATX_CTIME", V::Txt("0x00000080U")),
        ("STATX_INO", V::Txt("0x00000100U")),
        ("STATX_SIZE", V::Txt("0x00000200U")),
        ("STATX_BLOCKS", V::Txt("0x00000400U")),
        ("STATX_BASIC_STATS", V::Txt("0x000007ffU")),
        ("STATX_BTIME", V::Txt("0x00000800U")),
        ("STATX_MNT_ID", V::Txt("0x00001000U")),
        ("STATX_DIOALIGN", V::Txt("0x00002000U")),
        ("STATX_MNT_ID_UNIQUE", V::Txt("0x00004000U")),
        ("STATX_SUBVOL", V::Txt("0x00008000U")),
        ("STATX_WRITE_ATOMIC", V::Txt("0x00010000U")),
        ("STATX_DIO_READ_ALIGN", V::Txt("0x00020000U")),
        ("STATX__RESERVED", V::Txt("0x80000000U")),
        ("STATX_ALL", V::Txt("0x00000fffU")),
        ("STATX_ATTR_COMPRESSED", V::Txt("0x00000004")),
        ("STATX_ATTR_IMMUTABLE", V::Txt("0x00000010")),
        ("STATX_ATTR_APPEND", V::Txt("0x00000020")),
        ("STATX_ATTR_NODUMP", V::Txt("0x00000040")),
        ("STATX_ATTR_ENCRYPTED", V::Txt("0x00000800")),
        ("STATX_ATTR_AUTOMOUNT", V::Txt("0x00001000")),
        ("STATX_ATTR_MOUNT_ROOT", V::Txt("0x00002000")),
        ("STATX_ATTR_VERITY", V::Txt("0x00100000")),
        ("STATX_ATTR_DAX", V::Txt("0x00200000")),
        ("STATX_ATTR_WRITE_ATOMIC", V::Txt("0x00400000")),
    ]),
    Item::Blank,
    Item::Block { head: "struct stat64 ", body: &["", "  unsigned long st_dev;", "  unsigned long st_ino;", "  unsigned long st_nlink;", "  unsigned int st_mode;", "  unsigned int st_uid;", "  unsigned int st_gid;", "  int __pad0;", "  unsigned long st_rdev;", "  long st_size;", "  long st_blksize;", "  long st_blocks;", "  struct timespec st_atim;", "  struct timespec st_mtim;", "  struct timespec st_ctim;", "  long __glibc_reserved[3];", ""], tail: "" },
    Item::Consts(&[
        ("st_atime", V::Txt("st_atim.tv_sec")),
        ("st_mtime", V::Txt("st_mtim.tv_sec")),
        ("st_ctime", V::Txt("st_ctim.tv_sec")),
    ]),
    Item::Block { head: "struct statx_timestamp ", body: &["", "  int64_t tv_sec;", "  uint32_t tv_nsec;", "  int32_t __statx_timestamp_pad1[1];", ""], tail: "" },
    Item::Block { head: "struct statx ", body: &["", "  uint32_t stx_mask;", "  uint32_t stx_blksize;", "  uint64_t stx_attributes;", "  uint32_t stx_nlink;", "  uint32_t stx_uid;", "  uint32_t stx_gid;", "  uint16_t stx_mode;", "  uint16_t __statx_pad1[1];", "  uint64_t stx_ino;", "  uint64_t stx_size;", "  uint64_t stx_blocks;", "  uint64_t stx_attributes_mask;", "  struct statx_timestamp stx_atime;", "  struct statx_timestamp stx_btime;", "  struct statx_timestamp stx_ctime;", "  struct statx_timestamp stx_mtime;", "  uint32_t stx_rdev_major;", "  uint32_t stx_rdev_minor;", "  uint32_t stx_dev_major;", "  uint32_t stx_dev_minor;", "  uint64_t stx_mnt_id;", "  uint32_t stx_dio_mem_align;", "  uint32_t stx_dio_offset_align;", "  uint64_t stx_subvol;", "  uint32_t stx_atomic_write_unit_min;", "  uint32_t stx_atomic_write_unit_max;", "  uint32_t stx_atomic_write_segments_max;", "  uint32_t stx_dio_read_offset_align;", "  uint32_t stx_atomic_write_unit_max_opt;", "  uint32_t __statx_pad2[1];", "  uint64_t __statx_pad3[8];", ""], tail: "" },
    Item::Raw(Reason::StdMacro, "#define S_ISDIR(mode) (((mode) & S_IFMT) == S_IFDIR)"),
    Item::Raw(Reason::StdMacro, "#define S_ISCHR(mode) (((mode) & S_IFMT) == S_IFCHR)"),
    Item::Raw(Reason::StdMacro, "#define S_ISBLK(mode) (((mode) & S_IFMT) == S_IFBLK)"),
    Item::Raw(Reason::StdMacro, "#define S_ISREG(mode) (((mode) & S_IFMT) == S_IFREG)"),
    Item::Raw(Reason::StdMacro, "#define S_ISFIFO(mode) (((mode) & S_IFMT) == S_IFIFO)"),
    Item::Raw(Reason::StdMacro, "#define S_ISLNK(mode) (((mode) & S_IFMT) == S_IFLNK)"),
    Item::Raw(Reason::StdMacro, "#define S_ISSOCK(mode) (((mode) & S_IFMT) == S_IFSOCK)"),
    Item::Raw(Reason::StdMacro, "#define S_TYPEISMQ(buf) ((buf)->st_mode - (buf)->st_mode)"),
    Item::Raw(Reason::StdMacro, "#define S_TYPEISSEM(buf) ((buf)->st_mode - (buf)->st_mode)"),
    Item::Raw(Reason::StdMacro, "#define S_TYPEISSHM(buf) ((buf)->st_mode - (buf)->st_mode)"),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

