use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("MAP_32BIT", V::Hex(0x40)),
        ("MAP_ABOVE4G", V::Hex(0x80)),
        ("SHADOW_STACK_SET_TOKEN", V::Hex(0x1)),
        ("MAP_GROWSDOWN", V::Txt("0x00100")),
        ("MAP_DENYWRITE", V::Txt("0x00800")),
        ("MAP_EXECUTABLE", V::Txt("0x01000")),
        ("MAP_LOCKED", V::Txt("0x02000")),
        ("MAP_NORESERVE", V::Txt("0x04000")),
        ("MAP_POPULATE", V::Txt("0x08000")),
        ("MAP_NONBLOCK", V::Hex(0x10000)),
        ("MAP_STACK", V::Hex(0x20000)),
        ("MAP_HUGETLB", V::Hex(0x40000)),
        ("MAP_SYNC", V::Hex(0x80000)),
        ("MAP_FIXED_NOREPLACE", V::Hex(0x100000)),
        ("PROT_READ", V::Hex(0x1)),
        ("PROT_WRITE", V::Hex(0x2)),
        ("PROT_EXEC", V::Hex(0x4)),
        ("PROT_NONE", V::Txt("0x0")),
        ("PROT_GROWSDOWN", V::Txt("0x01000000")),
        ("PROT_GROWSUP", V::Txt("0x02000000")),
        ("MAP_SHARED", V::Txt("0x01")),
        ("MAP_PRIVATE", V::Txt("0x02")),
        ("MAP_SHARED_VALIDATE", V::Txt("0x03")),
        ("MAP_DROPPABLE", V::Txt("0x08")),
        ("MAP_TYPE", V::Txt("0x0f")),
        ("MAP_FIXED", V::Hex(0x10)),
        ("MAP_FILE", V::Dec(0)),
        ("MAP_ANONYMOUS", V::Hex(0x20)),
        ("MAP_ANON", V::Dec(32)),
        ("MAP_HUGE_SHIFT", V::Dec(26)),
        ("MAP_HUGE_MASK", V::Hex(0x3f)),
        ("MAP_HUGE_16KB", V::Hex(0x38000000)),
        ("MAP_HUGE_64KB", V::Hex(0x40000000)),
        ("MAP_HUGE_512KB", V::Hex(0x4c000000)),
        ("MAP_HUGE_1MB", V::Hex(0x50000000)),
        ("MAP_HUGE_2MB", V::Hex(0x54000000)),
        ("MAP_HUGE_8MB", V::Hex(0x5c000000)),
        ("MAP_HUGE_16MB", V::Hex(0x60000000)),
        ("MAP_HUGE_32MB", V::Hex(0x64000000)),
        ("MAP_HUGE_256MB", V::Hex(0x70000000)),
        ("MAP_HUGE_512MB", V::Hex(0x74000000)),
        ("MAP_HUGE_1GB", V::Hex(0x78000000)),
        ("MAP_HUGE_2GB", V::Hex(0x7c000000)),
        ("MAP_HUGE_16GB", V::Txt("0x88000000U")),
        ("MS_ASYNC", V::Dec(1)),
        ("MS_SYNC", V::Dec(4)),
        ("MS_INVALIDATE", V::Dec(2)),
        ("MADV_NORMAL", V::Dec(0)),
        ("MADV_RANDOM", V::Dec(1)),
        ("MADV_SEQUENTIAL", V::Dec(2)),
        ("MADV_WILLNEED", V::Dec(3)),
        ("MADV_DONTNEED", V::Dec(4)),
        ("MADV_FREE", V::Dec(8)),
        ("MADV_REMOVE", V::Dec(9)),
        ("MADV_DONTFORK", V::Dec(10)),
        ("MADV_DOFORK", V::Dec(11)),
        ("MADV_MERGEABLE", V::Dec(12)),
        ("MADV_UNMERGEABLE", V::Dec(13)),
        ("MADV_HUGEPAGE", V::Dec(14)),
        ("MADV_NOHUGEPAGE", V::Dec(15)),
        ("MADV_DONTDUMP", V::Dec(16)),
        ("MADV_DODUMP", V::Dec(17)),
        ("MADV_WIPEONFORK", V::Dec(18)),
        ("MADV_KEEPONFORK", V::Dec(19)),
        ("MADV_COLD", V::Dec(20)),
        ("MADV_PAGEOUT", V::Dec(21)),
        ("MADV_POPULATE_READ", V::Dec(22)),
        ("MADV_POPULATE_WRITE", V::Dec(23)),
        ("MADV_DONTNEED_LOCKED", V::Dec(24)),
        ("MADV_COLLAPSE", V::Dec(25)),
        ("MADV_HWPOISON", V::Dec(100)),
        ("MADV_GUARD_INSTALL", V::Dec(102)),
        ("MADV_GUARD_REMOVE", V::Dec(103)),
        ("POSIX_MADV_NORMAL", V::Dec(0)),
        ("POSIX_MADV_RANDOM", V::Dec(1)),
        ("POSIX_MADV_SEQUENTIAL", V::Dec(2)),
        ("POSIX_MADV_WILLNEED", V::Dec(3)),
        ("POSIX_MADV_DONTNEED", V::Dec(4)),
        ("MCL_CURRENT", V::Dec(1)),
        ("MCL_FUTURE", V::Dec(2)),
        ("MCL_ONFAULT", V::Dec(4)),
        ("MREMAP_MAYMOVE", V::Dec(1)),
        ("MREMAP_FIXED", V::Dec(2)),
        ("MREMAP_DONTUNMAP", V::Dec(4)),
        ("MFD_CLOEXEC", V::Txt("1U")),
        ("MFD_ALLOW_SEALING", V::Txt("2U")),
        ("MFD_HUGETLB", V::Txt("4U")),
        ("MFD_NOEXEC_SEAL", V::Txt("8U")),
        ("MFD_EXEC", V::Txt("0x10U")),
        ("MLOCK_ONFAULT", V::Txt("1U")),
        ("PKEY_UNRESTRICTED", V::Txt("0x0")),
        ("PKEY_DISABLE_ACCESS", V::Hex(0x1)),
        ("PKEY_DISABLE_WRITE", V::Hex(0x2)),
    ]),
    Item::Blank,
    Item::Consts(&[
        ("MAP_FAILED", V::Txt("((void *)-1)")),
    ]),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

