use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("ADJ_OFFSET", V::Txt("0x0001")),
        ("ADJ_FREQUENCY", V::Txt("0x0002")),
        ("ADJ_MAXERROR", V::Txt("0x0004")),
        ("ADJ_ESTERROR", V::Txt("0x0008")),
        ("ADJ_STATUS", V::Txt("0x0010")),
        ("ADJ_TIMECONST", V::Txt("0x0020")),
        ("ADJ_TAI", V::Txt("0x0080")),
        ("ADJ_SETOFFSET", V::Txt("0x0100")),
        ("ADJ_MICRO", V::Hex(0x1000)),
        ("ADJ_NANO", V::Hex(0x2000)),
        ("ADJ_TICK", V::Hex(0x4000)),
        ("ADJ_OFFSET_SINGLESHOT", V::Hex(0x8001)),
        ("ADJ_OFFSET_SS_READ", V::Hex(0xa001)),
        ("MOD_OFFSET", V::Dec(1)),
        ("MOD_FREQUENCY", V::Dec(2)),
        ("MOD_MAXERROR", V::Dec(4)),
        ("MOD_ESTERROR", V::Dec(8)),
        ("MOD_STATUS", V::Dec(16)),
        ("MOD_TIMECONST", V::Dec(32)),
        ("MOD_CLKB", V::Hex(0x4000)),
        ("MOD_CLKA", V::Hex(0x8001)),
        ("MOD_TAI", V::Dec(128)),
        ("MOD_MICRO", V::Hex(0x1000)),
        ("MOD_NANO", V::Hex(0x2000)),
        ("STA_PLL", V::Txt("0x0001")),
        ("STA_PPSFREQ", V::Txt("0x0002")),
        ("STA_PPSTIME", V::Txt("0x0004")),
        ("STA_FLL", V::Txt("0x0008")),
        ("STA_INS", V::Txt("0x0010")),
        ("STA_DEL", V::Txt("0x0020")),
        ("STA_UNSYNC", V::Txt("0x0040")),
        ("STA_FREQHOLD", V::Txt("0x0080")),
        ("STA_PPSSIGNAL", V::Txt("0x0100")),
        ("STA_PPSJITTER", V::Txt("0x0200")),
        ("STA_PPSWANDER", V::Txt("0x0400")),
        ("STA_PPSERROR", V::Txt("0x0800")),
        ("STA_CLOCKERR", V::Hex(0x1000)),
        ("STA_NANO", V::Hex(0x2000)),
        ("STA_MODE", V::Hex(0x4000)),
        ("STA_CLK", V::Hex(0x8000)),
        ("STA_RONLY", V::Hex(0xff00)),
        ("NTP_API", V::Dec(4)),
        ("TIME_OK", V::Dec(0)),
        ("TIME_INS", V::Dec(1)),
        ("TIME_DEL", V::Dec(2)),
        ("TIME_OOP", V::Dec(3)),
        ("TIME_WAIT", V::Dec(4)),
        ("TIME_ERROR", V::Dec(5)),
        ("TIME_BAD", V::Dec(5)),
        ("MAXTC", V::Dec(6)),
    ]),
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

