use crate::model::*;

pub static AFTER_INCLUDES: &[Item] = &[
    Item::Consts(&[
        ("PT_TRACE_ME", V::Dec(0)),
        ("PT_READ_I", V::Dec(1)),
        ("PT_READ_D", V::Dec(2)),
        ("PT_READ_U", V::Dec(3)),
        ("PT_WRITE_I", V::Dec(4)),
        ("PT_WRITE_D", V::Dec(5)),
        ("PT_WRITE_U", V::Dec(6)),
        ("PT_CONTINUE", V::Dec(7)),
        ("PT_KILL", V::Dec(8)),
        ("PT_STEP", V::Dec(9)),
        ("PT_GETREGS", V::Dec(12)),
        ("PT_SETREGS", V::Dec(13)),
        ("PT_GETFPREGS", V::Dec(14)),
        ("PT_SETFPREGS", V::Dec(15)),
        ("PT_ATTACH", V::Dec(16)),
        ("PT_DETACH", V::Dec(17)),
        ("PT_GETFPXREGS", V::Dec(18)),
        ("PT_SETFPXREGS", V::Dec(19)),
        ("PT_SYSCALL", V::Dec(24)),
        ("PT_GET_THREAD_AREA", V::Dec(25)),
        ("PT_SET_THREAD_AREA", V::Dec(26)),
        ("PT_ARCH_PRCTL", V::Dec(30)),
        ("PT_SYSEMU", V::Dec(31)),
        ("PT_SYSEMU_SINGLESTEP", V::Dec(32)),
        ("PT_STEPBLOCK", V::Dec(33)),
        ("PT_SETOPTIONS", V::Hex(0x4200)),
        ("PT_GETEVENTMSG", V::Hex(0x4201)),
        ("PT_GETSIGINFO", V::Hex(0x4202)),
        ("PT_SETSIGINFO", V::Hex(0x4203)),
        ("PTRACE_GETREGSET", V::Hex(0x4204)),
        ("PTRACE_SETREGSET", V::Hex(0x4205)),
        ("PTRACE_SEIZE", V::Hex(0x4206)),
        ("PTRACE_INTERRUPT", V::Hex(0x4207)),
        ("PTRACE_LISTEN", V::Hex(0x4208)),
        ("PTRACE_PEEKSIGINFO", V::Hex(0x4209)),
        ("PTRACE_GETSIGMASK", V::Hex(0x420a)),
        ("PTRACE_SETSIGMASK", V::Hex(0x420b)),
        ("PTRACE_SECCOMP_GET_FILTER", V::Hex(0x420c)),
        ("PTRACE_SECCOMP_GET_METADATA", V::Hex(0x420d)),
        ("PTRACE_GET_SYSCALL_INFO", V::Hex(0x420e)),
        ("PTRACE_GET_RSEQ_CONFIGURATION", V::Hex(0x420f)),
        ("PTRACE_SET_SYSCALL_USER_DISPATCH_CONFIG", V::Hex(0x4210)),
        ("PTRACE_GET_SYSCALL_USER_DISPATCH_CONFIG", V::Hex(0x4211)),
    ]),
    Item::Blank,
    Item::Consts(&[
        ("PTRACE_TRACEME", V::Dec(0)),
        ("PTRACE_PEEKTEXT", V::Dec(1)),
        ("PTRACE_PEEKDATA", V::Dec(2)),
        ("PTRACE_PEEKUSER", V::Dec(3)),
        ("PTRACE_POKETEXT", V::Dec(4)),
        ("PTRACE_POKEDATA", V::Dec(5)),
        ("PTRACE_POKEUSER", V::Dec(6)),
        ("PTRACE_CONT", V::Dec(7)),
        ("PTRACE_KILL", V::Dec(8)),
        ("PTRACE_SINGLESTEP", V::Dec(9)),
        ("PTRACE_GETREGS", V::Dec(12)),
        ("PTRACE_SETREGS", V::Dec(13)),
        ("PTRACE_GETFPREGS", V::Dec(14)),
        ("PTRACE_SETFPREGS", V::Dec(15)),
        ("PTRACE_ATTACH", V::Dec(16)),
        ("PTRACE_DETACH", V::Dec(17)),
        ("PTRACE_GETFPXREGS", V::Dec(18)),
        ("PTRACE_SETFPXREGS", V::Dec(19)),
        ("PTRACE_SYSCALL", V::Dec(24)),
        ("PTRACE_GET_THREAD_AREA", V::Dec(25)),
        ("PTRACE_SET_THREAD_AREA", V::Dec(26)),
        ("PTRACE_ARCH_PRCTL", V::Dec(30)),
        ("PTRACE_SYSEMU", V::Dec(31)),
        ("PTRACE_SYSEMU_SINGLESTEP", V::Dec(32)),
        ("PTRACE_SINGLEBLOCK", V::Dec(33)),
        ("PTRACE_SETOPTIONS", V::Hex(0x4200)),
        ("PTRACE_GETEVENTMSG", V::Hex(0x4201)),
        ("PTRACE_GETSIGINFO", V::Hex(0x4202)),
        ("PTRACE_SETSIGINFO", V::Hex(0x4203)),
    ]),
    Item::Block { head: "enum __ptrace_setoptions ", body: &["", "  PTRACE_O_TRACESYSGOOD = 0x00000001,", "  PTRACE_O_TRACEFORK = 0x00000002,", "  PTRACE_O_TRACEVFORK = 0x00000004,", "  PTRACE_O_TRACECLONE = 0x00000008,", "  PTRACE_O_TRACEEXEC = 0x00000010,", "  PTRACE_O_TRACEVFORKDONE = 0x00000020,", "  PTRACE_O_TRACEEXIT = 0x00000040,", "  PTRACE_O_TRACESECCOMP = 0x00000080,", "  PTRACE_O_EXITKILL = 0x00100000,", "  PTRACE_O_SUSPEND_SECCOMP = 0x00200000,", "  PTRACE_O_MASK = 0x003000ff", ""], tail: "" },
    Item::Block { head: "enum __ptrace_eventcodes ", body: &["", "  PTRACE_EVENT_FORK = 1,", "  PTRACE_EVENT_VFORK = 2,", "  PTRACE_EVENT_CLONE = 3,", "  PTRACE_EVENT_EXEC = 4,", "  PTRACE_EVENT_VFORK_DONE = 5,", "  PTRACE_EVENT_EXIT = 6,", "  PTRACE_EVENT_SECCOMP = 7,", "  PTRACE_EVENT_STOP = 128", ""], tail: "" },
    Item::Block { head: "enum __ptrace_get_syscall_info_op ", body: &["", "  PTRACE_SYSCALL_INFO_NONE = 0,", "  PTRACE_SYSCALL_INFO_ENTRY = 1,", "  PTRACE_SYSCALL_INFO_EXIT = 2,", "  PTRACE_SYSCALL_INFO_SECCOMP = 3", ""], tail: "" },
    Item::Block { head: "struct __ptrace_peeksiginfo_args ", body: &["", "  uint64_t off;", "  uint32_t flags;", "  int32_t nr;", ""], tail: "" },
    Item::Block { head: "enum __ptrace_peeksiginfo_flags ", body: &["", "  PTRACE_PEEKSIGINFO_SHARED = (1 << 0)", ""], tail: "" },
];
pub const AFTER_INCLUDES_CHOMP: bool = false;

