#ifndef _RLIBC_LIMITS_H
#define _RLIBC_LIMITS_H 1
#include <features.h>
#define AIO_PRIO_DELTA_MAX 20
#define BC_BASE_MAX _POSIX2_BC_BASE_MAX
#define BC_DIM_MAX _POSIX2_BC_DIM_MAX
#define BC_SCALE_MAX _POSIX2_BC_SCALE_MAX
#define BC_STRING_MAX _POSIX2_BC_STRING_MAX
#define BITINT_MAXWIDTH __BITINT_MAXWIDTH__
#define BOOL_MAX 1
#define BOOL_WIDTH 1
#define CHARCLASS_NAME_MAX 2048
#define CHAR_BIT __CHAR_BIT__
#define CHAR_MAX SCHAR_MAX
#define CHAR_MIN SCHAR_MIN
#define CHAR_WIDTH __SCHAR_WIDTH__
#define COLL_WEIGHTS_MAX 255
#define DELAYTIMER_MAX 2147483647
#define EXPR_NEST_MAX _POSIX2_EXPR_NEST_MAX
#define HOST_NAME_MAX 64
#define INT_MAX __INT_MAX__
#define INT_MIN (-INT_MAX - 1)
#define INT_WIDTH __INT_WIDTH__
#define IOV_MAX __IOV_MAX
#define LINE_MAX _POSIX2_LINE_MAX
#define LLONG_MAX __LONG_LONG_MAX__
#define LLONG_MIN (-LLONG_MAX - 1LL)
#define LLONG_WIDTH __LONG_LONG_WIDTH__
#define LOGIN_NAME_MAX 256
#define LONG_BIT 64
#define LONG_LONG_MAX __LONG_LONG_MAX__
#define LONG_LONG_MIN (-LONG_LONG_MAX - 1LL)
#define LONG_MAX __LONG_MAX__
#define LONG_MIN (-LONG_MAX - 1L)
#define LONG_WIDTH __LONG_WIDTH__
#define MAX_CANON 255
#define MAX_INPUT 255
#define MB_LEN_MAX 16
#define MQ_PRIO_MAX 32768
#define NAME_MAX 255
#define NGROUPS_MAX 65536
#define NL_ARGMAX _POSIX_ARG_MAX
#define NL_LANGMAX _POSIX2_LINE_MAX
#define NL_MSGMAX INT_MAX
#define NL_NMAX INT_MAX
#define NL_SETMAX INT_MAX
#define NL_TEXTMAX INT_MAX
#define NZERO 20
#define PATH_MAX 4096
#define PIPE_BUF 4096
#define PTHREAD_DESTRUCTOR_ITERATIONS _POSIX_THREAD_DESTRUCTOR_ITERATIONS
#define PTHREAD_KEYS_MAX 1024
#ifdef __USE_DYNAMIC_STACK_SIZE
extern long int __sysconf (int __name) __THROW;
# define PTHREAD_STACK_MIN __sysconf (__SC_THREAD_STACK_MIN_VALUE)
#else
# define PTHREAD_STACK_MIN 16384
#endif
#define RE_DUP_MAX (0x7fff)
#define RTSIG_MAX 32
#define SCHAR_MAX __SCHAR_MAX__
#define SCHAR_MIN (-SCHAR_MAX - 1)
#define SCHAR_WIDTH __SCHAR_WIDTH__
#define SEM_VALUE_MAX (2147483647)
#define SHRT_MAX __SHRT_MAX__
#define SHRT_MIN (-SHRT_MAX - 1)
#define SHRT_WIDTH __SHRT_WIDTH__
#define SSIZE_MAX LONG_MAX
#define TTY_NAME_MAX 32
#define UCHAR_MAX (SCHAR_MAX * 2 + 1)
#define UCHAR_WIDTH __SCHAR_WIDTH__
#define UINT_MAX (INT_MAX * 2U + 1U)
#define UINT_WIDTH __INT_WIDTH__
#define ULLONG_MAX (LLONG_MAX * 2ULL + 1ULL)
#define ULLONG_WIDTH __LONG_LONG_WIDTH__
#define ULONG_LONG_MAX (LONG_LONG_MAX * 2ULL + 1ULL)
#define ULONG_MAX (LONG_MAX * 2UL + 1UL)
#define ULONG_WIDTH __LONG_WIDTH__
#define USHRT_MAX (SHRT_MAX * 2 + 1)
#define USHRT_WIDTH __SHRT_WIDTH__
#define WORD_BIT 32
#define XATTR_LIST_MAX 65536
#define XATTR_NAME_MAX 255
#define XATTR_SIZE_MAX 65536
#define _BITS_POSIX2_LIM_H 1
#define _BITS_UIO_LIM_H 1
#define _LIMITS_H___ 
#define _LINUX_LIMITS_H 
#define _POSIX2_BC_BASE_MAX 99
#define _POSIX2_BC_DIM_MAX 2048
#define _POSIX2_BC_SCALE_MAX 99
#define _POSIX2_BC_STRING_MAX 1000
#define _POSIX2_CHARCLASS_NAME_MAX 14
#define _POSIX2_COLL_WEIGHTS_MAX 2
#define _POSIX2_EXPR_NEST_MAX 32
#define _POSIX2_LINE_MAX 2048
#define _POSIX2_RE_DUP_MAX 255
#define _POSIX_AIO_LISTIO_MAX 2
#define _POSIX_AIO_MAX 1
#define _POSIX_ARG_MAX 4096
#define _POSIX_CHILD_MAX 25
#define _POSIX_CLOCKRES_MIN 20000000
#define _POSIX_DELAYTIMER_MAX 32
#define _POSIX_FD_SETSIZE _POSIX_OPEN_MAX
#define _POSIX_HIWAT _POSIX_PIPE_BUF
#define _POSIX_HOST_NAME_MAX 255
#define _POSIX_LINK_MAX 8
#define _POSIX_LOGIN_NAME_MAX 9
#define _POSIX_MAX_CANON 255
#define _POSIX_MAX_INPUT 255
#define _POSIX_MQ_OPEN_MAX 8
#define _POSIX_MQ_PRIO_MAX 32
#define _POSIX_NAME_MAX 14
#define _POSIX_NGROUPS_MAX 8
#define _POSIX_OPEN_MAX 20
#define _POSIX_PATH_MAX 256
#define _POSIX_PIPE_BUF 512
#define _POSIX_QLIMIT 1
#define _POSIX_RE_DUP_MAX 255
#define _POSIX_RTSIG_MAX 8
#define _POSIX_SEM_NSEMS_MAX 256
#define _POSIX_SEM_VALUE_MAX 32767
#define _POSIX_SIGQUEUE_MAX 32
#define _POSIX_SSIZE_MAX 32767
#define _POSIX_STREAM_MAX 8
#define _POSIX_SYMLINK_MAX 255
#define _POSIX_SYMLOOP_MAX 8
#define _POSIX_THREAD_DESTRUCTOR_ITERATIONS 4
#define _POSIX_THREAD_KEYS_MAX 128
#define _POSIX_THREAD_THREADS_MAX 64
#define _POSIX_TIMER_MAX 32
#define _POSIX_TTY_NAME_MAX 9
#define _POSIX_TZNAME_MAX 6
#define _POSIX_UIO_MAXIOV 16
#define _XOPEN_IOV_MAX _POSIX_UIO_MAXIOV
#define _XOPEN_LIM_H 1
#define __IOV_MAX 1024
#define __SC_THREAD_STACK_MIN_VALUE 75
#define __STDC_VERSION_LIMITS_H__ 202311L

#endif
