use crate::model::*;

pub static HDR: Header = Header {
    path: "argp.h",
    items: &[
        Item::Guard { name: "_RLIBC_ARGP_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<bits/rlibc-features.h>"),
            Item::Include("<stdio.h>"),
            Item::Include("<ctype.h>"),
            Item::Include("<getopt.h>"),
            Item::Include("<limits.h>"),
            Item::Include("<errno.h>"),
            Item::Blank,
            Item::ExternBegin,
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifndef __error_t_defined", items: &[
                    Item::Consts(&[
                        ("__error_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("int", "error_t"),
                ] },
            ], ""),
            Item::Blank,
            Item::Block { head: "struct argp_option ", body: &["", "  const char *name;", "  int key;", "  const char *arg;", "  int flags;", "  const char *doc;", "  int group;", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("OPTION_ARG_OPTIONAL", V::Txt("0x1")),
                ("OPTION_HIDDEN", V::Txt("0x2")),
                ("OPTION_ALIAS", V::Txt("0x4")),
                ("OPTION_DOC", V::Txt("0x8")),
                ("OPTION_NO_USAGE", V::Txt("0x10")),
            ]),
            Item::Blank,
            Item::Decl("struct argp;"),
            Item::Decl("struct argp_state;"),
            Item::Decl("struct argp_child;"),
            Item::Blank,
            Item::Decl("typedef error_t (*argp_parser_t) (int __key, char *__arg, struct argp_state *__state);"),
            Item::Blank,
            Item::Consts(&[
                ("ARGP_ERR_UNKNOWN", V::Txt("E2BIG")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("ARGP_KEY_ARG", V::Dec(0)),
                ("ARGP_KEY_ARGS", V::Hex(0x1000006)),
                ("ARGP_KEY_END", V::Hex(0x1000001)),
                ("ARGP_KEY_NO_ARGS", V::Hex(0x1000002)),
                ("ARGP_KEY_INIT", V::Hex(0x1000003)),
                ("ARGP_KEY_FINI", V::Hex(0x1000007)),
                ("ARGP_KEY_SUCCESS", V::Hex(0x1000004)),
                ("ARGP_KEY_ERROR", V::Hex(0x1000005)),
            ]),
            Item::Blank,
            Item::Block { head: "struct argp ", body: &["", "  const struct argp_option *options;", "  argp_parser_t parser;", "  const char *args_doc;", r#"  const char *doc;"#, "  const struct argp_child *children;", "  char *(*help_filter) (int __key, const char *__text, void *__input);", "  const char *argp_domain;", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("ARGP_KEY_HELP_PRE_DOC", V::Hex(0x2000001)),
                ("ARGP_KEY_HELP_POST_DOC", V::Hex(0x2000002)),
                ("ARGP_KEY_HELP_HEADER", V::Hex(0x2000003)),
                ("ARGP_KEY_HELP_EXTRA", V::Hex(0x2000004)),
                ("ARGP_KEY_HELP_DUP_ARGS_NOTE", V::Hex(0x2000005)),
                ("ARGP_KEY_HELP_ARGS_DOC", V::Hex(0x2000006)),
            ]),
            Item::Blank,
            Item::Block { head: "struct argp_child ", body: &["", "  const struct argp *argp;", "  int flags;", "  const char *header;", "  int group;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct argp_state ", body: &["", "  const struct argp *root_argp;", "  int argc;", "  char **argv;", "  int next;", "  unsigned flags;", "  unsigned arg_num;", "  int quoted;", "  void *input;", "  void **child_inputs;", "  void *hook;", "  char *name;", "  FILE *err_stream;", "  FILE *out_stream;", "  void *pstate;", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("ARGP_PARSE_ARGV0", V::Txt("0x01")),
                ("ARGP_NO_ERRS", V::Txt("0x02")),
                ("ARGP_NO_ARGS", V::Txt("0x04")),
                ("ARGP_IN_ORDER", V::Txt("0x08")),
                ("ARGP_NO_HELP", V::Hex(0x10)),
                ("ARGP_NO_EXIT", V::Hex(0x20)),
                ("ARGP_LONG_ONLY", V::Hex(0x40)),
                ("ARGP_SILENT", V::Txt("(ARGP_NO_EXIT | ARGP_NO_ERRS | ARGP_NO_HELP)")),
            ]),
            Item::Blank,
            Item::Decl("extern error_t argp_parse (const struct argp *__restrict __argp, int __argc, char **__restrict __argv, unsigned __flags, int *__restrict __arg_index, void *__restrict __input);"),
            Item::Blank,
            Item::Decl("extern const char *argp_program_version;"),
            Item::Decl("extern void (*argp_program_version_hook) (FILE *__restrict __stream, struct argp_state *__restrict __state);"),
            Item::Decl("extern const char *argp_program_bug_address;"),
            Item::Decl("extern error_t argp_err_exit_status;"),
            Item::Blank,
            Item::Consts(&[
                ("ARGP_HELP_USAGE", V::Txt("0x01")),
                ("ARGP_HELP_SHORT_USAGE", V::Txt("0x02")),
                ("ARGP_HELP_SEE", V::Txt("0x04")),
                ("ARGP_HELP_LONG", V::Txt("0x08")),
                ("ARGP_HELP_PRE_DOC", V::Hex(0x10)),
                ("ARGP_HELP_POST_DOC", V::Hex(0x20)),
                ("ARGP_HELP_DOC", V::Txt("(ARGP_HELP_PRE_DOC | ARGP_HELP_POST_DOC)")),
                ("ARGP_HELP_BUG_ADDR", V::Hex(0x40)),
                ("ARGP_HELP_LONG_ONLY", V::Hex(0x80)),
                ("ARGP_HELP_EXIT_ERR", V::Hex(0x100)),
                ("ARGP_HELP_EXIT_OK", V::Hex(0x200)),
                ("ARGP_HELP_STD_ERR", V::Txt("(ARGP_HELP_SEE | ARGP_HELP_EXIT_ERR)")),
                ("ARGP_HELP_STD_USAGE", V::Txt("(ARGP_HELP_SHORT_USAGE | ARGP_HELP_SEE | ARGP_HELP_EXIT_ERR)")),
                ("ARGP_HELP_STD_HELP", V::Txt("(ARGP_HELP_SHORT_USAGE | ARGP_HELP_LONG | ARGP_HELP_EXIT_OK | ARGP_HELP_DOC | ARGP_HELP_BUG_ADDR)")),
            ]),
            Item::Blank,
            Item::Decl("extern void argp_help (const struct argp *__restrict __argp, FILE *__restrict __stream, unsigned __flags, char *__restrict __name);"),
            Item::Decl("extern void argp_state_help (const struct argp_state *__restrict __state, FILE *__restrict __stream, unsigned int __flags);"),
            Item::Decl("extern void argp_usage (const struct argp_state *__state);"),
            Item::Decl(r#"extern void argp_error (const struct argp_state *__restrict __state, const char *__restrict __fmt, ...)
  __attribute__ ((__format__ (__printf__, 2, 3)));"#),
            Item::Decl(r#"extern void argp_failure (const struct argp_state *__restrict __state, int __status, int __errnum, const char *__restrict __fmt, ...)
  __attribute__ ((__format__ (__printf__, 4, 5)));"#),
            Item::Decl("extern int _option_is_short (const struct argp_option *__opt) __attribute__ ((__nothrow__));"),
            Item::Decl("extern int _option_is_end (const struct argp_option *__opt) __attribute__ ((__nothrow__));"),
            Item::Decl("extern void *_argp_input (const struct argp *__restrict __argp, const struct argp_state *__restrict __state) __attribute__ ((__nothrow__));"),
            Item::Blank,
            Item::ExternEnd,
            Item::Blank,
        ]},
    ],
};
