use crate::model::*;

pub static HDR: Header = Header {
    path: "arpa/nameser.h",
    items: &[
        Item::Guard { name: "_ARPA_NAMESER_H", value: "1", end: "", items: &[
            Item::Include("<stdint.h>"),
            Item::Include("<sys/types.h>"),
            Item::Include("<stddef.h>"),
            Item::Blank,
            Item::Consts(&[
                ("__NAMESER", V::Dec(19991006)),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("NS_CMPRSFLGS", V::Dec(192)),
                ("NS_DEFAULTPORT", V::Dec(53)),
                ("NS_HFIXEDSZ", V::Dec(12)),
                ("NS_IN6ADDRSZ", V::Dec(16)),
                ("NS_INADDRSZ", V::Dec(4)),
                ("NS_INT16SZ", V::Dec(2)),
                ("NS_INT32SZ", V::Dec(4)),
                ("NS_INT8SZ", V::Dec(1)),
                ("NS_MAXCDNAME", V::Dec(255)),
                ("NS_MAXDNAME", V::Dec(1025)),
                ("NS_MAXLABEL", V::Dec(63)),
                ("NS_MAXMSG", V::Dec(65535)),
                ("NS_OPT_DNSSEC_OK", V::Txt("0x00008000U")),
                ("NS_OPT_NSID", V::Dec(3)),
                ("NS_PACKETSZ", V::Dec(512)),
                ("NS_QFIXEDSZ", V::Dec(4)),
                ("NS_RRFIXEDSZ", V::Dec(10)),
                ("NS_TSIG_ERROR_FORMERR", V::Dec(-12)),
                ("NS_TSIG_ERROR_NO_SPACE", V::Dec(-11)),
                ("NS_TSIG_ERROR_NO_TSIG", V::Dec(-10)),
                ("NS_TSIG_FUDGE", V::Dec(300)),
                ("NS_TSIG_TCP_COUNT", V::Dec(100)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define NS_GET16(s, cp) do { const unsigned char *t_cp = (const unsigned char *) (cp); (s) = ((uint16_t) t_cp[0] << 8) | ((uint16_t) t_cp[1]); (cp) += NS_INT16SZ; } while (0)"),
            Item::Raw(Reason::GlibcMacro, "#define NS_GET32(l, cp) do { const unsigned char *t_cp = (const unsigned char *) (cp); (l) = ((uint32_t) t_cp[0] << 24) | ((uint32_t) t_cp[1] << 16) | ((uint32_t) t_cp[2] << 8) | ((uint32_t) t_cp[3]); (cp) += NS_INT32SZ; } while (0)"),
            Item::Raw(Reason::GlibcMacro, "#define NS_PUT16(s, cp) do { uint16_t t_s = (uint16_t) (s); unsigned char *t_cp = (unsigned char *) (cp); *t_cp++ = t_s >> 8; *t_cp = t_s; (cp) += NS_INT16SZ; } while (0)"),
            Item::Raw(Reason::GlibcMacro, "#define NS_PUT32(l, cp) do { uint32_t t_l = (uint32_t) (l); unsigned char *t_cp = (unsigned char *) (cp); *t_cp++ = t_l >> 24; *t_cp++ = t_l >> 16; *t_cp++ = t_l >> 8; *t_cp = t_l; (cp) += NS_INT32SZ; } while (0)"),
            Item::Blank,
            Item::Block { head: "typedef enum __ns_sect ", body: &["", "  ns_s_qd = 0,", "  ns_s_zn = 0,", "  ns_s_an = 1,", "  ns_s_pr = 1,", "  ns_s_ns = 2,", "  ns_s_ud = 2,", "  ns_s_ar = 3,", "  ns_s_max = 4", ""], tail: " ns_sect" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_flag ", body: &["", "  ns_f_qr = 0,", "  ns_f_opcode = 1,", "  ns_f_aa = 2,", "  ns_f_tc = 3,", "  ns_f_rd = 4,", "  ns_f_ra = 5,", "  ns_f_z = 6,", "  ns_f_ad = 7,", "  ns_f_cd = 8,", "  ns_f_rcode = 9,", "  ns_f_max = 10", ""], tail: " ns_flag" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_opcode ", body: &["", "  ns_o_query = 0,", "  ns_o_iquery = 1,", "  ns_o_status = 2,", "  ns_o_notify = 4,", "  ns_o_update = 5,", "  ns_o_max = 6", ""], tail: " ns_opcode" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_rcode ", body: &["", "  ns_r_noerror = 0,", "  ns_r_formerr = 1,", "  ns_r_servfail = 2,", "  ns_r_nxdomain = 3,", "  ns_r_notimpl = 4,", "  ns_r_refused = 5,", "  ns_r_yxdomain = 6,", "  ns_r_yxrrset = 7,", "  ns_r_nxrrset = 8,", "  ns_r_notauth = 9,", "  ns_r_notzone = 10,", "  ns_r_max = 11,", "  ns_r_badvers = 16,", "  ns_r_badsig = 16,", "  ns_r_badkey = 17,", "  ns_r_badtime = 18", ""], tail: " ns_rcode" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_update_operation ", body: &["", "  ns_uop_delete = 0,", "  ns_uop_add = 1,", "  ns_uop_max = 2", ""], tail: " ns_update_operation" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_type ", body: &["", "  ns_t_invalid = 0,", "  ns_t_a = 1,", "  ns_t_ns = 2,", "  ns_t_md = 3,", "  ns_t_mf = 4,", "  ns_t_cname = 5,", "  ns_t_soa = 6,", "  ns_t_mb = 7,", "  ns_t_mg = 8,", "  ns_t_mr = 9,", "  ns_t_null = 10,", "  ns_t_wks = 11,", "  ns_t_ptr = 12,", "  ns_t_hinfo = 13,", "  ns_t_minfo = 14,", "  ns_t_mx = 15,", "  ns_t_txt = 16,", "  ns_t_rp = 17,", "  ns_t_afsdb = 18,", "  ns_t_x25 = 19,", "  ns_t_isdn = 20,", "  ns_t_rt = 21,", "  ns_t_nsap = 22,", "  ns_t_nsap_ptr = 23,", "  ns_t_sig = 24,", "  ns_t_key = 25,", "  ns_t_px = 26,", "  ns_t_gpos = 27,", "  ns_t_aaaa = 28,", "  ns_t_loc = 29,", "  ns_t_nxt = 30,", "  ns_t_eid = 31,", "  ns_t_nimloc = 32,", "  ns_t_srv = 33,", "  ns_t_atma = 34,", "  ns_t_naptr = 35,", "  ns_t_kx = 36,", "  ns_t_cert = 37,", "  ns_t_a6 = 38,", "  ns_t_dname = 39,", "  ns_t_sink = 40,", "  ns_t_opt = 41,", "  ns_t_apl = 42,", "  ns_t_ds = 43,", "  ns_t_sshfp = 44,", "  ns_t_ipseckey = 45,", "  ns_t_rrsig = 46,", "  ns_t_nsec = 47,", "  ns_t_dnskey = 48,", "  ns_t_dhcid = 49,", "  ns_t_nsec3 = 50,", "  ns_t_nsec3param = 51,", "  ns_t_tlsa = 52,", "  ns_t_smimea = 53,", "  ns_t_hip = 55,", "  ns_t_ninfo = 56,", "  ns_t_rkey = 57,", "  ns_t_talink = 58,", "  ns_t_cds = 59,", "  ns_t_cdnskey = 60,", "  ns_t_openpgpkey = 61,", "  ns_t_csync = 62,", "  ns_t_spf = 99,", "  ns_t_uinfo = 100,", "  ns_t_uid = 101,", "  ns_t_gid = 102,", "  ns_t_unspec = 103,", "  ns_t_nid = 104,", "  ns_t_l32 = 105,", "  ns_t_l64 = 106,", "  ns_t_lp = 107,", "  ns_t_eui48 = 108,", "  ns_t_eui64 = 109,", "  ns_t_tkey = 249,", "  ns_t_tsig = 250,", "  ns_t_ixfr = 251,", "  ns_t_axfr = 252,", "  ns_t_mailb = 253,", "  ns_t_maila = 254,", "  ns_t_any = 255,", "  ns_t_uri = 256,", "  ns_t_caa = 257,", "  ns_t_avc = 258,", "  ns_t_ta = 32768,", "  ns_t_dlv = 32769,", "  ns_t_max = 65536", ""], tail: " ns_type" },
            Item::Blank,
            Item::Block { head: "typedef enum __ns_class ", body: &["", "  ns_c_invalid = 0,", "  ns_c_in = 1,", "  ns_c_2 = 2,", "  ns_c_chaos = 3,", "  ns_c_hs = 4,", "  ns_c_none = 254,", "  ns_c_any = 255,", "  ns_c_max = 65536", ""], tail: " ns_class" },
            Item::Blank,
            Item::Blank,
            Item::Block { head: "typedef enum __ns_cert_types ", body: &["", "  cert_t_pkix = 1,", "  cert_t_spki = 2,", "  cert_t_pgp = 3,", "  cert_t_url = 253,", "  cert_t_oid = 254", ""], tail: " ns_cert_types" },
            Item::Blank,
            Item::Block { head: "typedef struct __ns_msg ", body: &["", "  const unsigned char *_msg, *_eom;", "  uint16_t _id, _flags, _counts[ns_s_max];", "  const unsigned char *_sections[ns_s_max];", "  ns_sect _sect;", "  int _rrnum;", "  const unsigned char *_msg_ptr;", ""], tail: " ns_msg" },
            Item::Blank,
            Item::Block { head: "struct _ns_flagdata ", body: &[" int mask, shift; "], tail: "" },
            Item::Decl("extern const struct _ns_flagdata _ns_flagdata[];"),
            Item::Blank,
            Item::Raw(Reason::GlibcMacro, "#define ns_msg_id(handle) ((handle)._id + 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_msg_base(handle) ((handle)._msg + 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_msg_end(handle) ((handle)._eom + 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_msg_size(handle) ((handle)._eom - (handle)._msg)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_msg_count(handle, section) ((handle)._counts[section] + 0)"),
            Item::Blank,
            Item::Block { head: "typedef struct __ns_rr ", body: &["", "  char name[NS_MAXDNAME];", "  uint16_t type;", "  uint16_t rr_class;", "  uint32_t ttl;", "  uint16_t rdlength;", "  const unsigned char *rdata;", ""], tail: " ns_rr" },
            Item::Blank,
            Item::Raw(Reason::GlibcMacro, r#"#define ns_rr_name(rr) (((rr).name[0] != '\0') ? (rr).name : ".")"#),
            Item::Raw(Reason::GlibcMacro, "#define ns_rr_type(rr) ((ns_type) ((rr).type + 0))"),
            Item::Raw(Reason::GlibcMacro, "#define ns_rr_class(rr) ((ns_class) ((rr).rr_class + 0))"),
            Item::Raw(Reason::GlibcMacro, "#define ns_rr_ttl(rr) ((rr).ttl + 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_rr_rdlen(rr) ((rr).rdlength + 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ns_rr_rdata(rr) ((rr).rdata + 0)"),
            Item::Blank,
            Item::Block { head: "struct ns_tsig_key ", body: &["", "  char name[NS_MAXDNAME], alg[NS_MAXDNAME];", "  unsigned char *data;", "  int len;", ""], tail: "" },
            Item::Typedef("struct ns_tsig_key", "ns_tsig_key"),
            Item::Blank,
            Item::Block { head: "struct ns_tcp_tsig_state ", body: &["", "  int counter;", "  struct dst_key *key;", "  void *ctx;", "  unsigned char sig[NS_PACKETSZ];", "  int siglen;", ""], tail: "" },
            Item::Typedef("struct ns_tcp_tsig_state", "ns_tcp_tsig_state"),
            Item::Blank,
            Item::Consts(&[
                ("NS_TSIG_ALG_HMAC_MD5", V::Txt(r#""HMAC-MD5.SIG-ALG.REG.INT""#)),
            ]),
            Item::Blank,
            Item::Block { head: "typedef struct ", body: &["", "  unsigned id :16;", "  unsigned rd :1;", "  unsigned tc :1;", "  unsigned aa :1;", "  unsigned opcode :4;", "  unsigned qr :1;", "  unsigned rcode :4;", "  unsigned cd :1;", "  unsigned ad :1;", "  unsigned unused :1;", "  unsigned ra :1;", "  unsigned qdcount :16;", "  unsigned ancount :16;", "  unsigned nscount :16;", "  unsigned arcount :16;", ""], tail: " HEADER" },
            Item::Blank,
            Item::Consts(&[
                ("PACKETSZ", V::Txt("NS_PACKETSZ")),
                ("MAXDNAME", V::Txt("NS_MAXDNAME")),
                ("MAXCDNAME", V::Txt("NS_MAXCDNAME")),
                ("MAXLABEL", V::Txt("NS_MAXLABEL")),
                ("HFIXEDSZ", V::Txt("NS_HFIXEDSZ")),
                ("QFIXEDSZ", V::Txt("NS_QFIXEDSZ")),
                ("RRFIXEDSZ", V::Txt("NS_RRFIXEDSZ")),
                ("INT32SZ", V::Txt("NS_INT32SZ")),
                ("INT16SZ", V::Txt("NS_INT16SZ")),
                ("INT8SZ", V::Txt("NS_INT8SZ")),
                ("INADDRSZ", V::Txt("NS_INADDRSZ")),
                ("IN6ADDRSZ", V::Txt("NS_IN6ADDRSZ")),
                ("INDIR_MASK", V::Txt("NS_CMPRSFLGS")),
                ("NAMESERVER_PORT", V::Txt("NS_DEFAULTPORT")),
                ("S_ZONE", V::Txt("ns_s_zn")),
                ("S_PREREQ", V::Txt("ns_s_pr")),
                ("S_UPDATE", V::Txt("ns_s_ud")),
                ("S_ADDT", V::Txt("ns_s_ar")),
                ("QUERY", V::Txt("ns_o_query")),
                ("IQUERY", V::Txt("ns_o_iquery")),
                ("STATUS", V::Txt("ns_o_status")),
                ("NS_NOTIFY_OP", V::Txt("ns_o_notify")),
                ("NS_UPDATE_OP", V::Txt("ns_o_update")),
                ("NOERROR", V::Txt("ns_r_noerror")),
                ("FORMERR", V::Txt("ns_r_formerr")),
                ("SERVFAIL", V::Txt("ns_r_servfail")),
                ("NXDOMAIN", V::Txt("ns_r_nxdomain")),
                ("NOTIMP", V::Txt("ns_r_notimpl")),
                ("REFUSED", V::Txt("ns_r_refused")),
                ("YXDOMAIN", V::Txt("ns_r_yxdomain")),
                ("YXRRSET", V::Txt("ns_r_yxrrset")),
                ("NXRRSET", V::Txt("ns_r_nxrrset")),
                ("NOTAUTH", V::Txt("ns_r_notauth")),
                ("NOTZONE", V::Txt("ns_r_notzone")),
                ("DELETE", V::Txt("ns_uop_delete")),
                ("ADD", V::Txt("ns_uop_add")),
                ("T_A", V::Txt("ns_t_a")),
                ("T_NS", V::Txt("ns_t_ns")),
                ("T_MD", V::Txt("ns_t_md")),
                ("T_MF", V::Txt("ns_t_mf")),
                ("T_CNAME", V::Txt("ns_t_cname")),
                ("T_SOA", V::Txt("ns_t_soa")),
                ("T_MB", V::Txt("ns_t_mb")),
                ("T_MG", V::Txt("ns_t_mg")),
                ("T_MR", V::Txt("ns_t_mr")),
                ("T_NULL", V::Txt("ns_t_null")),
                ("T_WKS", V::Txt("ns_t_wks")),
                ("T_PTR", V::Txt("ns_t_ptr")),
                ("T_HINFO", V::Txt("ns_t_hinfo")),
                ("T_MINFO", V::Txt("ns_t_minfo")),
                ("T_MX", V::Txt("ns_t_mx")),
                ("T_TXT", V::Txt("ns_t_txt")),
                ("T_RP", V::Txt("ns_t_rp")),
                ("T_AFSDB", V::Txt("ns_t_afsdb")),
                ("T_X25", V::Txt("ns_t_x25")),
                ("T_ISDN", V::Txt("ns_t_isdn")),
                ("T_RT", V::Txt("ns_t_rt")),
                ("T_NSAP", V::Txt("ns_t_nsap")),
                ("T_NSAP_PTR", V::Txt("ns_t_nsap_ptr")),
                ("T_SIG", V::Txt("ns_t_sig")),
                ("T_KEY", V::Txt("ns_t_key")),
                ("T_PX", V::Txt("ns_t_px")),
                ("T_GPOS", V::Txt("ns_t_gpos")),
                ("T_AAAA", V::Txt("ns_t_aaaa")),
                ("T_LOC", V::Txt("ns_t_loc")),
                ("T_NXT", V::Txt("ns_t_nxt")),
                ("T_EID", V::Txt("ns_t_eid")),
                ("T_NIMLOC", V::Txt("ns_t_nimloc")),
                ("T_SRV", V::Txt("ns_t_srv")),
                ("T_ATMA", V::Txt("ns_t_atma")),
                ("T_NAPTR", V::Txt("ns_t_naptr")),
                ("T_KX", V::Txt("ns_t_kx")),
                ("T_CERT", V::Txt("ns_t_cert")),
                ("T_A6", V::Txt("ns_t_a6")),
                ("T_DNAME", V::Txt("ns_t_dname")),
                ("T_SINK", V::Txt("ns_t_sink")),
                ("T_OPT", V::Txt("ns_t_opt")),
                ("T_APL", V::Txt("ns_t_apl")),
                ("T_DS", V::Txt("ns_t_ds")),
                ("T_SSHFP", V::Txt("ns_t_sshfp")),
                ("T_IPSECKEY", V::Txt("ns_t_ipseckey")),
                ("T_RRSIG", V::Txt("ns_t_rrsig")),
                ("T_NSEC", V::Txt("ns_t_nsec")),
                ("T_DNSKEY", V::Txt("ns_t_dnskey")),
                ("T_DHCID", V::Txt("ns_t_dhcid")),
                ("T_NSEC3", V::Txt("ns_t_nsec3")),
                ("T_NSEC3PARAM", V::Txt("ns_t_nsec3param")),
                ("T_TLSA", V::Txt("ns_t_tlsa")),
                ("T_SMIMEA", V::Txt("ns_t_smimea")),
                ("T_HIP", V::Txt("ns_t_hip")),
                ("T_NINFO", V::Txt("ns_t_ninfo")),
                ("T_RKEY", V::Txt("ns_t_rkey")),
                ("T_TALINK", V::Txt("ns_t_talink")),
                ("T_CDS", V::Txt("ns_t_cds")),
                ("T_CDNSKEY", V::Txt("ns_t_cdnskey")),
                ("T_OPENPGPKEY", V::Txt("ns_t_openpgpkey")),
                ("T_CSYNC", V::Txt("ns_t_csync")),
                ("T_SPF", V::Txt("ns_t_spf")),
                ("T_UINFO", V::Txt("ns_t_uinfo")),
                ("T_UID", V::Txt("ns_t_uid")),
                ("T_GID", V::Txt("ns_t_gid")),
                ("T_UNSPEC", V::Txt("ns_t_unspec")),
                ("T_NID", V::Txt("ns_t_nid")),
                ("T_L32", V::Txt("ns_t_l32")),
                ("T_L64", V::Txt("ns_t_l64")),
                ("T_LP", V::Txt("ns_t_lp")),
                ("T_EUI48", V::Txt("ns_t_eui48")),
                ("T_EUI64", V::Txt("ns_t_eui64")),
                ("T_TKEY", V::Txt("ns_t_tkey")),
                ("T_TSIG", V::Txt("ns_t_tsig")),
                ("T_IXFR", V::Txt("ns_t_ixfr")),
                ("T_AXFR", V::Txt("ns_t_axfr")),
                ("T_MAILB", V::Txt("ns_t_mailb")),
                ("T_MAILA", V::Txt("ns_t_maila")),
                ("T_ANY", V::Txt("ns_t_any")),
                ("T_URI", V::Txt("ns_t_uri")),
                ("T_CAA", V::Txt("ns_t_caa")),
                ("T_AVC", V::Txt("ns_t_avc")),
                ("T_TA", V::Txt("ns_t_ta")),
                ("T_DLV", V::Txt("ns_t_dlv")),
                ("C_IN", V::Txt("ns_c_in")),
                ("C_CHAOS", V::Txt("ns_c_chaos")),
                ("C_HS", V::Txt("ns_c_hs")),
                ("C_NONE", V::Txt("ns_c_none")),
                ("C_ANY", V::Txt("ns_c_any")),
                ("GETSHORT", V::Txt("NS_GET16")),
                ("GETLONG", V::Txt("NS_GET32")),
                ("PUTSHORT", V::Txt("NS_PUT16")),
                ("PUTLONG", V::Txt("NS_PUT32")),
            ]),
            Item::Blank,
            Item::Include("<bits/rlibc-net-nameser.h>"),
        ]},
    ],
};
