use crate::model::*;

pub static HDR: Header = Header {
    path: "arpa/telnet.h",
    items: &[
        Item::Guard { name: "_ARPA_TELNET_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::ExternBegin,
            Item::Consts(&[
                ("ABORT", V::Dec(238)),
                ("AO", V::Dec(245)),
                ("AUTHTYPE_CNT", V::Dec(5)),
                ("AUTHTYPE_KERBEROS_V4", V::Dec(1)),
                ("AUTHTYPE_KERBEROS_V5", V::Dec(2)),
                ("AUTHTYPE_MINK", V::Dec(4)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define AUTHTYPE_NAME_OK(x) ((unsigned int)(x) < AUTHTYPE_CNT)"),
            Item::Consts(&[
                ("AUTHTYPE_NULL", V::Dec(0)),
                ("AUTHTYPE_SPX", V::Dec(3)),
                ("AUTHTYPE_TEST", V::Dec(99)),
                ("AUTH_HOW_MASK", V::Dec(2)),
                ("AUTH_HOW_MUTUAL", V::Dec(2)),
                ("AUTH_HOW_ONE_WAY", V::Dec(0)),
                ("AUTH_WHO_CLIENT", V::Dec(0)),
                ("AUTH_WHO_MASK", V::Dec(1)),
                ("AUTH_WHO_SERVER", V::Dec(1)),
                ("AYT", V::Dec(246)),
                ("BREAK", V::Dec(243)),
                ("DM", V::Dec(242)),
                ("DO", V::Dec(253)),
                ("DONT", V::Dec(254)),
                ("EC", V::Dec(247)),
                ("EL", V::Dec(248)),
                ("ENCRYPT_CNT", V::Dec(9)),
                ("ENCRYPT_DEC_KEYID", V::Dec(8)),
                ("ENCRYPT_ENC_KEYID", V::Dec(7)),
                ("ENCRYPT_END", V::Dec(4)),
                ("ENCRYPT_IS", V::Dec(0)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define ENCRYPT_NAME_OK(x) ((unsigned int)(x) < ENCRYPT_CNT)"),
            Item::Consts(&[
                ("ENCRYPT_REPLY", V::Dec(2)),
                ("ENCRYPT_REQEND", V::Dec(6)),
                ("ENCRYPT_REQSTART", V::Dec(5)),
                ("ENCRYPT_START", V::Dec(3)),
                ("ENCRYPT_SUPPORT", V::Dec(1)),
                ("ENCTYPE_ANY", V::Dec(0)),
                ("ENCTYPE_CNT", V::Dec(3)),
                ("ENCTYPE_DES_CFB64", V::Dec(1)),
                ("ENCTYPE_DES_OFB64", V::Dec(2)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define ENCTYPE_NAME_OK(x) ((unsigned int)(x) < ENCTYPE_CNT)"),
            Item::Consts(&[
                ("ENV_ESC", V::Dec(2)),
                ("ENV_USERVAR", V::Dec(3)),
                ("EOR", V::Dec(239)),
                ("GA", V::Dec(249)),
                ("IAC", V::Dec(255)),
                ("IP", V::Dec(244)),
                ("LFLOW_OFF", V::Dec(0)),
                ("LFLOW_ON", V::Dec(1)),
                ("LFLOW_RESTART_ANY", V::Dec(2)),
                ("LFLOW_RESTART_XON", V::Dec(3)),
                ("LM_FORWARDMASK", V::Dec(2)),
                ("LM_MODE", V::Dec(1)),
                ("LM_SLC", V::Dec(3)),
                ("MODE_ACK", V::Txt("0x04")),
                ("MODE_ECHO", V::Txt("0x0200")),
                ("MODE_EDIT", V::Txt("0x01")),
                ("MODE_FLOW", V::Txt("0x0100")),
                ("MODE_FORCE", V::Hex(0x1000)),
                ("MODE_INBIN", V::Txt("0x0400")),
                ("MODE_LIT_ECHO", V::Hex(0x10)),
                ("MODE_MASK", V::Hex(0x1f)),
                ("MODE_OUTBIN", V::Txt("0x0800")),
                ("MODE_SOFT_TAB", V::Txt("0x08")),
                ("MODE_TRAPSIG", V::Txt("0x02")),
                ("NEW_ENV_VALUE", V::Dec(1)),
                ("NEW_ENV_VAR", V::Dec(0)),
                ("NOP", V::Dec(241)),
                ("NSLC", V::Dec(18)),
                ("NTELOPTS", V::Txt("(1+TELOPT_NEW_ENVIRON)")),
                ("OLD_ENV_VALUE", V::Dec(0)),
                ("OLD_ENV_VAR", V::Dec(1)),
                ("SB", V::Dec(250)),
                ("SE", V::Dec(240)),
                ("SLC_ABORT", V::Dec(7)),
                ("SLC_ACK", V::Hex(0x80)),
                ("SLC_AO", V::Dec(4)),
                ("SLC_AYT", V::Dec(5)),
                ("SLC_BRK", V::Dec(2)),
                ("SLC_CANTCHANGE", V::Dec(1)),
                ("SLC_DEFAULT", V::Dec(3)),
                ("SLC_EC", V::Dec(10)),
                ("SLC_EL", V::Dec(11)),
                ("SLC_EOF", V::Dec(8)),
                ("SLC_EOR", V::Dec(6)),
                ("SLC_EW", V::Dec(12)),
                ("SLC_FLAGS", V::Dec(1)),
                ("SLC_FLUSHIN", V::Hex(0x40)),
                ("SLC_FLUSHOUT", V::Hex(0x20)),
                ("SLC_FORW1", V::Dec(17)),
                ("SLC_FORW2", V::Dec(18)),
                ("SLC_FUNC", V::Dec(0)),
                ("SLC_IP", V::Dec(3)),
                ("SLC_LEVELBITS", V::Txt("0x03")),
                ("SLC_LNEXT", V::Dec(14)),
                ("SLC_NAMELIST", V::Txt(r#""0", "SYNCH", "BRK", "IP", "AO", "AYT", "EOR", "ABORT", "EOF", "SUSP", "EC", "EL", "EW", "RP", "LNEXT", "XON", "XOFF", "FORW1", "FORW2", 0,"#)),
                ("SLC_NAMES", V::Txt("SLC_NAMELIST")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define SLC_NAME_OK(x) ((unsigned int)(x) <= NSLC)"),
            Item::Consts(&[
                ("SLC_NOSUPPORT", V::Dec(0)),
                ("SLC_RP", V::Dec(13)),
                ("SLC_SUSP", V::Dec(9)),
                ("SLC_SYNCH", V::Dec(1)),
                ("SLC_VALUE", V::Dec(2)),
                ("SLC_VARIABLE", V::Dec(2)),
                ("SLC_XOFF", V::Dec(16)),
                ("SLC_XON", V::Dec(15)),
                ("SUSP", V::Dec(237)),
                ("SYNCH", V::Dec(242)),
                ("TELCMD_FIRST", V::Txt("xEOF")),
                ("TELCMD_LAST", V::Txt("IAC")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define TELCMD_OK(x) ((unsigned int)(x) <= TELCMD_LAST && (unsigned int)(x) >= TELCMD_FIRST)"),
            Item::Consts(&[
                ("TELOPT_3270REGIME", V::Dec(29)),
                ("TELOPT_AUTHENTICATION", V::Dec(37)),
                ("TELOPT_BINARY", V::Dec(0)),
                ("TELOPT_BM", V::Dec(19)),
                ("TELOPT_DET", V::Dec(20)),
                ("TELOPT_ECHO", V::Dec(1)),
                ("TELOPT_ENCRYPT", V::Dec(38)),
                ("TELOPT_EOR", V::Dec(25)),
                ("TELOPT_EXOPL", V::Dec(255)),
                ("TELOPT_LFLOW", V::Dec(33)),
                ("TELOPT_LINEMODE", V::Dec(34)),
                ("TELOPT_LOGOUT", V::Dec(18)),
                ("TELOPT_NAMS", V::Dec(4)),
                ("TELOPT_NAOCRD", V::Dec(10)),
                ("TELOPT_NAOFFD", V::Dec(13)),
                ("TELOPT_NAOHTD", V::Dec(12)),
                ("TELOPT_NAOHTS", V::Dec(11)),
                ("TELOPT_NAOL", V::Dec(8)),
                ("TELOPT_NAOLFD", V::Dec(16)),
                ("TELOPT_NAOP", V::Dec(9)),
                ("TELOPT_NAOVTD", V::Dec(15)),
                ("TELOPT_NAOVTS", V::Dec(14)),
                ("TELOPT_NAWS", V::Dec(31)),
                ("TELOPT_NEW_ENVIRON", V::Dec(39)),
                ("TELOPT_OLD_ENVIRON", V::Dec(36)),
                ("TELOPT_OUTMRK", V::Dec(27)),
                ("TELOPT_RCP", V::Dec(2)),
                ("TELOPT_RCTE", V::Dec(7)),
                ("TELOPT_SGA", V::Dec(3)),
                ("TELOPT_SNDLOC", V::Dec(23)),
                ("TELOPT_STATUS", V::Dec(5)),
                ("TELOPT_SUPDUP", V::Dec(21)),
                ("TELOPT_SUPDUPOUTPUT", V::Dec(22)),
                ("TELOPT_TM", V::Dec(6)),
                ("TELOPT_TSPEED", V::Dec(32)),
                ("TELOPT_TTYLOC", V::Dec(28)),
                ("TELOPT_TTYPE", V::Dec(24)),
                ("TELOPT_TUID", V::Dec(26)),
                ("TELOPT_X3PAD", V::Dec(30)),
                ("TELOPT_XASCII", V::Dec(17)),
                ("TELOPT_XDISPLOC", V::Dec(35)),
                ("TELQUAL_INFO", V::Dec(2)),
                ("TELQUAL_IS", V::Dec(0)),
                ("TELQUAL_NAME", V::Dec(3)),
                ("TELQUAL_REPLY", V::Dec(2)),
                ("TELQUAL_SEND", V::Dec(1)),
                ("WILL", V::Dec(251)),
                ("WONT", V::Dec(252)),
                ("xEOF", V::Dec(236)),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
