use crate::model::*;

pub static HDR: Header = Header {
    path: "bits/rlibc-cdefs.h",
    items: &[
        Item::Guard { name: "_RLIBC_CDEFS_H", value: "1", end: "", items: &[
            Item::Raw(Reason::GlibcMacro, "#define __ASMNAME(cname) __ASMNAME2 (__USER_LABEL_PREFIX__, cname)"),
            Item::Raw(Reason::GlibcMacro, "#define __ASMNAME2(prefix,cname) __STRING (prefix) cname"),
            Item::Gate(&[
                Branch { head: "ifdef __cplusplus", items: &[Item::Consts(&[("__BEGIN_DECLS", V::Txt("extern \"C\" {"))])] },
                Branch { head: "else", items: &[Item::Consts(&[("__BEGIN_DECLS", V::Sp(" "))])] },
            ], ""),
            Item::Consts(&[
                ("__COLD", V::Txt("__attribute__ ((__cold__))")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __CONCAT(x,y) x ## y"),
            Item::Gate(&[
                Branch { head: "ifdef __cplusplus", items: &[Item::Consts(&[("__END_DECLS", V::Txt("}"))])] },
                Branch { head: "else", items: &[Item::Consts(&[("__END_DECLS", V::Sp(" "))])] },
            ], ""),
            Item::Raw(Reason::GlibcMacro, "#define __GLIBC_USE(F) __GLIBC_USE_ ## F"),
            Item::Consts(&[
                ("__GLIBC_USE_IEC_60559_BFP_EXT", V::Dec(1)),
                ("__GLIBC_USE_IEC_60559_BFP_EXT_C23", V::Dec(1)),
                ("__GLIBC_USE_IEC_60559_EXT", V::Dec(1)),
                ("__GLIBC_USE_IEC_60559_FUNCS_EXT", V::Dec(1)),
                ("__GLIBC_USE_IEC_60559_FUNCS_EXT_C23", V::Dec(1)),
                ("__GLIBC_USE_IEC_60559_TYPES_EXT", V::Dec(1)),
                ("__GLIBC_USE_LIB_EXT2", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __GNUC_PREREQ(maj,min) ((__GNUC__ << 16) + __GNUC_MINOR__ >= ((maj) << 16) + (min))"),
            Item::Consts(&[
                ("__HAVE_GENERIC_SELECTION", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __KERNEL_STRICT_NAMES "),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR(name,proto) name proto"),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR1(name,proto,alias) name proto"),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR1_NTH(name,proto,alias) name proto __THROW"),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR2_DECL(name) "),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR_DECL(name) "),
            Item::Raw(Reason::GlibcMacro, "#define __LDBL_REDIR_NTH(name,proto) name proto __THROW"),
            Item::Consts(&[
                ("__LDOUBLE_REDIRECTS_TO_FLOAT128_ABI", V::Dec(0)),
                ("__LEAF", V::Txt(", __leaf__")),
                ("__LEAF_ATTR", V::Txt("__attribute__ ((__leaf__))")),
            ]),
            Item::Raw(Reason::Attribute, "#define __NTH(fct) __attribute__ ((__nothrow__ __LEAF)) fct"),
            Item::Raw(Reason::Attribute, "#define __NTHNL(fct) __attribute__ ((__nothrow__)) fct"),
            Item::Raw(Reason::GlibcMacro, "#define __P(args) args"),
            Item::Raw(Reason::GlibcMacro, "#define __PMT(args) args"),
            Item::Raw(Reason::GlibcMacro, "#define __REDIRECT(name,proto,alias) name proto __asm__ (__ASMNAME (#alias))"),
            Item::Consts(&[
                ("__REDIRECT_FORTIFY", V::Txt("__REDIRECT")),
                ("__REDIRECT_FORTIFY_NTH", V::Txt("__REDIRECT_NTH")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __REDIRECT_LDBL(name,proto,alias) __REDIRECT (name, proto, alias)"),
            Item::Raw(Reason::GlibcMacro, "#define __REDIRECT_NTH(name,proto,alias) name proto __asm__ (__ASMNAME (#alias)) __THROW"),
            Item::Raw(Reason::GlibcMacro, "#define __REDIRECT_NTHNL(name,proto,alias) name proto __asm__ (__ASMNAME (#alias)) __THROWNL"),
            Item::Raw(Reason::GlibcMacro, "#define __REDIRECT_NTH_LDBL(name,proto,alias) __REDIRECT_NTH (name, proto, alias)"),
            Item::Raw(Reason::GlibcMacro, "#define __STRING(x) #x"),
            Item::Consts(&[
                ("__SYSCALL_WORDSIZE", V::Dec(64)),
                ("__THROW", V::Txt("__attribute__ ((__nothrow__ __LEAF))")),
                ("__THROWNL", V::Txt("__attribute__ ((__nothrow__))")),
                ("__TIMESIZE", V::Txt("__WORDSIZE")),
                ("__WORDSIZE", V::Dec(64)),
                ("__WORDSIZE_TIME64_COMPAT32", V::Dec(1)),
                ("__always_inline", V::Txt("__inline __attribute__ ((__always_inline__))")),
            ]),
            Item::Raw(Reason::Attribute, "#define __attr_access(x) __attribute__ ((__access__ x))"),
            Item::Raw(Reason::Attribute, "#define __attr_access_none(argno) __attribute__ ((__access__ (__none__, argno)))"),
            Item::Raw(Reason::Attribute, "#define __attr_dealloc(dealloc,argno) __attribute__ ((__malloc__ (dealloc, argno)))"),
            Item::Consts(&[
                ("__attr_dealloc_free", V::Txt("__attr_dealloc (__builtin_free, 1)")),
            ]),
            Item::Raw(Reason::Attribute, "#define __attribute_alloc_align__(param) __attribute__ ((__alloc_align__ param))"),
            Item::Raw(Reason::Attribute, "#define __attribute_alloc_size__(params) __attribute__ ((__alloc_size__ params))"),
            Item::Consts(&[
                ("__attribute_artificial__", V::Txt("__attribute__ ((__artificial__))")),
                ("__attribute_const__", V::Txt("__attribute__ ((__const__))")),
            ]),
            Item::Raw(Reason::Attribute, "#define __attribute_copy__(arg) __attribute__ ((__copy__ (arg)))"),
            Item::Consts(&[
                ("__attribute_deprecated__", V::Txt("__attribute__ ((__deprecated__))")),
            ]),
            Item::Raw(Reason::Attribute, "#define __attribute_deprecated_msg__(msg) __attribute__ ((__deprecated__ (msg)))"),
            Item::Raw(Reason::Attribute, "#define __attribute_format_arg__(x) __attribute__ ((__format_arg__ (x)))"),
            Item::Raw(Reason::Attribute, "#define __attribute_format_strfmon__(a,b) __attribute__ ((__format__ (__strfmon__, a, b)))"),
            Item::Consts(&[
                ("__attribute_malloc__", V::Txt("__attribute__ ((__malloc__))")),
                ("__attribute_maybe_unused__", V::Txt("__attribute__ ((__unused__))")),
                ("__attribute_noinline__", V::Txt("__attribute__ ((__noinline__))")),
            ]),
            Item::Raw(Reason::Attribute, "#define __attribute_nonnull__(params) __attribute__ ((__nonnull__ params))"),
            Item::Consts(&[
                ("__attribute_nonstring__", V::Txt("__attribute__ ((__nonstring__))")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __attribute_overloadable__ "),
            Item::Consts(&[
                ("__attribute_pure__", V::Txt("__attribute__ ((__pure__))")),
                ("__attribute_returns_twice__", V::Txt("__attribute__ ((__returns_twice__))")),
                ("__attribute_struct_may_alias__", V::Txt("__attribute__ ((__may_alias__))")),
                ("__attribute_used__", V::Txt("__attribute__ ((__used__))")),
                ("__attribute_warn_unused_result__", V::Txt("__attribute__ ((__warn_unused_result__))")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __bos(ptr) __builtin_object_size (ptr, __USE_FORTIFY_LEVEL > 1)"),
            Item::Raw(Reason::GlibcMacro, "#define __bos0(ptr) __builtin_object_size (ptr, 0)"),
            Item::Raw(Reason::Attribute, "#define __errordecl(name,msg) extern void name (void) __attribute__((__error__ (msg)))"),
            Item::Consts(&[
                ("__extern_always_inline", V::Txt("extern __always_inline __attribute__ ((__gnu_inline__))")),
                ("__extern_inline", V::Txt("extern __inline __attribute__ ((__gnu_inline__))")),
                ("__flexarr", V::Txt("[]")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __fortified_attr_access(a,o,s) __attr_access ((a, o, s))"),
            Item::Consts(&[
                ("__fortify_function", V::Txt("__extern_always_inline __attribute_artificial__")),
                ("__glibc_c99_flexarr_available", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_clang_prereq(maj,min) 0"),
            Item::Raw(Reason::Generic, "#define __glibc_const_generic(PTR,CTYPE,CALL) _Generic (0 ? (PTR) : (void *) 1, const void *: (CTYPE) (CALL), default: CALL)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_has_attribute(attr) __has_attribute (attr)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_has_builtin(name) __has_builtin (name)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_has_extension(ext) __has_extension (ext)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_likely(cond) __builtin_expect ((cond), 1)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_macro_warning(message) __glibc_macro_warning1 (GCC warning message)"),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_macro_warning1(message) _Pragma (#message)"),
            Item::Gate(&[
                Branch { head: "if __USE_FORTIFY_LEVEL == 3 && __GNUC__ >= 12", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_objsize0(__o) __builtin_dynamic_object_size (__o, 0)"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_objsize(__o) __builtin_dynamic_object_size (__o, 1)"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_objsize(__o) __bos (__o)"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_objsize0(__o) __bos0 (__o)"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "if __USE_FORTIFY_LEVEL > 0", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_safe_len_cond(__l, __s, __osz) ((__l) <= (__osz) / (__s))"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_unsigned_or_positive(__l) ((__typeof (__l)) 0 < (__typeof (__l)) -1 || (__builtin_constant_p (__l) && (__l) > 0))"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_safe_or_unknown_len(__l, __s, __osz) ((__builtin_constant_p (__osz) && (__osz) == (__SIZE_TYPE__) -1) || (__glibc_unsigned_or_positive (__l) && __builtin_constant_p (__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), (__s), (__osz))) && __glibc_safe_len_cond ((__SIZE_TYPE__) (__l), (__s), (__osz))))"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_unsafe_len(__l, __s, __osz) (__glibc_unsigned_or_positive (__l) && __builtin_constant_p (__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz)) && !__glibc_safe_len_cond ((__SIZE_TYPE__) (__l), __s, __osz))"),
                    Item::Consts(&[
                        ("__fortify_use_clang", V::Dec(0)),
                    ]),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warning(__c, __msg)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warning_only_if_bos0_lt(__n, __buf, __complaint)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warning_only_if_bos0_lt2(__n, __buf, __div, complaint)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warning_only_if_bos_lt(__n, __buf, __complaint)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warning_only_if_bos_lt2(__n, __buf, div, __complaint)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_overload_arg(__type, __attr, __name) __type __attr __name"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_overload_arg0(__type, __attr, __name) __fortify_clang_overload_arg (__type, __attr, __name)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warn_if_src_too_large(__dest, __src)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warn_if_dest_too_small(__dest, __len)"),
                    Item::Raw(Reason::GlibcMacro, "# define __fortify_clang_warn_if_dest_too_small0(__dest, __len)"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_fortify(f, __l, __s, __osz, ...) (__glibc_safe_or_unknown_len (__l, __s, __osz) ? __ ## f ## _alias (__VA_ARGS__) : (__glibc_unsafe_len (__l, __s, __osz) ? __ ## f ## _chk_warn (__VA_ARGS__, __osz) : __ ## f ## _chk (__VA_ARGS__, __osz)))"),
                    Item::Raw(Reason::GlibcMacro, "# define __glibc_fortify_n(f, __l, __s, __osz, ...) (__glibc_safe_or_unknown_len (__l, __s, __osz) ? __ ## f ## _alias (__VA_ARGS__) : (__glibc_unsafe_len (__l, __s, __osz) ? __ ## f ## _chk_warn (__VA_ARGS__, (__osz) / (__s)) : __ ## f ## _chk (__VA_ARGS__, (__osz) / (__s))))"),
                ] },
            ], ""),
            Item::Raw(Reason::GlibcMacro, "#define __glibc_unlikely(cond) __builtin_expect ((cond), 0)"),
            Item::Raw(Reason::GlibcMacro, "#define __nonnull(params) __attribute_nonnull__ (params)"),
            Item::Consts(&[
                ("__ptr_t", V::Txt("void *")),
            ]),
            Item::Gate(&[
                Branch { head: "ifdef __cplusplus", items: &[Item::Consts(&[("__restrict_arr", V::Sp(" "))])] },
                Branch { head: "else", items: &[Item::Consts(&[("__restrict_arr", V::Txt("__restrict"))])] },
            ], ""),
            Item::Consts(&[
                ("__returns_nonnull", V::Txt("__attribute__ ((__returns_nonnull__))")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __stub___compat_bdflush "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_chflags "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_fchflags "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_gtty "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_revoke "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_setlogin "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_sigreturn "),
            Item::Raw(Reason::GlibcMacro, "#define __stub_stty "),
            Item::Raw(Reason::GlibcMacro, "#define __va_arg_pack() __builtin_va_arg_pack ()"),
            Item::Raw(Reason::GlibcMacro, "#define __va_arg_pack_len() __builtin_va_arg_pack_len ()"),
            Item::Raw(Reason::Attribute, "#define __warnattr(msg) __attribute__((__warning__ (msg)))"),
            Item::Gate(&[
                Branch { head: "if defined __USE_FORTIFY_LEVEL && __USE_FORTIFY_LEVEL > 0", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __wur __attribute_warn_unused_result__"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __wur "),
                ] },
            ], ""),
            Item::Blank,
        ]},
    ],
};
