use crate::model::*;

pub static HDR: Header = Header {
    path: "bits/pthreadtypes.h",
    items: &[
        Item::Guard { name: "_RLIBC_BITS_PTHREADTYPES_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Consts(&[
                ("__SIZEOF_PTHREAD_ATTR_T", V::Dec(56)),
                ("__SIZEOF_PTHREAD_MUTEX_T", V::Dec(40)),
                ("__SIZEOF_PTHREAD_MUTEXATTR_T", V::Dec(4)),
                ("__SIZEOF_PTHREAD_COND_T", V::Dec(48)),
                ("__SIZEOF_PTHREAD_CONDATTR_T", V::Dec(4)),
                ("__SIZEOF_PTHREAD_RWLOCK_T", V::Dec(56)),
                ("__SIZEOF_PTHREAD_RWLOCKATTR_T", V::Dec(8)),
                ("__SIZEOF_PTHREAD_BARRIER_T", V::Dec(32)),
                ("__SIZEOF_PTHREAD_BARRIERATTR_T", V::Dec(4)),
                ("__SIZEOF_SEM_T", V::Dec(32)),
            ]),
            Item::Blank,
            Item::Typedef("unsigned long int", "pthread_t"),
            Item::Blank,
            Item::Block { head: "union pthread_attr_t ", body: &["", "  char __size[__SIZEOF_PTHREAD_ATTR_T];", "  long int __align;", ""], tail: "" },
            Item::Gate(&[
                Branch { head: "ifndef __have_pthread_attr_t", items: &[
                    Item::Typedef("union pthread_attr_t", "pthread_attr_t"),
                    Item::Consts(&[
                        ("__have_pthread_attr_t", V::Dec(1)),
                    ]),
                ] },
            ], ""),
            Item::Blank,
            Item::Block { head: "typedef struct __pthread_internal_list ", body: &["", "  struct __pthread_internal_list *__prev;", "  struct __pthread_internal_list *__next;", ""], tail: " __pthread_list_t" },
            Item::Blank,
            Item::Block { head: "typedef struct __pthread_internal_slist ", body: &["", "  struct __pthread_internal_slist *__next;", ""], tail: " __pthread_slist_t" },
            Item::Blank,
            Item::Block { head: "struct __pthread_mutex_s ", body: &["", "  int __lock;", "  unsigned int __count;", "  int __owner;", "  unsigned int __nusers;", "  int __kind;", "  short __spins;", "  short __unused;", "  __pthread_list_t __list;", ""], tail: "" },
            Item::Consts(&[
                ("__PTHREAD_MUTEX_HAVE_PREV", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define __PTHREAD_MUTEX_INITIALIZER(__kind) 0, 0, 0, 0, __kind, 0, 0, { NULL, NULL }"),
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  struct __pthread_mutex_s __data;", "  char __size[__SIZEOF_PTHREAD_MUTEX_T];", "  long int __align;", ""], tail: " pthread_mutex_t" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  char __size[__SIZEOF_PTHREAD_MUTEXATTR_T];", "  int __align;", ""], tail: " pthread_mutexattr_t" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  unsigned long long int __value64;", "  struct {", "    unsigned int __low;", "    unsigned int __high;", "  } __value32;", ""], tail: " __atomic_wide_counter" },
            Item::Blank,
            Item::Block { head: "struct __pthread_cond_s ", body: &["", "  __atomic_wide_counter __wseq;", "  __atomic_wide_counter __g1_start;", "  unsigned int __g_size[2];", "  unsigned int __g1_orig_size;", "  unsigned int __wrefs;", "  unsigned int __g_signals[2];", "  unsigned int __unused_initialized_1;", "  unsigned int __unused_initialized_2;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  struct __pthread_cond_s __data;", "  char __size[__SIZEOF_PTHREAD_COND_T];", "  long long int __align;", ""], tail: " pthread_cond_t" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  char __size[__SIZEOF_PTHREAD_CONDATTR_T];", "  int __align;", ""], tail: " pthread_condattr_t" },
            Item::Blank,
            Item::Typedef("unsigned int", "pthread_key_t"),
            Item::Typedef("int", "pthread_once_t"),
            Item::Blank,
            Item::Block { head: "struct __pthread_rwlock_arch_t ", body: &["", "  unsigned int __readers;", "  unsigned int __writers;", "  unsigned int __wrphase_futex;", "  unsigned int __writers_futex;", "  unsigned int __pad3;", "  unsigned int __pad4;", "  int __cur_writer;", "  int __shared;", "  unsigned long int __pad1;", "  unsigned long int __pad2;", "  unsigned int __flags;", ""], tail: "" },
            Item::Raw(Reason::GlibcMacro, "#define __PTHREAD_RWLOCK_INITIALIZER(__flags) 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, __flags"),
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  struct __pthread_rwlock_arch_t __data;", "  char __size[__SIZEOF_PTHREAD_RWLOCK_T];", "  long int __align;", ""], tail: " pthread_rwlock_t" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  char __size[__SIZEOF_PTHREAD_RWLOCKATTR_T];", "  long int __align;", ""], tail: " pthread_rwlockattr_t" },
            Item::Blank,
            Item::Typedef("volatile int", "pthread_spinlock_t"),
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  char __size[__SIZEOF_PTHREAD_BARRIER_T];", "  long int __align;", ""], tail: " pthread_barrier_t" },
            Item::Blank,
            Item::Block { head: "typedef union ", body: &["", "  char __size[__SIZEOF_PTHREAD_BARRIERATTR_T];", "  int __align;", ""], tail: " pthread_barrierattr_t" },
            Item::Blank,
        ]},
    ],
};
