use crate::model::*;

pub static HDR: Header = Header {
    path: "bits/types.h",
    items: &[
        Item::Guard { name: "_BITS_TYPES_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Typedef("unsigned char", "__u_char"),
            Item::Typedef("unsigned short int", "__u_short"),
            Item::Typedef("unsigned int", "__u_int"),
            Item::Typedef("unsigned long int", "__u_long"),
            Item::Blank,
            Item::Typedef("signed char", "__int8_t"),
            Item::Typedef("unsigned char", "__uint8_t"),
            Item::Typedef("signed short int", "__int16_t"),
            Item::Typedef("unsigned short int", "__uint16_t"),
            Item::Typedef("signed int", "__int32_t"),
            Item::Typedef("unsigned int", "__uint32_t"),
            Item::Typedef("signed long int", "__int64_t"),
            Item::Typedef("unsigned long int", "__uint64_t"),
            Item::Blank,
            Item::Typedef("__int8_t", "__int_least8_t"),
            Item::Typedef("__uint8_t", "__uint_least8_t"),
            Item::Typedef("__int16_t", "__int_least16_t"),
            Item::Typedef("__uint16_t", "__uint_least16_t"),
            Item::Typedef("__int32_t", "__int_least32_t"),
            Item::Typedef("__uint32_t", "__uint_least32_t"),
            Item::Typedef("__int64_t", "__int_least64_t"),
            Item::Typedef("__uint64_t", "__uint_least64_t"),
            Item::Blank,
            Item::Typedef("long int", "__quad_t"),
            Item::Typedef("unsigned long int", "__u_quad_t"),
            Item::Typedef("long int", "__intmax_t"),
            Item::Typedef("unsigned long int", "__uintmax_t"),
            Item::Blank,
            Item::Typedef("unsigned long int", "__dev_t"),
            Item::Typedef("unsigned int", "__uid_t"),
            Item::Typedef("unsigned int", "__gid_t"),
            Item::Typedef("unsigned long int", "__ino_t"),
            Item::Typedef("unsigned long int", "__ino64_t"),
            Item::Typedef("unsigned int", "__mode_t"),
            Item::Typedef("unsigned long int", "__nlink_t"),
            Item::Typedef("long int", "__off_t"),
            Item::Typedef("long int", "__off64_t"),
            Item::Typedef("int", "__pid_t"),
            Item::Block { head: "typedef struct ", body: &[" int __val[2]; "], tail: " __fsid_t" },
            Item::Typedef("long int", "__clock_t"),
            Item::Typedef("unsigned long int", "__rlim_t"),
            Item::Typedef("unsigned long int", "__rlim64_t"),
            Item::Typedef("unsigned int", "__id_t"),
            Item::Typedef("long int", "__time_t"),
            Item::Typedef("unsigned int", "__useconds_t"),
            Item::Typedef("long int", "__suseconds_t"),
            Item::Typedef("long int", "__suseconds64_t"),
            Item::Typedef("int", "__daddr_t"),
            Item::Typedef("int", "__key_t"),
            Item::Typedef("int", "__clockid_t"),
            Item::Typedef("void *", "__timer_t"),
            Item::Typedef("long int", "__blksize_t"),
            Item::Typedef("long int", "__blkcnt_t"),
            Item::Typedef("long int", "__blkcnt64_t"),
            Item::Typedef("unsigned long int", "__fsblkcnt_t"),
            Item::Typedef("unsigned long int", "__fsblkcnt64_t"),
            Item::Typedef("unsigned long int", "__fsfilcnt_t"),
            Item::Typedef("unsigned long int", "__fsfilcnt64_t"),
            Item::Typedef("long int", "__fsword_t"),
            Item::Typedef("long int", "__ssize_t"),
            Item::Typedef("long int", "__syscall_slong_t"),
            Item::Typedef("unsigned long int", "__syscall_ulong_t"),
            Item::Typedef("__off64_t", "__loff_t"),
            Item::Typedef("char *", "__caddr_t"),
            Item::Typedef("long int", "__intptr_t"),
            Item::Typedef("unsigned int", "__socklen_t"),
            Item::Typedef("int", "__sig_atomic_t"),
            Item::Blank,
        ]},
    ],
};
