use crate::model::*;

pub static HDR: Header = Header {
    path: "inttypes.h",
    items: &[
        Item::Guard { name: "_RLIBC_INTTYPES_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<stdint.h>"),
            Item::Include("<stdlib.h>"),
            Item::Include("<wchar.h>"),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "if !defined __cplusplus || defined __STDC_FORMAT_MACROS", items: &[
                    Item::Consts(&[
                        ("PRIB16", V::Txt(r#""hB""#)),
                        ("PRIB32", V::Txt(r#""B""#)),
                        ("PRIB64", V::Txt(r#""lB""#)),
                        ("PRIB8", V::Txt(r#""hhB""#)),
                        ("PRIBFAST16", V::Txt(r#""lB""#)),
                        ("PRIBFAST32", V::Txt(r#""lB""#)),
                        ("PRIBFAST64", V::Txt(r#""lB""#)),
                        ("PRIBFAST8", V::Txt(r#""hhB""#)),
                        ("PRIBLEAST16", V::Txt(r#""hB""#)),
                        ("PRIBLEAST32", V::Txt(r#""B""#)),
                        ("PRIBLEAST64", V::Txt(r#""lB""#)),
                        ("PRIBLEAST8", V::Txt(r#""hhB""#)),
                        ("PRIBMAX", V::Txt(r#""lB""#)),
                        ("PRIBPTR", V::Txt(r#""lB""#)),
                        ("PRIX16", V::Txt(r#""hX""#)),
                        ("PRIX32", V::Txt(r#""X""#)),
                        ("PRIX64", V::Txt(r#""lX""#)),
                        ("PRIX8", V::Txt(r#""hhX""#)),
                        ("PRIXFAST16", V::Txt(r#""lX""#)),
                        ("PRIXFAST32", V::Txt(r#""lX""#)),
                        ("PRIXFAST64", V::Txt(r#""lX""#)),
                        ("PRIXFAST8", V::Txt(r#""hhX""#)),
                        ("PRIXLEAST16", V::Txt(r#""hX""#)),
                        ("PRIXLEAST32", V::Txt(r#""X""#)),
                        ("PRIXLEAST64", V::Txt(r#""lX""#)),
                        ("PRIXLEAST8", V::Txt(r#""hhX""#)),
                        ("PRIXMAX", V::Txt(r#""lX""#)),
                        ("PRIXPTR", V::Txt(r#""lX""#)),
                        ("PRIb16", V::Txt(r#""hb""#)),
                        ("PRIb32", V::Txt(r#""b""#)),
                        ("PRIb64", V::Txt(r#""lb""#)),
                        ("PRIb8", V::Txt(r#""hhb""#)),
                        ("PRIbFAST16", V::Txt(r#""lb""#)),
                        ("PRIbFAST32", V::Txt(r#""lb""#)),
                        ("PRIbFAST64", V::Txt(r#""lb""#)),
                        ("PRIbFAST8", V::Txt(r#""hhb""#)),
                        ("PRIbLEAST16", V::Txt(r#""hb""#)),
                        ("PRIbLEAST32", V::Txt(r#""b""#)),
                        ("PRIbLEAST64", V::Txt(r#""lb""#)),
                        ("PRIbLEAST8", V::Txt(r#""hhb""#)),
                        ("PRIbMAX", V::Txt(r#""lb""#)),
                        ("PRIbPTR", V::Txt(r#""lb""#)),
                        ("PRId16", V::Txt(r#""hd""#)),
                        ("PRId32", V::Txt(r#""d""#)),
                        ("PRId64", V::Txt(r#""ld""#)),
                        ("PRId8", V::Txt(r#""hhd""#)),
                        ("PRIdFAST16", V::Txt(r#""ld""#)),
                        ("PRIdFAST32", V::Txt(r#""ld""#)),
                        ("PRIdFAST64", V::Txt(r#""ld""#)),
                        ("PRIdFAST8", V::Txt(r#""hhd""#)),
                        ("PRIdLEAST16", V::Txt(r#""hd""#)),
                        ("PRIdLEAST32", V::Txt(r#""d""#)),
                        ("PRIdLEAST64", V::Txt(r#""ld""#)),
                        ("PRIdLEAST8", V::Txt(r#""hhd""#)),
                        ("PRIdMAX", V::Txt(r#""ld""#)),
                        ("PRIdPTR", V::Txt(r#""ld""#)),
                        ("PRIi16", V::Txt(r#""hi""#)),
                        ("PRIi32", V::Txt(r#""i""#)),
                        ("PRIi64", V::Txt(r#""li""#)),
                        ("PRIi8", V::Txt(r#""hhi""#)),
                        ("PRIiFAST16", V::Txt(r#""li""#)),
                        ("PRIiFAST32", V::Txt(r#""li""#)),
                        ("PRIiFAST64", V::Txt(r#""li""#)),
                        ("PRIiFAST8", V::Txt(r#""hhi""#)),
                        ("PRIiLEAST16", V::Txt(r#""hi""#)),
                        ("PRIiLEAST32", V::Txt(r#""i""#)),
                        ("PRIiLEAST64", V::Txt(r#""li""#)),
                        ("PRIiLEAST8", V::Txt(r#""hhi""#)),
                        ("PRIiMAX", V::Txt(r#""li""#)),
                        ("PRIiPTR", V::Txt(r#""li""#)),
                        ("PRIo16", V::Txt(r#""ho""#)),
                        ("PRIo32", V::Txt(r#""o""#)),
                        ("PRIo64", V::Txt(r#""lo""#)),
                        ("PRIo8", V::Txt(r#""hho""#)),
                        ("PRIoFAST16", V::Txt(r#""lo""#)),
                        ("PRIoFAST32", V::Txt(r#""lo""#)),
                        ("PRIoFAST64", V::Txt(r#""lo""#)),
                        ("PRIoFAST8", V::Txt(r#""hho""#)),
                        ("PRIoLEAST16", V::Txt(r#""ho""#)),
                        ("PRIoLEAST32", V::Txt(r#""o""#)),
                        ("PRIoLEAST64", V::Txt(r#""lo""#)),
                        ("PRIoLEAST8", V::Txt(r#""hho""#)),
                        ("PRIoMAX", V::Txt(r#""lo""#)),
                        ("PRIoPTR", V::Txt(r#""lo""#)),
                        ("PRIu16", V::Txt(r#""hu""#)),
                        ("PRIu32", V::Txt(r#""u""#)),
                        ("PRIu64", V::Txt(r#""lu""#)),
                        ("PRIu8", V::Txt(r#""hhu""#)),
                        ("PRIuFAST16", V::Txt(r#""lu""#)),
                        ("PRIuFAST32", V::Txt(r#""lu""#)),
                        ("PRIuFAST64", V::Txt(r#""lu""#)),
                        ("PRIuFAST8", V::Txt(r#""hhu""#)),
                        ("PRIuLEAST16", V::Txt(r#""hu""#)),
                        ("PRIuLEAST32", V::Txt(r#""u""#)),
                        ("PRIuLEAST64", V::Txt(r#""lu""#)),
                        ("PRIuLEAST8", V::Txt(r#""hhu""#)),
                        ("PRIuMAX", V::Txt(r#""lu""#)),
                        ("PRIuPTR", V::Txt(r#""lu""#)),
                        ("PRIx16", V::Txt(r#""hx""#)),
                        ("PRIx32", V::Txt(r#""x""#)),
                        ("PRIx64", V::Txt(r#""lx""#)),
                        ("PRIx8", V::Txt(r#""hhx""#)),
                        ("PRIxFAST16", V::Txt(r#""lx""#)),
                        ("PRIxFAST32", V::Txt(r#""lx""#)),
                        ("PRIxFAST64", V::Txt(r#""lx""#)),
                        ("PRIxFAST8", V::Txt(r#""hhx""#)),
                        ("PRIxLEAST16", V::Txt(r#""hx""#)),
                        ("PRIxLEAST32", V::Txt(r#""x""#)),
                        ("PRIxLEAST64", V::Txt(r#""lx""#)),
                        ("PRIxLEAST8", V::Txt(r#""hhx""#)),
                        ("PRIxMAX", V::Txt(r#""lx""#)),
                        ("PRIxPTR", V::Txt(r#""lx""#)),
                        ("SCNb16", V::Txt(r#""hb""#)),
                        ("SCNb32", V::Txt(r#""b""#)),
                        ("SCNb64", V::Txt(r#""lb""#)),
                        ("SCNb8", V::Txt(r#""hhb""#)),
                        ("SCNbFAST16", V::Txt(r#""lb""#)),
                        ("SCNbFAST32", V::Txt(r#""lb""#)),
                        ("SCNbFAST64", V::Txt(r#""lb""#)),
                        ("SCNbFAST8", V::Txt(r#""hhb""#)),
                        ("SCNbLEAST16", V::Txt(r#""hb""#)),
                        ("SCNbLEAST32", V::Txt(r#""b""#)),
                        ("SCNbLEAST64", V::Txt(r#""lb""#)),
                        ("SCNbLEAST8", V::Txt(r#""hhb""#)),
                        ("SCNbMAX", V::Txt(r#""lb""#)),
                        ("SCNbPTR", V::Txt(r#""lb""#)),
                        ("SCNd16", V::Txt(r#""hd""#)),
                        ("SCNd32", V::Txt(r#""d""#)),
                        ("SCNd64", V::Txt(r#""ld""#)),
                        ("SCNd8", V::Txt(r#""hhd""#)),
                        ("SCNdFAST16", V::Txt(r#""ld""#)),
                        ("SCNdFAST32", V::Txt(r#""ld""#)),
                        ("SCNdFAST64", V::Txt(r#""ld""#)),
                        ("SCNdFAST8", V::Txt(r#""hhd""#)),
                        ("SCNdLEAST16", V::Txt(r#""hd""#)),
                        ("SCNdLEAST32", V::Txt(r#""d""#)),
                        ("SCNdLEAST64", V::Txt(r#""ld""#)),
                        ("SCNdLEAST8", V::Txt(r#""hhd""#)),
                        ("SCNdMAX", V::Txt(r#""ld""#)),
                        ("SCNdPTR", V::Txt(r#""ld""#)),
                        ("SCNi16", V::Txt(r#""hi""#)),
                        ("SCNi32", V::Txt(r#""i""#)),
                        ("SCNi64", V::Txt(r#""li""#)),
                        ("SCNi8", V::Txt(r#""hhi""#)),
                        ("SCNiFAST16", V::Txt(r#""li""#)),
                        ("SCNiFAST32", V::Txt(r#""li""#)),
                        ("SCNiFAST64", V::Txt(r#""li""#)),
                        ("SCNiFAST8", V::Txt(r#""hhi""#)),
                        ("SCNiLEAST16", V::Txt(r#""hi""#)),
                        ("SCNiLEAST32", V::Txt(r#""i""#)),
                        ("SCNiLEAST64", V::Txt(r#""li""#)),
                        ("SCNiLEAST8", V::Txt(r#""hhi""#)),
                        ("SCNiMAX", V::Txt(r#""li""#)),
                        ("SCNiPTR", V::Txt(r#""li""#)),
                        ("SCNo16", V::Txt(r#""ho""#)),
                        ("SCNo32", V::Txt(r#""o""#)),
                        ("SCNo64", V::Txt(r#""lo""#)),
                        ("SCNo8", V::Txt(r#""hho""#)),
                        ("SCNoFAST16", V::Txt(r#""lo""#)),
                        ("SCNoFAST32", V::Txt(r#""lo""#)),
                        ("SCNoFAST64", V::Txt(r#""lo""#)),
                        ("SCNoFAST8", V::Txt(r#""hho""#)),
                        ("SCNoLEAST16", V::Txt(r#""ho""#)),
                        ("SCNoLEAST32", V::Txt(r#""o""#)),
                        ("SCNoLEAST64", V::Txt(r#""lo""#)),
                        ("SCNoLEAST8", V::Txt(r#""hho""#)),
                        ("SCNoMAX", V::Txt(r#""lo""#)),
                        ("SCNoPTR", V::Txt(r#""lo""#)),
                        ("SCNu16", V::Txt(r#""hu""#)),
                        ("SCNu32", V::Txt(r#""u""#)),
                        ("SCNu64", V::Txt(r#""lu""#)),
                        ("SCNu8", V::Txt(r#""hhu""#)),
                        ("SCNuFAST16", V::Txt(r#""lu""#)),
                        ("SCNuFAST32", V::Txt(r#""lu""#)),
                        ("SCNuFAST64", V::Txt(r#""lu""#)),
                        ("SCNuFAST8", V::Txt(r#""hhu""#)),
                        ("SCNuLEAST16", V::Txt(r#""hu""#)),
                        ("SCNuLEAST32", V::Txt(r#""u""#)),
                        ("SCNuLEAST64", V::Txt(r#""lu""#)),
                        ("SCNuLEAST8", V::Txt(r#""hhu""#)),
                        ("SCNuMAX", V::Txt(r#""lu""#)),
                        ("SCNuPTR", V::Txt(r#""lu""#)),
                        ("SCNx16", V::Txt(r#""hx""#)),
                        ("SCNx32", V::Txt(r#""x""#)),
                        ("SCNx64", V::Txt(r#""lx""#)),
                        ("SCNx8", V::Txt(r#""hhx""#)),
                        ("SCNxFAST16", V::Txt(r#""lx""#)),
                        ("SCNxFAST32", V::Txt(r#""lx""#)),
                        ("SCNxFAST64", V::Txt(r#""lx""#)),
                        ("SCNxFAST8", V::Txt(r#""hhx""#)),
                        ("SCNxLEAST16", V::Txt(r#""hx""#)),
                        ("SCNxLEAST32", V::Txt(r#""x""#)),
                        ("SCNxLEAST64", V::Txt(r#""lx""#)),
                        ("SCNxLEAST8", V::Txt(r#""hhx""#)),
                        ("SCNxMAX", V::Txt(r#""lx""#)),
                        ("SCNxPTR", V::Txt(r#""lx""#)),
                    ]),
                ] },
            ], ""),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "if __GLIBC_USE (C23_STRTOL)", items: &[
                    Item::Decl(r#"extern intmax_t strtoimax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __asm__ ("__isoc23_strtoimax") __attribute__ ((__nothrow__));"#),
                    Item::Decl(r#"extern uintmax_t strtoumax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __asm__ ("__isoc23_strtoumax") __attribute__ ((__nothrow__));"#),
                ] },
                Branch { head: "else", items: &[
                    Item::Decl("extern intmax_t strtoimax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __attribute__ ((__nothrow__));"),
                    Item::Decl("extern uintmax_t strtoumax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __attribute__ ((__nothrow__));"),
                ] },
            ], ""),
            Item::Blank,
        ]},
    ],
};
