use crate::model::*;

pub static HDR: Header = Header {
    path: "limits.h",
    items: &[
        Item::Guard { name: "_RLIBC_LIMITS_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Consts(&[
                ("AIO_PRIO_DELTA_MAX", V::Dec(20)),
                ("BC_BASE_MAX", V::Txt("_POSIX2_BC_BASE_MAX")),
                ("BC_DIM_MAX", V::Txt("_POSIX2_BC_DIM_MAX")),
                ("BC_SCALE_MAX", V::Txt("_POSIX2_BC_SCALE_MAX")),
                ("BC_STRING_MAX", V::Txt("_POSIX2_BC_STRING_MAX")),
                ("BITINT_MAXWIDTH", V::Txt("__BITINT_MAXWIDTH__")),
                ("BOOL_MAX", V::Dec(1)),
                ("BOOL_WIDTH", V::Dec(1)),
                ("CHARCLASS_NAME_MAX", V::Dec(2048)),
                ("CHAR_BIT", V::Txt("__CHAR_BIT__")),
                ("CHAR_MAX", V::Txt("SCHAR_MAX")),
                ("CHAR_MIN", V::Txt("SCHAR_MIN")),
                ("CHAR_WIDTH", V::Txt("__SCHAR_WIDTH__")),
                ("COLL_WEIGHTS_MAX", V::Dec(255)),
                ("DELAYTIMER_MAX", V::Dec(2147483647)),
                ("EXPR_NEST_MAX", V::Txt("_POSIX2_EXPR_NEST_MAX")),
                ("HOST_NAME_MAX", V::Dec(64)),
                ("INT_MAX", V::Txt("__INT_MAX__")),
                ("INT_MIN", V::Txt("(-INT_MAX - 1)")),
                ("INT_WIDTH", V::Txt("__INT_WIDTH__")),
                ("IOV_MAX", V::Txt("__IOV_MAX")),
                ("LINE_MAX", V::Txt("_POSIX2_LINE_MAX")),
                ("LLONG_MAX", V::Txt("__LONG_LONG_MAX__")),
                ("LLONG_MIN", V::Txt("(-LLONG_MAX - 1LL)")),
                ("LLONG_WIDTH", V::Txt("__LONG_LONG_WIDTH__")),
                ("LOGIN_NAME_MAX", V::Dec(256)),
                ("LONG_BIT", V::Dec(64)),
                ("LONG_LONG_MAX", V::Txt("__LONG_LONG_MAX__")),
                ("LONG_LONG_MIN", V::Txt("(-LONG_LONG_MAX - 1LL)")),
                ("LONG_MAX", V::Txt("__LONG_MAX__")),
                ("LONG_MIN", V::Txt("(-LONG_MAX - 1L)")),
                ("LONG_WIDTH", V::Txt("__LONG_WIDTH__")),
                ("MAX_CANON", V::Dec(255)),
                ("MAX_INPUT", V::Dec(255)),
                ("MB_LEN_MAX", V::Dec(16)),
                ("MQ_PRIO_MAX", V::Dec(32768)),
                ("NAME_MAX", V::Dec(255)),
                ("NGROUPS_MAX", V::Dec(65536)),
                ("NL_ARGMAX", V::Txt("_POSIX_ARG_MAX")),
                ("NL_LANGMAX", V::Txt("_POSIX2_LINE_MAX")),
                ("NL_MSGMAX", V::Txt("INT_MAX")),
                ("NL_NMAX", V::Txt("INT_MAX")),
                ("NL_SETMAX", V::Txt("INT_MAX")),
                ("NL_TEXTMAX", V::Txt("INT_MAX")),
                ("NZERO", V::Dec(20)),
                ("PATH_MAX", V::Dec(4096)),
                ("PIPE_BUF", V::Dec(4096)),
                ("PTHREAD_DESTRUCTOR_ITERATIONS", V::Txt("_POSIX_THREAD_DESTRUCTOR_ITERATIONS")),
                ("PTHREAD_KEYS_MAX", V::Dec(1024)),
            ]),
            Item::Gate(&[
                Branch { head: "ifdef __USE_DYNAMIC_STACK_SIZE", items: &[
                    Item::Decl("extern long int __sysconf (int __name) __THROW;"),
                    Item::Consts(&[
                        ("PTHREAD_STACK_MIN", V::Txt("__sysconf (__SC_THREAD_STACK_MIN_VALUE)")),
                    ]),
                ] },
                Branch { head: "else", items: &[
                    Item::Consts(&[
                        ("PTHREAD_STACK_MIN", V::Dec(16384)),
                    ]),
                ] },
            ], ""),
            Item::Consts(&[
                ("RE_DUP_MAX", V::Txt("(0x7fff)")),
                ("RTSIG_MAX", V::Dec(32)),
                ("SCHAR_MAX", V::Txt("__SCHAR_MAX__")),
                ("SCHAR_MIN", V::Txt("(-SCHAR_MAX - 1)")),
                ("SCHAR_WIDTH", V::Txt("__SCHAR_WIDTH__")),
                ("SEM_VALUE_MAX", V::Txt("(2147483647)")),
                ("SHRT_MAX", V::Txt("__SHRT_MAX__")),
                ("SHRT_MIN", V::Txt("(-SHRT_MAX - 1)")),
                ("SHRT_WIDTH", V::Txt("__SHRT_WIDTH__")),
                ("SSIZE_MAX", V::Txt("LONG_MAX")),
                ("TTY_NAME_MAX", V::Dec(32)),
                ("UCHAR_MAX", V::Txt("(SCHAR_MAX * 2 + 1)")),
                ("UCHAR_WIDTH", V::Txt("__SCHAR_WIDTH__")),
                ("UINT_MAX", V::Txt("(INT_MAX * 2U + 1U)")),
                ("UINT_WIDTH", V::Txt("__INT_WIDTH__")),
                ("ULLONG_MAX", V::Txt("(LLONG_MAX * 2ULL + 1ULL)")),
                ("ULLONG_WIDTH", V::Txt("__LONG_LONG_WIDTH__")),
                ("ULONG_LONG_MAX", V::Txt("(LONG_LONG_MAX * 2ULL + 1ULL)")),
                ("ULONG_MAX", V::Txt("(LONG_MAX * 2UL + 1UL)")),
                ("ULONG_WIDTH", V::Txt("__LONG_WIDTH__")),
                ("USHRT_MAX", V::Txt("(SHRT_MAX * 2 + 1)")),
                ("USHRT_WIDTH", V::Txt("__SHRT_WIDTH__")),
                ("WORD_BIT", V::Dec(32)),
                ("XATTR_LIST_MAX", V::Dec(65536)),
                ("XATTR_NAME_MAX", V::Dec(255)),
                ("XATTR_SIZE_MAX", V::Dec(65536)),
                ("_BITS_POSIX2_LIM_H", V::Dec(1)),
                ("_BITS_UIO_LIM_H", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define _LIMITS_H___ "),
            Item::Raw(Reason::GlibcMacro, "#define _LINUX_LIMITS_H "),
            Item::Consts(&[
                ("_POSIX2_BC_BASE_MAX", V::Dec(99)),
                ("_POSIX2_BC_DIM_MAX", V::Dec(2048)),
                ("_POSIX2_BC_SCALE_MAX", V::Dec(99)),
                ("_POSIX2_BC_STRING_MAX", V::Dec(1000)),
                ("_POSIX2_CHARCLASS_NAME_MAX", V::Dec(14)),
                ("_POSIX2_COLL_WEIGHTS_MAX", V::Dec(2)),
                ("_POSIX2_EXPR_NEST_MAX", V::Dec(32)),
                ("_POSIX2_LINE_MAX", V::Dec(2048)),
                ("_POSIX2_RE_DUP_MAX", V::Dec(255)),
                ("_POSIX_AIO_LISTIO_MAX", V::Dec(2)),
                ("_POSIX_AIO_MAX", V::Dec(1)),
                ("_POSIX_ARG_MAX", V::Dec(4096)),
                ("_POSIX_CHILD_MAX", V::Dec(25)),
                ("_POSIX_CLOCKRES_MIN", V::Dec(20000000)),
                ("_POSIX_DELAYTIMER_MAX", V::Dec(32)),
                ("_POSIX_FD_SETSIZE", V::Txt("_POSIX_OPEN_MAX")),
                ("_POSIX_HIWAT", V::Txt("_POSIX_PIPE_BUF")),
                ("_POSIX_HOST_NAME_MAX", V::Dec(255)),
                ("_POSIX_LINK_MAX", V::Dec(8)),
                ("_POSIX_LOGIN_NAME_MAX", V::Dec(9)),
                ("_POSIX_MAX_CANON", V::Dec(255)),
                ("_POSIX_MAX_INPUT", V::Dec(255)),
                ("_POSIX_MQ_OPEN_MAX", V::Dec(8)),
                ("_POSIX_MQ_PRIO_MAX", V::Dec(32)),
                ("_POSIX_NAME_MAX", V::Dec(14)),
                ("_POSIX_NGROUPS_MAX", V::Dec(8)),
                ("_POSIX_OPEN_MAX", V::Dec(20)),
                ("_POSIX_PATH_MAX", V::Dec(256)),
                ("_POSIX_PIPE_BUF", V::Dec(512)),
                ("_POSIX_QLIMIT", V::Dec(1)),
                ("_POSIX_RE_DUP_MAX", V::Dec(255)),
                ("_POSIX_RTSIG_MAX", V::Dec(8)),
                ("_POSIX_SEM_NSEMS_MAX", V::Dec(256)),
                ("_POSIX_SEM_VALUE_MAX", V::Dec(32767)),
                ("_POSIX_SIGQUEUE_MAX", V::Dec(32)),
                ("_POSIX_SSIZE_MAX", V::Dec(32767)),
                ("_POSIX_STREAM_MAX", V::Dec(8)),
                ("_POSIX_SYMLINK_MAX", V::Dec(255)),
                ("_POSIX_SYMLOOP_MAX", V::Dec(8)),
                ("_POSIX_THREAD_DESTRUCTOR_ITERATIONS", V::Dec(4)),
                ("_POSIX_THREAD_KEYS_MAX", V::Dec(128)),
                ("_POSIX_THREAD_THREADS_MAX", V::Dec(64)),
                ("_POSIX_TIMER_MAX", V::Dec(32)),
                ("_POSIX_TTY_NAME_MAX", V::Dec(9)),
                ("_POSIX_TZNAME_MAX", V::Dec(6)),
                ("_POSIX_UIO_MAXIOV", V::Dec(16)),
                ("_XOPEN_IOV_MAX", V::Txt("_POSIX_UIO_MAXIOV")),
                ("_XOPEN_LIM_H", V::Dec(1)),
                ("__IOV_MAX", V::Dec(1024)),
                ("__SC_THREAD_STACK_MIN_VALUE", V::Dec(75)),
                ("__STDC_VERSION_LIMITS_H__", V::Txt("202311L")),
            ]),
            Item::Blank,
        ]},
    ],
};
