use crate::model::*;

pub static HDR: Header = Header {
    path: "link.h",
    items: &[
        Item::Guard { name: "_RLIBC_LINK_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<stddef.h>"),
            Item::Include("<stdint.h>"),
            Item::Blank,
            Item::Include("<elf.h>"),
            Item::Blank,
            Item::Raw(Reason::GlibcMacro, "#define ElfW(type) _ElfW (Elf, 64, type)"),
            Item::Raw(Reason::GlibcMacro, "#define _ElfW(e, w, t) _ElfW_1 (e, w, _##t)"),
            Item::Raw(Reason::GlibcMacro, "#define _ElfW_1(e, w, t) e##w##t"),
            Item::Blank,
            Item::Block { head: "struct link_map ", body: &["", "  Elf64_Addr l_addr;", "  char *l_name;", "  Elf64_Dyn *l_ld;", "  struct link_map *l_next, *l_prev;", ""], tail: "" },
            Item::Blank,
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: "struct dl_phdr_info ", body: &["", "  Elf64_Addr dlpi_addr;", "  const char *dlpi_name;", "  const Elf64_Phdr *dlpi_phdr;", "  Elf64_Half dlpi_phnum;", "  unsigned long long int dlpi_adds;", "  unsigned long long int dlpi_subs;", "  size_t dlpi_tls_modid;", "  void *dlpi_tls_data;", ""], tail: "" },
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef _GNU_SOURCE", items: &[
                    Item::Block { head: "struct dl_find_object ", body: &["", "  unsigned long long int dlfo_flags;", "  void *dlfo_map_start;", "  void *dlfo_map_end;", "  struct link_map *dlfo_link_map;", "  void *dlfo_eh_frame;", "  unsigned long long int __dflo_reserved[7];", ""], tail: "" },
                    Item::Decl("extern int _dl_find_object (void *__address, struct dl_find_object *__result);"),
                ] },
            ], ""),
            Item::Blank,
            Item::Decl("extern int dl_iterate_phdr (int (*__callback) (struct dl_phdr_info *, size_t, void *), void *__data);"),
            Item::Blank,
            Item::Block { head: "struct r_debug ", body: &["", "  int r_version;", "  struct link_map *r_map;", "  Elf64_Addr r_brk;", "  enum { RT_CONSISTENT, RT_ADD, RT_DELETE } r_state;", "  Elf64_Addr r_ldbase;", ""], tail: "" },
            Item::Block { head: "struct r_debug_extended ", body: &["", "  int r_version;", "  struct link_map *r_map;", "  Elf64_Addr r_brk;", "  enum { RTX_CONSISTENT, RTX_ADD, RTX_DELETE } r_state;", "  Elf64_Addr r_ldbase;", "  struct r_debug_extended *r_next;", ""], tail: "" },
            Item::Decl("extern struct r_debug _r_debug;"),
            Item::Blank,
            Item::Decl("extern Elf64_Dyn _DYNAMIC[];"),
            Item::Blank,
            Item::Consts(&[
                ("LAV_CURRENT", V::Dec(2)),
                ("LA_ACT_CONSISTENT", V::Dec(0)),
                ("LA_ACT_ADD", V::Dec(1)),
                ("LA_ACT_DELETE", V::Dec(2)),
                ("LA_SER_ORIG", V::Txt("0x01")),
                ("LA_SER_LIBPATH", V::Txt("0x02")),
                ("LA_SER_RUNPATH", V::Txt("0x04")),
                ("LA_SER_CONFIG", V::Txt("0x08")),
                ("LA_SER_DEFAULT", V::Hex(0x40)),
                ("LA_SER_SECURE", V::Hex(0x80)),
                ("LA_FLG_BINDTO", V::Txt("0x01")),
                ("LA_FLG_BINDFROM", V::Txt("0x02")),
                ("LA_SYMB_NOPLTENTER", V::Txt("0x01")),
                ("LA_SYMB_NOPLTEXIT", V::Txt("0x02")),
                ("LA_SYMB_STRUCTCALL", V::Txt("0x04")),
                ("LA_SYMB_DLSYM", V::Txt("0x08")),
                ("LA_SYMB_ALTVALUE", V::Hex(0x10)),
            ]),
            Item::Blank,
            Item::ExternEnd,
            Item::Blank,
        ]},
    ],
};
