use crate::model::*;

pub static HDR: Header = Header {
    path: "net/if_arp.h",
    items: &[
        Item::Guard { name: "_NET_IF_ARP_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<sys/socket.h>"),
            Item::Include("<stdint.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Consts(&[
                ("MAX_ADDR_LEN", V::Dec(7)),
            ]),
            Item::Blank,
            Item::Block { head: r#"struct arphdr
  "#, body: &["", "    unsigned short int ar_hrd;", "    unsigned short int ar_pro;", "    unsigned char ar_hln;", "    unsigned char ar_pln;", "    unsigned short int ar_op;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct arpreq
  "#, body: &["", "    struct sockaddr arp_pa;", "    struct sockaddr arp_ha;", "    int arp_flags;", "    struct sockaddr arp_netmask;", "    char arp_dev[16];", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct arpreq_old
  "#, body: &["", "    struct sockaddr arp_pa;", "    struct sockaddr arp_ha;", "    int arp_flags;", "    struct sockaddr arp_netmask;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct arpd_request
  "#, body: &["", "    unsigned short int req;", "    uint32_t ip;", "    unsigned long int dev;", "    unsigned long int stamp;", "    unsigned long int updated;", "    unsigned char ha[MAX_ADDR_LEN];", "  "], tail: "" },
            Item::Consts(&[
                ("ARPD_FLUSH", V::Txt("0x03")),
                ("ARPD_LOOKUP", V::Txt("0x02")),
                ("ARPD_UPDATE", V::Txt("0x01")),
                ("ARPHRD_ADAPT", V::Dec(264)),
                ("ARPHRD_APPLETLK", V::Dec(8)),
                ("ARPHRD_ARCNET", V::Dec(7)),
                ("ARPHRD_ASH", V::Dec(781)),
                ("ARPHRD_ATM", V::Dec(19)),
                ("ARPHRD_AX25", V::Dec(3)),
                ("ARPHRD_BIF", V::Dec(775)),
                ("ARPHRD_CAN", V::Dec(280)),
                ("ARPHRD_CHAOS", V::Dec(5)),
                ("ARPHRD_CISCO", V::Dec(513)),
                ("ARPHRD_CSLIP", V::Dec(257)),
                ("ARPHRD_CSLIP6", V::Dec(259)),
                ("ARPHRD_DDCMP", V::Dec(517)),
                ("ARPHRD_DLCI", V::Dec(15)),
                ("ARPHRD_ECONET", V::Dec(782)),
                ("ARPHRD_EETHER", V::Dec(2)),
                ("ARPHRD_ETHER", V::Dec(1)),
                ("ARPHRD_EUI64", V::Dec(27)),
                ("ARPHRD_FCAL", V::Dec(785)),
                ("ARPHRD_FCFABRIC", V::Dec(787)),
                ("ARPHRD_FCPL", V::Dec(786)),
                ("ARPHRD_FCPP", V::Dec(784)),
                ("ARPHRD_FDDI", V::Dec(774)),
                ("ARPHRD_FRAD", V::Dec(770)),
                ("ARPHRD_HDLC", V::Txt("ARPHRD_CISCO")),
                ("ARPHRD_HIPPI", V::Dec(780)),
                ("ARPHRD_HWX25", V::Dec(272)),
                ("ARPHRD_IEEE1394", V::Dec(24)),
                ("ARPHRD_IEEE802", V::Dec(6)),
                ("ARPHRD_IEEE80211", V::Dec(801)),
                ("ARPHRD_IEEE80211_PRISM", V::Dec(802)),
                ("ARPHRD_IEEE80211_RADIOTAP", V::Dec(803)),
                ("ARPHRD_IEEE802154", V::Dec(804)),
                ("ARPHRD_IEEE802154_PHY", V::Dec(805)),
                ("ARPHRD_IEEE802_TR", V::Dec(800)),
                ("ARPHRD_INFINIBAND", V::Dec(32)),
                ("ARPHRD_IPDDP", V::Dec(777)),
                ("ARPHRD_IPGRE", V::Dec(778)),
                ("ARPHRD_IRDA", V::Dec(783)),
                ("ARPHRD_LAPB", V::Dec(516)),
                ("ARPHRD_LOCALTLK", V::Dec(773)),
                ("ARPHRD_LOOPBACK", V::Dec(772)),
                ("ARPHRD_MCTP", V::Dec(290)),
                ("ARPHRD_METRICOM", V::Dec(23)),
                ("ARPHRD_NETROM", V::Dec(0)),
                ("ARPHRD_NONE", V::Txt("0xFFFE")),
                ("ARPHRD_PIMREG", V::Dec(779)),
                ("ARPHRD_PPP", V::Dec(512)),
                ("ARPHRD_PRONET", V::Dec(4)),
                ("ARPHRD_RAWHDLC", V::Dec(518)),
                ("ARPHRD_RAWIP", V::Dec(519)),
                ("ARPHRD_ROSE", V::Dec(270)),
                ("ARPHRD_RSRVD", V::Dec(260)),
                ("ARPHRD_SIT", V::Dec(776)),
                ("ARPHRD_SKIP", V::Dec(771)),
                ("ARPHRD_SLIP", V::Dec(256)),
                ("ARPHRD_SLIP6", V::Dec(258)),
                ("ARPHRD_TUNNEL", V::Dec(768)),
                ("ARPHRD_TUNNEL6", V::Dec(769)),
                ("ARPHRD_VOID", V::Txt("0xFFFF")),
                ("ARPHRD_X25", V::Dec(271)),
                ("ARPOP_InREPLY", V::Dec(9)),
                ("ARPOP_InREQUEST", V::Dec(8)),
                ("ARPOP_NAK", V::Dec(10)),
                ("ARPOP_REPLY", V::Dec(2)),
                ("ARPOP_REQUEST", V::Dec(1)),
                ("ARPOP_RREPLY", V::Dec(4)),
                ("ARPOP_RREQUEST", V::Dec(3)),
                ("ATF_COM", V::Txt("0x02")),
                ("ATF_DONTPUB", V::Hex(0x40)),
                ("ATF_MAGIC", V::Hex(0x80)),
                ("ATF_NETMASK", V::Hex(0x20)),
                ("ATF_PERM", V::Txt("0x04")),
                ("ATF_PUBL", V::Txt("0x08")),
                ("ATF_USETRAILERS", V::Hex(0x10)),
                ("MAX_ADDR_LEN", V::Dec(7)),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
