use crate::model::*;

pub static HDR: Header = Header {
    path: "net/if.h",
    items: &[
        Item::Guard { name: "_NET_IF_H", value: "1", end: "", items: &[
            Item::Include("<sys/socket.h>"),
            Item::Gate(&[
                Branch { head: "ifndef __caddr_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__caddr_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("char *", "caddr_t"),
                ] },
            ], ""),
            Item::Blank,
            Item::Consts(&[
                ("IFF_ALLMULTI", V::Dec(512)),
                ("IFF_AUTOMEDIA", V::Dec(16384)),
                ("IFF_BROADCAST", V::Dec(2)),
                ("IFF_DEBUG", V::Dec(4)),
                ("IFF_DYNAMIC", V::Dec(32768)),
                ("IFF_LOOPBACK", V::Dec(8)),
                ("IFF_MASTER", V::Dec(1024)),
                ("IFF_MULTICAST", V::Dec(4096)),
                ("IFF_NOARP", V::Dec(128)),
                ("IFF_NOTRAILERS", V::Dec(32)),
                ("IFF_POINTOPOINT", V::Dec(16)),
                ("IFF_PORTSEL", V::Dec(8192)),
                ("IFF_PROMISC", V::Dec(256)),
                ("IFF_RUNNING", V::Dec(64)),
                ("IFF_SLAVE", V::Dec(2048)),
                ("IFF_UP", V::Dec(1)),
                ("IFHWADDRLEN", V::Dec(6)),
                ("IFNAMSIZ", V::Dec(16)),
                ("IF_NAMESIZE", V::Dec(16)),
            ]),
            Item::Blank,
            Item::Block { head: "struct if_nameindex ", body: &["", "  unsigned int if_index;", "  char *if_name;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ifmap ", body: &["", "  unsigned long int mem_start;", "  unsigned long int mem_end;", "  unsigned short int base_addr;", "  unsigned char irq;", "  unsigned char dma;", "  unsigned char port;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ifreq ", body: &["", "  union {", "    char ifrn_name[IFNAMSIZ];", "  } ifr_ifrn;", "  union {", "    struct sockaddr ifru_addr;", "    struct sockaddr ifru_dstaddr;", "    struct sockaddr ifru_broadaddr;", "    struct sockaddr ifru_netmask;", "    struct sockaddr ifru_hwaddr;", "    short int ifru_flags;", "    int ifru_ivalue;", "    int ifru_mtu;", "    struct ifmap ifru_map;", "    char ifru_slave[IFNAMSIZ];", "    char ifru_newname[IFNAMSIZ];", "    caddr_t ifru_data;", "  } ifr_ifru;", ""], tail: "" },
            Item::Consts(&[
                ("ifr_name", V::Txt("ifr_ifrn.ifrn_name")),
                ("ifr_hwaddr", V::Txt("ifr_ifru.ifru_hwaddr")),
                ("ifr_addr", V::Txt("ifr_ifru.ifru_addr")),
                ("ifr_dstaddr", V::Txt("ifr_ifru.ifru_dstaddr")),
                ("ifr_broadaddr", V::Txt("ifr_ifru.ifru_broadaddr")),
                ("ifr_netmask", V::Txt("ifr_ifru.ifru_netmask")),
                ("ifr_flags", V::Txt("ifr_ifru.ifru_flags")),
                ("ifr_metric", V::Txt("ifr_ifru.ifru_ivalue")),
                ("ifr_ifindex", V::Txt("ifr_ifru.ifru_ivalue")),
                ("ifr_mtu", V::Txt("ifr_ifru.ifru_mtu")),
                ("ifr_map", V::Txt("ifr_ifru.ifru_map")),
                ("ifr_slave", V::Txt("ifr_ifru.ifru_slave")),
                ("ifr_data", V::Txt("ifr_ifru.ifru_data")),
                ("ifr_qlen", V::Txt("ifr_ifru.ifru_ivalue")),
                ("ifr_newname", V::Txt("ifr_ifru.ifru_newname")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("_IOT_ifreq", V::Txt("_IOT (_IOTS (char), IFNAMSIZ, _IOTS (char), 16, 0, 0)")),
                ("_IOT_ifreq_short", V::Txt("_IOT (_IOTS (char), IFNAMSIZ, _IOTS (short), 1, 0, 0)")),
                ("_IOT_ifreq_int", V::Txt("_IOT (_IOTS (char), IFNAMSIZ, _IOTS (int), 1, 0, 0)")),
            ]),
            Item::Blank,
            Item::Block { head: "struct ifconf ", body: &["", "  int ifc_len;", "  union {", "    caddr_t ifcu_buf;", "    struct ifreq *ifcu_req;", "  } ifc_ifcu;", ""], tail: "" },
            Item::Consts(&[
                ("ifc_buf", V::Txt("ifc_ifcu.ifcu_buf")),
                ("ifc_req", V::Txt("ifc_ifcu.ifcu_req")),
                ("_IOT_ifconf", V::Txt("_IOT (_IOTS (struct ifconf), 1, 0, 0, 0, 0)")),
            ]),
            Item::Blank,
            Item::Include("<bits/rlibc-net-if.h>"),
        ]},
    ],
};
