use crate::model::*;

pub static HDR: Header = Header {
    path: "net/ethernet.h",
    items: &[
        Item::Guard { name: "_NET_ETHERNET_H", value: "1", end: "", items: &[
            Item::Include("<stdint.h>"),
            Item::Include("<sys/types.h>"),
            Item::Blank,
            Item::Consts(&[
                ("ETHERMIN", V::Dec(46)),
                ("ETHERMTU", V::Dec(1500)),
                ("ETHERTYPE_AARP", V::Dec(33011)),
                ("ETHERTYPE_ARP", V::Dec(2054)),
                ("ETHERTYPE_AT", V::Dec(32923)),
                ("ETHERTYPE_IP", V::Dec(2048)),
                ("ETHERTYPE_IPV6", V::Dec(34525)),
                ("ETHERTYPE_IPX", V::Dec(33079)),
                ("ETHERTYPE_LOOPBACK", V::Dec(36864)),
                ("ETHERTYPE_NTRAILER", V::Dec(16)),
                ("ETHERTYPE_PUP", V::Dec(512)),
                ("ETHERTYPE_REVARP", V::Dec(32821)),
                ("ETHERTYPE_SPRITE", V::Dec(1280)),
                ("ETHERTYPE_TRAIL", V::Dec(4096)),
                ("ETHERTYPE_VLAN", V::Dec(33024)),
                ("ETHER_ADDR_LEN", V::Dec(6)),
                ("ETHER_CRC_LEN", V::Dec(4)),
                ("ETHER_HDR_LEN", V::Dec(14)),
                ("ETHER_MAX_LEN", V::Dec(1518)),
                ("ETHER_MIN_LEN", V::Dec(64)),
                ("ETHER_TYPE_LEN", V::Dec(2)),
                ("ETH_ALEN", V::Dec(6)),
                ("ETH_DATA_LEN", V::Dec(1500)),
                ("ETH_FCS_LEN", V::Dec(4)),
                ("ETH_FRAME_LEN", V::Dec(1514)),
                ("ETH_HLEN", V::Dec(14)),
                ("ETH_MAX_MTU", V::Txt("0x0000ffffU")),
                ("ETH_MIN_MTU", V::Dec(68)),
                ("ETH_P_1588", V::Dec(35063)),
                ("ETH_P_8021AC", V::Dec(34928)),
                ("ETH_P_8021AD", V::Dec(34984)),
                ("ETH_P_8021AH", V::Dec(35047)),
                ("ETH_P_8021Q", V::Dec(33024)),
                ("ETH_P_80221", V::Dec(35095)),
                ("ETH_P_802_2", V::Dec(4)),
                ("ETH_P_802_3", V::Dec(1)),
                ("ETH_P_802_3_MIN", V::Dec(1536)),
                ("ETH_P_802_EX1", V::Dec(34997)),
                ("ETH_P_AARP", V::Dec(33011)),
                ("ETH_P_AF_IUCV", V::Dec(64507)),
                ("ETH_P_ALL", V::Dec(3)),
                ("ETH_P_AOE", V::Dec(34978)),
                ("ETH_P_ARCNET", V::Dec(26)),
                ("ETH_P_ARP", V::Dec(2054)),
                ("ETH_P_ATALK", V::Dec(32923)),
                ("ETH_P_ATMFATE", V::Dec(34948)),
                ("ETH_P_ATMMPOA", V::Dec(34892)),
                ("ETH_P_AX25", V::Dec(2)),
                ("ETH_P_BATMAN", V::Dec(17157)),
                ("ETH_P_BPQ", V::Dec(2303)),
                ("ETH_P_CAIF", V::Dec(247)),
                ("ETH_P_CAN", V::Dec(12)),
                ("ETH_P_CANFD", V::Dec(13)),
                ("ETH_P_CANXL", V::Dec(14)),
                ("ETH_P_CFM", V::Dec(35074)),
                ("ETH_P_CONTROL", V::Dec(22)),
                ("ETH_P_CUST", V::Dec(24582)),
                ("ETH_P_DDCMP", V::Dec(6)),
                ("ETH_P_DEC", V::Dec(24576)),
                ("ETH_P_DIAG", V::Dec(24581)),
                ("ETH_P_DNA_DL", V::Dec(24577)),
                ("ETH_P_DNA_RC", V::Dec(24578)),
                ("ETH_P_DNA_RT", V::Dec(24579)),
                ("ETH_P_DSA", V::Dec(27)),
                ("ETH_P_DSA_8021Q", V::Dec(56027)),
                ("ETH_P_DSA_A5PSW", V::Dec(57345)),
                ("ETH_P_ECONET", V::Dec(24)),
                ("ETH_P_EDSA", V::Dec(56026)),
                ("ETH_P_ERSPAN", V::Dec(35006)),
                ("ETH_P_ERSPAN2", V::Dec(8939)),
                ("ETH_P_ETHERCAT", V::Dec(34980)),
                ("ETH_P_FCOE", V::Dec(35078)),
                ("ETH_P_FIP", V::Dec(35092)),
                ("ETH_P_GRE_OSI", V::Dec(254)),
                ("ETH_P_HDLC", V::Dec(25)),
                ("ETH_P_HSR", V::Dec(35119)),
                ("ETH_P_IBOE", V::Dec(35093)),
                ("ETH_P_IEEE802154", V::Dec(246)),
                ("ETH_P_IEEEPUP", V::Dec(2560)),
                ("ETH_P_IEEEPUPAT", V::Dec(2561)),
                ("ETH_P_IFE", V::Dec(60734)),
                ("ETH_P_IP", V::Dec(2048)),
                ("ETH_P_IPV6", V::Dec(34525)),
                ("ETH_P_IPX", V::Dec(33079)),
                ("ETH_P_IRDA", V::Dec(23)),
                ("ETH_P_LAT", V::Dec(24580)),
                ("ETH_P_LINK_CTL", V::Dec(34924)),
                ("ETH_P_LLDP", V::Dec(35020)),
                ("ETH_P_LOCALTALK", V::Dec(9)),
                ("ETH_P_LOOP", V::Dec(96)),
                ("ETH_P_LOOPBACK", V::Dec(36864)),
                ("ETH_P_MACSEC", V::Dec(35045)),
                ("ETH_P_MAP", V::Dec(249)),
                ("ETH_P_MCTP", V::Dec(250)),
                ("ETH_P_MOBITEX", V::Dec(21)),
                ("ETH_P_MPLS_MC", V::Dec(34888)),
                ("ETH_P_MPLS_UC", V::Dec(34887)),
                ("ETH_P_MRP", V::Dec(35043)),
                ("ETH_P_MVRP", V::Dec(35061)),
                ("ETH_P_MXLGSW", V::Dec(35011)),
                ("ETH_P_NCSI", V::Dec(35064)),
                ("ETH_P_NSH", V::Dec(35151)),
                ("ETH_P_NXP_NETC", V::Dec(64826)),
                ("ETH_P_PAE", V::Dec(34958)),
                ("ETH_P_PAUSE", V::Dec(34824)),
                ("ETH_P_PHONET", V::Dec(245)),
                ("ETH_P_PPPTALK", V::Dec(16)),
                ("ETH_P_PPP_DISC", V::Dec(34915)),
                ("ETH_P_PPP_MP", V::Dec(8)),
                ("ETH_P_PPP_SES", V::Dec(34916)),
                ("ETH_P_PREAUTH", V::Dec(35015)),
                ("ETH_P_PROFINET", V::Dec(34962)),
                ("ETH_P_PRP", V::Dec(35067)),
                ("ETH_P_PUP", V::Dec(512)),
                ("ETH_P_PUPAT", V::Dec(513)),
                ("ETH_P_QINQ1", V::Dec(37120)),
                ("ETH_P_QINQ2", V::Dec(37376)),
                ("ETH_P_QINQ3", V::Dec(37632)),
                ("ETH_P_RARP", V::Dec(32821)),
                ("ETH_P_REALTEK", V::Dec(34969)),
                ("ETH_P_SCA", V::Dec(24583)),
                ("ETH_P_SLOW", V::Dec(34825)),
                ("ETH_P_SNAP", V::Dec(5)),
                ("ETH_P_TDLS", V::Dec(35085)),
                ("ETH_P_TEB", V::Dec(25944)),
                ("ETH_P_TIPC", V::Dec(35018)),
                ("ETH_P_TRAILER", V::Dec(28)),
                ("ETH_P_TR_802_2", V::Dec(17)),
                ("ETH_P_TSN", V::Dec(8944)),
                ("ETH_P_WAN_PPP", V::Dec(7)),
                ("ETH_P_WCCP", V::Dec(34878)),
                ("ETH_P_X25", V::Dec(2053)),
                ("ETH_P_XDSA", V::Dec(248)),
                ("ETH_P_YT921X", V::Dec(39304)),
                ("ETH_TLEN", V::Dec(2)),
                ("ETH_ZLEN", V::Dec(60)),
            ]),
            Item::Blank,
            Item::Block { head: "struct ether_addr ", body: &["", "  uint8_t ether_addr_octet[ETH_ALEN];", ""], tail: " __attribute__ ((__packed__))" },
            Item::Blank,
            Item::Block { head: "struct ether_header ", body: &["", "  uint8_t ether_dhost[ETH_ALEN];", "  uint8_t ether_shost[ETH_ALEN];", "  uint16_t ether_type;", ""], tail: " __attribute__ ((__packed__))" },
        ]},
    ],
};
