use crate::model::*;

pub static HDR: Header = Header {
    path: "net/route.h",
    items: &[
        Item::Guard { name: "_NET_ROUTE_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<sys/types.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<netinet/in.h>"),
            Item::Include("<sys/socket.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: r#"struct rtentry
  "#, body: &["", "    unsigned long int rt_pad1;", "    struct sockaddr rt_dst;", "    struct sockaddr rt_gateway;", "    struct sockaddr rt_genmask;", "    unsigned short int rt_flags;", "    short int rt_pad2;", "    unsigned long int rt_pad3;", "    unsigned char rt_tos;", "    unsigned char rt_class;", "    short int rt_pad4[3];", "    short int rt_metric;", "    char *rt_dev;", "    unsigned long int rt_mtu;", "    unsigned long int rt_window;", "    unsigned short int rt_irtt;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct in6_rtmsg
  "#, body: &["", "    struct in6_addr rtmsg_dst;", "    struct in6_addr rtmsg_src;", "    struct in6_addr rtmsg_gateway;", "    uint32_t rtmsg_type;", "    uint16_t rtmsg_dst_len;", "    uint16_t rtmsg_src_len;", "    uint32_t rtmsg_metric;", "    unsigned long int rtmsg_info;", "    uint32_t rtmsg_flags;", "    int rtmsg_ifindex;", "  "], tail: "" },
            Item::Consts(&[
                ("RTCF_DIRECTSRC", V::Txt("0x04000000")),
                ("RTCF_DOREDIRECT", V::Txt("0x01000000")),
                ("RTCF_LOG", V::Txt("0x02000000")),
                ("RTCF_MASQ", V::Txt("0x00400000")),
                ("RTCF_NAT", V::Txt("0x00800000")),
                ("RTCF_VALVE", V::Txt("0x00200000")),
                ("RTF_ADDRCLASSMASK", V::Txt("0xF8000000")),
                ("RTF_ADDRCONF", V::Txt("0x00040000")),
                ("RTF_ALLONLINK", V::Txt("0x00020000")),
                ("RTF_BROADCAST", V::Hex(0x10000000)),
                ("RTF_CACHE", V::Txt("0x01000000")),
                ("RTF_DEFAULT", V::Txt("0x00010000")),
                ("RTF_DYNAMIC", V::Txt("0x0010")),
                ("RTF_FLOW", V::Txt("0x02000000")),
                ("RTF_GATEWAY", V::Txt("0x0002")),
                ("RTF_HOST", V::Txt("0x0004")),
                ("RTF_INTERFACE", V::Hex(0x40000000)),
                ("RTF_IRTT", V::Txt("0x0100")),
                ("RTF_LINKRT", V::Txt("0x00100000")),
                ("RTF_LOCAL", V::Hex(0x80000000)),
                ("RTF_MODIFIED", V::Txt("0x0020")),
                ("RTF_MSS", V::Txt("RTF_MTU")),
                ("RTF_MTU", V::Txt("0x0040")),
                ("RTF_MULTICAST", V::Hex(0x20000000)),
                ("RTF_NAT", V::Txt("0x08000000")),
                ("RTF_NOFORWARD", V::Hex(0x1000)),
                ("RTF_NONEXTHOP", V::Txt("0x00200000")),
                ("RTF_NOPMTUDISC", V::Hex(0x4000)),
                ("RTF_POLICY", V::Txt("0x04000000")),
                ("RTF_REINSTATE", V::Txt("0x0008")),
                ("RTF_REJECT", V::Txt("0x0200")),
                ("RTF_STATIC", V::Txt("0x0400")),
                ("RTF_THROW", V::Hex(0x2000)),
                ("RTF_UP", V::Txt("0x0001")),
                ("RTF_WINDOW", V::Txt("0x0080")),
                ("RTF_XRESOLVE", V::Txt("0x0800")),
                ("RTMSG_ACK", V::Txt("NLMSG_ACK")),
                ("RTMSG_AR_FAILED", V::Hex(0x51)),
                ("RTMSG_CONTROL", V::Hex(0x40)),
                ("RTMSG_DELDEVICE", V::Hex(0x12)),
                ("RTMSG_DELROUTE", V::Hex(0x22)),
                ("RTMSG_DELRULE", V::Hex(0x32)),
                ("RTMSG_NEWDEVICE", V::Hex(0x11)),
                ("RTMSG_NEWROUTE", V::Hex(0x21)),
                ("RTMSG_NEWRULE", V::Hex(0x31)),
                ("RTMSG_OVERRUN", V::Txt("NLMSG_OVERRUN")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define RT_ADDRCLASS(flags) ((uint32_t) flags >> 23)"),
            Item::Consts(&[
                ("RT_CLASS_DEFAULT", V::Dec(253)),
                ("RT_CLASS_LOCAL", V::Dec(255)),
                ("RT_CLASS_MAIN", V::Dec(254)),
                ("RT_CLASS_MAX", V::Dec(255)),
                ("RT_CLASS_UNSPEC", V::Dec(0)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define RT_LOCALADDR(flags) ((flags & RTF_ADDRCLASSMASK) == (RTF_LOCAL|RTF_INTERFACE))"),
            Item::Raw(Reason::GlibcMacro, "#define RT_TOS(tos) ((tos) & IPTOS_TOS_MASK)"),
            Item::Consts(&[
                ("rt_mss", V::Txt("rt_mtu")),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
