use crate::model::*;

pub static HDR: Header = Header {
    path: "netdb.h",
    items: &[
        Item::Guard { name: "_NETDB_H", value: "1", end: "", items: &[
            Item::Include("<stddef.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<netinet/in.h>"),
            Item::Include("<bits/types/struct_timespec.h>"),
            Item::Include("<bits/types/struct_sigevent.h>"),
            Item::Blank,
            Item::Consts(&[
                ("_PATH_HEQUIV", V::Txt(r#""/etc/hosts.equiv""#)),
                ("_PATH_HOSTS", V::Txt(r#""/etc/hosts""#)),
                ("_PATH_NETWORKS", V::Txt(r#""/etc/networks""#)),
                ("_PATH_NSSWITCH_CONF", V::Txt(r#""/etc/nsswitch.conf""#)),
                ("_PATH_PROTOCOLS", V::Txt(r#""/etc/protocols""#)),
                ("_PATH_SERVICES", V::Txt(r#""/etc/services""#)),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("h_errno", V::Txt("(*__h_errno_location ())")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("AI_ADDRCONFIG", V::Dec(32)),
                ("AI_ALL", V::Dec(16)),
                ("AI_CANONIDN", V::Dec(128)),
                ("AI_CANONNAME", V::Dec(2)),
                ("AI_IDN", V::Dec(64)),
                ("AI_NUMERICHOST", V::Dec(4)),
                ("AI_NUMERICSERV", V::Dec(1024)),
                ("AI_PASSIVE", V::Dec(1)),
                ("AI_V4MAPPED", V::Dec(8)),
                ("EAI_ADDRFAMILY", V::Dec(-9)),
                ("EAI_AGAIN", V::Dec(-3)),
                ("EAI_ALLDONE", V::Dec(-103)),
                ("EAI_BADFLAGS", V::Dec(-1)),
                ("EAI_CANCELED", V::Dec(-101)),
                ("EAI_FAIL", V::Dec(-4)),
                ("EAI_FAMILY", V::Dec(-6)),
                ("EAI_IDN_ENCODE", V::Dec(-105)),
                ("EAI_INPROGRESS", V::Dec(-100)),
                ("EAI_INTR", V::Dec(-104)),
                ("EAI_MEMORY", V::Dec(-10)),
                ("EAI_NODATA", V::Dec(-5)),
                ("EAI_NONAME", V::Dec(-2)),
                ("EAI_NOTCANCELED", V::Dec(-102)),
                ("EAI_OVERFLOW", V::Dec(-12)),
                ("EAI_SERVICE", V::Dec(-8)),
                ("EAI_SOCKTYPE", V::Dec(-7)),
                ("EAI_SYSTEM", V::Dec(-11)),
                ("GAI_NOWAIT", V::Dec(1)),
                ("GAI_WAIT", V::Dec(0)),
                ("HOST_NOT_FOUND", V::Dec(1)),
                ("NETDB_INTERNAL", V::Dec(-1)),
                ("NETDB_SUCCESS", V::Dec(0)),
                ("NI_DGRAM", V::Dec(16)),
                ("NI_IDN", V::Dec(32)),
                ("NI_MAXHOST", V::Dec(1025)),
                ("NI_MAXSERV", V::Dec(32)),
                ("NI_NAMEREQD", V::Dec(8)),
                ("NI_NOFQDN", V::Dec(4)),
                ("NI_NUMERICHOST", V::Dec(1)),
                ("NI_NUMERICSERV", V::Dec(2)),
                ("NO_ADDRESS", V::Dec(4)),
                ("NO_DATA", V::Dec(4)),
                ("NO_RECOVERY", V::Dec(3)),
                ("TRY_AGAIN", V::Dec(2)),
            ]),
            Item::Blank,
            Item::Block { head: "struct hostent ", body: &["", "  char *h_name;", "  char **h_aliases;", "  int h_addrtype;", "  int h_length;", "  char **h_addr_list;", ""], tail: "" },
            Item::Consts(&[
                ("h_addr", V::Txt("h_addr_list[0]")),
            ]),
            Item::Blank,
            Item::Block { head: "struct servent ", body: &["", "  char *s_name;", "  char **s_aliases;", "  int s_port;", "  char *s_proto;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct protoent ", body: &["", "  char *p_name;", "  char **p_aliases;", "  int p_proto;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct netent ", body: &["", "  char *n_name;", "  char **n_aliases;", "  int n_addrtype;", "  uint32_t n_net;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct rpcent ", body: &["", "  char *r_name;", "  char **r_aliases;", "  int r_number;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct addrinfo ", body: &["", "  int ai_flags;", "  int ai_family;", "  int ai_socktype;", "  int ai_protocol;", "  socklen_t ai_addrlen;", "  struct sockaddr *ai_addr;", "  char *ai_canonname;", "  struct addrinfo *ai_next;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct gaicb ", body: &["", "  const char *ar_name;", "  const char *ar_service;", "  const struct addrinfo *ar_request;", "  struct addrinfo *ar_result;", "", "  int __return;", "  int __glibc_reserved[5];", ""], tail: "" },
            Item::Blank,
            Item::Include("<bits/rlibc-net-netdb.h>"),
        ]},
    ],
};
