use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/ip.h",
    items: &[
        Item::Guard { name: "_NETINET_IP_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<sys/types.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<endian.h>"),
            Item::Include("<netinet/in.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: r#"struct timestamp
  "#, body: &["", "    uint8_t len;", "    uint8_t ptr;", "#if __BYTE_ORDER == __LITTLE_ENDIAN", "    unsigned int flags:4;", "    unsigned int overflow:4;", "#else", "    unsigned int overflow:4;", "    unsigned int flags:4;", "#endif", "    uint32_t data[9];", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct iphdr
  "#, body: &["", "#if __BYTE_ORDER == __LITTLE_ENDIAN", "    unsigned int ihl:4;", "    unsigned int version:4;", "#else", "    unsigned int version:4;", "    unsigned int ihl:4;", "#endif", "    uint8_t tos;", "    uint16_t tot_len;", "    uint16_t id;", "    uint16_t frag_off;", "    uint8_t ttl;", "    uint8_t protocol;", "    uint16_t check;", "    uint32_t saddr;", "    uint32_t daddr;", "  "], tail: "" },
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __USE_MISC", items: &[
                    Item::Block { head: r#"struct ip
  "#, body: &["", "#if __BYTE_ORDER == __LITTLE_ENDIAN", "    unsigned int ip_hl:4;", "    unsigned int ip_v:4;", "#else", "    unsigned int ip_v:4;", "    unsigned int ip_hl:4;", "#endif", "    uint8_t ip_tos;", "    unsigned short ip_len;", "    unsigned short ip_id;", "    unsigned short ip_off;", "    uint8_t ip_ttl;", "    uint8_t ip_p;", "    unsigned short ip_sum;", "    struct in_addr ip_src, ip_dst;", "  "], tail: "" },
                    Item::Blank,
                    Item::Block { head: r#"struct ip_timestamp
  "#, body: &["", "    uint8_t ipt_code;", "    uint8_t ipt_len;", "    uint8_t ipt_ptr;", "#if __BYTE_ORDER == __LITTLE_ENDIAN", "    unsigned int ipt_flg:4;", "    unsigned int ipt_oflw:4;", "#else", "    unsigned int ipt_oflw:4;", "    unsigned int ipt_flg:4;", "#endif", "    uint32_t data[9];", "  "], tail: "" },
                ] },
            ], ""),
            Item::Consts(&[
                ("IPDEFTTL", V::Dec(64)),
                ("IPFRAGTTL", V::Dec(60)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPOPT_CLASS(o) ((o) & IPOPT_CLASS_MASK)"),
            Item::Consts(&[
                ("IPOPT_CLASS_MASK", V::Hex(0x60)),
                ("IPOPT_CONTROL", V::Txt("0x00")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPOPT_COPIED(o) ((o) & IPOPT_COPY)"),
            Item::Consts(&[
                ("IPOPT_COPY", V::Hex(0x80)),
                ("IPOPT_DEBMEAS", V::Hex(0x40)),
                ("IPOPT_END", V::Txt("IPOPT_EOL")),
                ("IPOPT_EOL", V::Dec(0)),
                ("IPOPT_LSRR", V::Dec(131)),
                ("IPOPT_MEASUREMENT", V::Txt("IPOPT_DEBMEAS")),
                ("IPOPT_MINOFF", V::Dec(4)),
                ("IPOPT_NOOP", V::Txt("IPOPT_NOP")),
                ("IPOPT_NOP", V::Dec(1)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPOPT_NUMBER(o) ((o) & IPOPT_NUMBER_MASK)"),
            Item::Consts(&[
                ("IPOPT_NUMBER_MASK", V::Hex(0x1f)),
                ("IPOPT_OFFSET", V::Dec(2)),
                ("IPOPT_OLEN", V::Dec(1)),
                ("IPOPT_OPTVAL", V::Dec(0)),
                ("IPOPT_RA", V::Dec(148)),
                ("IPOPT_RESERVED1", V::Hex(0x20)),
                ("IPOPT_RESERVED2", V::Hex(0x60)),
                ("IPOPT_RR", V::Dec(7)),
                ("IPOPT_SATID", V::Dec(136)),
                ("IPOPT_SEC", V::Txt("IPOPT_SECURITY")),
                ("IPOPT_SECURITY", V::Dec(130)),
                ("IPOPT_SECUR_CONFID", V::Hex(0xf135)),
                ("IPOPT_SECUR_EFTO", V::Hex(0x789a)),
                ("IPOPT_SECUR_MMMM", V::Hex(0xbc4d)),
                ("IPOPT_SECUR_RESTR", V::Hex(0xaf13)),
                ("IPOPT_SECUR_SECRET", V::Hex(0xd788)),
                ("IPOPT_SECUR_TOPSECRET", V::Hex(0x6bc5)),
                ("IPOPT_SECUR_UNCLASS", V::Txt("0x0000")),
                ("IPOPT_SID", V::Txt("IPOPT_SATID")),
                ("IPOPT_SSRR", V::Dec(137)),
                ("IPOPT_TIMESTAMP", V::Txt("IPOPT_TS")),
                ("IPOPT_TS", V::Dec(68)),
                ("IPOPT_TS_PRESPEC", V::Dec(3)),
                ("IPOPT_TS_TSANDADDR", V::Dec(1)),
                ("IPOPT_TS_TSONLY", V::Dec(0)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPTOS_CLASS(class) ((class) & IPTOS_CLASS_MASK)"),
            Item::Consts(&[
                ("IPTOS_CLASS_CS0", V::Txt("0x00")),
                ("IPTOS_CLASS_CS1", V::Hex(0x20)),
                ("IPTOS_CLASS_CS2", V::Hex(0x40)),
                ("IPTOS_CLASS_CS3", V::Hex(0x60)),
                ("IPTOS_CLASS_CS4", V::Hex(0x80)),
                ("IPTOS_CLASS_CS5", V::Hex(0xa0)),
                ("IPTOS_CLASS_CS6", V::Hex(0xc0)),
                ("IPTOS_CLASS_CS7", V::Hex(0xe0)),
                ("IPTOS_CLASS_DEFAULT", V::Txt("IPTOS_CLASS_CS0")),
                ("IPTOS_CLASS_MASK", V::Hex(0xe0)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPTOS_DSCP(x) ((x) & IPTOS_DSCP_MASK)"),
            Item::Consts(&[
                ("IPTOS_DSCP_AF11", V::Hex(0x28)),
                ("IPTOS_DSCP_AF12", V::Hex(0x30)),
                ("IPTOS_DSCP_AF13", V::Hex(0x38)),
                ("IPTOS_DSCP_AF21", V::Hex(0x48)),
                ("IPTOS_DSCP_AF22", V::Hex(0x50)),
                ("IPTOS_DSCP_AF23", V::Hex(0x58)),
                ("IPTOS_DSCP_AF31", V::Hex(0x68)),
                ("IPTOS_DSCP_AF32", V::Hex(0x70)),
                ("IPTOS_DSCP_AF33", V::Hex(0x78)),
                ("IPTOS_DSCP_AF41", V::Hex(0x88)),
                ("IPTOS_DSCP_AF42", V::Hex(0x90)),
                ("IPTOS_DSCP_AF43", V::Hex(0x98)),
                ("IPTOS_DSCP_EF", V::Hex(0xb8)),
                ("IPTOS_DSCP_LE", V::Txt("0x04")),
                ("IPTOS_DSCP_MASK", V::Hex(0xfc)),
                ("IPTOS_DSCP_VA", V::Hex(0xb0)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPTOS_ECN(x) ((x) & IPTOS_ECN_MASK)"),
            Item::Consts(&[
                ("IPTOS_ECN_CE", V::Txt("0x03")),
                ("IPTOS_ECN_ECT0", V::Txt("0x02")),
                ("IPTOS_ECN_ECT1", V::Txt("0x01")),
                ("IPTOS_ECN_MASK", V::Txt("0x03")),
                ("IPTOS_ECN_NOT_ECT", V::Txt("0x00")),
                ("IPTOS_LOWCOST", V::Txt("0x02")),
                ("IPTOS_LOWDELAY", V::Hex(0x10)),
                ("IPTOS_MINCOST", V::Txt("IPTOS_LOWCOST")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPTOS_PREC(tos) IPTOS_CLASS(tos)"),
            Item::Consts(&[
                ("IPTOS_PREC_CRITIC_ECP", V::Txt("IPTOS_CLASS_CS5")),
                ("IPTOS_PREC_FLASH", V::Txt("IPTOS_CLASS_CS3")),
                ("IPTOS_PREC_FLASHOVERRIDE", V::Txt("IPTOS_CLASS_CS4")),
                ("IPTOS_PREC_IMMEDIATE", V::Txt("IPTOS_CLASS_CS2")),
                ("IPTOS_PREC_INTERNETCONTROL", V::Txt("IPTOS_CLASS_CS6")),
                ("IPTOS_PREC_MASK", V::Txt("IPTOS_CLASS_MASK")),
                ("IPTOS_PREC_NETCONTROL", V::Txt("IPTOS_CLASS_CS7")),
                ("IPTOS_PREC_PRIORITY", V::Txt("IPTOS_CLASS_CS1")),
                ("IPTOS_PREC_ROUTINE", V::Txt("IPTOS_CLASS_CS0")),
                ("IPTOS_RELIABILITY", V::Txt("0x04")),
                ("IPTOS_THROUGHPUT", V::Txt("0x08")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define IPTOS_TOS(tos) ((tos) & IPTOS_TOS_MASK)"),
            Item::Consts(&[
                ("IPTOS_TOS_MASK", V::Txt("0x1E")),
                ("IPTTLDEC", V::Dec(1)),
                ("IPVERSION", V::Dec(4)),
                ("IP_DF", V::Hex(0x4000)),
                ("IP_MAXPACKET", V::Dec(65535)),
                ("IP_MF", V::Hex(0x2000)),
                ("IP_MSS", V::Dec(576)),
                ("IP_OFFMASK", V::Hex(0x1fff)),
                ("IP_RF", V::Hex(0x8000)),
                ("MAXTTL", V::Dec(255)),
                ("MAX_IPOPTLEN", V::Dec(40)),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
