use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/in.h",
    items: &[
        Item::Guard { name: "_NETINET_IN_H", value: "1", end: "", items: &[
            Item::Include("<stdint.h>"),
            Item::Include("<sys/socket.h>"),
            Item::Blank,
            Item::Typedef("uint16_t", "in_port_t"),
            Item::Typedef("uint32_t", "in_addr_t"),
            Item::Blank,
            Item::Block { head: "struct in_addr ", body: &["", "  in_addr_t s_addr;", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("INET6_ADDRSTRLEN", V::Dec(46)),
                ("INET_ADDRSTRLEN", V::Dec(16)),
                ("IN_CLASSA_HOST", V::Txt("0x00ffffffU")),
                ("IN_CLASSA_MAX", V::Dec(128)),
                ("IN_CLASSA_NET", V::Txt("0xff000000U")),
                ("IN_CLASSA_NSHIFT", V::Dec(24)),
                ("IN_CLASSB_HOST", V::Txt("0x0000ffffU")),
                ("IN_CLASSB_MAX", V::Dec(65536)),
                ("IN_CLASSB_NET", V::Txt("0xffff0000U")),
                ("IN_CLASSB_NSHIFT", V::Dec(16)),
                ("IN_CLASSC_HOST", V::Txt("0x000000ffU")),
                ("IN_CLASSC_NET", V::Txt("0xffffff00U")),
                ("IN_CLASSC_NSHIFT", V::Dec(8)),
                ("IN_LOOPBACKNET", V::Dec(127)),
                ("IPPROTO_AH", V::Dec(51)),
                ("IPPROTO_BEETPH", V::Dec(94)),
                ("IPPROTO_COMP", V::Dec(108)),
                ("IPPROTO_DCCP", V::Dec(33)),
                ("IPPROTO_DSTOPTS", V::Dec(60)),
                ("IPPROTO_EGP", V::Dec(8)),
                ("IPPROTO_ENCAP", V::Dec(98)),
                ("IPPROTO_ESP", V::Dec(50)),
                ("IPPROTO_ETHERNET", V::Dec(143)),
                ("IPPROTO_FRAGMENT", V::Dec(44)),
                ("IPPROTO_GRE", V::Dec(47)),
                ("IPPROTO_HOPOPTS", V::Dec(0)),
                ("IPPROTO_ICMP", V::Dec(1)),
                ("IPPROTO_ICMPV6", V::Dec(58)),
                ("IPPROTO_IDP", V::Dec(22)),
                ("IPPROTO_IGMP", V::Dec(2)),
                ("IPPROTO_IP", V::Dec(0)),
                ("IPPROTO_IPIP", V::Dec(4)),
                ("IPPROTO_IPV6", V::Dec(41)),
                ("IPPROTO_L2TP", V::Dec(115)),
                ("IPPROTO_MH", V::Dec(135)),
                ("IPPROTO_MPLS", V::Dec(137)),
                ("IPPROTO_MPTCP", V::Dec(262)),
                ("IPPROTO_MTP", V::Dec(92)),
                ("IPPROTO_NONE", V::Dec(59)),
                ("IPPROTO_PIM", V::Dec(103)),
                ("IPPROTO_PUP", V::Dec(12)),
                ("IPPROTO_RAW", V::Dec(255)),
                ("IPPROTO_ROUTING", V::Dec(43)),
                ("IPPROTO_RSVP", V::Dec(46)),
                ("IPPROTO_SCTP", V::Dec(132)),
                ("IPPROTO_SMC", V::Dec(256)),
                ("IPPROTO_TCP", V::Dec(6)),
                ("IPPROTO_TP", V::Dec(29)),
                ("IPPROTO_UDP", V::Dec(17)),
                ("IPPROTO_UDPLITE", V::Dec(136)),
                ("IPV6_2292DSTOPTS", V::Dec(4)),
                ("IPV6_2292HOPLIMIT", V::Dec(8)),
                ("IPV6_2292HOPOPTS", V::Dec(3)),
                ("IPV6_2292PKTINFO", V::Dec(2)),
                ("IPV6_2292PKTOPTIONS", V::Dec(6)),
                ("IPV6_2292RTHDR", V::Dec(5)),
                ("IPV6_ADDRFORM", V::Dec(1)),
                ("IPV6_ADDR_PREFERENCES", V::Dec(72)),
                ("IPV6_ADD_MEMBERSHIP", V::Dec(20)),
                ("IPV6_AUTHHDR", V::Dec(10)),
                ("IPV6_AUTOFLOWLABEL", V::Dec(70)),
                ("IPV6_CHECKSUM", V::Dec(7)),
                ("IPV6_DONTFRAG", V::Dec(62)),
                ("IPV6_DROP_MEMBERSHIP", V::Dec(21)),
                ("IPV6_DSTOPTS", V::Dec(59)),
                ("IPV6_FREEBIND", V::Dec(78)),
                ("IPV6_HDRINCL", V::Dec(36)),
                ("IPV6_HOPLIMIT", V::Dec(52)),
                ("IPV6_HOPOPTS", V::Dec(54)),
                ("IPV6_IPSEC_POLICY", V::Dec(34)),
                ("IPV6_JOIN_ANYCAST", V::Dec(27)),
                ("IPV6_JOIN_GROUP", V::Dec(20)),
                ("IPV6_LEAVE_ANYCAST", V::Dec(28)),
                ("IPV6_LEAVE_GROUP", V::Dec(21)),
                ("IPV6_MINHOPCOUNT", V::Dec(73)),
                ("IPV6_MTU", V::Dec(24)),
                ("IPV6_MTU_DISCOVER", V::Dec(23)),
                ("IPV6_MULTICAST_ALL", V::Dec(29)),
                ("IPV6_MULTICAST_HOPS", V::Dec(18)),
                ("IPV6_MULTICAST_IF", V::Dec(17)),
                ("IPV6_MULTICAST_LOOP", V::Dec(19)),
                ("IPV6_NEXTHOP", V::Dec(9)),
                ("IPV6_ORIGDSTADDR", V::Dec(74)),
                ("IPV6_PATHMTU", V::Dec(61)),
                ("IPV6_PKTINFO", V::Dec(50)),
                ("IPV6_PMTUDISC_DO", V::Dec(2)),
                ("IPV6_PMTUDISC_DONT", V::Dec(0)),
                ("IPV6_PMTUDISC_INTERFACE", V::Dec(4)),
                ("IPV6_PMTUDISC_OMIT", V::Dec(5)),
                ("IPV6_PMTUDISC_PROBE", V::Dec(3)),
                ("IPV6_PMTUDISC_WANT", V::Dec(1)),
                ("IPV6_RECVDSTOPTS", V::Dec(58)),
                ("IPV6_RECVERR", V::Dec(25)),
                ("IPV6_RECVERR_RFC4884", V::Dec(31)),
                ("IPV6_RECVFRAGSIZE", V::Dec(77)),
                ("IPV6_RECVHOPLIMIT", V::Dec(51)),
                ("IPV6_RECVHOPOPTS", V::Dec(53)),
                ("IPV6_RECVORIGDSTADDR", V::Dec(74)),
                ("IPV6_RECVPATHMTU", V::Dec(60)),
                ("IPV6_RECVPKTINFO", V::Dec(49)),
                ("IPV6_RECVRTHDR", V::Dec(56)),
                ("IPV6_RECVTCLASS", V::Dec(66)),
                ("IPV6_ROUTER_ALERT", V::Dec(22)),
                ("IPV6_ROUTER_ALERT_ISOLATE", V::Dec(30)),
                ("IPV6_RTHDR", V::Dec(57)),
                ("IPV6_RTHDRDSTOPTS", V::Dec(55)),
                ("IPV6_RTHDR_LOOSE", V::Dec(0)),
                ("IPV6_RTHDR_STRICT", V::Dec(1)),
                ("IPV6_RTHDR_TYPE_0", V::Dec(0)),
                ("IPV6_RXDSTOPTS", V::Dec(59)),
                ("IPV6_RXHOPOPTS", V::Dec(54)),
                ("IPV6_TCLASS", V::Dec(67)),
                ("IPV6_TRANSPARENT", V::Dec(75)),
                ("IPV6_UNICAST_HOPS", V::Dec(16)),
                ("IPV6_UNICAST_IF", V::Dec(76)),
                ("IPV6_V6ONLY", V::Dec(26)),
                ("IPV6_XFRM_POLICY", V::Dec(35)),
                ("IP_ADD_MEMBERSHIP", V::Dec(35)),
                ("IP_ADD_SOURCE_MEMBERSHIP", V::Dec(39)),
                ("IP_BIND_ADDRESS_NO_PORT", V::Dec(24)),
                ("IP_BLOCK_SOURCE", V::Dec(38)),
                ("IP_CHECKSUM", V::Dec(23)),
                ("IP_DEFAULT_MULTICAST_LOOP", V::Dec(1)),
                ("IP_DEFAULT_MULTICAST_TTL", V::Dec(1)),
                ("IP_DROP_MEMBERSHIP", V::Dec(36)),
                ("IP_DROP_SOURCE_MEMBERSHIP", V::Dec(40)),
                ("IP_FREEBIND", V::Dec(15)),
                ("IP_HDRINCL", V::Dec(3)),
                ("IP_IPSEC_POLICY", V::Dec(16)),
                ("IP_LOCAL_PORT_RANGE", V::Dec(51)),
                ("IP_MAX_MEMBERSHIPS", V::Dec(20)),
                ("IP_MINTTL", V::Dec(21)),
                ("IP_MSFILTER", V::Dec(41)),
                ("IP_MTU", V::Dec(14)),
                ("IP_MTU_DISCOVER", V::Dec(10)),
                ("IP_MULTICAST_ALL", V::Dec(49)),
                ("IP_MULTICAST_IF", V::Dec(32)),
                ("IP_MULTICAST_LOOP", V::Dec(34)),
                ("IP_MULTICAST_TTL", V::Dec(33)),
                ("IP_NODEFRAG", V::Dec(22)),
                ("IP_OPTIONS", V::Dec(4)),
                ("IP_ORIGDSTADDR", V::Dec(20)),
                ("IP_PASSSEC", V::Dec(18)),
                ("IP_PKTINFO", V::Dec(8)),
                ("IP_PKTOPTIONS", V::Dec(9)),
                ("IP_PMTUDISC", V::Dec(10)),
                ("IP_PMTUDISC_DO", V::Dec(2)),
                ("IP_PMTUDISC_DONT", V::Dec(0)),
                ("IP_PMTUDISC_INTERFACE", V::Dec(4)),
                ("IP_PMTUDISC_OMIT", V::Dec(5)),
                ("IP_PMTUDISC_PROBE", V::Dec(3)),
                ("IP_PMTUDISC_WANT", V::Dec(1)),
                ("IP_PROTOCOL", V::Dec(52)),
                ("IP_RECVERR", V::Dec(11)),
                ("IP_RECVERR_RFC4884", V::Dec(26)),
                ("IP_RECVFRAGSIZE", V::Dec(25)),
                ("IP_RECVOPTS", V::Dec(6)),
                ("IP_RECVORIGDSTADDR", V::Dec(20)),
                ("IP_RECVRETOPTS", V::Dec(7)),
                ("IP_RECVTOS", V::Dec(13)),
                ("IP_RECVTTL", V::Dec(12)),
                ("IP_RETOPTS", V::Dec(7)),
                ("IP_ROUTER_ALERT", V::Dec(5)),
                ("IP_TOS", V::Dec(1)),
                ("IP_TRANSPARENT", V::Dec(19)),
                ("IP_TTL", V::Dec(2)),
                ("IP_UNBLOCK_SOURCE", V::Dec(37)),
                ("IP_UNICAST_IF", V::Dec(50)),
                ("IP_XFRM_POLICY", V::Dec(17)),
                ("MCAST_BLOCK_SOURCE", V::Dec(43)),
                ("MCAST_EXCLUDE", V::Dec(0)),
                ("MCAST_INCLUDE", V::Dec(1)),
                ("MCAST_JOIN_GROUP", V::Dec(42)),
                ("MCAST_JOIN_SOURCE_GROUP", V::Dec(46)),
                ("MCAST_LEAVE_GROUP", V::Dec(45)),
                ("MCAST_LEAVE_SOURCE_GROUP", V::Dec(47)),
                ("MCAST_MSFILTER", V::Dec(48)),
                ("MCAST_UNBLOCK_SOURCE", V::Dec(44)),
                ("SOL_ICMPV6", V::Dec(58)),
                ("SOL_IP", V::Dec(0)),
                ("SOL_IPV6", V::Dec(41)),
                ("INADDR_ANY", V::Txt("((in_addr_t) 0x00000000)")),
                ("INADDR_BROADCAST", V::Txt("((in_addr_t) 0xffffffff)")),
                ("INADDR_NONE", V::Txt("((in_addr_t) 0xffffffff)")),
                ("INADDR_LOOPBACK", V::Txt("((in_addr_t) 0x7f000001)")),
                ("INADDR_UNSPEC_GROUP", V::Txt("((in_addr_t) 0xe0000000)")),
                ("INADDR_ALLHOSTS_GROUP", V::Txt("((in_addr_t) 0xe0000001)")),
                ("INADDR_ALLRTRS_GROUP", V::Txt("((in_addr_t) 0xe0000002)")),
                ("INADDR_ALLSNOOPERS_GROUP", V::Txt("((in_addr_t) 0xe000006a)")),
                ("INADDR_MAX_LOCAL_GROUP", V::Txt("((in_addr_t) 0xe00000ff)")),
                ("INADDR_DUMMY", V::Txt("((in_addr_t) 0xc0000008)")),
                ("IPPORT_ECHO", V::Dec(7)),
                ("IPPORT_DISCARD", V::Dec(9)),
                ("IPPORT_SYSTAT", V::Dec(11)),
                ("IPPORT_DAYTIME", V::Dec(13)),
                ("IPPORT_NETSTAT", V::Dec(15)),
                ("IPPORT_FTP", V::Dec(21)),
                ("IPPORT_TELNET", V::Dec(23)),
                ("IPPORT_SMTP", V::Dec(25)),
                ("IPPORT_TIMESERVER", V::Dec(37)),
                ("IPPORT_NAMESERVER", V::Dec(42)),
                ("IPPORT_WHOIS", V::Dec(43)),
                ("IPPORT_MTP", V::Dec(57)),
                ("IPPORT_TFTP", V::Dec(69)),
                ("IPPORT_RJE", V::Dec(77)),
                ("IPPORT_FINGER", V::Dec(79)),
                ("IPPORT_TTYLINK", V::Dec(87)),
                ("IPPORT_SUPDUP", V::Dec(95)),
                ("IPPORT_EXECSERVER", V::Dec(512)),
                ("IPPORT_LOGINSERVER", V::Dec(513)),
                ("IPPORT_CMDSERVER", V::Dec(514)),
                ("IPPORT_EFSSERVER", V::Dec(520)),
                ("IPPORT_BIFFUDP", V::Dec(512)),
                ("IPPORT_WHOSERVER", V::Dec(513)),
                ("IPPORT_ROUTESERVER", V::Dec(520)),
                ("IPPORT_RESERVED", V::Dec(1024)),
                ("IPPORT_USERRESERVED", V::Dec(5000)),
            ]),
            Item::Blank,
            Item::Block { head: "struct in6_addr ", body: &["", "  union {", "    uint8_t __u6_addr8[16];", "    uint16_t __u6_addr16[8];", "    uint32_t __u6_addr32[4];", "  } __in6_u;", "#define s6_addr __in6_u.__u6_addr8", "#define s6_addr16 __in6_u.__u6_addr16", "#define s6_addr32 __in6_u.__u6_addr32", ""], tail: "" },
            Item::Blank,
            Item::Decl("extern const struct in6_addr in6addr_any;"),
            Item::Decl("extern const struct in6_addr in6addr_loopback;"),
            Item::Consts(&[
                ("IN6ADDR_ANY_INIT", V::Txt("{ { { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } } }")),
                ("IN6ADDR_LOOPBACK_INIT", V::Txt("{ { { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1 } } }")),
            ]),
            Item::Blank,
            Item::Block { head: "struct sockaddr_in ", body: &["", "  sa_family_t sin_family;", "  in_port_t sin_port;", "  struct in_addr sin_addr;", "  unsigned char sin_zero[sizeof (struct sockaddr) - sizeof (sa_family_t) - sizeof (in_port_t) - sizeof (struct in_addr)];", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct sockaddr_in6 ", body: &["", "  sa_family_t sin6_family;", "  in_port_t sin6_port;", "  uint32_t sin6_flowinfo;", "  struct in6_addr sin6_addr;", "  uint32_t sin6_scope_id;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ip_mreq ", body: &["", "  struct in_addr imr_multiaddr;", "  struct in_addr imr_interface;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ip_mreq_source ", body: &["", "  struct in_addr imr_multiaddr;", "  struct in_addr imr_interface;", "  struct in_addr imr_sourceaddr;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ipv6_mreq ", body: &["", "  struct in6_addr ipv6mr_multiaddr;", "  unsigned int ipv6mr_interface;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct group_req ", body: &["", "  uint32_t gr_interface;", "  struct sockaddr_storage gr_group;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct group_source_req ", body: &["", "  uint32_t gsr_interface;", "  struct sockaddr_storage gsr_group;", "  struct sockaddr_storage gsr_source;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ip_msfilter ", body: &["", "  struct in_addr imsf_multiaddr;", "  struct in_addr imsf_interface;", "  uint32_t imsf_fmode;", "  uint32_t imsf_numsrc;", "  struct in_addr imsf_slist[1];", ""], tail: "" },
            Item::Raw(Reason::GlibcMacro, "#define IP_MSFILTER_SIZE(numsrc) (sizeof (struct ip_msfilter) - sizeof (struct in_addr) + (numsrc) * sizeof (struct in_addr))"),
            Item::Blank,
            Item::Block { head: "struct group_filter ", body: &["", "  uint32_t gf_interface;", "  struct sockaddr_storage gf_group;", "  uint32_t gf_fmode;", "  uint32_t gf_numsrc;", "  struct sockaddr_storage gf_slist[1];", ""], tail: "" },
            Item::Raw(Reason::GlibcMacro, "#define GROUP_FILTER_SIZE(numsrc) (sizeof (struct group_filter) - sizeof (struct sockaddr_storage) + (numsrc) * sizeof (struct sockaddr_storage))"),
            Item::Blank,
            Item::Block { head: "struct in_pktinfo ", body: &["", "  int ipi_ifindex;", "  struct in_addr ipi_spec_dst;", "  struct in_addr ipi_addr;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct in6_pktinfo ", body: &["", "  struct in6_addr ipi6_addr;", "  unsigned int ipi6_ifindex;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ip6_mtuinfo ", body: &["", "  struct sockaddr_in6 ip6m_addr;", "  uint32_t ip6m_mtu;", ""], tail: "" },
            Item::Blank,
            Item::Raw(Reason::GlibcMacro, "#define IN_CLASSA(a) ((((in_addr_t) (a)) & 0x80000000) == 0)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_CLASSB(a) ((((in_addr_t) (a)) & 0xc0000000) == 0x80000000)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_CLASSC(a) ((((in_addr_t) (a)) & 0xe0000000) == 0xc0000000)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_CLASSD(a) ((((in_addr_t) (a)) & 0xf0000000) == 0xe0000000)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_MULTICAST(a) IN_CLASSD (a)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_EXPERIMENTAL(a) ((((in_addr_t) (a)) & 0xe0000000) == 0xe0000000)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_BADCLASS(a) ((((in_addr_t) (a)) & 0xf0000000) == 0xf0000000)"),
            Item::Raw(Reason::GlibcMacro, "#define IN_LOOPBACK(a) ((((in_addr_t) (a)) & 0xff000000) == 0x7f000000)"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_UNSPECIFIED(a) \
  (((const uint32_t *) (a))[0] == 0 && ((const uint32_t *) (a))[1] == 0 \
   && ((const uint32_t *) (a))[2] == 0 && ((const uint32_t *) (a))[3] == 0)"#),
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_LOOPBACK(a) \
  (((const uint32_t *) (a))[0] == 0 && ((const uint32_t *) (a))[1] == 0 \
   && ((const uint32_t *) (a))[2] == 0 && ((const uint32_t *) (a))[3] == htonl (1))"#),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MULTICAST(a) (((const uint8_t *) (a))[0] == 0xff)"),
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_LINKLOCAL(a) \
  ((((const uint32_t *) (a))[0] & htonl (0xffc00000)) == htonl (0xfe800000))"#),
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_SITELOCAL(a) \
  ((((const uint32_t *) (a))[0] & htonl (0xffc00000)) == htonl (0xfec00000))"#),
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_V4MAPPED(a) \
  ((((const uint32_t *) (a))[0] == 0) && (((const uint32_t *) (a))[1] == 0) \
   && (((const uint32_t *) (a))[2] == htonl (0xffff)))"#),
            Item::Raw(Reason::StdMacro, r#"#define IN6_IS_ADDR_V4COMPAT(a) \
  ((((const uint32_t *) (a))[0] == 0) && (((const uint32_t *) (a))[1] == 0) \
   && (((const uint32_t *) (a))[2] == 0) && (ntohl (((const uint32_t *) (a))[3]) > 1))"#),
            Item::Raw(Reason::GlibcMacro, r#"#define IN6_ARE_ADDR_EQUAL(a, b) \
  ((((const uint32_t *) (a))[0] == ((const uint32_t *) (b))[0]) \
   && (((const uint32_t *) (a))[1] == ((const uint32_t *) (b))[1]) \
   && (((const uint32_t *) (a))[2] == ((const uint32_t *) (b))[2]) \
   && (((const uint32_t *) (a))[3] == ((const uint32_t *) (b))[3]))"#),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MC_NODELOCAL(a) (IN6_IS_ADDR_MULTICAST (a) && ((((const uint8_t *) (a))[1] & 0xf) == 0x1))"),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MC_LINKLOCAL(a) (IN6_IS_ADDR_MULTICAST (a) && ((((const uint8_t *) (a))[1] & 0xf) == 0x2))"),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MC_SITELOCAL(a) (IN6_IS_ADDR_MULTICAST (a) && ((((const uint8_t *) (a))[1] & 0xf) == 0x5))"),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MC_ORGLOCAL(a) (IN6_IS_ADDR_MULTICAST (a) && ((((const uint8_t *) (a))[1] & 0xf) == 0x8))"),
            Item::Raw(Reason::StdMacro, "#define IN6_IS_ADDR_MC_GLOBAL(a) (IN6_IS_ADDR_MULTICAST (a) && ((((const uint8_t *) (a))[1] & 0xf) == 0xe))"),
            Item::Blank,
            Item::Include("<bits/rlibc-net-in.h>"),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __OPTIMIZE__", items: &[
                    Item::Raw(Reason::StdMacro, "# define ntohl(x) __builtin_bswap32 (x)"),
                    Item::Raw(Reason::StdMacro, "# define ntohs(x) __builtin_bswap16 (x)"),
                    Item::Raw(Reason::StdMacro, "# define htonl(x) __builtin_bswap32 (x)"),
                    Item::Raw(Reason::StdMacro, "# define htons(x) __builtin_bswap16 (x)"),
                ] },
            ], ""),
        ]},
    ],
};
