use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/if_fddi.h",
    items: &[
        Item::Guard { name: "_NETINET_IF_FDDI_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<sys/types.h>"),
            Item::Include("<stdint.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: "struct fddi_8022_1_hdr ", body: &["", "  uint8_t dsap;", "  uint8_t ssap;", "  uint8_t ctrl;", ""], tail: " __attribute__((packed))" },
            Item::Blank,
            Item::Block { head: "struct fddi_8022_2_hdr ", body: &["", "  uint8_t dsap;", "  uint8_t ssap;", "  uint8_t ctrl_1;", "  uint8_t ctrl_2;", ""], tail: " __attribute__((packed))" },
            Item::Blank,
            Item::Block { head: "struct fddi_snap_hdr ", body: &["", "  uint8_t dsap;", "  uint8_t ssap;", "  uint8_t ctrl;", "  uint8_t oui[3];", "  uint16_t ethertype;", ""], tail: " __attribute__((packed))" },
            Item::Blank,
            Item::Block { head: "struct fddihdr ", body: &["", "  uint8_t fc;", "  uint8_t daddr[6];", "  uint8_t saddr[6];", "  union {", "    struct fddi_8022_1_hdr llc_8022_1;", "    struct fddi_8022_2_hdr llc_8022_2;", "    struct fddi_snap_hdr llc_snap;", "  } hdr;", ""], tail: " __attribute__((packed))" },
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __USE_MISC", items: &[
                    Item::Block { head: "struct fddi_header ", body: &["", "  uint8_t fddi_fc;", "  uint8_t fddi_dhost[6];", "  uint8_t fddi_shost[6];", ""], tail: "" },
                ] },
            ], ""),
            Item::Consts(&[
                ("FDDI_EXTENDED_SAP", V::Txt("0xAA")),
                ("FDDI_FC_K_ALEN_16", V::Txt("0x00")),
                ("FDDI_FC_K_ALEN_48", V::Hex(0x40)),
                ("FDDI_FC_K_ALEN_MASK", V::Hex(0x40)),
                ("FDDI_FC_K_ASYNC_LLC_DEF", V::Hex(0x54)),
                ("FDDI_FC_K_ASYNC_LLC_MAX", V::Txt("0x5F")),
                ("FDDI_FC_K_ASYNC_LLC_MIN", V::Hex(0x50)),
                ("FDDI_FC_K_CLASS_ASYNC", V::Txt("0x00")),
                ("FDDI_FC_K_CLASS_MASK", V::Hex(0x80)),
                ("FDDI_FC_K_CLASS_SYNC", V::Hex(0x80)),
                ("FDDI_FC_K_CONTROL_MASK", V::Txt("0x0f")),
                ("FDDI_FC_K_FORMAT_FUTURE", V::Hex(0x30)),
                ("FDDI_FC_K_FORMAT_IMPLEMENTOR", V::Hex(0x20)),
                ("FDDI_FC_K_FORMAT_LLC", V::Hex(0x10)),
                ("FDDI_FC_K_FORMAT_MANAGEMENT", V::Txt("0x00")),
                ("FDDI_FC_K_FORMAT_MASK", V::Hex(0x30)),
                ("FDDI_FC_K_IMPLEMENTOR_MAX", V::Txt("0x6F")),
                ("FDDI_FC_K_IMPLEMENTOR_MIN", V::Hex(0x60)),
                ("FDDI_FC_K_MAC_MAX", V::Txt("0xCF")),
                ("FDDI_FC_K_MAC_MIN", V::Txt("0xC1")),
                ("FDDI_FC_K_NON_RESTRICTED_TOKEN", V::Hex(0x80)),
                ("FDDI_FC_K_RESERVED_MAX", V::Txt("0x7F")),
                ("FDDI_FC_K_RESERVED_MIN", V::Hex(0x70)),
                ("FDDI_FC_K_RESTRICTED_TOKEN", V::Txt("0xC0")),
                ("FDDI_FC_K_SMT_MAX", V::Txt("0x4F")),
                ("FDDI_FC_K_SMT_MIN", V::Hex(0x41)),
                ("FDDI_FC_K_SYNC_LLC_MAX", V::Txt("0xD7")),
                ("FDDI_FC_K_SYNC_LLC_MIN", V::Txt("0xD0")),
                ("FDDI_FC_K_VOID", V::Txt("0x00")),
                ("FDDI_K_8022_DLEN", V::Dec(4475)),
                ("FDDI_K_8022_HLEN", V::Dec(16)),
                ("FDDI_K_8022_ZLEN", V::Dec(16)),
                ("FDDI_K_ALEN", V::Dec(6)),
                ("FDDI_K_LLC_LEN", V::Dec(4491)),
                ("FDDI_K_LLC_ZLEN", V::Dec(13)),
                ("FDDI_K_OUI_LEN", V::Dec(3)),
                ("FDDI_K_SNAP_DLEN", V::Dec(4470)),
                ("FDDI_K_SNAP_HLEN", V::Dec(21)),
                ("FDDI_K_SNAP_ZLEN", V::Dec(21)),
                ("FDDI_UI_CMD", V::Txt("0x03")),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
