use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/icmp6.h",
    items: &[
        Item::Guard { name: "_NETINET_ICMP6_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<endian.h>"),
            Item::Include("<netinet/in.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: r#"struct icmp6_filter
  "#, body: &["", "    uint32_t icmp6_filt[8];", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct icmp6_hdr
  "#, body: &["", "    uint8_t     icmp6_type;", "    uint8_t     icmp6_code;", "    uint16_t    icmp6_cksum;", "    union", "      {", r#"	uint32_t  icmp6_un_data32[1];"#, r#"	uint16_t  icmp6_un_data16[2];"#, r#"	uint8_t   icmp6_un_data8[4];"#, "      } icmp6_dataun;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_router_solicit
  "#, body: &["", "    struct icmp6_hdr  nd_rs_hdr;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_router_advert
  "#, body: &["", "    struct icmp6_hdr  nd_ra_hdr;", "    uint32_t   nd_ra_reachable;", "    uint32_t   nd_ra_retransmit;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_neighbor_solicit
  "#, body: &["", "    struct icmp6_hdr  nd_ns_hdr;", "    struct in6_addr   nd_ns_target;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_neighbor_advert
  "#, body: &["", "    struct icmp6_hdr  nd_na_hdr;", "    struct in6_addr   nd_na_target;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_redirect
  "#, body: &["", "    struct icmp6_hdr  nd_rd_hdr;", "    struct in6_addr   nd_rd_target;", "    struct in6_addr   nd_rd_dst;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_hdr
  "#, body: &["", "    uint8_t  nd_opt_type;", "    uint8_t  nd_opt_len;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_prefix_info
  "#, body: &["", "    uint8_t   nd_opt_pi_type;", "    uint8_t   nd_opt_pi_len;", "    uint8_t   nd_opt_pi_prefix_len;", "    uint8_t   nd_opt_pi_flags_reserved;", "    uint32_t  nd_opt_pi_valid_time;", "    uint32_t  nd_opt_pi_preferred_time;", "    uint32_t  nd_opt_pi_reserved2;", "    struct in6_addr  nd_opt_pi_prefix;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_rd_hdr
  "#, body: &["", "    uint8_t   nd_opt_rh_type;", "    uint8_t   nd_opt_rh_len;", "    uint16_t  nd_opt_rh_reserved1;", "    uint32_t  nd_opt_rh_reserved2;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_mtu
  "#, body: &["", "    uint8_t   nd_opt_mtu_type;", "    uint8_t   nd_opt_mtu_len;", "    uint16_t  nd_opt_mtu_reserved;", "    uint32_t  nd_opt_mtu_mtu;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct mld_hdr
  "#, body: &["", "    struct icmp6_hdr    mld_icmp6_hdr;", "    struct in6_addr     mld_addr;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_adv_interval
  "#, body: &["", "    uint8_t   nd_opt_adv_interval_type;", "    uint8_t   nd_opt_adv_interval_len;", "    uint16_t  nd_opt_adv_interval_reserved;", "    uint32_t  nd_opt_adv_interval_ival;", "  "], tail: "" },
            Item::Blank,
            Item::Block { head: r#"struct nd_opt_home_agent_info
  "#, body: &["", "    uint8_t   nd_opt_home_agent_info_type;", "    uint8_t   nd_opt_home_agent_info_len;", "    uint16_t  nd_opt_home_agent_info_reserved;", "    uint16_t  nd_opt_home_agent_info_preference;", "    uint16_t  nd_opt_home_agent_info_lifetime;", "  "], tail: "" },
            Item::Consts(&[
                ("ICMP6_DST_UNREACH", V::Dec(1)),
                ("ICMP6_DST_UNREACH_ADDR", V::Dec(3)),
                ("ICMP6_DST_UNREACH_ADMIN", V::Dec(1)),
                ("ICMP6_DST_UNREACH_BEYONDSCOPE", V::Dec(2)),
                ("ICMP6_DST_UNREACH_NOPORT", V::Dec(4)),
                ("ICMP6_DST_UNREACH_NOROUTE", V::Dec(0)),
                ("ICMP6_ECHO_REPLY", V::Dec(129)),
                ("ICMP6_ECHO_REQUEST", V::Dec(128)),
                ("ICMP6_FILTER", V::Dec(1)),
                ("ICMP6_FILTER_BLOCK", V::Dec(1)),
                ("ICMP6_FILTER_BLOCKOTHERS", V::Dec(3)),
                ("ICMP6_FILTER_PASS", V::Dec(2)),
                ("ICMP6_FILTER_PASSONLY", V::Dec(4)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_SETBLOCK(type,filterp) ((((filterp)->icmp6_filt[(type) >> 5]) |= (1U << ((type) & 31))))"),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_SETBLOCKALL(filterp) memset (filterp, 0xFF, sizeof (struct icmp6_filter));"),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_SETPASS(type,filterp) ((((filterp)->icmp6_filt[(type) >> 5]) &= ~(1U << ((type) & 31))))"),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_SETPASSALL(filterp) memset (filterp, 0, sizeof (struct icmp6_filter));"),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_WILLBLOCK(type,filterp) ((((filterp)->icmp6_filt[(type) >> 5]) & (1U << ((type) & 31))) != 0)"),
            Item::Raw(Reason::GlibcMacro, "#define ICMP6_FILTER_WILLPASS(type,filterp) ((((filterp)->icmp6_filt[(type) >> 5]) & (1U << ((type) & 31))) == 0)"),
            Item::Consts(&[
                ("ICMP6_INFOMSG_MASK", V::Hex(0x80)),
                ("ICMP6_PACKET_TOO_BIG", V::Dec(2)),
                ("ICMP6_PARAMPROB_HEADER", V::Dec(0)),
                ("ICMP6_PARAMPROB_NEXTHEADER", V::Dec(1)),
                ("ICMP6_PARAMPROB_OPTION", V::Dec(2)),
                ("ICMP6_PARAM_PROB", V::Dec(4)),
                ("ICMP6_ROUTER_RENUMBERING", V::Dec(138)),
                ("ICMP6_RR_FLAGS_FORCEAPPLY", V::Hex(0x20)),
                ("ICMP6_RR_FLAGS_PREVDONE", V::Txt("0x08")),
                ("ICMP6_RR_FLAGS_REQRESULT", V::Hex(0x40)),
                ("ICMP6_RR_FLAGS_SPECSITE", V::Hex(0x10)),
                ("ICMP6_RR_FLAGS_TEST", V::Hex(0x80)),
                ("ICMP6_RR_PCOUSE_FLAGS_DECRPLTIME", V::Hex(0x40)),
                ("ICMP6_RR_PCOUSE_FLAGS_DECRVLTIME", V::Hex(0x80)),
                ("ICMP6_RR_PCOUSE_RAFLAGS_AUTO", V::Hex(0x10)),
                ("ICMP6_RR_PCOUSE_RAFLAGS_ONLINK", V::Hex(0x20)),
                ("ICMP6_RR_RESULT_FLAGS_FORBIDDEN", V::Txt("0x0100")),
                ("ICMP6_RR_RESULT_FLAGS_OOB", V::Txt("0x0200")),
                ("ICMP6_TIME_EXCEEDED", V::Dec(3)),
                ("ICMP6_TIME_EXCEED_REASSEMBLY", V::Dec(1)),
                ("ICMP6_TIME_EXCEED_TRANSIT", V::Dec(0)),
                ("ICMPV6_EXT_ECHO_REPLY", V::Dec(161)),
                ("ICMPV6_EXT_ECHO_REQUEST", V::Dec(160)),
                ("MLD_LISTENER_QUERY", V::Dec(130)),
                ("MLD_LISTENER_REDUCTION", V::Dec(132)),
                ("MLD_LISTENER_REPORT", V::Dec(131)),
                ("ND_NA_FLAG_OVERRIDE", V::Txt("0x00000020")),
                ("ND_NA_FLAG_ROUTER", V::Txt("0x00000080")),
                ("ND_NA_FLAG_SOLICITED", V::Txt("0x00000040")),
                ("ND_NEIGHBOR_ADVERT", V::Dec(136)),
                ("ND_NEIGHBOR_SOLICIT", V::Dec(135)),
                ("ND_OPT_HOME_AGENT_INFO", V::Dec(8)),
                ("ND_OPT_MTU", V::Dec(5)),
                ("ND_OPT_PI_FLAG_AUTO", V::Hex(0x40)),
                ("ND_OPT_PI_FLAG_ONLINK", V::Hex(0x80)),
                ("ND_OPT_PI_FLAG_RADDR", V::Hex(0x20)),
                ("ND_OPT_PREFIX_INFORMATION", V::Dec(3)),
                ("ND_OPT_REDIRECTED_HEADER", V::Dec(4)),
                ("ND_OPT_RTR_ADV_INTERVAL", V::Dec(7)),
                ("ND_OPT_SOURCE_LINKADDR", V::Dec(1)),
                ("ND_OPT_TARGET_LINKADDR", V::Dec(2)),
                ("ND_RA_FLAG_HOME_AGENT", V::Hex(0x20)),
                ("ND_RA_FLAG_MANAGED", V::Hex(0x80)),
                ("ND_RA_FLAG_OTHER", V::Hex(0x40)),
                ("ND_REDIRECT", V::Dec(137)),
                ("ND_ROUTER_ADVERT", V::Dec(134)),
                ("ND_ROUTER_SOLICIT", V::Dec(133)),
                ("PRIB16", V::Txt(r#""hB""#)),
                ("PRIB32", V::Txt(r#""B""#)),
                ("PRIB64", V::Txt(r#"__PRI64_PREFIX "B""#)),
                ("PRIB8", V::Txt(r#""hhB""#)),
                ("PRIBFAST16", V::Txt(r#"__PRIPTR_PREFIX "B""#)),
                ("PRIBFAST32", V::Txt(r#"__PRIPTR_PREFIX "B""#)),
                ("PRIBFAST64", V::Txt(r#"__PRI64_PREFIX "B""#)),
                ("PRIBFAST8", V::Txt(r#""hhB""#)),
                ("PRIBLEAST16", V::Txt(r#""hB""#)),
                ("PRIBLEAST32", V::Txt(r#""B""#)),
                ("PRIBLEAST64", V::Txt(r#"__PRI64_PREFIX "B""#)),
                ("PRIBLEAST8", V::Txt(r#""hhB""#)),
                ("PRIBMAX", V::Txt(r#"__PRI64_PREFIX "B""#)),
                ("PRIBPTR", V::Txt(r#"__PRIPTR_PREFIX "B""#)),
                ("PRIX16", V::Txt(r#""hX""#)),
                ("PRIX32", V::Txt(r#""X""#)),
                ("PRIX64", V::Txt(r#"__PRI64_PREFIX "X""#)),
                ("PRIX8", V::Txt(r#""hhX""#)),
                ("PRIXFAST16", V::Txt(r#"__PRIPTR_PREFIX "X""#)),
                ("PRIXFAST32", V::Txt(r#"__PRIPTR_PREFIX "X""#)),
                ("PRIXFAST64", V::Txt(r#"__PRI64_PREFIX "X""#)),
                ("PRIXFAST8", V::Txt(r#""hhX""#)),
                ("PRIXLEAST16", V::Txt(r#""hX""#)),
                ("PRIXLEAST32", V::Txt(r#""X""#)),
                ("PRIXLEAST64", V::Txt(r#"__PRI64_PREFIX "X""#)),
                ("PRIXLEAST8", V::Txt(r#""hhX""#)),
                ("PRIXMAX", V::Txt(r#"__PRI64_PREFIX "X""#)),
                ("PRIXPTR", V::Txt(r#"__PRIPTR_PREFIX "X""#)),
                ("PRIb16", V::Txt(r#""hb""#)),
                ("PRIb32", V::Txt(r#""b""#)),
                ("PRIb64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("PRIb8", V::Txt(r#""hhb""#)),
                ("PRIbFAST16", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("PRIbFAST32", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("PRIbFAST64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("PRIbFAST8", V::Txt(r#""hhb""#)),
                ("PRIbLEAST16", V::Txt(r#""hb""#)),
                ("PRIbLEAST32", V::Txt(r#""b""#)),
                ("PRIbLEAST64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("PRIbLEAST8", V::Txt(r#""hhb""#)),
                ("PRIbMAX", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("PRIbPTR", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("PRId16", V::Txt(r#""hd""#)),
                ("PRId32", V::Txt(r#""d""#)),
                ("PRId64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("PRId8", V::Txt(r#""hhd""#)),
                ("PRIdFAST16", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("PRIdFAST32", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("PRIdFAST64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("PRIdFAST8", V::Txt(r#""hhd""#)),
                ("PRIdLEAST16", V::Txt(r#""hd""#)),
                ("PRIdLEAST32", V::Txt(r#""d""#)),
                ("PRIdLEAST64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("PRIdLEAST8", V::Txt(r#""hhd""#)),
                ("PRIdMAX", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("PRIdPTR", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("PRIi16", V::Txt(r#""hi""#)),
                ("PRIi32", V::Txt(r#""i""#)),
                ("PRIi64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("PRIi8", V::Txt(r#""hhi""#)),
                ("PRIiFAST16", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("PRIiFAST32", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("PRIiFAST64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("PRIiFAST8", V::Txt(r#""hhi""#)),
                ("PRIiLEAST16", V::Txt(r#""hi""#)),
                ("PRIiLEAST32", V::Txt(r#""i""#)),
                ("PRIiLEAST64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("PRIiLEAST8", V::Txt(r#""hhi""#)),
                ("PRIiMAX", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("PRIiPTR", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("PRIo16", V::Txt(r#""ho""#)),
                ("PRIo32", V::Txt(r#""o""#)),
                ("PRIo64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("PRIo8", V::Txt(r#""hho""#)),
                ("PRIoFAST16", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("PRIoFAST32", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("PRIoFAST64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("PRIoFAST8", V::Txt(r#""hho""#)),
                ("PRIoLEAST16", V::Txt(r#""ho""#)),
                ("PRIoLEAST32", V::Txt(r#""o""#)),
                ("PRIoLEAST64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("PRIoLEAST8", V::Txt(r#""hho""#)),
                ("PRIoMAX", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("PRIoPTR", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("PRIu16", V::Txt(r#""hu""#)),
                ("PRIu32", V::Txt(r#""u""#)),
                ("PRIu64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("PRIu8", V::Txt(r#""hhu""#)),
                ("PRIuFAST16", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("PRIuFAST32", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("PRIuFAST64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("PRIuFAST8", V::Txt(r#""hhu""#)),
                ("PRIuLEAST16", V::Txt(r#""hu""#)),
                ("PRIuLEAST32", V::Txt(r#""u""#)),
                ("PRIuLEAST64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("PRIuLEAST8", V::Txt(r#""hhu""#)),
                ("PRIuMAX", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("PRIuPTR", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("PRIx16", V::Txt(r#""hx""#)),
                ("PRIx32", V::Txt(r#""x""#)),
                ("PRIx64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("PRIx8", V::Txt(r#""hhx""#)),
                ("PRIxFAST16", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("PRIxFAST32", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("PRIxFAST64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("PRIxFAST8", V::Txt(r#""hhx""#)),
                ("PRIxLEAST16", V::Txt(r#""hx""#)),
                ("PRIxLEAST32", V::Txt(r#""x""#)),
                ("PRIxLEAST64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("PRIxLEAST8", V::Txt(r#""hhx""#)),
                ("PRIxMAX", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("PRIxPTR", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("RPM_PCO_ADD", V::Dec(1)),
                ("RPM_PCO_CHANGE", V::Dec(2)),
                ("RPM_PCO_SETGLOBAL", V::Dec(3)),
                ("SCNb16", V::Txt(r#""hb""#)),
                ("SCNb32", V::Txt(r#""b""#)),
                ("SCNb64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("SCNb8", V::Txt(r#""hhb""#)),
                ("SCNbFAST16", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("SCNbFAST32", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("SCNbFAST64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("SCNbFAST8", V::Txt(r#""hhb""#)),
                ("SCNbLEAST16", V::Txt(r#""hb""#)),
                ("SCNbLEAST32", V::Txt(r#""b""#)),
                ("SCNbLEAST64", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("SCNbLEAST8", V::Txt(r#""hhb""#)),
                ("SCNbMAX", V::Txt(r#"__PRI64_PREFIX "b""#)),
                ("SCNbPTR", V::Txt(r#"__PRIPTR_PREFIX "b""#)),
                ("SCNd16", V::Txt(r#""hd""#)),
                ("SCNd32", V::Txt(r#""d""#)),
                ("SCNd64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("SCNd8", V::Txt(r#""hhd""#)),
                ("SCNdFAST16", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("SCNdFAST32", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("SCNdFAST64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("SCNdFAST8", V::Txt(r#""hhd""#)),
                ("SCNdLEAST16", V::Txt(r#""hd""#)),
                ("SCNdLEAST32", V::Txt(r#""d""#)),
                ("SCNdLEAST64", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("SCNdLEAST8", V::Txt(r#""hhd""#)),
                ("SCNdMAX", V::Txt(r#"__PRI64_PREFIX "d""#)),
                ("SCNdPTR", V::Txt(r#"__PRIPTR_PREFIX "d""#)),
                ("SCNi16", V::Txt(r#""hi""#)),
                ("SCNi32", V::Txt(r#""i""#)),
                ("SCNi64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("SCNi8", V::Txt(r#""hhi""#)),
                ("SCNiFAST16", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("SCNiFAST32", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("SCNiFAST64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("SCNiFAST8", V::Txt(r#""hhi""#)),
                ("SCNiLEAST16", V::Txt(r#""hi""#)),
                ("SCNiLEAST32", V::Txt(r#""i""#)),
                ("SCNiLEAST64", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("SCNiLEAST8", V::Txt(r#""hhi""#)),
                ("SCNiMAX", V::Txt(r#"__PRI64_PREFIX "i""#)),
                ("SCNiPTR", V::Txt(r#"__PRIPTR_PREFIX "i""#)),
                ("SCNo16", V::Txt(r#""ho""#)),
                ("SCNo32", V::Txt(r#""o""#)),
                ("SCNo64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("SCNo8", V::Txt(r#""hho""#)),
                ("SCNoFAST16", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("SCNoFAST32", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("SCNoFAST64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("SCNoFAST8", V::Txt(r#""hho""#)),
                ("SCNoLEAST16", V::Txt(r#""ho""#)),
                ("SCNoLEAST32", V::Txt(r#""o""#)),
                ("SCNoLEAST64", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("SCNoLEAST8", V::Txt(r#""hho""#)),
                ("SCNoMAX", V::Txt(r#"__PRI64_PREFIX "o""#)),
                ("SCNoPTR", V::Txt(r#"__PRIPTR_PREFIX "o""#)),
                ("SCNu16", V::Txt(r#""hu""#)),
                ("SCNu32", V::Txt(r#""u""#)),
                ("SCNu64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("SCNu8", V::Txt(r#""hhu""#)),
                ("SCNuFAST16", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("SCNuFAST32", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("SCNuFAST64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("SCNuFAST8", V::Txt(r#""hhu""#)),
                ("SCNuLEAST16", V::Txt(r#""hu""#)),
                ("SCNuLEAST32", V::Txt(r#""u""#)),
                ("SCNuLEAST64", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("SCNuLEAST8", V::Txt(r#""hhu""#)),
                ("SCNuMAX", V::Txt(r#"__PRI64_PREFIX "u""#)),
                ("SCNuPTR", V::Txt(r#"__PRIPTR_PREFIX "u""#)),
                ("SCNx16", V::Txt(r#""hx""#)),
                ("SCNx32", V::Txt(r#""x""#)),
                ("SCNx64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("SCNx8", V::Txt(r#""hhx""#)),
                ("SCNxFAST16", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("SCNxFAST32", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("SCNxFAST64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("SCNxFAST8", V::Txt(r#""hhx""#)),
                ("SCNxLEAST16", V::Txt(r#""hx""#)),
                ("SCNxLEAST32", V::Txt(r#""x""#)),
                ("SCNxLEAST64", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("SCNxLEAST8", V::Txt(r#""hhx""#)),
                ("SCNxMAX", V::Txt(r#"__PRI64_PREFIX "x""#)),
                ("SCNxPTR", V::Txt(r#"__PRIPTR_PREFIX "x""#)),
                ("icmp6_data16", V::Txt("icmp6_dataun.icmp6_un_data16")),
                ("icmp6_data32", V::Txt("icmp6_dataun.icmp6_un_data32")),
                ("icmp6_data8", V::Txt("icmp6_dataun.icmp6_un_data8")),
                ("icmp6_id", V::Txt("icmp6_data16[0]")),
                ("icmp6_maxdelay", V::Txt("icmp6_data16[0]")),
                ("icmp6_mtu", V::Txt("icmp6_data32[0]")),
                ("icmp6_pptr", V::Txt("icmp6_data32[0]")),
                ("icmp6_seq", V::Txt("icmp6_data16[1]")),
                ("mld_cksum", V::Txt("mld_icmp6_hdr.icmp6_cksum")),
                ("mld_code", V::Txt("mld_icmp6_hdr.icmp6_code")),
                ("mld_maxdelay", V::Txt("mld_icmp6_hdr.icmp6_data16[0]")),
                ("mld_reserved", V::Txt("mld_icmp6_hdr.icmp6_data16[1]")),
                ("mld_type", V::Txt("mld_icmp6_hdr.icmp6_type")),
                ("nd_na_cksum", V::Txt("nd_na_hdr.icmp6_cksum")),
                ("nd_na_code", V::Txt("nd_na_hdr.icmp6_code")),
                ("nd_na_flags_reserved", V::Txt("nd_na_hdr.icmp6_data32[0]")),
                ("nd_na_type", V::Txt("nd_na_hdr.icmp6_type")),
                ("nd_ns_cksum", V::Txt("nd_ns_hdr.icmp6_cksum")),
                ("nd_ns_code", V::Txt("nd_ns_hdr.icmp6_code")),
                ("nd_ns_reserved", V::Txt("nd_ns_hdr.icmp6_data32[0]")),
                ("nd_ns_type", V::Txt("nd_ns_hdr.icmp6_type")),
                ("nd_ra_cksum", V::Txt("nd_ra_hdr.icmp6_cksum")),
                ("nd_ra_code", V::Txt("nd_ra_hdr.icmp6_code")),
                ("nd_ra_curhoplimit", V::Txt("nd_ra_hdr.icmp6_data8[0]")),
                ("nd_ra_flags_reserved", V::Txt("nd_ra_hdr.icmp6_data8[1]")),
                ("nd_ra_router_lifetime", V::Txt("nd_ra_hdr.icmp6_data16[1]")),
                ("nd_ra_type", V::Txt("nd_ra_hdr.icmp6_type")),
                ("nd_rd_cksum", V::Txt("nd_rd_hdr.icmp6_cksum")),
                ("nd_rd_code", V::Txt("nd_rd_hdr.icmp6_code")),
                ("nd_rd_reserved", V::Txt("nd_rd_hdr.icmp6_data32[0]")),
                ("nd_rd_type", V::Txt("nd_rd_hdr.icmp6_type")),
                ("nd_rs_cksum", V::Txt("nd_rs_hdr.icmp6_cksum")),
                ("nd_rs_code", V::Txt("nd_rs_hdr.icmp6_code")),
                ("nd_rs_reserved", V::Txt("nd_rs_hdr.icmp6_data32[0]")),
                ("nd_rs_type", V::Txt("nd_rs_hdr.icmp6_type")),
                ("rr_cksum", V::Txt("rr_hdr.icmp6_cksum")),
                ("rr_code", V::Txt("rr_hdr.icmp6_code")),
                ("rr_seqnum", V::Txt("rr_hdr.icmp6_data32[0]")),
                ("rr_type", V::Txt("rr_hdr.icmp6_type")),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
