use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/tcp.h",
    items: &[
        Item::Guard { name: "_NETINET_TCP_H", value: "1", end: "", items: &[
            Item::Include("<stdint.h>"),
            Item::Include("<sys/socket.h>"),
            Item::Blank,
            Item::Typedef("uint32_t", "tcp_seq"),
            Item::Blank,
            Item::Consts(&[
                ("SOL_TCP", V::Dec(6)),
                ("TCPI_OPT_ECN", V::Dec(8)),
                ("TCPI_OPT_ECN_SEEN", V::Dec(16)),
                ("TCPI_OPT_SACK", V::Dec(2)),
                ("TCPI_OPT_SYN_DATA", V::Dec(32)),
                ("TCPI_OPT_TFO_CHILD", V::Dec(128)),
                ("TCPI_OPT_TIMESTAMPS", V::Dec(1)),
                ("TCPI_OPT_USEC_TS", V::Dec(64)),
                ("TCPI_OPT_WSCALE", V::Dec(4)),
                ("TCPOLEN_MAXSEG", V::Dec(4)),
                ("TCPOLEN_SACK_PERMITTED", V::Dec(2)),
                ("TCPOLEN_TIMESTAMP", V::Dec(10)),
                ("TCPOLEN_TSTAMP_APPA", V::Dec(12)),
                ("TCPOLEN_WINDOW", V::Dec(3)),
                ("TCPOPT_EOL", V::Dec(0)),
                ("TCPOPT_MAXSEG", V::Dec(2)),
                ("TCPOPT_NOP", V::Dec(1)),
                ("TCPOPT_SACK", V::Dec(5)),
                ("TCPOPT_SACK_PERMITTED", V::Dec(4)),
                ("TCPOPT_TIMESTAMP", V::Dec(8)),
                ("TCPOPT_TSTAMP_HDR", V::Dec(16844810)),
                ("TCPOPT_WINDOW", V::Dec(3)),
                ("TCP_AO_KEYF_EXCLUDE_OPT", V::Dec(2)),
                ("TCP_AO_KEYF_IFINDEX", V::Dec(1)),
                ("TCP_AO_MAXKEYLEN", V::Dec(80)),
                ("TCP_CC_INFO", V::Dec(26)),
                ("TCP_CM_INQ", V::Dec(36)),
                ("TCP_CONGESTION", V::Dec(13)),
                ("TCP_COOKIE_IN_ALWAYS", V::Dec(1)),
                ("TCP_COOKIE_MAX", V::Dec(16)),
                ("TCP_COOKIE_MIN", V::Dec(8)),
                ("TCP_COOKIE_OUT_NEVER", V::Dec(2)),
                ("TCP_COOKIE_PAIR_SIZE", V::Dec(32)),
                ("TCP_COOKIE_TRANSACTIONS", V::Dec(15)),
                ("TCP_CORK", V::Dec(3)),
                ("TCP_DEFER_ACCEPT", V::Dec(9)),
                ("TCP_FASTOPEN", V::Dec(23)),
                ("TCP_FASTOPEN_CONNECT", V::Dec(30)),
                ("TCP_FASTOPEN_KEY", V::Dec(33)),
                ("TCP_FASTOPEN_NO_COOKIE", V::Dec(34)),
                ("TCP_INFO", V::Dec(11)),
                ("TCP_INQ", V::Dec(36)),
                ("TCP_KEEPCNT", V::Dec(6)),
                ("TCP_KEEPIDLE", V::Dec(4)),
                ("TCP_KEEPINTVL", V::Dec(5)),
                ("TCP_LINGER2", V::Dec(8)),
                ("TCP_MAXSEG", V::Dec(2)),
                ("TCP_MAXWIN", V::Dec(65535)),
                ("TCP_MAX_WINSHIFT", V::Dec(14)),
                ("TCP_MD5SIG", V::Dec(14)),
                ("TCP_MD5SIG_EXT", V::Dec(32)),
                ("TCP_MD5SIG_FLAG_IFINDEX", V::Dec(2)),
                ("TCP_MD5SIG_FLAG_PREFIX", V::Dec(1)),
                ("TCP_MD5SIG_MAXKEYLEN", V::Dec(80)),
                ("TCP_MSS", V::Dec(512)),
                ("TCP_MSS_DEFAULT", V::Txt("0x00000218U")),
                ("TCP_MSS_DESIRED", V::Txt("0x000004c4U")),
                ("TCP_NODELAY", V::Dec(1)),
                ("TCP_NOTSENT_LOWAT", V::Dec(25)),
                ("TCP_QUEUE_SEQ", V::Dec(21)),
                ("TCP_QUICKACK", V::Dec(12)),
                ("TCP_REPAIR", V::Dec(19)),
                ("TCP_REPAIR_OFF", V::Dec(0)),
                ("TCP_REPAIR_OFF_NO_WP", V::Dec(-1)),
                ("TCP_REPAIR_ON", V::Dec(1)),
                ("TCP_REPAIR_OPTIONS", V::Dec(22)),
                ("TCP_REPAIR_QUEUE", V::Dec(20)),
                ("TCP_REPAIR_WINDOW", V::Dec(29)),
                ("TCP_SAVED_SYN", V::Dec(28)),
                ("TCP_SAVE_SYN", V::Dec(27)),
                ("TCP_SYNCNT", V::Dec(7)),
                ("TCP_S_DATA_IN", V::Dec(4)),
                ("TCP_S_DATA_OUT", V::Dec(8)),
                ("TCP_THIN_DUPACK", V::Dec(17)),
                ("TCP_THIN_LINEAR_TIMEOUTS", V::Dec(16)),
                ("TCP_TIMESTAMP", V::Dec(24)),
                ("TCP_TX_DELAY", V::Dec(37)),
                ("TCP_ULP", V::Dec(31)),
                ("TCP_USER_TIMEOUT", V::Dec(18)),
                ("TCP_WINDOW_CLAMP", V::Dec(10)),
                ("TCP_ZEROCOPY_RECEIVE", V::Dec(35)),
                ("TH_ACK", V::Dec(16)),
                ("TH_FIN", V::Dec(1)),
                ("TH_PUSH", V::Dec(8)),
                ("TH_RST", V::Dec(4)),
                ("TH_SYN", V::Dec(2)),
                ("TH_URG", V::Dec(32)),
            ]),
            Item::Blank,
            Item::Block { head: "struct tcphdr ", body: &["", "  __extension__ union {", "    struct {", "      uint16_t th_sport;", "      uint16_t th_dport;", "      tcp_seq th_seq;", "      tcp_seq th_ack;", "      uint8_t th_x2:4;", "      uint8_t th_off:4;", "      uint8_t th_flags;", "      uint16_t th_win;", "      uint16_t th_sum;", "      uint16_t th_urp;", "    };", "    struct {", "      uint16_t source;", "      uint16_t dest;", "      uint32_t seq;", "      uint32_t ack_seq;", "      uint16_t res1:4;", "      uint16_t doff:4;", "      uint16_t fin:1;", "      uint16_t syn:1;", "      uint16_t rst:1;", "      uint16_t psh:1;", "      uint16_t ack:1;", "      uint16_t urg:1;", "      uint16_t res2:2;", "      uint16_t window;", "      uint16_t check;", "      uint16_t urg_ptr;", "    };", "  };", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "enum tcp_ca_state ", body: &["", "  TCP_CA_Open = 0,", "  TCP_CA_Disorder = 1,", "  TCP_CA_CWR = 2,", "  TCP_CA_Recovery = 3,", "  TCP_CA_Loss = 4", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct tcp_info ", body: &["", "  uint8_t tcpi_state;", "  uint8_t tcpi_ca_state;", "  uint8_t tcpi_retransmits;", "  uint8_t tcpi_probes;", "  uint8_t tcpi_backoff;", "  uint8_t tcpi_options;", "  uint8_t tcpi_snd_wscale : 4, tcpi_rcv_wscale : 4;", "  uint32_t tcpi_rto;", "  uint32_t tcpi_ato;", "  uint32_t tcpi_snd_mss;", "  uint32_t tcpi_rcv_mss;", "  uint32_t tcpi_unacked;", "  uint32_t tcpi_sacked;", "  uint32_t tcpi_lost;", "  uint32_t tcpi_retrans;", "  uint32_t tcpi_fackets;", "  uint32_t tcpi_last_data_sent;", "  uint32_t tcpi_last_ack_sent;", "  uint32_t tcpi_last_data_recv;", "  uint32_t tcpi_last_ack_recv;", "  uint32_t tcpi_pmtu;", "  uint32_t tcpi_rcv_ssthresh;", "  uint32_t tcpi_rtt;", "  uint32_t tcpi_rttvar;", "  uint32_t tcpi_snd_ssthresh;", "  uint32_t tcpi_snd_cwnd;", "  uint32_t tcpi_advmss;", "  uint32_t tcpi_reordering;", "  uint32_t tcpi_rcv_rtt;", "  uint32_t tcpi_rcv_space;", "  uint32_t tcpi_total_retrans;", "  uint64_t tcpi_pacing_rate;", "  uint64_t tcpi_max_pacing_rate;", "  uint64_t tcpi_bytes_acked;", "  uint64_t tcpi_bytes_received;", "  uint32_t tcpi_segs_out;", "  uint32_t tcpi_segs_in;", "  uint32_t tcpi_notsent_bytes;", "  uint32_t tcpi_min_rtt;", "  uint32_t tcpi_data_segs_in;", "  uint32_t tcpi_data_segs_out;", "  uint64_t tcpi_delivery_rate;", "  uint64_t tcpi_busy_time;", "  uint64_t tcpi_rwnd_limited;", "  uint64_t tcpi_sndbuf_limited;", "  uint32_t tcpi_delivered;", "  uint32_t tcpi_delivered_ce;", "  uint64_t tcpi_bytes_sent;", "  uint64_t tcpi_bytes_retrans;", "  uint32_t tcpi_dsack_dups;", "  uint32_t tcpi_reord_seen;", "  uint32_t tcpi_rcv_ooopack;", "  uint32_t tcpi_snd_wnd;", "  uint32_t tcpi_rcv_wnd;", "  uint32_t tcpi_rehash;", "  uint16_t tcpi_total_rto;", "  uint16_t tcpi_total_rto_recoveries;", "  uint32_t tcpi_total_rto_time;", "  uint32_t tcpi_received_ce;", "  uint32_t tcpi_delivered_e1_bytes;", "  uint32_t tcpi_delivered_e0_bytes;", "  uint32_t tcpi_delivered_ce_bytes;", "  uint32_t tcpi_received_e1_bytes;", "  uint32_t tcpi_received_e0_bytes;", "  uint32_t tcpi_received_ce_bytes;", "  uint16_t tcpi_accecn_fail_mode;", "  uint16_t tcpi_accecn_opt_seen;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct tcp_md5sig ", body: &["", "  struct sockaddr_storage tcpm_addr;", "  uint8_t tcpm_flags;", "  uint8_t tcpm_prefixlen;", "  uint16_t tcpm_keylen;", "  int tcpm_ifindex;", "  uint8_t tcpm_key[TCP_MD5SIG_MAXKEYLEN];", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct tcp_repair_opt ", body: &["", "  uint32_t opt_code;", "  uint32_t opt_val;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct tcp_repair_window ", body: &["", "  uint32_t snd_wl1;", "  uint32_t snd_wnd;", "  uint32_t max_window;", "  uint32_t rcv_wnd;", "  uint32_t rcv_wup;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct tcp_cookie_transactions ", body: &["", "  uint16_t tcpct_flags;", "  uint8_t __tcpct_pad1;", "  uint8_t tcpct_cookie_desired;", "  uint16_t tcpct_s_data_desired;", "  uint16_t tcpct_used;", "  uint8_t tcpct_value[TCP_MSS_DEFAULT];", ""], tail: "" },
        ]},
    ],
};
