use crate::model::*;

pub static HDR: Header = Header {
    path: "netinet/ip_icmp.h",
    items: &[
        Item::Guard { name: "_NETINET_IP_ICMP_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::Include("<sys/types.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<netinet/in.h>"),
            Item::Include("<netinet/in_systm.h>"),
            Item::Include("<netinet/ip.h>"),
            Item::ExternBegin,
            Item::Blank,
            Item::Block { head: r#"struct icmphdr
"#, body: &["", "  uint8_t type;", "  uint8_t code;", "  uint16_t checksum;", "  union", "  {", "    struct", "    {", "      uint16_t id;", "      uint16_t sequence;", "    } echo;", "    uint32_t gateway;", "    struct", "    {", "      uint16_t __glibc_reserved;", "      uint16_t mtu;", "    } frag;", "  } un;", ""], tail: "" },
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __USE_MISC", items: &[
                    Item::Block { head: r#"struct icmp_ra_addr
"#, body: &["", "  uint32_t ira_addr;", "  uint32_t ira_preference;", ""], tail: "" },
                    Item::Blank,
                    Item::Block { head: r#"struct icmp
"#, body: &["", "  uint8_t  icmp_type;", "  uint8_t  icmp_code;", "  uint16_t icmp_cksum;", "  union", "  {", "    unsigned char ih_pptr;", "    struct in_addr ih_gwaddr;", "    struct ih_idseq", "    {", "      uint16_t icd_id;", "      uint16_t icd_seq;", "    } ih_idseq;", "    uint32_t ih_void;", "    struct ih_pmtu", "    {", "      uint16_t ipm_void;", "      uint16_t ipm_nextmtu;", "    } ih_pmtu;", "    struct ih_rtradv", "    {", "      uint8_t irt_num_addrs;", "      uint8_t irt_wpa;", "      uint16_t irt_lifetime;", "    } ih_rtradv;", "  } icmp_hun;", "  union", "  {", "    struct", "    {", "      uint32_t its_otime;", "      uint32_t its_rtime;", "      uint32_t its_ttime;", "    } id_ts;", "    struct", "    {", "      struct ip idi_ip;", "    } id_ip;", "    struct icmp_ra_addr id_radv;", "    uint32_t   id_mask;", "    uint8_t    id_data[1];", "  } icmp_dun;", ""], tail: "" },
                ] },
            ], ""),
            Item::Consts(&[
                ("ICMP_ADDRESS", V::Dec(17)),
                ("ICMP_ADDRESSREPLY", V::Dec(18)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define ICMP_ADVLEN(p) (8 + ((p)->icmp_ip.ip_hl << 2) + 8)"),
            Item::Consts(&[
                ("ICMP_ADVLENMIN", V::Txt("(8 + sizeof (struct ip) + 8)")),
                ("ICMP_AFI_IP", V::Dec(1)),
                ("ICMP_AFI_IP6", V::Dec(2)),
                ("ICMP_DEST_UNREACH", V::Dec(3)),
                ("ICMP_ECHO", V::Dec(8)),
                ("ICMP_ECHOREPLY", V::Dec(0)),
                ("ICMP_EXC_FRAGTIME", V::Dec(1)),
                ("ICMP_EXC_TTL", V::Dec(0)),
                ("ICMP_EXT_CODE_MAL_QUERY", V::Dec(1)),
                ("ICMP_EXT_CODE_MULT_IFS", V::Dec(4)),
                ("ICMP_EXT_CODE_NO_IF", V::Dec(2)),
                ("ICMP_EXT_CODE_NO_TABLE_ENT", V::Dec(3)),
                ("ICMP_EXT_ECHO", V::Dec(42)),
                ("ICMP_EXT_ECHOREPLY", V::Dec(43)),
                ("ICMP_EXT_ECHOREPLY_ACTIVE", V::Txt("(1 << 2)")),
                ("ICMP_EXT_ECHOREPLY_IPV4", V::Txt("(1 << 1)")),
                ("ICMP_EXT_ECHOREPLY_IPV6", V::Dec(1)),
                ("ICMP_EXT_ECHO_CTYPE_ADDR", V::Dec(3)),
                ("ICMP_EXT_ECHO_CTYPE_INDEX", V::Dec(2)),
                ("ICMP_EXT_ECHO_CTYPE_NAME", V::Dec(1)),
                ("ICMP_FRAG_NEEDED", V::Dec(4)),
                ("ICMP_HOST_ANO", V::Dec(10)),
                ("ICMP_HOST_ISOLATED", V::Dec(8)),
                ("ICMP_HOST_UNKNOWN", V::Dec(7)),
                ("ICMP_HOST_UNREACH", V::Dec(1)),
                ("ICMP_HOST_UNR_TOS", V::Dec(12)),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define ICMP_INFOTYPE(type) ((type) == ICMP_ECHOREPLY || (type) == ICMP_ECHO || (type) == ICMP_ROUTERADVERT || (type) == ICMP_ROUTERSOLICIT || (type) == ICMP_TSTAMP || (type) == ICMP_TSTAMPREPLY || (type) == ICMP_IREQ || (type) == ICMP_IREQREPLY || (type) == ICMP_MASKREQ || (type) == ICMP_MASKREPLY)"),
            Item::Consts(&[
                ("ICMP_INFO_REPLY", V::Dec(16)),
                ("ICMP_INFO_REQUEST", V::Dec(15)),
                ("ICMP_IREQ", V::Dec(15)),
                ("ICMP_IREQREPLY", V::Dec(16)),
                ("ICMP_MASKLEN", V::Dec(12)),
                ("ICMP_MASKREPLY", V::Dec(18)),
                ("ICMP_MASKREQ", V::Dec(17)),
                ("ICMP_MAXTYPE", V::Dec(18)),
                ("ICMP_MINLEN", V::Dec(8)),
                ("ICMP_NET_ANO", V::Dec(9)),
                ("ICMP_NET_UNKNOWN", V::Dec(6)),
                ("ICMP_NET_UNREACH", V::Dec(0)),
                ("ICMP_NET_UNR_TOS", V::Dec(11)),
                ("ICMP_PARAMETERPROB", V::Dec(12)),
                ("ICMP_PARAMPROB", V::Dec(12)),
                ("ICMP_PARAMPROB_OPTABSENT", V::Dec(1)),
                ("ICMP_PKT_FILTERED", V::Dec(13)),
                ("ICMP_PORT_UNREACH", V::Dec(3)),
                ("ICMP_PREC_CUTOFF", V::Dec(15)),
                ("ICMP_PREC_VIOLATION", V::Dec(14)),
                ("ICMP_PROT_UNREACH", V::Dec(2)),
                ("ICMP_REDIRECT", V::Dec(5)),
                ("ICMP_REDIRECT_HOST", V::Dec(1)),
                ("ICMP_REDIRECT_NET", V::Dec(0)),
                ("ICMP_REDIRECT_TOSHOST", V::Dec(3)),
                ("ICMP_REDIRECT_TOSNET", V::Dec(2)),
                ("ICMP_REDIR_HOST", V::Dec(1)),
                ("ICMP_REDIR_HOSTTOS", V::Dec(3)),
                ("ICMP_REDIR_NET", V::Dec(0)),
                ("ICMP_REDIR_NETTOS", V::Dec(2)),
                ("ICMP_ROUTERADVERT", V::Dec(9)),
                ("ICMP_ROUTERSOLICIT", V::Dec(10)),
                ("ICMP_SOURCEQUENCH", V::Dec(4)),
                ("ICMP_SOURCE_QUENCH", V::Dec(4)),
                ("ICMP_SR_FAILED", V::Dec(5)),
                ("ICMP_TIMESTAMP", V::Dec(13)),
                ("ICMP_TIMESTAMPREPLY", V::Dec(14)),
                ("ICMP_TIME_EXCEEDED", V::Dec(11)),
                ("ICMP_TIMXCEED", V::Dec(11)),
                ("ICMP_TIMXCEED_INTRANS", V::Dec(0)),
                ("ICMP_TIMXCEED_REASS", V::Dec(1)),
                ("ICMP_TSLEN", V::Txt("(8 + 3 * sizeof (n_time))")),
                ("ICMP_TSTAMP", V::Dec(13)),
                ("ICMP_TSTAMPREPLY", V::Dec(14)),
                ("ICMP_UNREACH", V::Dec(3)),
                ("ICMP_UNREACH_FILTER_PROHIB", V::Dec(13)),
                ("ICMP_UNREACH_HOST", V::Dec(1)),
                ("ICMP_UNREACH_HOST_PRECEDENCE", V::Dec(14)),
                ("ICMP_UNREACH_HOST_PROHIB", V::Dec(10)),
                ("ICMP_UNREACH_HOST_UNKNOWN", V::Dec(7)),
                ("ICMP_UNREACH_ISOLATED", V::Dec(8)),
                ("ICMP_UNREACH_NEEDFRAG", V::Dec(4)),
                ("ICMP_UNREACH_NET", V::Dec(0)),
                ("ICMP_UNREACH_NET_PROHIB", V::Dec(9)),
                ("ICMP_UNREACH_NET_UNKNOWN", V::Dec(6)),
                ("ICMP_UNREACH_PORT", V::Dec(3)),
                ("ICMP_UNREACH_PRECEDENCE_CUTOFF", V::Dec(15)),
                ("ICMP_UNREACH_PROTOCOL", V::Dec(2)),
                ("ICMP_UNREACH_SRCFAIL", V::Dec(5)),
                ("ICMP_UNREACH_TOSHOST", V::Dec(12)),
                ("ICMP_UNREACH_TOSNET", V::Dec(11)),
                ("NR_ICMP_TYPES", V::Dec(18)),
                ("NR_ICMP_UNREACH", V::Dec(15)),
                ("icmp_data", V::Txt("icmp_dun.id_data")),
                ("icmp_gwaddr", V::Txt("icmp_hun.ih_gwaddr")),
                ("icmp_id", V::Txt("icmp_hun.ih_idseq.icd_id")),
                ("icmp_ip", V::Txt("icmp_dun.id_ip.idi_ip")),
                ("icmp_lifetime", V::Txt("icmp_hun.ih_rtradv.irt_lifetime")),
                ("icmp_mask", V::Txt("icmp_dun.id_mask")),
                ("icmp_nextmtu", V::Txt("icmp_hun.ih_pmtu.ipm_nextmtu")),
                ("icmp_num_addrs", V::Txt("icmp_hun.ih_rtradv.irt_num_addrs")),
                ("icmp_otime", V::Txt("icmp_dun.id_ts.its_otime")),
                ("icmp_pmvoid", V::Txt("icmp_hun.ih_pmtu.ipm_void")),
                ("icmp_pptr", V::Txt("icmp_hun.ih_pptr")),
                ("icmp_radv", V::Txt("icmp_dun.id_radv")),
                ("icmp_rtime", V::Txt("icmp_dun.id_ts.its_rtime")),
                ("icmp_seq", V::Txt("icmp_hun.ih_idseq.icd_seq")),
                ("icmp_ttime", V::Txt("icmp_dun.id_ts.its_ttime")),
                ("icmp_void", V::Txt("icmp_hun.ih_void")),
                ("icmp_wpa", V::Txt("icmp_hun.ih_rtradv.irt_wpa")),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
