use crate::model::*;

pub static HDR: Header = Header {
    path: "netpacket/packet.h",
    items: &[
        Item::Guard { name: "_NETPACKET_PACKET_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Block { head: "struct sockaddr_ll ", body: &["", "  unsigned short int sll_family;", "  unsigned short int sll_protocol;", "  int sll_ifindex;", "  unsigned short int sll_hatype;", "  unsigned char sll_pkttype;", "  unsigned char sll_halen;", "  unsigned char sll_addr[8];", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct packet_mreq ", body: &["", "  int mr_ifindex;", "  unsigned short int mr_type;", "  unsigned short int mr_alen;", "  unsigned char mr_address[8];", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("PACKET_ADD_MEMBERSHIP", V::Dec(1)),
                ("PACKET_AUXDATA", V::Dec(8)),
                ("PACKET_BROADCAST", V::Dec(1)),
                ("PACKET_COPY_THRESH", V::Dec(7)),
                ("PACKET_DROP_MEMBERSHIP", V::Dec(2)),
                ("PACKET_FANOUT", V::Dec(18)),
                ("PACKET_FANOUT_DATA", V::Dec(22)),
                ("PACKET_FASTROUTE", V::Dec(6)),
                ("PACKET_HDRLEN", V::Dec(11)),
                ("PACKET_HOST", V::Dec(0)),
                ("PACKET_IGNORE_OUTGOING", V::Dec(23)),
                ("PACKET_LOOPBACK", V::Dec(5)),
                ("PACKET_LOSS", V::Dec(14)),
                ("PACKET_MR_ALLMULTI", V::Dec(2)),
                ("PACKET_MR_MULTICAST", V::Dec(0)),
                ("PACKET_MR_PROMISC", V::Dec(1)),
                ("PACKET_MR_UNICAST", V::Dec(3)),
                ("PACKET_MULTICAST", V::Dec(2)),
                ("PACKET_ORIGDEV", V::Dec(9)),
                ("PACKET_OTHERHOST", V::Dec(3)),
                ("PACKET_OUTGOING", V::Dec(4)),
                ("PACKET_QDISC_BYPASS", V::Dec(20)),
                ("PACKET_RECV_OUTPUT", V::Dec(3)),
                ("PACKET_RESERVE", V::Dec(12)),
                ("PACKET_ROLLOVER_STATS", V::Dec(21)),
                ("PACKET_RX_RING", V::Dec(5)),
                ("PACKET_STATISTICS", V::Dec(6)),
                ("PACKET_TIMESTAMP", V::Dec(17)),
                ("PACKET_TX_HAS_OFF", V::Dec(19)),
                ("PACKET_TX_RING", V::Dec(13)),
                ("PACKET_TX_TIMESTAMP", V::Dec(16)),
                ("PACKET_VERSION", V::Dec(10)),
                ("PACKET_VNET_HDR", V::Dec(15)),
                ("PACKET_VNET_HDR_SZ", V::Dec(24)),
            ]),
        ]},
    ],
};
