use crate::model::*;

pub static HDR: Header = Header {
    path: "regex.h",
    items: &[
        Item::Guard { name: "_RLIBC_REGEX_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<stddef.h>"),
            Item::Include("<sys/types.h>"),
            Item::Blank,
            Item::ExternBegin,
            Item::Blank,
            Item::Typedef("int", "regoff_t"),
            Item::Typedef("unsigned long int", "reg_syntax_t"),
            Item::Blank,
            Item::Block { head: r#"typedef enum
"#, body: &["", "  _REG_ENOSYS = -1,", "  _REG_NOERROR = 0,", "  _REG_NOMATCH,", "  _REG_BADPAT,", "  _REG_ECOLLATE,", "  _REG_ECTYPE,", "  _REG_EESCAPE,", "  _REG_ESUBREG,", "  _REG_EBRACK,", "  _REG_EPAREN,", "  _REG_EBRACE,", "  _REG_BADBR,", "  _REG_ERANGE,", "  _REG_ESPACE,", "  _REG_BADRPT,", "  _REG_EEND,", "  _REG_ESIZE,", "  _REG_ERPAREN", ""], tail: " reg_errcode_t" },
            Item::Blank,
            Item::Consts(&[
                ("REG_BADBR", V::Txt("_REG_BADBR")),
                ("REG_BADPAT", V::Txt("_REG_BADPAT")),
                ("REG_BADRPT", V::Txt("_REG_BADRPT")),
                ("REG_EBRACE", V::Txt("_REG_EBRACE")),
                ("REG_EBRACK", V::Txt("_REG_EBRACK")),
                ("REG_ECOLLATE", V::Txt("_REG_ECOLLATE")),
                ("REG_ECTYPE", V::Txt("_REG_ECTYPE")),
                ("REG_EEND", V::Txt("_REG_EEND")),
                ("REG_EESCAPE", V::Txt("_REG_EESCAPE")),
                ("REG_ENOSYS", V::Txt("_REG_ENOSYS")),
                ("REG_EPAREN", V::Txt("_REG_EPAREN")),
                ("REG_ERANGE", V::Txt("_REG_ERANGE")),
                ("REG_ERPAREN", V::Txt("_REG_ERPAREN")),
                ("REG_ESIZE", V::Txt("_REG_ESIZE")),
                ("REG_ESPACE", V::Txt("_REG_ESPACE")),
                ("REG_ESUBREG", V::Txt("_REG_ESUBREG")),
                ("REG_EXTENDED", V::Dec(1)),
                ("REG_ICASE", V::Txt("(1 << 1)")),
                ("REG_NEWLINE", V::Txt("(1 << 2)")),
                ("REG_NOERROR", V::Txt("_REG_NOERROR")),
                ("REG_NOMATCH", V::Txt("_REG_NOMATCH")),
                ("REG_NOSUB", V::Txt("(1 << 3)")),
                ("REG_NOTBOL", V::Dec(1)),
                ("REG_NOTEOL", V::Txt("(1 << 1)")),
                ("REG_STARTEND", V::Txt("(1 << 2)")),
            ]),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef _GNU_SOURCE", items: &[
                    Item::ConstsFlat(&[
                        ("REGS_FIXED", V::Dec(2)),
                        ("REGS_REALLOCATE", V::Dec(1)),
                        ("REGS_UNALLOCATED", V::Dec(0)),
                        ("RE_BACKSLASH_ESCAPE_IN_LISTS", V::Txt("((unsigned long int) 1)")),
                        ("RE_BK_PLUS_QM", V::Txt("(RE_BACKSLASH_ESCAPE_IN_LISTS << 1)")),
                        ("RE_CARET_ANCHORS_HERE", V::Txt("(RE_ICASE << 1)")),
                        ("RE_CHAR_CLASSES", V::Txt("(RE_BK_PLUS_QM << 1)")),
                        ("RE_CONTEXT_INDEP_ANCHORS", V::Txt("(RE_CHAR_CLASSES << 1)")),
                        ("RE_CONTEXT_INDEP_OPS", V::Txt("(RE_CONTEXT_INDEP_ANCHORS << 1)")),
                        ("RE_CONTEXT_INVALID_DUP", V::Txt("(RE_CARET_ANCHORS_HERE << 1)")),
                        ("RE_CONTEXT_INVALID_OPS", V::Txt("(RE_CONTEXT_INDEP_OPS << 1)")),
                        ("RE_DEBUG", V::Txt("(RE_NO_GNU_OPS << 1)")),
                        ("RE_DOT_NEWLINE", V::Txt("(RE_CONTEXT_INVALID_OPS << 1)")),
                        ("RE_DOT_NOT_NULL", V::Txt("(RE_DOT_NEWLINE << 1)")),
                        ("RE_DUP_MAX", V::Txt("(0x7fff)")),
                        ("RE_HAT_LISTS_NOT_NEWLINE", V::Txt("(RE_DOT_NOT_NULL << 1)")),
                        ("RE_ICASE", V::Txt("(RE_INVALID_INTERVAL_ORD << 1)")),
                        ("RE_INTERVALS", V::Txt("(RE_HAT_LISTS_NOT_NEWLINE << 1)")),
                        ("RE_INVALID_INTERVAL_ORD", V::Txt("(RE_DEBUG << 1)")),
                        ("RE_LIMITED_OPS", V::Txt("(RE_INTERVALS << 1)")),
                        ("RE_NEWLINE_ALT", V::Txt("(RE_LIMITED_OPS << 1)")),
                        ("RE_NO_BK_BRACES", V::Txt("(RE_NEWLINE_ALT << 1)")),
                        ("RE_NO_BK_PARENS", V::Txt("(RE_NO_BK_BRACES << 1)")),
                        ("RE_NO_BK_REFS", V::Txt("(RE_NO_BK_PARENS << 1)")),
                        ("RE_NO_BK_VBAR", V::Txt("(RE_NO_BK_REFS << 1)")),
                        ("RE_NO_EMPTY_RANGES", V::Txt("(RE_NO_BK_VBAR << 1)")),
                        ("RE_NO_GNU_OPS", V::Txt("(RE_NO_POSIX_BACKTRACKING << 1)")),
                        ("RE_NO_POSIX_BACKTRACKING", V::Txt("(RE_UNMATCHED_RIGHT_PAREN_ORD << 1)")),
                        ("RE_NO_SUB", V::Txt("(RE_CONTEXT_INVALID_DUP << 1)")),
                        ("RE_NREGS", V::Dec(30)),
                        ("RE_SYNTAX_AWK", V::Txt("(RE_BACKSLASH_ESCAPE_IN_LISTS | RE_DOT_NOT_NULL | RE_NO_BK_PARENS | RE_NO_BK_REFS | RE_NO_BK_VBAR | RE_NO_EMPTY_RANGES | RE_DOT_NEWLINE | RE_CONTEXT_INDEP_ANCHORS | RE_CHAR_CLASSES | RE_UNMATCHED_RIGHT_PAREN_ORD | RE_NO_GNU_OPS)")),
                        ("RE_SYNTAX_ED", V::Txt("RE_SYNTAX_POSIX_BASIC")),
                        ("RE_SYNTAX_EGREP", V::Txt("((RE_SYNTAX_POSIX_EXTENDED | RE_INVALID_INTERVAL_ORD | RE_NEWLINE_ALT) & ~(RE_CONTEXT_INVALID_OPS | RE_DOT_NOT_NULL))")),
                        ("RE_SYNTAX_EMACS", V::Dec(0)),
                        ("RE_SYNTAX_GNU_AWK", V::Txt("((RE_SYNTAX_POSIX_EXTENDED | RE_BACKSLASH_ESCAPE_IN_LISTS | RE_INVALID_INTERVAL_ORD) & ~(RE_DOT_NOT_NULL | RE_CONTEXT_INDEP_OPS | RE_CONTEXT_INVALID_OPS ))")),
                        ("RE_SYNTAX_GREP", V::Txt("((RE_SYNTAX_POSIX_BASIC | RE_NEWLINE_ALT) & ~(RE_CONTEXT_INVALID_DUP | RE_DOT_NOT_NULL))")),
                        ("RE_SYNTAX_POSIX_AWK", V::Txt("(RE_SYNTAX_POSIX_EXTENDED | RE_BACKSLASH_ESCAPE_IN_LISTS | RE_INTERVALS | RE_NO_GNU_OPS | RE_INVALID_INTERVAL_ORD)")),
                        ("RE_SYNTAX_POSIX_BASIC", V::Txt("(_RE_SYNTAX_POSIX_COMMON | RE_BK_PLUS_QM | RE_CONTEXT_INVALID_DUP)")),
                        ("RE_SYNTAX_POSIX_EGREP", V::Txt("RE_SYNTAX_EGREP")),
                        ("RE_SYNTAX_POSIX_EXTENDED", V::Txt("(_RE_SYNTAX_POSIX_COMMON | RE_CONTEXT_INDEP_ANCHORS | RE_CONTEXT_INDEP_OPS | RE_NO_BK_BRACES | RE_NO_BK_PARENS | RE_NO_BK_VBAR | RE_CONTEXT_INVALID_OPS | RE_UNMATCHED_RIGHT_PAREN_ORD)")),
                        ("RE_SYNTAX_POSIX_MINIMAL_BASIC", V::Txt("(_RE_SYNTAX_POSIX_COMMON | RE_LIMITED_OPS)")),
                        ("RE_SYNTAX_POSIX_MINIMAL_EXTENDED", V::Txt("(_RE_SYNTAX_POSIX_COMMON | RE_CONTEXT_INDEP_ANCHORS | RE_CONTEXT_INVALID_OPS | RE_NO_BK_BRACES | RE_NO_BK_PARENS | RE_NO_BK_REFS | RE_NO_BK_VBAR | RE_UNMATCHED_RIGHT_PAREN_ORD)")),
                        ("RE_SYNTAX_SED", V::Txt("RE_SYNTAX_POSIX_BASIC")),
                        ("RE_TRANSLATE_TYPE", V::Txt("__RE_TRANSLATE_TYPE")),
                        ("RE_UNMATCHED_RIGHT_PAREN_ORD", V::Txt("(RE_NO_EMPTY_RANGES << 1)")),
                        ("_RE_SYNTAX_POSIX_COMMON", V::Txt("(RE_CHAR_CLASSES | RE_DOT_NEWLINE | RE_DOT_NOT_NULL | RE_INTERVALS | RE_NO_EMPTY_RANGES)")),
                    ]),
                ] },
            ], ""),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef _GNU_SOURCE", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __REPB_PREFIX(name) name"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __REPB_PREFIX(name) __##name"),
                ] },
            ], ""),
            Item::Blank,
            Item::Block { head: r#"struct re_pattern_buffer
"#, body: &["", "  struct re_dfa_t *__REPB_PREFIX(buffer);", "  unsigned long int __REPB_PREFIX(allocated);", "  unsigned long int __REPB_PREFIX(used);", "  reg_syntax_t __REPB_PREFIX(syntax);", "  char *__REPB_PREFIX(fastmap);", "  unsigned char *__REPB_PREFIX(translate);", "  size_t re_nsub;", "  unsigned __REPB_PREFIX(can_be_null) : 1;", "  unsigned __REPB_PREFIX(regs_allocated) : 2;", "  unsigned __REPB_PREFIX(fastmap_accurate) : 1;", "  unsigned __REPB_PREFIX(no_sub) : 1;", "  unsigned __REPB_PREFIX(not_bol) : 1;", "  unsigned __REPB_PREFIX(not_eol) : 1;", "  unsigned __REPB_PREFIX(newline_anchor) : 1;", ""], tail: "" },
            Item::Typedef("struct re_pattern_buffer", "regex_t"),
            Item::Blank,
            Item::Block { head: r#"typedef struct
"#, body: &["", "  regoff_t rm_so;", "  regoff_t rm_eo;", ""], tail: " regmatch_t" },
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef _GNU_SOURCE", items: &[
                    Item::Block { head: r#"struct re_registers
"#, body: &["", "  unsigned num_regs;", "  regoff_t *start;", "  regoff_t *end;", ""], tail: "" },
                    Item::Decl("extern reg_syntax_t re_syntax_options;"),
                    Item::Decl("extern reg_syntax_t re_set_syntax (reg_syntax_t __syntax);"),
                    Item::Decl("extern const char *re_compile_pattern (const char *__pattern, size_t __length, struct re_pattern_buffer *__buffer);"),
                    Item::Decl("extern int re_compile_fastmap (struct re_pattern_buffer *__buffer);"),
                    Item::Decl(r#"extern regoff_t re_search (struct re_pattern_buffer *__buffer, const char *__String, regoff_t __length,
                           regoff_t __start, regoff_t __range, struct re_registers *__regs);"#),
                    Item::Decl(r#"extern regoff_t re_search_2 (struct re_pattern_buffer *__buffer, const char *__string1, regoff_t __length1,
                             const char *__string2, regoff_t __length2, regoff_t __start, regoff_t __range,
                             struct re_registers *__regs, regoff_t __stop);"#),
                    Item::Decl(r#"extern regoff_t re_match (struct re_pattern_buffer *__buffer, const char *__String, regoff_t __length,
                          regoff_t __start, struct re_registers *__regs);"#),
                    Item::Decl(r#"extern regoff_t re_match_2 (struct re_pattern_buffer *__buffer, const char *__string1, regoff_t __length1,
                            const char *__string2, regoff_t __length2, regoff_t __start,
                            struct re_registers *__regs, regoff_t __stop);"#),
                    Item::Decl(r#"extern void re_set_registers (struct re_pattern_buffer *__buffer, struct re_registers *__regs,
                              unsigned __num_regs, regoff_t *__starts, regoff_t *__ends);"#),
                ] },
            ], ""),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "if defined _REGEX_RE_COMP || (defined _GNU_SOURCE && !defined _POSIX_C_SOURCE) || defined _DEFAULT_SOURCE", items: &[
                    Item::Decl("extern char *re_comp (const char *);"),
                    Item::Decl("extern int re_exec (const char *);"),
                ] },
            ], ""),
            Item::Blank,
            Item::Decl("extern int regcomp (regex_t *__restrict __preg, const char *__restrict __pattern, int __cflags);"),
            Item::Decl(r#"extern int regexec (const regex_t *__restrict __preg, const char *__restrict __String, size_t __nmatch,
                    regmatch_t __pmatch[__restrict_arr], int __eflags);"#),
            Item::Decl("extern size_t regerror (int __errcode, const regex_t *__restrict __preg, char *__restrict __errbuf, size_t __errbuf_size);"),
            Item::Decl("extern void regfree (regex_t *__preg);"),
            Item::Blank,
            Item::ExternEnd,
            Item::Blank,
        ]},
    ],
};
