use crate::model::*;

pub static HDR: Header = Header {
    path: "resolv.h",
    items: &[
        Item::Guard { name: "_RESOLV_H", value: "1", end: "", items: &[
            Item::Include("<sys/types.h>"),
            Item::Include("<stdio.h>"),
            Item::Include("<netinet/in.h>"),
            Item::Include("<arpa/nameser.h>"),
            Item::Blank,
            Item::Consts(&[
                ("MAXDFLSRCH", V::Dec(3)),
                ("MAXDNSRCH", V::Dec(6)),
                ("MAXNS", V::Dec(3)),
                ("MAXRESOLVSORT", V::Dec(10)),
                ("RES_DEBUG", V::Dec(2)),
                ("RES_DEFAULT", V::Dec(704)),
                ("RES_DEFNAMES", V::Dec(128)),
                ("RES_DFLRETRY", V::Dec(2)),
                ("RES_DNSRCH", V::Dec(512)),
                ("RES_IGNTC", V::Dec(32)),
                ("RES_INIT", V::Dec(1)),
                ("RES_MAXNDOTS", V::Dec(15)),
                ("RES_MAXRETRANS", V::Dec(30)),
                ("RES_MAXRETRY", V::Dec(5)),
                ("RES_MAXTIME", V::Dec(65535)),
                ("RES_NOAAAA", V::Dec(134217728)),
                ("RES_NOALIASES", V::Dec(4096)),
                ("RES_NORELOAD", V::Dec(33554432)),
                ("RES_NOTLDQUERY", V::Dec(16777216)),
                ("RES_RECURSE", V::Dec(64)),
                ("RES_ROTATE", V::Dec(16384)),
                ("RES_SNGLKUP", V::Dec(2097152)),
                ("RES_SNGLKUPREOP", V::Dec(4194304)),
                ("RES_STAYOPEN", V::Dec(256)),
                ("RES_STRICTERR", V::Dec(268435456)),
                ("RES_TIMEOUT", V::Dec(5)),
                ("RES_TRUSTAD", V::Dec(67108864)),
                ("RES_USEVC", V::Dec(8)),
                ("RES_USE_DNSSEC", V::Dec(8388608)),
                ("RES_USE_EDNS0", V::Dec(1048576)),
                ("RES_PRF_ADD", V::Dec(128)),
                ("RES_PRF_ANS", V::Dec(32)),
                ("RES_PRF_AUTH", V::Dec(64)),
                ("RES_PRF_CLASS", V::Dec(4)),
                ("RES_PRF_CMD", V::Dec(8)),
                ("RES_PRF_HEAD1", V::Dec(256)),
                ("RES_PRF_HEAD2", V::Dec(512)),
                ("RES_PRF_HEADX", V::Dec(2048)),
                ("RES_PRF_INIT", V::Dec(16384)),
                ("RES_PRF_QUERY", V::Dec(4096)),
                ("RES_PRF_QUES", V::Dec(16)),
                ("RES_PRF_REPLY", V::Dec(8192)),
                ("RES_PRF_STATS", V::Dec(1)),
                ("RES_PRF_TTLID", V::Dec(1024)),
                ("RES_PRF_UPDATE", V::Dec(2)),
            ]),
            Item::Blank,
            Item::Blank,
            Item::Block { head: "struct __res_state ", body: &["", "  int retrans;", "  int retry;", "  unsigned long options;", "  int nscount;", "  struct sockaddr_in nsaddr_list[MAXNS];", "#define nsaddr nsaddr_list[0]", "  unsigned short id;", "  char *dnsrch[MAXDNSRCH + 1];", "  char defdname[256];", "  unsigned long pfcode;", "  unsigned ndots:4;", "  unsigned nsort:4;", "  unsigned ipv6_unavail:1;", "  unsigned unused:23;", "  struct {", "    struct in_addr addr;", "    uint32_t mask;", "  } sort_list[MAXRESOLVSORT];", "  void *__glibc_unused_qhook;", "  void *__glibc_unused_rhook;", "  int res_h_errno;", "  int _vcsock;", "  unsigned int _flags;", "  union {", "    char pad[52];", "    struct {", "      uint16_t nscount;", "      uint16_t nsmap[MAXNS];", "      int nssocks[MAXNS];", "      uint16_t nscount6;", "      uint16_t nsinit;", "      struct sockaddr_in6 *nsaddrs[MAXNS];", "      unsigned int __glibc_extension_index;", "    } _ext;", "  } _u;", ""], tail: "" },
            Item::Typedef("struct __res_state *", "res_state"),
            Item::Blank,
            Item::Consts(&[
                ("_res", V::Txt("(*__res_state())")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("res_init", V::Txt("__res_init")),
                ("res_ninit", V::Txt("__res_ninit")),
                ("res_nclose", V::Txt("__res_nclose")),
                ("res_iclose", V::Txt("__res_iclose")),
                ("loc_ntoa", V::Txt("__loc_ntoa")),
            ]),
            Item::Blank,
            Item::Include("<bits/rlibc-net-resolv.h>"),
        ]},
    ],
};
