use crate::model::*;

pub static HDR: Header = Header {
    path: "stdint.h",
    items: &[
        Item::Guard { name: "_RLIBC_STDINT_H", value: "", end: "", items: &[
            Item::Typedef("signed char", "int8_t"),
            Item::Typedef("short int", "int16_t"),
            Item::Typedef("int", "int32_t"),
            Item::Typedef("long int", "int64_t"),
            Item::Typedef("unsigned char", "uint8_t"),
            Item::Typedef("unsigned short int", "uint16_t"),
            Item::Typedef("unsigned int", "uint32_t"),
            Item::Typedef("unsigned long int", "uint64_t"),
            Item::Typedef("signed char", "int_least8_t"),
            Item::Typedef("short int", "int_least16_t"),
            Item::Typedef("int", "int_least32_t"),
            Item::Typedef("long int", "int_least64_t"),
            Item::Typedef("unsigned char", "uint_least8_t"),
            Item::Typedef("unsigned short int", "uint_least16_t"),
            Item::Typedef("unsigned int", "uint_least32_t"),
            Item::Typedef("unsigned long int", "uint_least64_t"),
            Item::Typedef("signed char", "int_fast8_t"),
            Item::Typedef("long int", "int_fast16_t"),
            Item::Typedef("long int", "int_fast32_t"),
            Item::Typedef("long int", "int_fast64_t"),
            Item::Typedef("unsigned char", "uint_fast8_t"),
            Item::Typedef("unsigned long int", "uint_fast16_t"),
            Item::Typedef("unsigned long int", "uint_fast32_t"),
            Item::Typedef("unsigned long int", "uint_fast64_t"),
            Item::Typedef("long int", "intptr_t"),
            Item::Typedef("unsigned long int", "uintptr_t"),
            Item::Typedef("long int", "intmax_t"),
            Item::Typedef("unsigned long int", "uintmax_t"),
            Item::Blank,
            Item::Consts(&[
                ("INT8_MIN", V::Txt("(-128)")),
                ("INT16_MIN", V::Txt("(-32767 - 1)")),
                ("INT32_MIN", V::Txt("(-2147483647 - 1)")),
                ("INT64_MIN", V::Txt("(-9223372036854775807L - 1)")),
                ("INT8_MAX", V::Dec(127)),
                ("INT16_MAX", V::Dec(32767)),
                ("INT32_MAX", V::Dec(2147483647)),
                ("INT64_MAX", V::Txt("9223372036854775807L")),
                ("UINT8_MAX", V::Dec(255)),
                ("UINT16_MAX", V::Dec(65535)),
                ("UINT32_MAX", V::Txt("4294967295U")),
                ("UINT64_MAX", V::Txt("18446744073709551615UL")),
                ("INT_LEAST8_MIN", V::Txt("INT8_MIN")),
                ("INT_LEAST16_MIN", V::Txt("INT16_MIN")),
                ("INT_LEAST32_MIN", V::Txt("INT32_MIN")),
                ("INT_LEAST64_MIN", V::Txt("INT64_MIN")),
                ("INT_LEAST8_MAX", V::Txt("INT8_MAX")),
                ("INT_LEAST16_MAX", V::Txt("INT16_MAX")),
                ("INT_LEAST32_MAX", V::Txt("INT32_MAX")),
                ("INT_LEAST64_MAX", V::Txt("INT64_MAX")),
                ("UINT_LEAST8_MAX", V::Txt("UINT8_MAX")),
                ("UINT_LEAST16_MAX", V::Txt("UINT16_MAX")),
                ("UINT_LEAST32_MAX", V::Txt("UINT32_MAX")),
                ("UINT_LEAST64_MAX", V::Txt("UINT64_MAX")),
                ("INT_FAST8_MIN", V::Txt("INT8_MIN")),
                ("INT_FAST16_MIN", V::Txt("INT64_MIN")),
                ("INT_FAST32_MIN", V::Txt("INT64_MIN")),
                ("INT_FAST64_MIN", V::Txt("INT64_MIN")),
                ("INT_FAST8_MAX", V::Txt("INT8_MAX")),
                ("INT_FAST16_MAX", V::Txt("INT64_MAX")),
                ("INT_FAST32_MAX", V::Txt("INT64_MAX")),
                ("INT_FAST64_MAX", V::Txt("INT64_MAX")),
                ("UINT_FAST8_MAX", V::Txt("UINT8_MAX")),
                ("UINT_FAST16_MAX", V::Txt("UINT64_MAX")),
                ("UINT_FAST32_MAX", V::Txt("UINT64_MAX")),
                ("UINT_FAST64_MAX", V::Txt("UINT64_MAX")),
                ("INTPTR_MIN", V::Txt("INT64_MIN")),
                ("INTPTR_MAX", V::Txt("INT64_MAX")),
                ("UINTPTR_MAX", V::Txt("UINT64_MAX")),
                ("INTMAX_MIN", V::Txt("INT64_MIN")),
                ("INTMAX_MAX", V::Txt("INT64_MAX")),
                ("UINTMAX_MAX", V::Txt("UINT64_MAX")),
                ("PTRDIFF_MIN", V::Txt("INT64_MIN")),
                ("PTRDIFF_MAX", V::Txt("INT64_MAX")),
                ("SIG_ATOMIC_MIN", V::Txt("INT32_MIN")),
                ("SIG_ATOMIC_MAX", V::Txt("INT32_MAX")),
                ("SIZE_MAX", V::Txt("UINT64_MAX")),
                ("WCHAR_MIN", V::Txt("INT32_MIN")),
                ("WCHAR_MAX", V::Txt("INT32_MAX")),
                ("WINT_MIN", V::Txt("0U")),
                ("WINT_MAX", V::Txt("UINT32_MAX")),
            ]),
            Item::Raw(Reason::StdMacro, "#define INT8_C(c) c"),
            Item::Raw(Reason::StdMacro, "#define INT16_C(c) c"),
            Item::Raw(Reason::StdMacro, "#define INT32_C(c) c"),
            Item::Raw(Reason::StdMacro, "#define INT64_C(c) c ## L"),
            Item::Raw(Reason::StdMacro, "#define UINT8_C(c) c"),
            Item::Raw(Reason::StdMacro, "#define UINT16_C(c) c"),
            Item::Raw(Reason::StdMacro, "#define UINT32_C(c) c ## U"),
            Item::Raw(Reason::StdMacro, "#define UINT64_C(c) c ## UL"),
            Item::Raw(Reason::StdMacro, "#define INTMAX_C(c) c ## L"),
            Item::Raw(Reason::StdMacro, "#define UINTMAX_C(c) c ## UL"),
            Item::Gate(&[
                Branch { head: "if defined _GNU_SOURCE || (defined __STDC_VERSION__ && __STDC_VERSION__ > 201710L)", items: &[
                    Item::Consts(&[
                        ("INT8_WIDTH", V::Dec(8)),
                        ("UINT8_WIDTH", V::Dec(8)),
                        ("INT16_WIDTH", V::Dec(16)),
                        ("UINT16_WIDTH", V::Dec(16)),
                        ("INT32_WIDTH", V::Dec(32)),
                        ("UINT32_WIDTH", V::Dec(32)),
                        ("INT64_WIDTH", V::Dec(64)),
                        ("UINT64_WIDTH", V::Dec(64)),
                        ("INT_LEAST8_WIDTH", V::Dec(8)),
                        ("UINT_LEAST8_WIDTH", V::Dec(8)),
                        ("INT_LEAST16_WIDTH", V::Dec(16)),
                        ("UINT_LEAST16_WIDTH", V::Dec(16)),
                        ("INT_LEAST32_WIDTH", V::Dec(32)),
                        ("UINT_LEAST32_WIDTH", V::Dec(32)),
                        ("INT_LEAST64_WIDTH", V::Dec(64)),
                        ("UINT_LEAST64_WIDTH", V::Dec(64)),
                        ("INT_FAST8_WIDTH", V::Dec(8)),
                        ("UINT_FAST8_WIDTH", V::Dec(8)),
                        ("INT_FAST16_WIDTH", V::Dec(64)),
                        ("UINT_FAST16_WIDTH", V::Dec(64)),
                        ("INT_FAST32_WIDTH", V::Dec(64)),
                        ("UINT_FAST32_WIDTH", V::Dec(64)),
                        ("INT_FAST64_WIDTH", V::Dec(64)),
                        ("UINT_FAST64_WIDTH", V::Dec(64)),
                        ("INTMAX_WIDTH", V::Dec(64)),
                        ("UINTMAX_WIDTH", V::Dec(64)),
                        ("INTPTR_WIDTH", V::Dec(64)),
                        ("UINTPTR_WIDTH", V::Dec(64)),
                        ("PTRDIFF_WIDTH", V::Dec(64)),
                        ("SIZE_WIDTH", V::Dec(64)),
                        ("SIG_ATOMIC_WIDTH", V::Dec(32)),
                        ("WCHAR_WIDTH", V::Dec(32)),
                        ("WINT_WIDTH", V::Dec(32)),
                    ]),
                ] },
            ], ""),
        ]},
    ],
};
