use crate::model::*;

pub static HDR: Header = Header {
    path: "sys/socket.h",
    items: &[
        Item::Guard { name: "_SYS_SOCKET_H", value: "1", end: "", items: &[
            Item::Include("<stddef.h>"),
            Item::Include("<stdint.h>"),
            Item::Include("<bits/types/struct_timespec.h>"),
            Item::Gate(&[
                Branch { head: "ifndef __socklen_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__socklen_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("unsigned int", "socklen_t"),
                ] },
            ], ""),
            Item::Include("<bits/sockaddr.h>"),
            Item::Gate(&[
                Branch { head: "ifndef __sa_family_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__sa_family_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("unsigned short int", "sa_family_t"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "ifndef __pid_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__pid_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("int", "pid_t"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "ifndef __uid_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__uid_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("unsigned int", "uid_t"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "ifndef __gid_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__gid_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("unsigned int", "gid_t"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "ifndef __ssize_t_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__ssize_t_defined", V::Dec(1)),
                    ]),
                    Item::Typedef("long", "ssize_t"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "ifndef __iovec_defined", items: &[
                    Item::ConstsFlat(&[
                        ("__iovec_defined", V::Dec(1)),
                    ]),
                    Item::Block { head: "struct iovec ", body: &["", "  void *iov_base;", "  size_t iov_len;", ""], tail: "" },
                ] },
            ], ""),
            Item::Blank,
            Item::Consts(&[
                ("AF_ALG", V::Dec(38)),
                ("AF_APPLETALK", V::Dec(5)),
                ("AF_ASH", V::Dec(18)),
                ("AF_ATMPVC", V::Dec(8)),
                ("AF_ATMSVC", V::Dec(20)),
                ("AF_AX25", V::Dec(3)),
                ("AF_BLUETOOTH", V::Dec(31)),
                ("AF_BRIDGE", V::Dec(7)),
                ("AF_CAIF", V::Dec(37)),
                ("AF_CAN", V::Dec(29)),
                ("AF_DECnet", V::Dec(12)),
                ("AF_ECONET", V::Dec(19)),
                ("AF_FILE", V::Dec(1)),
                ("AF_IB", V::Dec(27)),
                ("AF_IEEE802154", V::Dec(36)),
                ("AF_INET", V::Dec(2)),
                ("AF_INET6", V::Dec(10)),
                ("AF_IPX", V::Dec(4)),
                ("AF_IRDA", V::Dec(23)),
                ("AF_ISDN", V::Dec(34)),
                ("AF_IUCV", V::Dec(32)),
                ("AF_KCM", V::Dec(41)),
                ("AF_KEY", V::Dec(15)),
                ("AF_LLC", V::Dec(26)),
                ("AF_LOCAL", V::Dec(1)),
                ("AF_MAX", V::Dec(46)),
                ("AF_MCTP", V::Dec(45)),
                ("AF_MPLS", V::Dec(28)),
                ("AF_NETBEUI", V::Dec(13)),
                ("AF_NETLINK", V::Dec(16)),
                ("AF_NETROM", V::Dec(6)),
                ("AF_NFC", V::Dec(39)),
                ("AF_PACKET", V::Dec(17)),
                ("AF_PHONET", V::Dec(35)),
                ("AF_PPPOX", V::Dec(24)),
                ("AF_QIPCRTR", V::Dec(42)),
                ("AF_RDS", V::Dec(21)),
                ("AF_ROSE", V::Dec(11)),
                ("AF_ROUTE", V::Dec(16)),
                ("AF_RXRPC", V::Dec(33)),
                ("AF_SECURITY", V::Dec(14)),
                ("AF_SMC", V::Dec(43)),
                ("AF_SNA", V::Dec(22)),
                ("AF_TIPC", V::Dec(30)),
                ("AF_UNIX", V::Dec(1)),
                ("AF_UNSPEC", V::Dec(0)),
                ("AF_VSOCK", V::Dec(40)),
                ("AF_WANPIPE", V::Dec(25)),
                ("AF_X25", V::Dec(9)),
                ("AF_XDP", V::Dec(44)),
                ("FIOGETOWN", V::Dec(35075)),
                ("FIOSETOWN", V::Dec(35073)),
                ("MSG_BATCH", V::Dec(262144)),
                ("MSG_CMSG_CLOEXEC", V::Dec(1073741824)),
                ("MSG_CONFIRM", V::Dec(2048)),
                ("MSG_CTRUNC", V::Dec(8)),
                ("MSG_DONTROUTE", V::Dec(4)),
                ("MSG_DONTWAIT", V::Dec(64)),
                ("MSG_EOR", V::Dec(128)),
                ("MSG_ERRQUEUE", V::Dec(8192)),
                ("MSG_FASTOPEN", V::Dec(536870912)),
                ("MSG_FIN", V::Dec(512)),
                ("MSG_MORE", V::Dec(32768)),
                ("MSG_NOSIGNAL", V::Dec(16384)),
                ("MSG_OOB", V::Dec(1)),
                ("MSG_PEEK", V::Dec(2)),
                ("MSG_PROXY", V::Dec(16)),
                ("MSG_RST", V::Dec(4096)),
                ("MSG_SOCK_DEVMEM", V::Dec(33554432)),
                ("MSG_SYN", V::Dec(1024)),
                ("MSG_TRUNC", V::Dec(32)),
                ("MSG_TRYHARD", V::Dec(4)),
                ("MSG_WAITALL", V::Dec(256)),
                ("MSG_WAITFORONE", V::Dec(65536)),
                ("MSG_ZEROCOPY", V::Dec(67108864)),
                ("PF_ALG", V::Dec(38)),
                ("PF_APPLETALK", V::Dec(5)),
                ("PF_ASH", V::Dec(18)),
                ("PF_ATMPVC", V::Dec(8)),
                ("PF_ATMSVC", V::Dec(20)),
                ("PF_AX25", V::Dec(3)),
                ("PF_BLUETOOTH", V::Dec(31)),
                ("PF_BRIDGE", V::Dec(7)),
                ("PF_CAIF", V::Dec(37)),
                ("PF_CAN", V::Dec(29)),
                ("PF_DECnet", V::Dec(12)),
                ("PF_ECONET", V::Dec(19)),
                ("PF_FILE", V::Dec(1)),
                ("PF_IB", V::Dec(27)),
                ("PF_IEEE802154", V::Dec(36)),
                ("PF_INET", V::Dec(2)),
                ("PF_INET6", V::Dec(10)),
                ("PF_IPX", V::Dec(4)),
                ("PF_IRDA", V::Dec(23)),
                ("PF_ISDN", V::Dec(34)),
                ("PF_IUCV", V::Dec(32)),
                ("PF_KCM", V::Dec(41)),
                ("PF_KEY", V::Dec(15)),
                ("PF_LLC", V::Dec(26)),
                ("PF_LOCAL", V::Dec(1)),
                ("PF_MAX", V::Dec(46)),
                ("PF_MCTP", V::Dec(45)),
                ("PF_MPLS", V::Dec(28)),
                ("PF_NETBEUI", V::Dec(13)),
                ("PF_NETLINK", V::Dec(16)),
                ("PF_NETROM", V::Dec(6)),
                ("PF_NFC", V::Dec(39)),
                ("PF_PACKET", V::Dec(17)),
                ("PF_PHONET", V::Dec(35)),
                ("PF_PPPOX", V::Dec(24)),
                ("PF_QIPCRTR", V::Dec(42)),
                ("PF_RDS", V::Dec(21)),
                ("PF_ROSE", V::Dec(11)),
                ("PF_ROUTE", V::Dec(16)),
                ("PF_RXRPC", V::Dec(33)),
                ("PF_SECURITY", V::Dec(14)),
                ("PF_SMC", V::Dec(43)),
                ("PF_SNA", V::Dec(22)),
                ("PF_TIPC", V::Dec(30)),
                ("PF_UNIX", V::Dec(1)),
                ("PF_UNSPEC", V::Dec(0)),
                ("PF_VSOCK", V::Dec(40)),
                ("PF_WANPIPE", V::Dec(25)),
                ("PF_X25", V::Dec(9)),
                ("PF_XDP", V::Dec(44)),
                ("SCM_CREDENTIALS", V::Dec(2)),
                ("SCM_DEVMEM_DMABUF", V::Dec(79)),
                ("SCM_DEVMEM_LINEAR", V::Dec(78)),
                ("SCM_INQ", V::Dec(84)),
                ("SCM_PIDFD", V::Dec(4)),
                ("SCM_RIGHTS", V::Dec(1)),
                ("SCM_SECURITY", V::Dec(3)),
                ("SCM_TIMESTAMP", V::Dec(29)),
                ("SCM_TIMESTAMPING", V::Dec(37)),
                ("SCM_TIMESTAMPING_OPT_STATS", V::Dec(54)),
                ("SCM_TIMESTAMPING_PKTINFO", V::Dec(58)),
                ("SCM_TIMESTAMPNS", V::Dec(35)),
                ("SCM_TS_OPT_ID", V::Dec(81)),
                ("SCM_TXTIME", V::Dec(61)),
                ("SCM_WIFI_STATUS", V::Dec(41)),
                ("SHUT_RD", V::Dec(0)),
                ("SHUT_RDWR", V::Dec(2)),
                ("SHUT_WR", V::Dec(1)),
                ("SIOCATMARK", V::Dec(35077)),
                ("SIOCGPGRP", V::Dec(35076)),
                ("SIOCGSTAMPNS_OLD", V::Dec(35079)),
                ("SIOCGSTAMP_OLD", V::Dec(35078)),
                ("SIOCSPGRP", V::Dec(35074)),
                ("SOCK_CLOEXEC", V::Dec(524288)),
                ("SOCK_DCCP", V::Dec(6)),
                ("SOCK_DGRAM", V::Dec(2)),
                ("SOCK_NONBLOCK", V::Dec(2048)),
                ("SOCK_PACKET", V::Dec(10)),
                ("SOCK_RAW", V::Dec(3)),
                ("SOCK_RDM", V::Dec(4)),
                ("SOCK_SEQPACKET", V::Dec(5)),
                ("SOCK_STREAM", V::Dec(1)),
                ("SOL_AAL", V::Dec(265)),
                ("SOL_ALG", V::Dec(279)),
                ("SOL_ATM", V::Dec(264)),
                ("SOL_BLUETOOTH", V::Dec(274)),
                ("SOL_CAIF", V::Dec(278)),
                ("SOL_DCCP", V::Dec(269)),
                ("SOL_DECNET", V::Dec(261)),
                ("SOL_IRDA", V::Dec(266)),
                ("SOL_IUCV", V::Dec(277)),
                ("SOL_KCM", V::Dec(281)),
                ("SOL_LLC", V::Dec(268)),
                ("SOL_MCTP", V::Dec(285)),
                ("SOL_MPTCP", V::Dec(284)),
                ("SOL_NETBEUI", V::Dec(267)),
                ("SOL_NETLINK", V::Dec(270)),
                ("SOL_NFC", V::Dec(280)),
                ("SOL_PACKET", V::Dec(263)),
                ("SOL_PNPIPE", V::Dec(275)),
                ("SOL_PPPOL2TP", V::Dec(273)),
                ("SOL_RAW", V::Dec(255)),
                ("SOL_RDS", V::Dec(276)),
                ("SOL_RXRPC", V::Dec(272)),
                ("SOL_SMC", V::Dec(286)),
                ("SOL_SOCKET", V::Dec(1)),
                ("SOL_TIPC", V::Dec(271)),
                ("SOL_TLS", V::Dec(282)),
                ("SOL_VSOCK", V::Dec(287)),
                ("SOL_X25", V::Dec(262)),
                ("SOL_XDP", V::Dec(283)),
                ("SOMAXCONN", V::Dec(4096)),
                ("SO_ACCEPTCONN", V::Dec(30)),
                ("SO_ATTACH_BPF", V::Dec(50)),
                ("SO_ATTACH_FILTER", V::Dec(26)),
                ("SO_ATTACH_REUSEPORT_CBPF", V::Dec(51)),
                ("SO_ATTACH_REUSEPORT_EBPF", V::Dec(52)),
                ("SO_BINDTODEVICE", V::Dec(25)),
                ("SO_BINDTOIFINDEX", V::Dec(62)),
                ("SO_BPF_EXTENSIONS", V::Dec(48)),
                ("SO_BROADCAST", V::Dec(6)),
                ("SO_BSDCOMPAT", V::Dec(14)),
                ("SO_BUF_LOCK", V::Dec(72)),
                ("SO_BUSY_POLL", V::Dec(46)),
                ("SO_BUSY_POLL_BUDGET", V::Dec(70)),
                ("SO_CNX_ADVICE", V::Dec(53)),
                ("SO_COOKIE", V::Dec(57)),
                ("SO_DEBUG", V::Dec(1)),
                ("SO_DETACH_BPF", V::Dec(27)),
                ("SO_DETACH_FILTER", V::Dec(27)),
                ("SO_DETACH_REUSEPORT_BPF", V::Dec(68)),
                ("SO_DEVMEM_DMABUF", V::Dec(79)),
                ("SO_DEVMEM_DONTNEED", V::Dec(80)),
                ("SO_DEVMEM_LINEAR", V::Dec(78)),
                ("SO_DOMAIN", V::Dec(39)),
                ("SO_DONTROUTE", V::Dec(5)),
                ("SO_ERROR", V::Dec(4)),
                ("SO_GET_FILTER", V::Dec(26)),
                ("SO_INCOMING_CPU", V::Dec(49)),
                ("SO_INCOMING_NAPI_ID", V::Dec(56)),
                ("SO_INQ", V::Dec(84)),
                ("SO_KEEPALIVE", V::Dec(9)),
                ("SO_LINGER", V::Dec(13)),
                ("SO_LOCK_FILTER", V::Dec(44)),
                ("SO_MARK", V::Dec(36)),
                ("SO_MAX_PACING_RATE", V::Dec(47)),
                ("SO_MEMINFO", V::Dec(55)),
                ("SO_NETNS_COOKIE", V::Dec(71)),
                ("SO_NOFCS", V::Dec(43)),
                ("SO_NO_CHECK", V::Dec(11)),
                ("SO_OOBINLINE", V::Dec(10)),
                ("SO_PASSCRED", V::Dec(16)),
                ("SO_PASSPIDFD", V::Dec(76)),
                ("SO_PASSRIGHTS", V::Dec(83)),
                ("SO_PASSSEC", V::Dec(34)),
                ("SO_PEEK_OFF", V::Dec(42)),
                ("SO_PEERCRED", V::Dec(17)),
                ("SO_PEERGROUPS", V::Dec(59)),
                ("SO_PEERNAME", V::Dec(28)),
                ("SO_PEERPIDFD", V::Dec(77)),
                ("SO_PEERSEC", V::Dec(31)),
                ("SO_PREFER_BUSY_POLL", V::Dec(69)),
                ("SO_PRIORITY", V::Dec(12)),
                ("SO_PROTOCOL", V::Dec(38)),
                ("SO_RCVBUF", V::Dec(8)),
                ("SO_RCVBUFFORCE", V::Dec(33)),
                ("SO_RCVLOWAT", V::Dec(18)),
                ("SO_RCVMARK", V::Dec(75)),
                ("SO_RCVPRIORITY", V::Dec(82)),
                ("SO_RCVTIMEO", V::Dec(20)),
                ("SO_RCVTIMEO_NEW", V::Dec(66)),
                ("SO_RCVTIMEO_OLD", V::Dec(20)),
                ("SO_RESERVE_MEM", V::Dec(73)),
                ("SO_REUSEADDR", V::Dec(2)),
                ("SO_REUSEPORT", V::Dec(15)),
                ("SO_RXQ_OVFL", V::Dec(40)),
                ("SO_SECURITY_AUTHENTICATION", V::Dec(22)),
                ("SO_SECURITY_ENCRYPTION_NETWORK", V::Dec(24)),
                ("SO_SECURITY_ENCRYPTION_TRANSPORT", V::Dec(23)),
                ("SO_SELECT_ERR_QUEUE", V::Dec(45)),
                ("SO_SNDBUF", V::Dec(7)),
                ("SO_SNDBUFFORCE", V::Dec(32)),
                ("SO_SNDLOWAT", V::Dec(19)),
                ("SO_SNDTIMEO", V::Dec(21)),
                ("SO_SNDTIMEO_NEW", V::Dec(67)),
                ("SO_SNDTIMEO_OLD", V::Dec(21)),
                ("SO_TIMESTAMP", V::Dec(29)),
                ("SO_TIMESTAMPING", V::Dec(37)),
                ("SO_TIMESTAMPING_NEW", V::Dec(65)),
                ("SO_TIMESTAMPING_OLD", V::Dec(37)),
                ("SO_TIMESTAMPNS", V::Dec(35)),
                ("SO_TIMESTAMPNS_NEW", V::Dec(64)),
                ("SO_TIMESTAMPNS_OLD", V::Dec(35)),
                ("SO_TIMESTAMP_NEW", V::Dec(63)),
                ("SO_TIMESTAMP_OLD", V::Dec(29)),
                ("SO_TXREHASH", V::Dec(74)),
                ("SO_TXTIME", V::Dec(61)),
                ("SO_TYPE", V::Dec(3)),
                ("SO_WIFI_STATUS", V::Dec(41)),
                ("SO_ZEROCOPY", V::Dec(60)),
            ]),
            Item::Blank,
            Item::Block { head: "struct sockaddr ", body: &["", "  sa_family_t sa_family;", "  char sa_data[14];", ""], tail: "" },
            Item::Blank,
            Item::Consts(&[
                ("_SS_SIZE", V::Dec(128)),
            ]),
            Item::Typedef("unsigned long int", "__ss_aligntype"),
            Item::Consts(&[
                ("_SS_PADSIZE", V::Txt("(_SS_SIZE - __SOCKADDR_COMMON_SIZE - sizeof (__ss_aligntype))")),
            ]),
            Item::Block { head: "struct sockaddr_storage ", body: &["", "  __SOCKADDR_COMMON (ss_);", "  char __ss_padding[_SS_PADSIZE];", "  __ss_aligntype __ss_align;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct osockaddr ", body: &["", "  unsigned short int sa_family;", "  unsigned char sa_data[14];", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct msghdr ", body: &["", "  void *msg_name;", "  socklen_t msg_namelen;", "  struct iovec *msg_iov;", "  size_t msg_iovlen;", "  void *msg_control;", "  size_t msg_controllen;", "  int msg_flags;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct cmsghdr ", body: &["", "  size_t cmsg_len;", "  int cmsg_level;", "  int cmsg_type;", "  __extension__ unsigned char __cmsg_data[];", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct mmsghdr ", body: &["", "  struct msghdr msg_hdr;", "  unsigned int msg_len;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct linger ", body: &["", "  int l_onoff;", "  int l_linger;", ""], tail: "" },
            Item::Blank,
            Item::Block { head: "struct ucred ", body: &["", "  pid_t pid;", "  uid_t uid;", "  gid_t gid;", ""], tail: "" },
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define CMSG_DATA(cmsg) ((cmsg)->__cmsg_data)"),
            Item::Raw(Reason::StdMacro, "#define CMSG_NXTHDR(mhdr, cmsg) __cmsg_nxthdr (mhdr, cmsg)"),
            Item::Raw(Reason::StdMacro, r#"#define CMSG_FIRSTHDR(mhdr) \
  ((size_t) (mhdr)->msg_controllen >= sizeof (struct cmsghdr) \
   ? (struct cmsghdr *) (mhdr)->msg_control : (struct cmsghdr *) 0)"#),
            Item::Raw(Reason::StdMacro, "#define CMSG_ALIGN(len) (((len) + sizeof (size_t) - 1) & (size_t) ~(sizeof (size_t) - 1))"),
            Item::Raw(Reason::StdMacro, "#define CMSG_SPACE(len) (CMSG_ALIGN (len) + CMSG_ALIGN (sizeof (struct cmsghdr)))"),
            Item::Raw(Reason::StdMacro, "#define CMSG_LEN(len) (CMSG_ALIGN (sizeof (struct cmsghdr)) + (len))"),
            Item::Blank,
            Item::Include("<bits/rlibc-net-sock.h>"),
            Item::Gate(&[
                Branch { head: "if __USE_FORTIFY_LEVEL > 0 && defined __fortify_function", items: &[
                    Item::Raw(Reason::GlibcMacro, "# define __SOCKADDR_ARG struct sockaddr *__restrict"),
                    Item::Raw(Reason::GlibcMacro, "# define __CONST_SOCKADDR_ARG const struct sockaddr *"),
                    Item::Include("<bits/socket2.h>"),
                ] },
            ], ""),
        ]},
    ],
};
