use crate::model::*;

pub static HDR: Header = Header {
    path: "sys/syslog.h",
    items: &[
        Item::Guard { name: "_RLIBC_SYS_SYSLOG_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<stdarg.h>"),
            Item::Include("<stddef.h>"),
            Item::Include("<bits/rlibc-features.h>"),
            Item::Blank,
            Item::Consts(&[
                ("_PATH_LOG", V::Txt(r#""/dev/log""#)),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("LOG_EMERG", V::Dec(0)),
                ("LOG_ALERT", V::Dec(1)),
                ("LOG_CRIT", V::Dec(2)),
                ("LOG_ERR", V::Dec(3)),
                ("LOG_WARNING", V::Dec(4)),
                ("LOG_NOTICE", V::Dec(5)),
                ("LOG_INFO", V::Dec(6)),
                ("LOG_DEBUG", V::Dec(7)),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("LOG_PRIMASK", V::Txt("0x07")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define LOG_PRI(p) ((p) & LOG_PRIMASK)"),
            Item::Raw(Reason::GlibcMacro, "#define LOG_MAKEPRI(fac, pri) ((fac) | (pri))"),
            Item::Blank,
            Item::Consts(&[
                ("LOG_KERN", V::Txt("(0 << 3)")),
                ("LOG_USER", V::Txt("(1 << 3)")),
                ("LOG_MAIL", V::Txt("(2 << 3)")),
                ("LOG_DAEMON", V::Txt("(3 << 3)")),
                ("LOG_AUTH", V::Txt("(4 << 3)")),
                ("LOG_SYSLOG", V::Txt("(5 << 3)")),
                ("LOG_LPR", V::Txt("(6 << 3)")),
                ("LOG_NEWS", V::Txt("(7 << 3)")),
                ("LOG_UUCP", V::Txt("(8 << 3)")),
                ("LOG_CRON", V::Txt("(9 << 3)")),
                ("LOG_AUTHPRIV", V::Txt("(10 << 3)")),
                ("LOG_FTP", V::Txt("(11 << 3)")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("LOG_LOCAL0", V::Txt("(16 << 3)")),
                ("LOG_LOCAL1", V::Txt("(17 << 3)")),
                ("LOG_LOCAL2", V::Txt("(18 << 3)")),
                ("LOG_LOCAL3", V::Txt("(19 << 3)")),
                ("LOG_LOCAL4", V::Txt("(20 << 3)")),
                ("LOG_LOCAL5", V::Txt("(21 << 3)")),
                ("LOG_LOCAL6", V::Txt("(22 << 3)")),
                ("LOG_LOCAL7", V::Txt("(23 << 3)")),
            ]),
            Item::Blank,
            Item::Consts(&[
                ("LOG_NFACILITIES", V::Dec(24)),
                ("LOG_FACMASK", V::Txt("0x03f8")),
            ]),
            Item::Raw(Reason::GlibcMacro, "#define LOG_FAC(p) (((p) & LOG_FACMASK) >> 3)"),
            Item::Blank,
            Item::Raw(Reason::GlibcMacro, "#define LOG_MASK(pri) (1 << (pri))"),
            Item::Raw(Reason::GlibcMacro, "#define LOG_UPTO(pri) ((1 << ((pri) + 1)) - 1)"),
            Item::Blank,
            Item::Consts(&[
                ("LOG_PID", V::Txt("0x01")),
                ("LOG_CONS", V::Txt("0x02")),
                ("LOG_ODELAY", V::Txt("0x04")),
                ("LOG_NDELAY", V::Txt("0x08")),
                ("LOG_NOWAIT", V::Hex(0x10)),
                ("LOG_PERROR", V::Hex(0x20)),
            ]),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef SYSLOG_NAMES", items: &[
                    Item::Consts(&[
                        ("INTERNAL_NOPRI", V::Hex(0x10)),
                        ("INTERNAL_MARK", V::Txt("(LOG_NFACILITIES << 3)")),
                    ]),
                    Item::Block { head: "typedef struct _code ", body: &["", "  const char *c_name;", "  int c_val;", ""], tail: " CODE" },
                    Item::Blank,
                    Item::Decl(r#"CODE prioritynames[] = {
  {"alert", LOG_ALERT},
  {"crit", LOG_CRIT},
  {"debug", LOG_DEBUG},
  {"emerg", LOG_EMERG},
  {"err", LOG_ERR},
  {"error", LOG_ERR},
  {"info", LOG_INFO},
  {"none", INTERNAL_NOPRI},
  {"notice", LOG_NOTICE},
  {"panic", LOG_EMERG},
  {"warn", LOG_WARNING},
  {"warning", LOG_WARNING},
  {NULL, -1}
};"#),
                    Item::Blank,
                    Item::Decl(r#"CODE facilitynames[] = {
  {"auth", LOG_AUTH},
  {"authpriv", LOG_AUTHPRIV},
  {"cron", LOG_CRON},
  {"daemon", LOG_DAEMON},
  {"ftp", LOG_FTP},
  {"kern", LOG_KERN},
  {"lpr", LOG_LPR},
  {"mail", LOG_MAIL},
  {"mark", INTERNAL_MARK},
  {"news", LOG_NEWS},
  {"security", LOG_AUTH},
  {"syslog", LOG_SYSLOG},
  {"user", LOG_USER},
  {"uucp", LOG_UUCP},
  {"local0", LOG_LOCAL0},
  {"local1", LOG_LOCAL1},
  {"local2", LOG_LOCAL2},
  {"local3", LOG_LOCAL3},
  {"local4", LOG_LOCAL4},
  {"local5", LOG_LOCAL5},
  {"local6", LOG_LOCAL6},
  {"local7", LOG_LOCAL7},
  {NULL, -1}
};"#),
                ] },
            ], ""),
            Item::Blank,
            Item::ExternBegin,
            Item::Include("<bits/rlibc-syslogcalls.h>"),
            Item::ExternEnd,
            Item::Blank,
        ]},
    ],
};
