use crate::model::*;

pub static HDR: Header = Header {
    path: "tar.h",
    items: &[
        Item::Guard { name: "_TAR_H", value: "1", end: "", items: &[
            Item::Include("<features.h>"),
            Item::ExternBegin,
            Item::Consts(&[
                ("AREGTYPE", V::Txt(r#"'\0'"#)),
                ("BLKTYPE", V::Txt("'4'")),
                ("CHRTYPE", V::Txt("'3'")),
                ("CONTTYPE", V::Txt("'7'")),
                ("DIRTYPE", V::Txt("'5'")),
                ("FIFOTYPE", V::Txt("'6'")),
                ("LNKTYPE", V::Txt("'1'")),
                ("REGTYPE", V::Txt("'0'")),
                ("SYMTYPE", V::Txt("'2'")),
                ("TGEXEC", V::Txt("00010")),
                ("TGREAD", V::Txt("00040")),
                ("TGWRITE", V::Txt("00020")),
                ("TMAGIC", V::Txt(r#""ustar""#)),
                ("TMAGLEN", V::Dec(6)),
                ("TOEXEC", V::Txt("00001")),
                ("TOREAD", V::Txt("00004")),
                ("TOWRITE", V::Txt("00002")),
                ("TSGID", V::Txt("02000")),
                ("TSUID", V::Txt("04000")),
                ("TSVTX", V::Txt("01000")),
                ("TUEXEC", V::Txt("00100")),
                ("TUREAD", V::Txt("00400")),
                ("TUWRITE", V::Txt("00200")),
                ("TVERSION", V::Txt(r#""00""#)),
                ("TVERSLEN", V::Dec(2)),
                ("_ATFILE_SOURCE", V::Dec(1)),
                ("_DEFAULT_SOURCE", V::Dec(1)),
                ("_DYNAMIC_STACK_SIZE_SOURCE", V::Dec(1)),
                ("_ISOC11_SOURCE", V::Dec(1)),
                ("_ISOC23_SOURCE", V::Dec(1)),
                ("_ISOC2Y_SOURCE", V::Dec(1)),
                ("_ISOC95_SOURCE", V::Dec(1)),
                ("_ISOC99_SOURCE", V::Dec(1)),
                ("_LARGEFILE64_SOURCE", V::Dec(1)),
                ("_LARGEFILE_SOURCE", V::Dec(1)),
                ("_POSIX_C_SOURCE", V::Txt("202405L")),
                ("_POSIX_SOURCE", V::Dec(1)),
                ("_XOPEN_SOURCE", V::Dec(800)),
                ("_XOPEN_SOURCE_EXTENDED", V::Dec(1)),
            ]),
            Item::ExternEnd,
        ]},
    ],
};
