use crate::model::*;

pub static HDR: Header = Header {
    path: "tgmath.h",
    items: &[
        Item::Guard { name: "_TGMATH_H", value: "1", end: "", items: &[
            Item::Blank,
            Item::Include("<features.h>"),
            Item::Include("<math.h>"),
            Item::Include("<complex.h>"),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "if __GLIBC_USE_ISOC23", items: &[
                    Item::Consts(&[
                        ("__STDC_VERSION_TGMATH_H__", V::Txt("202311L")),
                    ]),
                ] },
            ], ""),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "if !defined __GNUC__ || (__GNUC__ < 8)", items: &[
                    Item::Raw(Reason::Other, r#"# error "Unsupported compiler; you cannot use <tgmath.h>""#),
                ] },
            ], ""),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_FLOATN", items: &[
                    Item::Raw(Reason::StdMacro, "# define __TG_FN_ARGS(X) X ## f32, X ## f64, X ## f32x, X ## f64x,"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::StdMacro, "# define __TG_FN_ARGS(X)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_FUNCS(X) X ## f, X, X ## l, __TG_FN_ARGS (X)"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_RCFUNCS(F, C) __TGMATH_FUNCS (F) __TGMATH_FUNCS (C)"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_1(F, X) __builtin_tgmath (__TGMATH_FUNCS (F) (X))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_2(F, X, Y) __builtin_tgmath (__TGMATH_FUNCS (F) (X), (Y))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_2STD(F, X, Y) __builtin_tgmath (F ## f, F, F ## l, (X), (Y))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_3(F, X, Y, Z) __builtin_tgmath (__TGMATH_FUNCS (F) (X), (Y), (Z))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_1C(F, C, X) __builtin_tgmath (__TGMATH_RCFUNCS (F, C) (X))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_2C(F, C, X, Y) __builtin_tgmath (__TGMATH_RCFUNCS (F, C) (X), (Y))"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define __TGMATH_NARROW_FUNCS_F(X) X, X ## l,"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_1_NARROW_F(F, X) __builtin_tgmath (__TGMATH_NARROW_FUNCS_F (F) (X))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_2_NARROW_F(F, X, Y) __builtin_tgmath (__TGMATH_NARROW_FUNCS_F (F) (X), (Y))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_3_NARROW_F(F, X, Y, Z) __builtin_tgmath (__TGMATH_NARROW_FUNCS_F (F) (X), (Y), (Z))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_1_NARROW_D(F, X) (F ## l (X))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_2_NARROW_D(F, X, Y) (F ## l (X, Y))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_3_NARROW_D(F, X, Y, Z) (F ## l (X, Y, Z))"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_REAL_ONLY(Val, Fct) __TGMATH_1 (Fct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_REAL_RET_ONLY(Val, Fct) __TGMATH_1 (Fct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_BINARY_FIRST_REAL_ONLY(Val1, Val2, Fct) __TGMATH_2 (Fct, (Val1), (Val2))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_BINARY_FIRST_REAL_STD_ONLY(Val1, Val2, Fct) __TGMATH_2STD (Fct, (Val1), (Val2))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_BINARY_REAL_ONLY(Val1, Val2, Fct) __TGMATH_2 (Fct, (Val1), (Val2))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_BINARY_REAL_STD_ONLY(Val1, Val2, Fct) __TGMATH_2STD (Fct, (Val1), (Val2))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_TERNARY_FIRST_SECOND_REAL_ONLY(Val1, Val2, Val3, Fct) __TGMATH_3 (Fct, (Val1), (Val2), (Val3))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_TERNARY_REAL_ONLY(Val1, Val2, Val3, Fct) __TGMATH_3 (Fct, (Val1), (Val2), (Val3))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_TERNARY_FIRST_REAL_ONLY(Val1, Val2, Val3, Fct) __TGMATH_3 (Fct, (Val1), (Val2), (Val3))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_REAL_IMAG(Val, Fct, Cfct) __TGMATH_1C (Fct, Cfct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_IMAG(Val, Cfct) __TGMATH_1 (Cfct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_REAL_IMAG_RET_REAL(Val, Fct, Cfct) __TGMATH_1C (Fct, Cfct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_UNARY_REAL_IMAG_RET_REAL_SAME(Val, Cfct) __TGMATH_1 (Cfct, (Val))"),
            Item::Raw(Reason::StdMacro, "#define __TGMATH_BINARY_REAL_IMAG(Val1, Val2, Fct, Cfct) __TGMATH_2C (Fct, Cfct, (Val1), (Val2))"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define acos(Val) __TGMATH_UNARY_REAL_IMAG (Val, acos, cacos)"),
            Item::Raw(Reason::StdMacro, "#define asin(Val) __TGMATH_UNARY_REAL_IMAG (Val, asin, casin)"),
            Item::Raw(Reason::StdMacro, "#define atan(Val) __TGMATH_UNARY_REAL_IMAG (Val, atan, catan)"),
            Item::Raw(Reason::StdMacro, "#define atan2(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, atan2)"),
            Item::Raw(Reason::StdMacro, "#define cos(Val) __TGMATH_UNARY_REAL_IMAG (Val, cos, ccos)"),
            Item::Raw(Reason::StdMacro, "#define sin(Val) __TGMATH_UNARY_REAL_IMAG (Val, sin, csin)"),
            Item::Raw(Reason::StdMacro, "#define tan(Val) __TGMATH_UNARY_REAL_IMAG (Val, tan, ctan)"),
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define acospi(Val) __TGMATH_UNARY_REAL_ONLY (Val, acospi)"),
                    Item::Raw(Reason::StdMacro, "# define asinpi(Val) __TGMATH_UNARY_REAL_ONLY (Val, asinpi)"),
                    Item::Raw(Reason::StdMacro, "# define atanpi(Val) __TGMATH_UNARY_REAL_ONLY (Val, atanpi)"),
                    Item::Raw(Reason::StdMacro, "# define atan2pi(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, atan2pi)"),
                    Item::Raw(Reason::StdMacro, "# define cospi(Val) __TGMATH_UNARY_REAL_ONLY (Val, cospi)"),
                    Item::Raw(Reason::StdMacro, "# define sinpi(Val) __TGMATH_UNARY_REAL_ONLY (Val, sinpi)"),
                    Item::Raw(Reason::StdMacro, "# define tanpi(Val) __TGMATH_UNARY_REAL_ONLY (Val, tanpi)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define acosh(Val) __TGMATH_UNARY_REAL_IMAG (Val, acosh, cacosh)"),
            Item::Raw(Reason::StdMacro, "#define asinh(Val) __TGMATH_UNARY_REAL_IMAG (Val, asinh, casinh)"),
            Item::Raw(Reason::StdMacro, "#define atanh(Val) __TGMATH_UNARY_REAL_IMAG (Val, atanh, catanh)"),
            Item::Raw(Reason::StdMacro, "#define cosh(Val) __TGMATH_UNARY_REAL_IMAG (Val, cosh, ccosh)"),
            Item::Raw(Reason::StdMacro, "#define sinh(Val) __TGMATH_UNARY_REAL_IMAG (Val, sinh, csinh)"),
            Item::Raw(Reason::StdMacro, "#define tanh(Val) __TGMATH_UNARY_REAL_IMAG (Val, tanh, ctanh)"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define exp(Val) __TGMATH_UNARY_REAL_IMAG (Val, exp, cexp)"),
            Item::Raw(Reason::StdMacro, "#define frexp(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, frexp)"),
            Item::Raw(Reason::StdMacro, "#define ldexp(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, ldexp)"),
            Item::Raw(Reason::StdMacro, "#define log(Val) __TGMATH_UNARY_REAL_IMAG (Val, log, clog)"),
            Item::Gate(&[
                Branch { head: "ifdef __USE_GNU", items: &[
                    Item::Raw(Reason::StdMacro, "# define log10(Val) __TGMATH_UNARY_REAL_IMAG (Val, log10, clog10)"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::StdMacro, "# define log10(Val) __TGMATH_UNARY_REAL_ONLY (Val, log10)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define expm1(Val) __TGMATH_UNARY_REAL_ONLY (Val, expm1)"),
            Item::Raw(Reason::StdMacro, "#define log1p(Val) __TGMATH_UNARY_REAL_ONLY (Val, log1p)"),
            Item::Raw(Reason::StdMacro, "#define logb(Val) __TGMATH_UNARY_REAL_ONLY (Val, logb)"),
            Item::Raw(Reason::StdMacro, "#define exp2(Val) __TGMATH_UNARY_REAL_ONLY (Val, exp2)"),
            Item::Raw(Reason::StdMacro, "#define log2(Val) __TGMATH_UNARY_REAL_ONLY (Val, log2)"),
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define exp10(Val) __TGMATH_UNARY_REAL_ONLY (Val, exp10)"),
                    Item::Raw(Reason::StdMacro, "# define exp2m1(Val) __TGMATH_UNARY_REAL_ONLY (Val, exp2m1)"),
                    Item::Raw(Reason::StdMacro, "# define exp10m1(Val) __TGMATH_UNARY_REAL_ONLY (Val, exp10m1)"),
                    Item::Raw(Reason::StdMacro, "# define log2p1(Val) __TGMATH_UNARY_REAL_ONLY (Val, log2p1)"),
                    Item::Raw(Reason::StdMacro, "# define log10p1(Val) __TGMATH_UNARY_REAL_ONLY (Val, log10p1)"),
                    Item::Raw(Reason::StdMacro, "# define logp1(Val) __TGMATH_UNARY_REAL_ONLY (Val, logp1)"),
                ] },
            ], ""),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define pow(Val1, Val2) __TGMATH_BINARY_REAL_IMAG (Val1, Val2, pow, cpow)"),
            Item::Raw(Reason::StdMacro, "#define sqrt(Val) __TGMATH_UNARY_REAL_IMAG (Val, sqrt, csqrt)"),
            Item::Raw(Reason::StdMacro, "#define hypot(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, hypot)"),
            Item::Raw(Reason::StdMacro, "#define cbrt(Val) __TGMATH_UNARY_REAL_ONLY (Val, cbrt)"),
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define compoundn(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, compoundn)"),
                    Item::Raw(Reason::StdMacro, "# define pown(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, pown)"),
                    Item::Raw(Reason::StdMacro, "# define powr(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, powr)"),
                    Item::Raw(Reason::StdMacro, "# define rootn(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, rootn)"),
                    Item::Raw(Reason::StdMacro, "# define rsqrt(Val) __TGMATH_UNARY_REAL_ONLY (Val, rsqrt)"),
                ] },
            ], ""),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define ceil(Val) __TGMATH_UNARY_REAL_ONLY (Val, ceil)"),
            Item::Raw(Reason::StdMacro, "#define fabs(Val) __TGMATH_UNARY_REAL_IMAG_RET_REAL (Val, fabs, cabs)"),
            Item::Raw(Reason::StdMacro, "#define floor(Val) __TGMATH_UNARY_REAL_ONLY (Val, floor)"),
            Item::Raw(Reason::StdMacro, "#define fmod(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmod)"),
            Item::Raw(Reason::StdMacro, "#define nearbyint(Val) __TGMATH_UNARY_REAL_ONLY (Val, nearbyint)"),
            Item::Raw(Reason::StdMacro, "#define round(Val) __TGMATH_UNARY_REAL_ONLY (Val, round)"),
            Item::Raw(Reason::StdMacro, "#define trunc(Val) __TGMATH_UNARY_REAL_ONLY (Val, trunc)"),
            Item::Raw(Reason::StdMacro, "#define remquo(Val1, Val2, Val3) __TGMATH_TERNARY_FIRST_SECOND_REAL_ONLY (Val1, Val2, Val3, remquo)"),
            Item::Raw(Reason::StdMacro, "#define lrint(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, lrint)"),
            Item::Raw(Reason::StdMacro, "#define llrint(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, llrint)"),
            Item::Raw(Reason::StdMacro, "#define lround(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, lround)"),
            Item::Raw(Reason::StdMacro, "#define llround(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, llround)"),
            Item::Raw(Reason::StdMacro, "#define copysign(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, copysign)"),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define erf(Val) __TGMATH_UNARY_REAL_ONLY (Val, erf)"),
            Item::Raw(Reason::StdMacro, "#define erfc(Val) __TGMATH_UNARY_REAL_ONLY (Val, erfc)"),
            Item::Raw(Reason::StdMacro, "#define tgamma(Val) __TGMATH_UNARY_REAL_ONLY (Val, tgamma)"),
            Item::Raw(Reason::StdMacro, "#define lgamma(Val) __TGMATH_UNARY_REAL_ONLY (Val, lgamma)"),
            Item::Raw(Reason::StdMacro, "#define rint(Val) __TGMATH_UNARY_REAL_ONLY (Val, rint)"),
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define nextdown(Val) __TGMATH_UNARY_REAL_ONLY (Val, nextdown)"),
                    Item::Raw(Reason::StdMacro, "# define nextup(Val) __TGMATH_UNARY_REAL_ONLY (Val, nextup)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define nextafter(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, nextafter)"),
            Item::Raw(Reason::StdMacro, "#define nexttoward(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_STD_ONLY (Val1, Val2, nexttoward)"),
            Item::Raw(Reason::StdMacro, "#define remainder(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, remainder)"),
            Item::Gate(&[
                Branch { head: "ifdef __USE_MISC", items: &[
                    Item::Raw(Reason::StdMacro, "# define scalb(Val1, Val2) __TGMATH_BINARY_REAL_STD_ONLY (Val1, Val2, scalb)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define scalbn(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, scalbn)"),
            Item::Raw(Reason::StdMacro, "#define scalbln(Val1, Val2) __TGMATH_BINARY_FIRST_REAL_ONLY (Val1, Val2, scalbln)"),
            Item::Raw(Reason::StdMacro, "#define ilogb(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, ilogb)"),
            Item::Raw(Reason::StdMacro, "#define fdim(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fdim)"),
            Item::Gate(&[
                Branch { head: "if __GLIBC_USE_ISOC23 && !defined __USE_GNU", items: &[
                    Item::Raw(Reason::StdMacro, "# define fmax(Val1, Val2) __TGMATH_BINARY_REAL_STD_ONLY (Val1, Val2, fmax)"),
                    Item::Raw(Reason::StdMacro, "# define fmin(Val1, Val2) __TGMATH_BINARY_REAL_STD_ONLY (Val1, Val2, fmin)"),
                ] },
                Branch { head: "else", items: &[
                    Item::Raw(Reason::StdMacro, "# define fmax(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmax)"),
                    Item::Raw(Reason::StdMacro, "# define fmin(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmin)"),
                ] },
            ], ""),
            Item::Raw(Reason::StdMacro, "#define fma(Val1, Val2, Val3) __TGMATH_TERNARY_REAL_ONLY (Val1, Val2, Val3, fma)"),
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define roundeven(Val) __TGMATH_UNARY_REAL_ONLY (Val, roundeven)"),
                    Item::Raw(Reason::StdMacro, "# define fromfp(Val1, Val2, Val3) __TGMATH_TERNARY_FIRST_REAL_ONLY (Val1, Val2, Val3, fromfp)"),
                    Item::Raw(Reason::StdMacro, "# define ufromfp(Val1, Val2, Val3) __TGMATH_TERNARY_FIRST_REAL_ONLY (Val1, Val2, Val3, ufromfp)"),
                    Item::Raw(Reason::StdMacro, "# define fromfpx(Val1, Val2, Val3) __TGMATH_TERNARY_FIRST_REAL_ONLY (Val1, Val2, Val3, fromfpx)"),
                    Item::Raw(Reason::StdMacro, "# define ufromfpx(Val1, Val2, Val3) __TGMATH_TERNARY_FIRST_REAL_ONLY (Val1, Val2, Val3, ufromfpx)"),
                    Item::Raw(Reason::StdMacro, "# define llogb(Val) __TGMATH_UNARY_REAL_RET_ONLY (Val, llogb)"),
                    Item::Raw(Reason::StdMacro, "# define fmaxmag(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmaxmag)"),
                    Item::Raw(Reason::StdMacro, "# define fminmag(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fminmag)"),
                ] },
            ], ""),
            Item::Gate(&[
                Branch { head: "if __GLIBC_USE_ISOC23", items: &[
                    Item::Raw(Reason::StdMacro, "# define fmaximum(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmaximum)"),
                    Item::Raw(Reason::StdMacro, "# define fminimum(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fminimum)"),
                    Item::Raw(Reason::StdMacro, "# define fmaximum_num(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmaximum_num)"),
                    Item::Raw(Reason::StdMacro, "# define fminimum_num(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fminimum_num)"),
                    Item::Raw(Reason::StdMacro, "# define fmaximum_mag(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmaximum_mag)"),
                    Item::Raw(Reason::StdMacro, "# define fminimum_mag(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fminimum_mag)"),
                    Item::Raw(Reason::StdMacro, "# define fmaximum_mag_num(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fmaximum_mag_num)"),
                    Item::Raw(Reason::StdMacro, "# define fminimum_mag_num(Val1, Val2) __TGMATH_BINARY_REAL_ONLY (Val1, Val2, fminimum_mag_num)"),
                ] },
            ], ""),
            Item::Blank,
            Item::Raw(Reason::StdMacro, "#define carg(Val) __TGMATH_UNARY_REAL_IMAG_RET_REAL_SAME (Val, carg)"),
            Item::Raw(Reason::StdMacro, "#define conj(Val) __TGMATH_UNARY_IMAG (Val, conj)"),
            Item::Raw(Reason::StdMacro, "#define cproj(Val) __TGMATH_UNARY_IMAG (Val, cproj)"),
            Item::Raw(Reason::StdMacro, "#define cimag(Val) __TGMATH_UNARY_REAL_IMAG_RET_REAL_SAME (Val, cimag)"),
            Item::Raw(Reason::StdMacro, "#define creal(Val) __TGMATH_UNARY_REAL_IMAG_RET_REAL_SAME (Val, creal)"),
            Item::Blank,
            Item::Gate(&[
                Branch { head: "ifdef __RLIBC_MATH_EXT", items: &[
                    Item::Raw(Reason::StdMacro, "# define fadd(Val1, Val2) __TGMATH_2_NARROW_F (fadd, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define dadd(Val1, Val2) __TGMATH_2_NARROW_D (dadd, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define fdiv(Val1, Val2) __TGMATH_2_NARROW_F (fdiv, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define ddiv(Val1, Val2) __TGMATH_2_NARROW_D (ddiv, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define fmul(Val1, Val2) __TGMATH_2_NARROW_F (fmul, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define dmul(Val1, Val2) __TGMATH_2_NARROW_D (dmul, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define fsub(Val1, Val2) __TGMATH_2_NARROW_F (fsub, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define dsub(Val1, Val2) __TGMATH_2_NARROW_D (dsub, Val1, Val2)"),
                    Item::Raw(Reason::StdMacro, "# define fsqrt(Val) __TGMATH_1_NARROW_F (fsqrt, Val)"),
                    Item::Raw(Reason::StdMacro, "# define dsqrt(Val) __TGMATH_1_NARROW_D (dsqrt, Val)"),
                    Item::Raw(Reason::StdMacro, "# define ffma(Val1, Val2, Val3) __TGMATH_3_NARROW_F (ffma, Val1, Val2, Val3)"),
                    Item::Raw(Reason::StdMacro, "# define dfma(Val1, Val2, Val3) __TGMATH_3_NARROW_D (dfma, Val1, Val2, Val3)"),
                ] },
            ], ""),
            Item::Blank,
        ]},
    ],
};
