[package]
name = "rusty-libc-util"
version = "0.0.0"
edition.workspace = true
license.workspace = true

[dependencies]
rusty-libc-core = { path = "../rusty-libc-core" }
rusty-libc-mem = { path = "../rusty-libc-mem" }
rusty-libc-malloc = { path = "../rusty-libc-malloc" }
rusty-libc-ctype = { path = "../rusty-libc-ctype" }
rusty-libc-stdlib = { path = "../rusty-libc-stdlib" }
rusty-libc-wchar = { path = "../rusty-libc-wchar" }
rusty-libc-locale = { path = "../rusty-libc-locale" }
rusty-libc-stdio = { path = "../rusty-libc-stdio" }

[features]
export = []
