#!/usr/bin/env python3
import os
import struct
import subprocess
import sys
import tempfile

C_SRC = r"""
#define _GNU_SOURCE
#include <stdio.h>
#include <stdint.h>
#include <wchar.h>
#include <wctype.h>
#include <locale.h>
int main(void) {
    if (!setlocale(LC_ALL, "C.UTF-8")) { fprintf(stderr, "C.UTF-8 locale missing\n"); return 1; }
    wctype_t comb = wctype("combining"), comb3 = wctype("combining_level3");
    wctrans_t title = wctrans("totitle");
    for (long c = 0; c <= 0x10ffff; c++) {
        wint_t w = (wint_t)c;
        uint32_t m = (!!iswalnum(w)) | (!!iswalpha(w)) << 1 | (!!iswblank(w)) << 2 | (!!iswcntrl(w)) << 3
            | (!!iswdigit(w)) << 4 | (!!iswgraph(w)) << 5 | (!!iswlower(w)) << 6 | (!!iswprint(w)) << 7
            | (!!iswpunct(w)) << 8 | (!!iswspace(w)) << 9 | (!!iswupper(w)) << 10 | (!!iswxdigit(w)) << 11
            | (!!iswctype(w, comb)) << 12 | (!!iswctype(w, comb3)) << 13;
        int wd = wcwidth((wchar_t)c);
        uint32_t wc = wd < 0 ? 3 : (uint32_t)wd;
        if (wc > 3) { fprintf(stderr, "width %d\n", wd); return 1; }
        m |= wc << 14;
        int32_t up = (int32_t)towupper(w) - (int32_t)c;
        int32_t lo = (int32_t)towlower(w) - (int32_t)c;
        int32_t ti = (int32_t)towctrans(w, title) - (int32_t)c;
        fwrite(&m, 4, 1, stdout); fwrite(&up, 4, 1, stdout); fwrite(&lo, 4, 1, stdout); fwrite(&ti, 4, 1, stdout);
    }
    return 0;
}
"""


def host_data():
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "dump.c")
        exe = os.path.join(d, "dump")
        with open(src, "w") as f:
            f.write(C_SRC)
        subprocess.check_call(["gcc", "-O1", src, "-o", exe])
        out = subprocess.check_output([exe])
    n = 0x110000
    vals = struct.unpack("<%dI" % (n * 4), out)
    props = [vals[4 * i] for i in range(n)]
    up = [struct.unpack("<i", struct.pack("<I", vals[4 * i + 1]))[0] for i in range(n)]
    lo = [struct.unpack("<i", struct.pack("<I", vals[4 * i + 2]))[0] for i in range(n)]
    ti = [struct.unpack("<i", struct.pack("<I", vals[4 * i + 3]))[0] for i in range(n)]
    return props, up, lo, ti


def two_stage(values, elem_bytes):
    best = None
    for shift in range(4, 10):
        size = 1 << shift
        blocks = {}
        order = []
        index = []
        for start in range(0, len(values), size):
            blk = tuple(values[start:start + size])
            if blk not in blocks:
                blocks[blk] = len(order)
                order.append(blk)
            index.append(blocks[blk])
        idx_bytes = 1 if len(order) <= 256 else 2
        total = len(index) * idx_bytes + len(order) * size * elem_bytes
        if best is None or total < best[0]:
            best = (total, shift, index, order, idx_bytes)
    return best


def emit(name, values, rust_type, elem_bytes, out):
    total, shift, index, order, idx_bytes = two_stage(values, elem_bytes)
    idx_type = "u8" if idx_bytes == 1 else "u16"
    out.write("pub const %s_SHIFT: u32 = %d;\n" % (name, shift))
    out.write("pub static %s_INDEX: [%s; %d] = [\n" % (name, idx_type, len(index)))
    for i in range(0, len(index), 24):
        out.write("    " + ", ".join(str(x) for x in index[i:i + 24]) + ",\n")
    out.write("];\n")
    flat = [v for blk in order for v in blk]
    out.write("pub static %s_DATA: [%s; %d] = [\n" % (name, rust_type, len(flat)))
    for i in range(0, len(flat), 16):
        out.write("    " + ", ".join(str(x) for x in flat[i:i + 16]) + ",\n")
    out.write("];\n\n")
    sys.stderr.write("%s: block %d, %d blocks, %d bytes\n" % (name, 1 << shift, len(order), total))


def main():
    props, up, lo, ti = host_data()
    out = sys.stdout
    out.write("// @generated by tools/gen_tables.py from the behaviour of the host glibc (C.UTF-8); do not edit.\n")
    out.write("// Property word: bits 0..=11 alnum alpha blank cntrl digit graph lower print punct space upper xdigit,\n")
    out.write("// bit 12 combining, bit 13 combining_level3, bits 14..=15 width (0, 1, 2; 3 means -1).\n")
    out.write("// Case tables hold (mapped - code point) as i32. Code points above 0x10FFFF have no entry.\n\n")
    emit("PROPS", props, "u16", 2, out)
    emit("UPPER", up, "i32", 4, out)
    emit("LOWER", lo, "i32", 4, out)
    emit("TITLE", ti, "i32", 4, out)


if __name__ == "__main__":
    main()
