#!/usr/bin/env python3
from fractions import Fraction

P = 200


def icbrt(n):
    x = 1 << ((n.bit_length() + 2) // 3 + 1)
    while True:
        y = (2 * x + n // (x * x)) // 3
        if y >= x:
            break
        x = y
    while x * x * x > n:
        x -= 1
    while (x + 1) ** 3 <= n:
        x += 1
    return x


def cbrt_frac(c):
    n = (c.numerator << (3 * P)) // c.denominator
    return Fraction(icbrt(n), 1 << P)


def binom13(k):
    r = Fraction(1)
    for i in range(k):
        r = r * (Fraction(1, 3) - i) / (i + 1)
    return r


def lit(x):
    r = repr(x)
    if "e" not in r and "." not in r:
        r += ".0"
    return r


print("//! Constant table for cbrt_impl.rs. GENERATED by gen_cbrt.py (same directory) from exact")
print("//! integer arithmetic; derived data, nothing copied from another library. Do not edit.")
print("#![allow(clippy::excessive_precision, clippy::unreadable_literal, clippy::approx_constant)]")
print()
print("/// [c_j, g0, ..., g5]: cbrt(c_j + d) = g0 + g1 d + ... + g5 d^5 on [1 + j/128, 1 + (j + 1)/128).")
print("pub const CBRTF_ROWS: [[f64; 7]; 128] = [")
for j in range(128):
    c = Fraction(257 + 2 * j, 256)
    y = cbrt_frac(c)
    g = [float(binom13(k) * y / c**k) for k in range(6)]
    print("    [%s, %s]," % (lit(float(c)), ", ".join(lit(v) for v in g)))
print("];")
