language = "C"
include_guard = "_RLIBC_ERRNO_H"
no_includes = true
after_includes = """
extern char *program_invocation_name;
extern char *program_invocation_short_name;
extern char *__progname;
extern char *__progname_full;
"""
trailer = "#define errno (*__errno_location())"
