language = "C"
style = "tag"
include_guard = "_RLIBC_FCNTL_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h"]
after_includes = '''
#include <sys/types.h>
#ifdef __USE_LARGEFILE64
# ifndef __off64_t_defined
#  define __off64_t_defined 1
typedef long off64_t;
# endif
#endif
#define F_GETLK64 5
#define F_SETLK64 6
#define F_SETLKW64 7
#define O_ACCMODE 0003
#define O_RDONLY 00
#define O_WRONLY 01
#define O_RDWR 02
#define O_CREAT 0100
#define O_EXCL 0200
#define O_NOCTTY 0400
#define O_TRUNC 01000
#define O_APPEND 02000
#define O_NONBLOCK 04000
#define O_NDELAY 2048
#define O_SYNC 04010000
#define O_FSYNC 0x101000
#define O_ASYNC 020000
#define F_GETLK 5
#define F_SETLK 6
#define F_SETLKW 7
#define F_OFD_GETLK 36
#define F_OFD_SETLK 37
#define F_OFD_SETLKW 38
#define O_LARGEFILE 0
#define O_DIRECTORY 0x10000
#define O_NOFOLLOW 0x20000
#define O_CLOEXEC 0x80000
#define O_DIRECT 0x4000
#define O_NOATIME 0x40000
#define O_PATH 0x200000
#define O_TMPFILE 0x410000
#define O_DSYNC 0x1000
#define O_RSYNC 0x101000
#define F_DUPFD 0
#define F_GETFD 1
#define F_SETFD 2
#define F_GETFL 3
#define F_SETFL 4
#define F_SETOWN 8
#define F_GETOWN 9
#define F_SETSIG 10
#define F_GETSIG 11
#define F_SETOWN_EX 15
#define F_GETOWN_EX 16
#define F_SETLEASE 1024
#define F_GETLEASE 1025
#define F_NOTIFY 1026
#define F_DUPFD_QUERY 1027
#define F_CREATED_QUERY 1028
#define F_SETPIPE_SZ 1031
#define F_GETPIPE_SZ 1032
#define F_ADD_SEALS 1033
#define F_GET_SEALS 1034
#define F_GET_RW_HINT 1035
#define F_SET_RW_HINT 1036
#define F_GET_FILE_RW_HINT 1037
#define F_SET_FILE_RW_HINT 1038
#define F_DUPFD_CLOEXEC 1030
#define FD_CLOEXEC 1
#define FD_PIDFS_ROOT -10002
#define F_RDLCK 0
#define F_WRLCK 1
#define F_UNLCK 2
#define F_EXLCK 4
#define F_SHLCK 8
#define LOCK_SH 1
#define LOCK_EX 2
#define LOCK_NB 4
#define LOCK_UN 8
#define LOCK_MAND 32
#define LOCK_READ 64
#define LOCK_WRITE 128
#define LOCK_RW 192
#define DN_ACCESS 0x00000001
#define DN_MODIFY 0x00000002
#define DN_CREATE 0x00000004
#define DN_DELETE 0x00000008
#define DN_RENAME 0x00000010
#define DN_ATTRIB 0x00000020
#define DN_MULTISHOT 0x80000000
#define F_SEAL_SEAL 0x0001
#define F_SEAL_SHRINK 0x0002
#define F_SEAL_GROW 0x0004
#define F_SEAL_WRITE 0x0008
#define F_SEAL_FUTURE_WRITE 0x0010
#define F_SEAL_EXEC 0x0020
#define RWH_WRITE_LIFE_NOT_SET 0
#define RWF_WRITE_LIFE_NOT_SET 0
#define RWH_WRITE_LIFE_NONE 1
#define RWH_WRITE_LIFE_SHORT 2
#define RWH_WRITE_LIFE_MEDIUM 3
#define RWH_WRITE_LIFE_LONG 4
#define RWH_WRITE_LIFE_EXTREME 5
#define FAPPEND 1024
#define FFSYNC 0x101000
#define FASYNC 0x2000
#define FNONBLOCK 2048
#define FNDELAY 2048
#define POSIX_FADV_NORMAL 0
#define POSIX_FADV_RANDOM 1
#define POSIX_FADV_SEQUENTIAL 2
#define POSIX_FADV_WILLNEED 3
#define POSIX_FADV_DONTNEED 4
#define POSIX_FADV_NOREUSE 5
#define SYNC_FILE_RANGE_WAIT_BEFORE 1
#define SYNC_FILE_RANGE_WRITE 2
#define SYNC_FILE_RANGE_WAIT_AFTER 4
#define SYNC_FILE_RANGE_WRITE_AND_WAIT 7
#define SPLICE_F_MOVE 1
#define SPLICE_F_NONBLOCK 2
#define SPLICE_F_MORE 4
#define SPLICE_F_GIFT 8
#define FALLOC_FL_ALLOCATE_RANGE 0x00
#define FALLOC_FL_KEEP_SIZE 0x01
#define FALLOC_FL_PUNCH_HOLE 0x02
#define FALLOC_FL_NO_HIDE_STALE 0x04
#define FALLOC_FL_COLLAPSE_RANGE 0x08
#define FALLOC_FL_ZERO_RANGE 0x10
#define FALLOC_FL_INSERT_RANGE 0x20
#define FALLOC_FL_UNSHARE_RANGE 0x40
#define FALLOC_FL_WRITE_ZEROES 0x80
#define MAX_HANDLE_SZ 128
#define AT_HANDLE_FID 512
#define AT_HANDLE_MNT_ID_UNIQUE 1
#define AT_HANDLE_CONNECTABLE 2
#define AT_EXECVE_CHECK 0x10000
#define OPENAT2_REGULAR 0x100000000ULL
#define RESOLVE_NO_XDEV 0x01
#define RESOLVE_NO_MAGICLINKS 0x02
#define RESOLVE_NO_SYMLINKS 0x04
#define RESOLVE_BENEATH 0x08
#define RESOLVE_IN_ROOT 0x10
#define RESOLVE_CACHED 0x20
#define UTIME_NOW 0x3fffffffL
#define UTIME_OMIT 0x3ffffffeL
#define S_IFMT 0xf000
#define S_IFDIR 0x4000
#define S_IFCHR 0x2000
#define S_IFBLK 0x6000
#define S_IFREG 0x8000
#define S_IFIFO 0x1000
#define S_IFLNK 0xa000
#define S_IFSOCK 0xc000
#define S_ISUID 2048
#define S_ISGID 1024
#define S_ISVTX 512
#define S_IRUSR 256
#define S_IWUSR 128
#define S_IXUSR 64
#define S_IRWXU 448
#define S_IRGRP 32
#define S_IWGRP 16
#define S_IXGRP 8
#define S_IRWXG 56
#define S_IROTH 4
#define S_IWOTH 2
#define S_IXOTH 1
#define S_IRWXO 7
#define R_OK 4
#define W_OK 2
#define X_OK 1
#define F_OK 0
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define AT_FDCWD -100
#define AT_SYMLINK_NOFOLLOW 0x100
#define AT_REMOVEDIR 0x200
#define AT_SYMLINK_FOLLOW 0x400
#define AT_NO_AUTOMOUNT 0x800
#define AT_EMPTY_PATH 0x1000
#define AT_STATX_SYNC_TYPE 0x6000
#define AT_STATX_SYNC_AS_STAT 0x0000
#define AT_STATX_FORCE_SYNC 0x2000
#define AT_STATX_DONT_SYNC 0x4000
#define AT_RECURSIVE 0x8000
#define AT_EACCESS 0x200
#define F_ULOCK 0
#define F_LOCK 1
#define F_TLOCK 2
#define F_TEST 3

struct f_owner_ex {
  int type;
  pid_t pid;
};
struct flock64 {
  short l_type;
  short l_whence;
  long l_start;
  long l_len;
  pid_t l_pid;
};
struct file_handle {
  unsigned int handle_bytes;
  int handle_type;
  unsigned char f_handle[];
};
struct open_how {
  uint64_t flags;
  uint64_t mode;
  uint64_t resolve;
};
'''
[export]
include = ["flock"]
[fn]
