language = "C"
style = "type"
include_guard = "_RLIBC_FSTABCALLS_H"
usize_is_size_t = true
no_includes = true
documentation = false
[export]
item_types = ["functions"]
[export.rename]
"Fstab" = "struct fstab"
"File" = "FILE"
