language = "C"
include_guard = "_GRP_H"
usize_is_size_t = true
documentation = false
no_includes = true
sys_includes = ["stddef.h"]
[export.rename]
"Group" = "struct group"
"File" = "FILE"
"Gid" = "gid_t"
[fn]
no_return = "__attribute__((noreturn))"
