language = "C"
include_guard = "_PWD_H"
usize_is_size_t = true
documentation = false
no_includes = true
sys_includes = ["stddef.h"]
[export.rename]
"Passwd" = "struct passwd"
"File" = "FILE"
"Uid" = "uid_t"
"Gid" = "gid_t"
[fn]
no_return = "__attribute__((noreturn))"
