language = "C"
include_guard = "_SEARCH_H"
usize_is_size_t = true
documentation = false
no_includes = true
sys_includes = ["stddef.h"]
[export.rename]
"Entry" = "ENTRY"
"Action" = "ACTION"
"HsearchData" = "struct hsearch_data"
"Compar" = "__compar_fn_t"
[fn]
no_return = "__attribute__((noreturn))"
