language = "C"
include_guard = "_RLIBC_SIGCALLS_K8_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h"]

[export]
exclude = ["Sigset", "Sigaction", "Siginfo", "StackT", "Sigstack", "Sigval", "Timespec", "Sigcontext", "Sighandler", "PidT"]

[export.rename]
"Sigset" = "sigset_t"
"Sigaction" = "struct sigaction"
"Siginfo" = "siginfo_t"
"StackT" = "stack_t"
"Sigstack" = "struct sigstack"
"Sigval" = "union sigval"
"Timespec" = "struct timespec"
"Sigcontext" = "struct sigcontext"
"Sighandler" = "__sighandler_t"
"PidT" = "pid_t"

[fn]
