language = "C"
include_guard = "_RLIBC_STDIO_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdarg.h", "sys/types.h"]

[export]
exclude = ["off_t", "FILE", "__underflow"]
[export.rename]
"Obstack" = "struct obstack"
