language = "C"
include_guard = "_RLIBC_STDIO_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdarg.h", "sys/types.h"]
after_includes = """
#ifndef __FILE_defined
#define __FILE_defined 1
#include <bits/types/struct_FILE.h>
typedef struct _IO_FILE FILE;
#endif
struct obstack;

#define EOF (-1)
#define BUFSIZ 8192
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define _IOFBF 0
#define _IOLBF 1
#define _IONBF 2
#define FILENAME_MAX 4096
#define FOPEN_MAX 16
#define L_tmpnam 20
#define L_cuserid 9
#define TMP_MAX 238328
#define P_tmpdir "/tmp"
#if __GLIBC_USE (DEPRECATED_SCANF)
# define __RLIBC_SCANF_ASM(n)
#elif __GLIBC_USE (C23_STRTOL)
# define __RLIBC_SCANF_ASM(n) __asm__(__RLIBC_STR(__isoc23_##n))
#else
# define __RLIBC_SCANF_ASM(n) __asm__(__RLIBC_STR(__isoc99_##n))
#endif
#define __RLIBC_STR2(x) #x
#define __RLIBC_STR(x) __RLIBC_STR2(x)
int fscanf(FILE *, const char *, ...) __RLIBC_SCANF_ASM(fscanf);
int scanf(const char *, ...) __RLIBC_SCANF_ASM(scanf);
int sscanf(const char *, const char *, ...) __RLIBC_SCANF_ASM(sscanf);
int vfscanf(FILE *, const char *, va_list) __RLIBC_SCANF_ASM(vfscanf);
int vscanf(const char *, va_list) __RLIBC_SCANF_ASM(vscanf);
int vsscanf(const char *, const char *, va_list) __RLIBC_SCANF_ASM(vsscanf);

int fgetc_unlocked(FILE *);
int getc_unlocked(FILE *);
int getchar_unlocked(void);
int fputc_unlocked(int, FILE *);
int putc_unlocked(int, FILE *);
int putchar_unlocked(int);
char *fgets_unlocked(char *, int, FILE *);
int fputs_unlocked(const char *, FILE *);
size_t fread_unlocked(void *, size_t, size_t, FILE *);
size_t fwrite_unlocked(const void *, size_t, size_t, FILE *);
int feof_unlocked(FILE *);
int ferror_unlocked(FILE *);
void clearerr_unlocked(FILE *);
int fflush_unlocked(FILE *);
int fileno_unlocked(FILE *);
FILE *fopen64(const char *, const char *);
FILE *freopen64(const char *, const char *, FILE *);
int fseeko64(FILE *, off_t, int);
off_t ftello64(FILE *);
FILE *tmpfile64(void);
ssize_t __getdelim(char **, size_t *, int, FILE *);
"""
trailer = """
#if defined __USE_LARGEFILE64 || defined __USE_FILE_OFFSET64
typedef fpos_t fpos64_t;
#endif
#define stdin stdin
#define stdout stdout
#define stderr stderr
#define L_ctermid 9
#if defined __USE_GNU || defined __USE_XOPEN2K24
# define SEEK_DATA 3
# define SEEK_HOLE 4
#endif
#ifdef __USE_GNU
# define AT_RENAME_NOREPLACE 0x1
# define AT_RENAME_EXCHANGE 0x2
# define AT_RENAME_WHITEOUT 0x4
#endif
#ifdef __USE_GNU
# define RENAME_NOREPLACE (1 << 0)
# define RENAME_EXCHANGE (1 << 1)
# define RENAME_WHITEOUT (1 << 2)
#endif
"""

[export]
exclude = ["off_t", "FILE"]
[export.rename]
"Obstack" = "struct obstack"
