language = "C"
include_guard = "_RLIBC_STRING_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h"]
after_includes = """
#ifdef __USE_MISC
# include <strings.h>
#endif
#ifdef _GNU_SOURCE
char *strerror_r(int, char *, size_t);
#else
int strerror_r(int, char *, size_t) __asm__("__xpg_strerror_r");
#endif
extern int __memcmpeq(const void *, const void *, size_t);
"""
trailer = """
#if __GLIBC_USE (ISOC23) && defined __glibc_const_generic && !defined _LIBC
# define memchr(S, C, N) __glibc_const_generic (S, const void *, memchr (S, C, N))
# define strchr(S, C) __glibc_const_generic (S, const char *, strchr (S, C))
# define strrchr(S, C) __glibc_const_generic (S, const char *, strrchr (S, C))
# define strpbrk(S, ACCEPT) __glibc_const_generic (S, const char *, strpbrk (S, ACCEPT))
# define strstr(HAYSTACK, NEEDLE) __glibc_const_generic (HAYSTACK, const char *, strstr (HAYSTACK, NEEDLE))
#endif
#define strdupa(s) (__extension__ ({ const char *__old = (s); size_t __len = strlen (__old) + 1; char *__new = (char *) __builtin_alloca (__len); (char *) memcpy (__new, __old, __len); }))
#define strndupa(s, n) (__extension__ ({ const char *__old = (s); size_t __len = strnlen (__old, (n)); char *__new = (char *) __builtin_alloca (__len + 1); __new[__len] = '\\0'; (char *) memcpy (__new, __old, __len); }))
"""

[export]
exclude = ["strerror_r", "__xpg_strerror_r"]
