language = "C"
style = "tag"
include_guard = "_RLIBC_SYS_MOUNT_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h"]
after_includes = '''
#define MS_RDONLY 1U
#define MS_NOSUID 2U
#define MS_NODEV 4U
#define MS_NOEXEC 8U
#define MS_SYNCHRONOUS 16U
#define MS_REMOUNT 32U
#define MS_MANDLOCK 64U
#define MS_DIRSYNC 128U
#define MS_NOSYMFOLLOW 256U
#define MS_NOATIME 1024U
#define MS_NODIRATIME 2048U
#define MS_BIND 0x1000U
#define MS_MOVE 0x2000U
#define MS_REC 0x4000U
#define MS_VERBOSE 32768
#define MS_SILENT 0x8000U
#define MS_POSIXACL 0x10000U
#define MS_UNBINDABLE 0x20000U
#define MS_PRIVATE 0x40000U
#define MS_SLAVE 0x80000U
#define MS_SHARED 0x100000U
#define MS_RELATIME 0x200000U
#define MS_KERNMOUNT 0x400000U
#define MS_I_VERSION 0x800000U
#define MS_STRICTATIME 0x1000000U
#define MS_LAZYTIME 0x2000000U
#define MS_SUBMOUNT 0x4000000
#define MS_NOREMOTELOCK 0x8000000
#define MS_NOSEC 0x10000000
#define MS_BORN 0x20000000
#define MS_ACTIVE 0x40000000U
#define MS_NOUSER 0x80000000U
#define MS_RMT_MASK 0x2800051U
#define MS_MGC_VAL 0xc0ed0000
#define MS_MGC_MSK 0xffff0000
#define OPEN_TREE_CLONE 1
#define OPEN_TREE_NAMESPACE 2
#define OPEN_TREE_CLOEXEC 0x80000
#define MOVE_MOUNT_F_SYMLINKS 0x00000001
#define MOVE_MOUNT_F_AUTOMOUNTS 0x00000002
#define MOVE_MOUNT_F_EMPTY_PATH 0x00000004
#define MOVE_MOUNT_T_SYMLINKS 0x00000010
#define MOVE_MOUNT_T_AUTOMOUNTS 0x00000020
#define MOVE_MOUNT_T_EMPTY_PATH 0x00000040
#define MOVE_MOUNT_SET_GROUP 0x00000100
#define MOVE_MOUNT_BENEATH 0x00000200
#define MOVE_MOUNT__MASK 0x00000377
#define FSOPEN_CLOEXEC 0x00000001
#define FSPICK_CLOEXEC 0x00000001
#define FSPICK_SYMLINK_NOFOLLOW 0x00000002
#define FSPICK_NO_AUTOMOUNT 0x00000004
#define FSPICK_EMPTY_PATH 0x00000008
#define FSMOUNT_CLOEXEC 0x00000001
#define FSMOUNT_NAMESPACE 0x00000002
#define MOUNT_ATTR_RDONLY 0x00000001
#define MOUNT_ATTR_NOSUID 0x00000002
#define MOUNT_ATTR_NODEV 0x00000004
#define MOUNT_ATTR_NOEXEC 0x00000008
#define MOUNT_ATTR__ATIME 0x00000070
#define MOUNT_ATTR_RELATIME 0x00000000
#define MOUNT_ATTR_NOATIME 0x00000010
#define MOUNT_ATTR_STRICTATIME 0x00000020
#define MOUNT_ATTR_NODIRATIME 0x00000080
#define MOUNT_ATTR_IDMAP 0x00100000
#define MOUNT_ATTR_NOSYMFOLLOW 0x00200000
#define MOUNT_ATTR_SIZE_VER0 32
#define MNT_ID_REQ_SIZE_VER0 24
#define MNT_ID_REQ_SIZE_VER1 32
#define STATMOUNT_SB_BASIC 0x00000001U
#define STATMOUNT_MNT_BASIC 0x00000002U
#define STATMOUNT_PROPAGATE_FROM 0x00000004U
#define STATMOUNT_MNT_ROOT 0x00000008U
#define STATMOUNT_MNT_POINT 0x00000010U
#define STATMOUNT_FS_TYPE 0x00000020U
#define STATMOUNT_MNT_NS_ID 0x00000040U
#define STATMOUNT_MNT_OPTS 0x00000080U
#define STATMOUNT_FS_SUBTYPE 0x00000100U
#define STATMOUNT_SB_SOURCE 0x00000200U
#define STATMOUNT_OPT_ARRAY 0x00000400U
#define STATMOUNT_OPT_SEC_ARRAY 0x00000800U
#define STATMOUNT_SUPPORTED_MASK 0x00001000U
#define STATMOUNT_MNT_UIDMAP 0x00002000U
#define STATMOUNT_MNT_GIDMAP 0x00004000U
#define LSMT_ROOT 0xffffffffffffffff
#define LISTMOUNT_REVERSE 1
#define STATMOUNT_BY_FD 0x00000001U
#define BLOCK_SIZE_BITS 10
#define BLOCK_SIZE 1024
#define BLKROSET 0x125dU
#define BLKROGET 0x125eU
#define BLKRRPART 0x125fU
#define BLKGETSIZE 0x1260U
#define BLKFLSBUF 0x1261U
#define BLKRASET 0x1262U
#define BLKRAGET 0x1263U
#define BLKFRASET 0x1264U
#define BLKFRAGET 0x1265U
#define BLKSECTSET 0x1266U
#define BLKSECTGET 0x1267U
#define BLKSSZGET 0x1268U
#define BLKBSZGET 0x80081270UL
#define BLKBSZSET 0x40081271UL
#define BLKGETSIZE64 0x80081272UL
#define MNT_FORCE 1
#define MNT_DETACH 2
#define MNT_EXPIRE 4
#define UMOUNT_NOFOLLOW 8
#define O_CLOEXEC 0x80000

struct mount_attr {
  uint64_t attr_set;
  uint64_t attr_clr;
  uint64_t propagation;
  uint64_t userns_fd;
};
'''
[export]
[fn]
