language = "C"
style = "tag"
include_guard = "_RLIBC_SYS_QUOTA_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h"]
after_includes = '''
#define MAXQUOTAS 3
#define USRQUOTA 0
#define GRPQUOTA 1
#define PRJQUOTA 2
#define SUBCMDMASK 0x00ff
#define SUBCMDSHIFT 8
#define Q_SYNC 0x800001
#define Q_QUOTAON 0x800002
#define Q_QUOTAOFF 0x800003
#define Q_GETFMT 0x800004
#define Q_GETINFO 0x800005
#define Q_SETINFO 0x800006
#define Q_GETQUOTA 0x800007
#define Q_SETQUOTA 0x800008
#define Q_GETNEXTQUOTA 0x800009
#define QFMT_VFS_OLD 1
#define QFMT_VFS_V0 2
#define QFMT_OCFS2 3
#define QFMT_VFS_V1 4
#define QFMT_SHMEM 5
#define QIF_DQBLKSIZE_BITS 10
#define QIF_DQBLKSIZE 1024
#define QIF_BLIMITS 1
#define QIF_SPACE 2
#define QIF_ILIMITS 4
#define QIF_INODES 8
#define QIF_BTIME 16
#define QIF_ITIME 32
#define QIF_LIMITS 5
#define QIF_USAGE 10
#define QIF_TIMES 48
#define QIF_ALL 63
#define IIF_BGRACE 1
#define IIF_IGRACE 2
#define IIF_FLAGS 4
#define IIF_ALL 7
#define DQF_ROOT_SQUASH 1
#define DQF_SYS_FILE 0x10000
#define QUOTA_NL_NOWARN 0
#define QUOTA_NL_IHARDWARN 1
#define QUOTA_NL_ISOFTLONGWARN 2
#define QUOTA_NL_ISOFTWARN 3
#define QUOTA_NL_BHARDWARN 4
#define QUOTA_NL_BSOFTLONGWARN 5
#define QUOTA_NL_BSOFTWARN 6
#define QUOTA_NL_IHARDBELOW 7
#define QUOTA_NL_ISOFTBELOW 8
#define QUOTA_NL_BHARDBELOW 9
#define QUOTA_NL_BSOFTBELOW 10
#define QUOTA_NL_C_MAX 1
#define QUOTA_NL_A_MAX 7
#define MAX_IQ_TIME 604800
#define MAX_DQ_TIME 604800
#define NR_DQHASH 43
#define NR_DQUOTS 256

#define QCMD(cmd, type) (((cmd) << SUBCMDSHIFT) | ((type) & SUBCMDMASK))
struct if_dqblk {
  uint64_t dqb_bhardlimit;
  uint64_t dqb_bsoftlimit;
  uint64_t dqb_curspace;
  uint64_t dqb_ihardlimit;
  uint64_t dqb_isoftlimit;
  uint64_t dqb_curinodes;
  uint64_t dqb_btime;
  uint64_t dqb_itime;
  uint32_t dqb_valid;
};
struct dqblk {
  uint64_t dqb_bhardlimit;
  uint64_t dqb_bsoftlimit;
  uint64_t dqb_curspace;
  uint64_t dqb_ihardlimit;
  uint64_t dqb_isoftlimit;
  uint64_t dqb_curinodes;
  uint64_t dqb_btime;
  uint64_t dqb_itime;
  uint32_t dqb_valid;
};
struct if_nextdqblk {
  uint64_t dqb_bhardlimit;
  uint64_t dqb_bsoftlimit;
  uint64_t dqb_curspace;
  uint64_t dqb_ihardlimit;
  uint64_t dqb_isoftlimit;
  uint64_t dqb_curinodes;
  uint64_t dqb_btime;
  uint64_t dqb_itime;
  uint32_t dqb_valid;
  uint32_t dqb_id;
};
struct if_dqinfo {
  uint64_t dqi_bgrace;
  uint64_t dqi_igrace;
  uint32_t dqi_flags;
  uint32_t dqi_valid;
};
struct dqinfo {
  uint64_t dqi_bgrace;
  uint64_t dqi_igrace;
  uint32_t dqi_flags;
  uint32_t dqi_valid;
};
#define dqoff(UID) ((long)((UID) * sizeof (struct dqblk)))
'''
[export]
[fn]
