language = "C"
style = "tag"
include_guard = "_RLIBC_SYS_PIDFD_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h", "fcntl.h", "sys/ioctl.h"]
after_includes = '''
#define PIDFD_NONBLOCK 2048
#define PIDFD_THREAD 128
#define PIDFD_SIGNAL_THREAD 1UL
#define PIDFD_SIGNAL_THREAD_GROUP 2UL
#define PIDFD_SIGNAL_PROCESS_GROUP 4UL
#define PIDFS_IOCTL_MAGIC 0xFF
#define PIDFD_GET_CGROUP_NAMESPACE 0xff01U
#define PIDFD_GET_IPC_NAMESPACE 0xff02U
#define PIDFD_GET_MNT_NAMESPACE 0xff03U
#define PIDFD_GET_NET_NAMESPACE 0xff04U
#define PIDFD_GET_PID_NAMESPACE 0xff05U
#define PIDFD_GET_PID_FOR_CHILDREN_NAMESPACE 0xff06U
#define PIDFD_GET_TIME_NAMESPACE 0xff07U
#define PIDFD_GET_TIME_FOR_CHILDREN_NAMESPACE 0xff08U
#define PIDFD_GET_USER_NAMESPACE 0xff09U
#define PIDFD_GET_UTS_NAMESPACE 0xff0aU
#define PIDFD_SELF_THREAD -10000
#define PIDFD_SELF_THREAD_GROUP -10001
#define PIDFD_SELF -10000
#define PIDFD_SELF_PROCESS -10001
#define PIDFD_INFO_PID 1UL
#define PIDFD_INFO_CREDS 2UL
#define PIDFD_INFO_CGROUPID 4UL
#define PIDFD_INFO_EXIT 8UL
#define PIDFD_INFO_COREDUMP 16UL
#define PIDFD_COREDUMPED 1U
#define PIDFD_COREDUMP_SKIP 2U
#define PIDFD_COREDUMP_USER 4U
#define PIDFD_COREDUMP_ROOT 8U
#define PIDFD_INFO_SIZE_VER0 64
#define PIDFD_GET_INFO 0xc048ff0bUL
struct pidfd_info {
  uint64_t mask;
  uint64_t cgroupid;
  uint32_t pid;
  uint32_t tgid;
  uint32_t ppid;
  uint32_t ruid;
  uint32_t rgid;
  uint32_t euid;
  uint32_t egid;
  uint32_t suid;
  uint32_t sgid;
  uint32_t fsuid;
  uint32_t fsgid;
  int32_t exit_code;
  uint32_t coredump_mask;
  uint32_t __spare1;
};
'''
[export]
[fn]
