language = "C"
style = "tag"
include_guard = "_RLIBC_SYS_TTYDEFAULTS_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h"]
after_includes = '''
#define TTYDEF_IFLAG 0x2d22
#define TTYDEF_OFLAG 0x1805
#define TTYDEF_LFLAG 0x8a1b
#define TTYDEF_CFLAG 1440
#define TTYDEF_SPEED 0x2580U
#define CEOF 4
#define CEOL 0
#define CERASE 0177
#define CINTR 3
#define CSTATUS 0
#define CKILL 21
#define CMIN 1
#define CQUIT 034
#define CSUSP 26
#define CTIME 0
#define CDSUSP 25
#define CSTART 17
#define CSTOP 19
#define CLNEXT 22
#define CDISCARD 15
#define CWERASE 23
#define CREPRINT 18
#define CEOT 4
#define CBRK 0
#define CRPRNT 18
#define CFLUSH 15

#define CTRL(x) ((x) & 037)
#define CEOF CTRL('d')
#define CEOL '\0'
#define CERASE 0177
#define CINTR CTRL('c')
#define CSTATUS '\0'
#define CKILL CTRL('u')
#define CMIN 1
#define CQUIT 034
#define CSUSP CTRL('z')
#define CTIME 0
#define CDSUSP CTRL('y')
#define CSTART CTRL('q')
#define CSTOP CTRL('s')
#define CLNEXT CTRL('v')
#define CDISCARD CTRL('o')
#define CWERASE CTRL('w')
#define CREPRINT CTRL('r')
#define CEOT CEOF
#define CBRK CEOL
#define CRPRNT CREPRINT
#define CFLUSH CDISCARD
'''
[export]
[fn]
