language = "C"
include_guard = "_RLIBC_TIME_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h"]
after_includes = """
#include <bits/types/clock_t.h>
#include <bits/types/time_t.h>
#include <bits/types/struct_tm.h>
#include <bits/types/struct_timespec.h>
#include <bits/types/clockid_t.h>
#include <bits/types/timer_t.h>
#include <bits/types/struct_itimerspec.h>
#include <bits/types/struct_sigevent.h>
#include <bits/types/locale_t.h>

#define CLOCKS_PER_SEC ((clock_t) 1000000)
#define CLOCK_REALTIME 0
#define CLOCK_MONOTONIC 1
#define CLOCK_PROCESS_CPUTIME_ID 2
#define CLOCK_THREAD_CPUTIME_ID 3
#define CLOCK_MONOTONIC_RAW 4
#define CLOCK_REALTIME_COARSE 5
#define CLOCK_MONOTONIC_COARSE 6
#define CLOCK_BOOTTIME 7
#define CLOCK_REALTIME_ALARM 8
#define CLOCK_BOOTTIME_ALARM 9
#define CLOCK_TAI 11
#define TIMER_ABSTIME 1
#define TIME_UTC 1
#define TIME_MONOTONIC 2
#define TIME_ACTIVE 3
#define TIME_THREAD_ACTIVE 4

extern char *tzname[2];
extern int daylight;
extern long timezone;
"""

[export]
exclude = ["Timespec", "Timeval", "Itimerval", "Itimerspec", "Timezone", "Utimbuf", "Timeb", "Sigval", "SigevUn", "Sigevent", "Tm",
  "ClockId", "TimerId", "TimeT", "ClockT", "LocaleT",
  "CLOCK_REALTIME", "CLOCK_MONOTONIC", "CLOCK_PROCESS_CPUTIME_ID", "CLOCK_THREAD_CPUTIME_ID", "CLOCK_MONOTONIC_RAW",
  "CLOCK_REALTIME_COARSE", "CLOCK_MONOTONIC_COARSE", "CLOCK_BOOTTIME", "CLOCK_REALTIME_ALARM", "CLOCK_BOOTTIME_ALARM", "CLOCK_TAI",
  "TIMER_ABSTIME", "ITIMER_REAL", "ITIMER_VIRTUAL", "ITIMER_PROF", "TIME_UTC", "TIME_MONOTONIC", "TIME_ACTIVE", "TIME_THREAD_ACTIVE",
  "CLOCKS_PER_SEC", "SIGEV_SIGNAL", "SIGEV_NONE", "SIGEV_THREAD", "SIGEV_THREAD_ID", "SIGALRM", "UTIME_NOW", "UTIME_OMIT"]

[export.rename]
"Timespec" = "struct timespec"
"Itimerspec" = "struct itimerspec"
"Sigevent" = "struct sigevent"
"Tm" = "struct tm"
"ClockId" = "clockid_t"
"TimerId" = "timer_t"
"TimeT" = "time_t"
"ClockT" = "clock_t"
"LocaleT" = "locale_t"
