language = "C"
include_guard = "_RLIBC_SYS_TYPES_H"
no_includes = true
sys_includes = ["stddef.h"]
after_includes = """
#ifdef __USE_MISC
# include <endian.h>
# include <sys/select.h>
#endif
#ifdef __USE_MISC
# ifndef __bsd_types_defined
#  define __bsd_types_defined 1
typedef unsigned char u_char;
typedef unsigned short int u_short;
typedef unsigned int u_int;
typedef unsigned long int u_long;
typedef long int quad_t;
typedef unsigned long int u_quad_t;
typedef unsigned long int ulong;
typedef unsigned short int ushort;
typedef unsigned int uint;
typedef unsigned char u_int8_t;
typedef unsigned short int u_int16_t;
typedef unsigned int u_int32_t;
typedef unsigned long int u_int64_t;
typedef long int register_t;
typedef int daddr_t;
#  ifndef __fsid_t_defined
#   define __fsid_t_defined 1
typedef struct { int __val[2]; } fsid_t;
#  endif
# endif
#endif
#include <bits/types/timer_t.h>
#include <bits/pthreadtypes.h>
"""
