language = "C"
include_guard = "_RLIBC_WCHAR_H"
usize_is_size_t = true
no_includes = true
sys_includes = ["stddef.h", "stdint.h", "stdarg.h"]

[export]
exclude = ["FILE", "locale_t", "wcswcs", "wcstold", "wcstold_l", "wcstof64x", "wcstof64x_l", "wcstof128", "wcstof128_l", "wcsftime", "wcsftime_l"]
