language = "C"
style = "type"
include_guard = "_RLIBC_WORDEXPCALLS_H"
usize_is_size_t = true
no_includes = true
documentation = false
[export]
item_types = ["functions"]
[export.rename]
"Wordexp" = "wordexp_t"
