#!/usr/bin/env python3
import os, re, subprocess, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
names = sorted(set(re.findall(r"^#define ((?:PRI|SCN)[a-zA-Z]+[0-9A-Z]*)\b", subprocess.run(
    ["gcc", "-E", "-dM", "-include", "inttypes.h", "-x", "c", "/dev/null"], capture_output=True, text=True).stdout, re.M)))
with tempfile.TemporaryDirectory() as d:
    src = os.path.join(d, "p.c")
    with open(src, "w") as f:
        f.write("#include <inttypes.h>\n#include <stdio.h>\nint main(void){\n")
        for n in names:
            f.write('printf("%s %%s\\n", %s);\n' % (n, n))
        f.write("return 0;}\n")
    subprocess.run(["gcc", "-std=gnu2x", "-w", src, "-o", os.path.join(d, "p")], check=True)
    vals = dict(l.split(" ", 1) for l in subprocess.run([os.path.join(d, "p")], capture_output=True, text=True, check=True).stdout.splitlines())

def key(n):
    m = re.match(r"(PRI|SCN)([a-zA-Z])(.*)", n)
    return (m.group(1), m.group(2), m.group(3))

out = ["""/* inttypes.h for the Rust libc (generated by tools/gen_inttypes.py; x86-64 Linux values).
   imaxdiv_t, imaxabs and imaxdiv are declared by stdlib.h, which this header includes. */
#ifndef _RLIBC_INTTYPES_H
#define _RLIBC_INTTYPES_H 1

#include <stdint.h>
#include <stdlib.h>
#include <wchar.h>

#if !defined __cplusplus || defined __STDC_FORMAT_MACROS"""]
for n in sorted(names, key=lambda n: (n[:3], n[3], n[4:])):
    out.append('# define %s "%s"' % (n, vals[n]))
out.append("#endif")
out.append("""
#if defined _GNU_SOURCE || (defined __STDC_VERSION__ && __STDC_VERSION__ > 201710L)
extern intmax_t strtoimax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __asm__ ("__isoc23_strtoimax") __attribute__ ((__nothrow__));
extern uintmax_t strtoumax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __asm__ ("__isoc23_strtoumax") __attribute__ ((__nothrow__));
#else
extern intmax_t strtoimax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __attribute__ ((__nothrow__));
extern uintmax_t strtoumax (const char *__restrict __nptr, char **__restrict __endptr, int __base) __attribute__ ((__nothrow__));
#endif

#endif
""")
with open(os.path.join(ROOT, "include-static", "inttypes.h"), "w") as f:
    f.write("\n".join(out))
print(len(names), "macros")
