#!/usr/bin/env python3
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ALIASES = {
    "__open": "open", "__open64": "open64", "__close": "close", "__read": "read", "__pread64": "pread64", "__pwrite64": "pwrite64",
    "__lseek": "lseek", "__fcntl": "fcntl", "__poll": "poll", "__select": "select", "__send": "send", "__connect": "connect",
    "__waitpid": "waitpid", "__fork": "fork", "__vfork": "vfork", "__getpid": "getpid", "__setpgid": "setpgid", "__pipe": "pipe",
    "__dup2": "dup2", "__clone": "clone", "__sbrk": "sbrk", "__gettimeofday": "gettimeofday", "__gmtime_r": "gmtime_r",
    "__nanosleep": "nanosleep", "__statfs": "statfs", "__adjtimex": "adjtimex", "__arch_prctl": "arch_prctl",
    "__sched_get_priority_max": "sched_get_priority_max", "__sched_get_priority_min": "sched_get_priority_min",
    "__sched_getparam": "sched_getparam", "__sched_getscheduler": "sched_getscheduler", "__sched_setscheduler": "sched_setscheduler",
    "__sched_yield": "sched_yield", "__getmntent_r": "getmntent_r", "__setmntent": "setmntent", "__endmntent": "endmntent",
    "__mbrtowc": "mbrtowc", "__strdup": "strdup", "__strndup": "strndup", "__strcasecmp": "strcasecmp", "__strcasestr": "strcasestr",
    "__strerror_r": "strerror_r", "__strverscmp": "strverscmp", "__strsep_g": "strsep", "__rawmemchr": "rawmemchr", "__bzero": "bzero",
    "__ffs": "ffs", "__vsnprintf": "vsnprintf", "__vfscanf": "vfscanf", "__vsscanf": "vsscanf", "__iswctype": "iswctype",
    "__towctrans": "towctrans",
    "__iswalnum_l": "iswalnum_l", "__iswalpha_l": "iswalpha_l", "__iswblank_l": "iswblank_l", "__iswcntrl_l": "iswcntrl_l",
    "__iswdigit_l": "iswdigit_l", "__iswgraph_l": "iswgraph_l", "__iswlower_l": "iswlower_l", "__iswprint_l": "iswprint_l",
    "__iswpunct_l": "iswpunct_l", "__iswspace_l": "iswspace_l", "__iswupper_l": "iswupper_l", "__iswxdigit_l": "iswxdigit_l",
    "__strtol_internal": "strtol", "__strtoul_internal": "strtoul", "__strtoll_internal": "strtoll", "__strtoull_internal": "strtoull",
    "__strtod_internal": "strtod", "__strtof_internal": "strtof", "__strtold_internal": "strtold", "__strtof128_internal": "strtof128",
    "__wcstol_internal": "wcstol", "__wcstoul_internal": "wcstoul", "__wcstoll_internal": "wcstoll", "__wcstoull_internal": "wcstoull",
    "__wcstod_internal": "wcstod", "__wcstof_internal": "wcstof", "__wcstold_internal": "wcstold", "__wcstof128_internal": "wcstof128",
}


def defined_names():
    if "--defined" in sys.argv:
        return set(l.strip() for l in open(sys.argv[sys.argv.index("--defined") + 1]))
    so = os.path.join(ROOT, "target/shared/libc.so.6")
    out = subprocess.run(["nm", "-D", "--defined-only", so], capture_output=True, text=True).stdout
    names = set()
    for line in out.splitlines():
        p = line.split()
        if len(p) == 3:
            names.add(p[2].split("@")[0])
    return names


def main():
    ours = defined_names()
    mapped = set()
    for line in open(os.path.join(ROOT, "crates/rusty-libc-cabi/shared/libc.map")):
        t = line.strip().rstrip(";")
        if t and not t.endswith("{") and not t.startswith(("}", "global", "local", "*")):
            mapped.add(t)
    done, skipped = [], []
    for name, target in sorted(ALIASES.items()):
        if name not in mapped:
            skipped.append("%s (glibc does not export it)" % name)
        elif target not in ours:
            skipped.append("%s (no %s here)" % (name, target))
        else:
            done.append((name, target))
    out = ["//! GENERATED by tools/gen_old_abi.py: do not edit.", "//!",
           "//! Old public names that glibc 2.43 still exports and that programs built against glibc older than 2.33 import",
           "//! (`__open`, `__read`, `__strdup`, `__strtol_internal`, `__libc_malloc`, ...): each is a `jmp` to the function it names.",
           "//! Not provided: " + ("; ".join(skipped) if skipped else "none"), "#![allow(missing_docs)]", "", "core::arch::global_asm!(",
           '    ".pushsection .text.rl_compat,\\"ax\\",@progbits",']
    for name, target in done:
        out.append('    ".p2align 3",')
        out.append('    ".globl %s",' % name)
        out.append('    ".type %s, @function",' % name)
        out.append('    "%s:",' % name)
        out.append('    "jmp %s",' % target)
    out.append('    ".popsection",')
    out.append(");")
    open(os.path.join(ROOT, "crates/rusty-libc-cabi/src/compat_abi.rs"), "w").write("\n".join(out) + "\n")
    print("%d aliases written, %d skipped" % (len(done), len(skipped)))
    for s in skipped:
        print("  skipped:", s)


main()
