#!/usr/bin/env python3
import os
import re
import subprocess
import sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
lib = sys.argv[1] if len(sys.argv) > 1 else "/usr/lib64/libmvec.so.1"
out = subprocess.run(["readelf", "--dyn-syms", "-W", lib], capture_output=True, text=True, check=True, env={**os.environ, "LC_ALL": "C"}).stdout
syms = []
for line in out.splitlines():
    f = line.split()
    if len(f) < 8 or not f[0].endswith(":") or f[6] == "UND":
        continue
    m = re.match(r"(_ZGV\w+)@@(\S+)$", f[7])
    if m:
        syms.append((m.group(1), m.group(2)))
syms.sort()

FEATURE = {"b": "sse2", "c": "avx", "d": "avx2", "e": "avx512f"}
VT = {("b", "d"): "__m128d", ("b", "s"): "__m128", ("c", "d"): "__m256d", ("c", "s"): "__m256", ("d", "d"): "__m256d", ("d", "s"): "__m256",
      ("e", "d"): "__m512d", ("e", "s"): "__m512"}
IT = {"b": "__m128i", "c": "__m256i", "d": "__m256i", "e": "__m512i"}
REGBYTES = {"b": 16, "c": 32, "d": 32, "e": 64}

body = ["// GENERATED by tools/gen_libmvec.py from the system's libmvec.so.1: do not edit.", ""]
by_ver = {}
for name, ver in syms:
    m = re.match(r"_ZGV([bcde])N(\d+)(v+)_(\w+)$", name)
    if not m:
        sys.exit("unexpected name " + name)
    isa, lanes, shape, fn = m.group(1), int(m.group(2)), m.group(3), m.group(4)
    by_ver.setdefault(ver, []).append(name)
    isdouble = (isa, lanes) in (("b", 2), ("c", 4), ("d", 4), ("e", 8))
    elem = "f64" if isdouble else "f32"
    vt = VT[(isa, "d" if isdouble else "s")]
    feat = FEATURE[isa]
    if shape == "v":
        body.append('vec1!(%s, %s, %s, %d, "%s", %s);' % (name, vt, elem, lanes, feat, fn))
    elif shape == "vv":
        body.append('vec2!(%s, %s, %s, %d, "%s", %s);' % (name, vt, elem, lanes, feat, fn))
    elif shape == "vvv":
        it = IT[isa]
        regs = (lanes * 8) // REGBYTES[isa]
        if regs == 1:
            body.append('sincos1!(%s, %s, %s, %s, %d, "%s", %s);' % (name, vt, it, elem, lanes, feat, fn))
        else:
            body.append('sincos2!(%s, %s, %s, %s, %d, "%s", %s);' % (name, vt, it, elem, lanes, feat, fn))
    else:
        sys.exit("shape " + shape)
open(os.path.join(root, "crates/rusty-libc-mvec/src/vecs.rs"), "w").write("\n".join(body) + "\n")

vers = sorted(by_ver, key=lambda v: [int(x) for x in v.replace("GLIBC_", "").split(".")])
text = []
prev = None
for v in vers:
    text.append("%s {\n  global:\n%s\n}%s;\n" % (v, "\n".join("    %s;" % n for n in sorted(by_ver[v])), (" " + prev) if prev else ""))
    prev = v
text[-1] = text[-1].replace("\n}", "\n  local:\n    *;\n}", 1)
open(os.path.join(root, "crates/rusty-libc-mvec/libmvec.map"), "w").write("/* GENERATED by tools/gen_libmvec.py */\n" + "\n".join(text))
print("%d symbols in %d version nodes" % (len(syms), len(vers)))
