#!/usr/bin/env python3
import os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def macros(src):
    out = subprocess.run(["gcc", "-E", "-dM", "-D_GNU_SOURCE", "-x", "c", "-"], input=src, capture_output=True, text=True).stdout
    d = {}
    for line in out.splitlines():
        m = re.match(r"#define (\w+(?:\([^)]*\))?) ?(.*)", line)
        if m:
            d[m.group(1)] = m.group(2)
    return d


def consts(hdr, drop=lambda n: False, pre=()):
    base = macros("".join("#include <%s>\n" % h for h in pre))
    full = macros("".join("#include <%s>\n" % h for h in pre) + "#include <%s>\n" % hdr)
    lines = []
    for n in sorted(full):
        bare = re.match(r"\w+", n).group(0)
        if (n in base and base[n] == full[n]) or bare.startswith("__") or re.fullmatch(r"_[A-Z0-9_]*_H_?", bare) or drop(bare):
            continue
        lines.append("#define %s %s" % (n, full[n]))
    return "\n".join(lines)


def write(rel, text):
    path = os.path.join(ROOT, "include-static", rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print(rel, text.count("\n"), "lines")


def wrap(rel, guard, body, includes=()):
    t = "/* %s for the Rust libc (generated by tools/gen_misc_headers.py: constants and macros copied from the system header's\n   definitions, types written by hand) */\n" % rel
    t += "#ifndef %s\n#define %s 1\n#include <features.h>\n" % (guard, guard)
    for i in includes:
        t += "#include <%s>\n" % i
    t += "#ifdef __cplusplus\nextern \"C\" {\n#endif\n" + body + "\n#ifdef __cplusplus\n}\n#endif\n#endif\n"
    write(rel, t)


ELF_TYPES = r"""
typedef uint16_t Elf32_Half;
typedef uint16_t Elf64_Half;
typedef uint32_t Elf32_Word;
typedef int32_t Elf32_Sword;
typedef uint32_t Elf64_Word;
typedef int32_t Elf64_Sword;
typedef uint64_t Elf32_Xword;
typedef int64_t Elf32_Sxword;
typedef uint64_t Elf64_Xword;
typedef int64_t Elf64_Sxword;
typedef uint32_t Elf32_Addr;
typedef uint64_t Elf64_Addr;
typedef uint32_t Elf32_Off;
typedef uint64_t Elf64_Off;
typedef uint16_t Elf32_Section;
typedef uint16_t Elf64_Section;
typedef Elf32_Half Elf32_Versym;
typedef Elf64_Half Elf64_Versym;

#define EI_NIDENT (16)

typedef struct { unsigned char e_ident[EI_NIDENT]; Elf32_Half e_type; Elf32_Half e_machine; Elf32_Word e_version; Elf32_Addr e_entry;
  Elf32_Off e_phoff; Elf32_Off e_shoff; Elf32_Word e_flags; Elf32_Half e_ehsize; Elf32_Half e_phentsize; Elf32_Half e_phnum;
  Elf32_Half e_shentsize; Elf32_Half e_shnum; Elf32_Half e_shstrndx; } Elf32_Ehdr;
typedef struct { unsigned char e_ident[EI_NIDENT]; Elf64_Half e_type; Elf64_Half e_machine; Elf64_Word e_version; Elf64_Addr e_entry;
  Elf64_Off e_phoff; Elf64_Off e_shoff; Elf64_Word e_flags; Elf64_Half e_ehsize; Elf64_Half e_phentsize; Elf64_Half e_phnum;
  Elf64_Half e_shentsize; Elf64_Half e_shnum; Elf64_Half e_shstrndx; } Elf64_Ehdr;

typedef struct { Elf32_Word sh_name; Elf32_Word sh_type; Elf32_Word sh_flags; Elf32_Addr sh_addr; Elf32_Off sh_offset; Elf32_Word sh_size;
  Elf32_Word sh_link; Elf32_Word sh_info; Elf32_Word sh_addralign; Elf32_Word sh_entsize; } Elf32_Shdr;
typedef struct { Elf64_Word sh_name; Elf64_Word sh_type; Elf64_Xword sh_flags; Elf64_Addr sh_addr; Elf64_Off sh_offset; Elf64_Xword sh_size;
  Elf64_Word sh_link; Elf64_Word sh_info; Elf64_Xword sh_addralign; Elf64_Xword sh_entsize; } Elf64_Shdr;

typedef struct { Elf32_Word st_name; Elf32_Addr st_value; Elf32_Word st_size; unsigned char st_info; unsigned char st_other; Elf32_Section st_shndx; } Elf32_Sym;
typedef struct { Elf64_Word st_name; unsigned char st_info; unsigned char st_other; Elf64_Section st_shndx; Elf64_Addr st_value; Elf64_Xword st_size; } Elf64_Sym;
typedef struct { Elf32_Half si_boundto; Elf32_Half si_flags; } Elf32_Syminfo;
typedef struct { Elf64_Half si_boundto; Elf64_Half si_flags; } Elf64_Syminfo;

#define ELF32_ST_BIND(val) (((unsigned char) (val)) >> 4)
#define ELF32_ST_TYPE(val) ((val) & 0xf)
#define ELF32_ST_INFO(bind, type) (((bind) << 4) + ((type) & 0xf))
#define ELF64_ST_BIND(val) ELF32_ST_BIND (val)
#define ELF64_ST_TYPE(val) ELF32_ST_TYPE (val)
#define ELF64_ST_INFO(bind, type) ELF32_ST_INFO ((bind), (type))
#define ELF32_ST_VISIBILITY(o) ((o) & 0x03)
#define ELF64_ST_VISIBILITY(o) ELF32_ST_VISIBILITY (o)

typedef struct { Elf32_Addr r_offset; Elf32_Word r_info; } Elf32_Rel;
typedef struct { Elf64_Addr r_offset; Elf64_Xword r_info; } Elf64_Rel;
typedef struct { Elf32_Addr r_offset; Elf32_Word r_info; Elf32_Sword r_addend; } Elf32_Rela;
typedef struct { Elf64_Addr r_offset; Elf64_Xword r_info; Elf64_Sxword r_addend; } Elf64_Rela;
#define ELF32_R_SYM(val) ((val) >> 8)
#define ELF32_R_TYPE(val) ((val) & 0xff)
#define ELF32_R_INFO(sym, type) (((sym) << 8) + ((type) & 0xff))
#define ELF64_R_SYM(i) ((i) >> 32)
#define ELF64_R_TYPE(i) ((i) & 0xffffffff)
#define ELF64_R_INFO(sym, type) ((((Elf64_Xword) (sym)) << 32) + (type))

typedef struct { Elf32_Word p_type; Elf32_Off p_offset; Elf32_Addr p_vaddr; Elf32_Addr p_paddr; Elf32_Word p_filesz; Elf32_Word p_memsz;
  Elf32_Word p_flags; Elf32_Word p_align; } Elf32_Phdr;
typedef struct { Elf64_Word p_type; Elf64_Word p_flags; Elf64_Off p_offset; Elf64_Addr p_vaddr; Elf64_Addr p_paddr; Elf64_Xword p_filesz;
  Elf64_Xword p_memsz; Elf64_Xword p_align; } Elf64_Phdr;

typedef struct { Elf32_Sword d_tag; union { Elf32_Word d_val; Elf32_Addr d_ptr; } d_un; } Elf32_Dyn;
typedef struct { Elf64_Sxword d_tag; union { Elf64_Xword d_val; Elf64_Addr d_ptr; } d_un; } Elf64_Dyn;

typedef struct { uint32_t a_type; union { uint32_t a_val; } a_un; } Elf32_auxv_t;
typedef struct { uint64_t a_type; union { uint64_t a_val; } a_un; } Elf64_auxv_t;

typedef struct { Elf32_Word n_namesz; Elf32_Word n_descsz; Elf32_Word n_type; } Elf32_Nhdr;
typedef struct { Elf64_Word n_namesz; Elf64_Word n_descsz; Elf64_Word n_type; } Elf64_Nhdr;

typedef struct { Elf32_Word ch_type; Elf32_Word ch_size; Elf32_Word ch_addralign; } Elf32_Chdr;
typedef struct { Elf64_Word ch_type; Elf64_Word ch_reserved; Elf64_Xword ch_size; Elf64_Xword ch_addralign; } Elf64_Chdr;

typedef struct { Elf32_Half vd_version; Elf32_Half vd_flags; Elf32_Half vd_ndx; Elf32_Half vd_cnt; Elf32_Word vd_hash; Elf32_Word vd_aux; Elf32_Word vd_next; } Elf32_Verdef;
typedef struct { Elf64_Half vd_version; Elf64_Half vd_flags; Elf64_Half vd_ndx; Elf64_Half vd_cnt; Elf64_Word vd_hash; Elf64_Word vd_aux; Elf64_Word vd_next; } Elf64_Verdef;
typedef struct { Elf32_Word vda_name; Elf32_Word vda_next; } Elf32_Verdaux;
typedef struct { Elf64_Word vda_name; Elf64_Word vda_next; } Elf64_Verdaux;
typedef struct { Elf32_Half vn_version; Elf32_Half vn_cnt; Elf32_Word vn_file; Elf32_Word vn_aux; Elf32_Word vn_next; } Elf32_Verneed;
typedef struct { Elf64_Half vn_version; Elf64_Half vn_cnt; Elf64_Word vn_file; Elf64_Word vn_aux; Elf64_Word vn_next; } Elf64_Verneed;
typedef struct { Elf32_Word vna_hash; Elf32_Half vna_flags; Elf32_Half vna_other; Elf32_Word vna_name; Elf32_Word vna_next; } Elf32_Vernaux;
typedef struct { Elf64_Word vna_hash; Elf64_Half vna_flags; Elf64_Half vna_other; Elf64_Word vna_name; Elf64_Word vna_next; } Elf64_Vernaux;

typedef struct { Elf32_Word l_name; Elf32_Word l_time_stamp; Elf32_Word l_checksum; Elf32_Word l_version; Elf32_Word l_flags; } Elf32_Lib;
typedef struct { Elf64_Word l_name; Elf64_Word l_time_stamp; Elf64_Word l_checksum; Elf64_Word l_version; Elf64_Word l_flags; } Elf64_Lib;
typedef Elf32_Addr Elf32_Conflict;
"""

ELF_HAND = set("EI_NIDENT ELF32_ST_BIND ELF32_ST_TYPE ELF32_ST_INFO ELF64_ST_BIND ELF64_ST_TYPE ELF64_ST_INFO ELF32_ST_VISIBILITY ELF64_ST_VISIBILITY "
               "ELF32_R_SYM ELF32_R_TYPE ELF32_R_INFO ELF64_R_SYM ELF64_R_TYPE ELF64_R_INFO".split())

wrap("elf.h", "_ELF_H", ELF_TYPES + consts("elf.h", lambda n: n in ELF_HAND), includes=["stdint.h"])

wrap("tar.h", "_TAR_H", consts("tar.h"))
wrap("cpio.h", "_CPIO_H", consts("cpio.h"))
wrap("values.h", "_VALUES_H", consts("values.h", pre=["limits.h", "float.h"]), includes=["limits.h", "float.h"])

write("stdc-predef.h", "/* stdc-predef.h for the Rust libc (gcc includes it implicitly): what the C library promises, same as glibc 2.43. */\n"
      "#ifndef _STDC_PREDEF_H\n#define _STDC_PREDEF_H 1\n"
      "#define __STDC_IEC_559__ 1\n#define __STDC_IEC_60559_BFP__ 201404L\n#define __STDC_IEC_559_COMPLEX__ 1\n"
      "#define __STDC_IEC_60559_COMPLEX__ 201404L\n#define __STDC_ISO_10646__ 201706L\n#endif\n")

wrap("sys/ttychars.h", "_SYS_TTYCHARS_H", consts("sys/ttychars.h") + """
struct ttychars {
  char tc_erase;
  char tc_kill;
  char tc_intrc;
  char tc_quitc;
  char tc_startc;
  char tc_stopc;
  char tc_eofc;
  char tc_brkc;
  char tc_suspc;
  char tc_dsuspc;
  char tc_rprntc;
  char tc_flushc;
  char tc_werasc;
  char tc_lnextc;
};
""")
wrap("sys/vlimit.h", "_SYS_VLIMIT_H", r"""
enum __vlimit_resource
{
  LIM_NORAISE,
  LIM_CPU,
  LIM_FSIZE,
  LIM_DATA,
  LIM_STACK,
  LIM_CORE,
  LIM_MAXRSS
};
#define INFINITY 0x7fffffff
extern int vlimit (enum __vlimit_resource __resource, int __value) __attribute__ ((__nothrow__));
""")
wrap("sys/perm.h", "_SYS_PERM_H", """
extern int ioperm (unsigned long int __from, unsigned long int __num, int __turn_on) __attribute__ ((__nothrow__));
extern int iopl (int __level) __attribute__ ((__nothrow__));
""")
wrap("sys/io.h", "_SYS_IO_H", """
#include <sys/perm.h>
static __inline unsigned char inb (unsigned short int __port) { unsigned char _v; __asm__ __volatile__ ("inb %w1,%0":"=a" (_v):"Nd" (__port)); return _v; }
static __inline unsigned char inb_p (unsigned short int __port) { unsigned char _v; __asm__ __volatile__ ("inb %w1,%0\\noutb %%al,$0x80":"=a" (_v):"Nd" (__port)); return _v; }
static __inline unsigned short int inw (unsigned short int __port) { unsigned short _v; __asm__ __volatile__ ("inw %w1,%0":"=a" (_v):"Nd" (__port)); return _v; }
static __inline unsigned int inl (unsigned short int __port) { unsigned int _v; __asm__ __volatile__ ("inl %w1,%0":"=a" (_v):"Nd" (__port)); return _v; }
static __inline void outb (unsigned char __value, unsigned short int __port) { __asm__ __volatile__ ("outb %b0,%w1": :"a" (__value), "Nd" (__port)); }
static __inline void outb_p (unsigned char __value, unsigned short int __port) { __asm__ __volatile__ ("outb %b0,%w1\\noutb %%al,$0x80": :"a" (__value), "Nd" (__port)); }
static __inline void outw (unsigned short int __value, unsigned short int __port) { __asm__ __volatile__ ("outw %w0,%w1": :"a" (__value), "Nd" (__port)); }
static __inline void outl (unsigned int __value, unsigned short int __port) { __asm__ __volatile__ ("outl %0,%w1": :"a" (__value), "Nd" (__port)); }
""")
