#!/usr/bin/env python3
import os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def macros(extra):
    out = subprocess.run(["gcc", "-E", "-dM", "-D_GNU_SOURCE", "-x", "c", "-"] + extra, input="", capture_output=True, text=True).stdout
    d = {}
    for line in out.splitlines():
        m = re.match(r"#define (\w+(?:\([^)]*\))?) ?(.*)", line)
        if m:
            d[m.group(1)] = m.group(2)
    return d

base = macros([])
full = macros(["-include", "limits.h"])
names = sorted(n for n in full if n not in base or base[n] != full[n])
FEATURE = re.compile(r"^(_POSIX_SOURCE|_POSIX_C_SOURCE|_XOPEN_SOURCE|_XOPEN_SOURCE_EXTENDED|_DEFAULT_SOURCE|_ATFILE_SOURCE|"
                     r"_DYNAMIC_STACK_SIZE_SOURCE|_FEATURES_H|_ISOC\w+_SOURCE|_LARGEFILE\w*_SOURCE|_SYS_CDEFS_H|"
                     r"__USE_\w+|__GLIBC_USE_ISOC2\w+|__GLIBC_USE_DEPRECATED_\w+|__GLIBC_USE_C23_STRTOL|__GLIBC__|__GLIBC_MINOR__|__GNU_LIBRARY__|__GLIBC_PREREQ)\b")
LIMITISH = ("__IOV_MAX", "__SC_THREAD_STACK_MIN_VALUE", "__STDC_VERSION_LIMITS_H__")
lim, cdefs = [], []
for n in names:
    base_name = re.match(r"\w+", n).group(0)
    if n.startswith("_LIBC_LIMITS_H_") or n in ("_GCC_LIMITS_H_", "_BITS_POSIX1_LIM_H") or FEATURE.match(n):
        continue
    line = "#define %s %s" % (n, full[n])
    if n == "PTHREAD_STACK_MIN":
        line = ("#ifdef __USE_DYNAMIC_STACK_SIZE\nextern long int __sysconf (int __name) __THROW;\n# define PTHREAD_STACK_MIN %s\n#else\n"
                "# define PTHREAD_STACK_MIN 16384\n#endif") % full[n]
    (cdefs if base_name.startswith("__") and base_name not in LIMITISH else lim).append(line)
with open(os.path.join(ROOT, "include-static", "limits.h"), "w") as f:
    f.write("""/* limits.h for the Rust libc (generated by tools/gen_limits.py from the system header's values:
   x86-64 Linux, glibc 2.43). Self-contained, no #include_next. Limit values only: the glibc identity
   and feature macros come from <features.h>. */
#ifndef _RLIBC_LIMITS_H
#define _RLIBC_LIMITS_H 1
#include <features.h>
""" + "\n".join(lim) + "\n\n#endif\n")
os.makedirs(os.path.join(ROOT, "include-static", "bits"), exist_ok=True)
with open(os.path.join(ROOT, "include-static", "bits", "rlibc-cdefs.h"), "w") as f:
    f.write("""/* glibc's sys/cdefs.h macros for the Rust libc (generated by tools/gen_limits.py from the system header:
   x86-64, gcc, glibc 2.43). Included by <features.h> and <sys/cdefs.h>. */
#ifndef _RLIBC_CDEFS_H
#define _RLIBC_CDEFS_H 1
""" + "\n".join(cdefs) + "\n\n#endif\n")
print(len(lim), "limit macros,", len(cdefs), "cdefs macros")
