#!/usr/bin/env python3
import argparse
import json
import os
import re
import subprocess
import sys

LIBS = ["libc.so.6", "libm.so.6", "libpthread.so.0", "libdl.so.2", "librt.so.1", "libutil.so.1",
        "libresolv.so.2", "libanl.so.1", "ld-linux-x86-64.so.2"]
INTERPOSE = {"malloc", "free", "calloc", "realloc", "memalign", "aligned_alloc", "posix_memalign", "valloc",
             "pvalloc", "malloc_usable_size", "reallocarray"}


def vkey(v):
    m = re.match(r"GLIBC_(\d+(?:\.\d+)*)$", v)
    return (0, tuple(int(x) for x in m.group(1).split("."))) if m else (1, v)


def readelf(*args):
    return subprocess.run(["readelf", "-W", *args], capture_output=True, text=True, check=True,
                          env={**os.environ, "LC_ALL": "C"}).stdout


def parse(path):
    verdefs = {}
    soname = None
    order = []
    cur = None
    for line in readelf("-V", path).splitlines():
        m = re.search(r"Index: (\d+)\s+Cnt: (\d+)\s+Name: (\S+)", line)
        if m:
            cur = m.group(3)
            if "BASE" in line:
                soname = cur
                cur = None
                continue
            verdefs[cur] = None
            order.append(cur)
            continue
        m = re.search(r"Parent \d+: (\S+)", line)
        if m and cur:
            verdefs[cur] = m.group(1)
    syms = []
    for line in readelf("--dyn-syms", path).splitlines():
        f = line.split()
        if len(f) < 8 or not f[0].endswith(":") or f[0] == "Num:":
            continue
        ndx = f[6]
        if ndx in ("UND", "ABS"):
            continue
        name = f[7]
        m = re.match(r"([^@]+)(@@?)(\S+)", name)
        if not m:
            syms.append(dict(name=name, version=None, default=True, type=f[3], bind=f[4], size=int(f[2])))
            continue
        syms.append(dict(name=m.group(1), version=m.group(3), default=(m.group(2) == "@@"),
                         type=f[3], bind=f[4], size=int(f[2])))
    return dict(soname=soname, verdefs=[dict(name=n, parent=verdefs[n]) for n in order], symbols=syms)


def script(nodes, syms_by_node, local=True, comment=""):
    out = [comment] if comment else []
    for idx, (n, parent) in enumerate(nodes):
        out.append("%s {" % n)
        names = sorted(syms_by_node.get(n, ()))
        if names:
            out.append("  global:")
            out += ["    %s;" % s for s in names]
        if local and idx == len(nodes) - 1:
            out.append("  local:\n    *;")
        out.append("}%s;" % (" " + parent if parent else ""))
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--libdir", default="/usr/lib64")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "crates", "rusty-libc-cabi", "shared"))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    info = {}
    for lib in LIBS:
        p = os.path.join(a.libdir, lib)
        if not os.path.exists(p):
            print("missing", p, file=sys.stderr)
            continue
        info[lib] = parse(p)
        with open(os.path.join(a.out, lib + ".json"), "w") as f:
            json.dump(info[lib], f, indent=1)
            f.write("\n")
    libc_nodes = {d["name"]: d["parent"] for d in info["libc.so.6"]["verdefs"]}
    allnodes = set(libc_nodes)
    for lib, i in info.items():
        if lib != "ld-linux-x86-64.so.2":
            allnodes |= {d["name"] for d in i["verdefs"]}
    nodes = []
    prev = None
    added = []
    for n in sorted(allnodes, key=vkey):
        if n in libc_nodes:
            nodes.append((n, libc_nodes[n]))
        else:
            nodes.append((n, prev))
            added.append(n)
        prev = n
    nodes.sort(key=lambda t: t[0] == "GLIBC_PRIVATE")
    by_node = {}
    compat = []
    for lib, i in info.items():
        if lib == "ld-linux-x86-64.so.2":
            continue
        for s in i["symbols"]:
            if s["version"] is None:
                continue
            if s["default"]:
                by_node.setdefault(s["version"], set()).add(s["name"])
            else:
                compat.append("%s@%s %s %s %d %s" % (s["name"], s["version"], s["type"], s["bind"], s["size"], lib))
    extra_path = os.path.join(a.out, "extra-exports.txt")
    if os.path.exists(extra_path):
        for line in open(extra_path):
            line = line.split("#")[0].split()
            if line:
                by_node.setdefault(line[1], set()).add(line[0])
    text = script(nodes, by_node, comment="/* generated by tools/gen_versions.py from the system's glibc; do not edit.\n   Nodes added to libc.so.6's own list (they belong to other glibc libraries): %s */" % ", ".join(added))
    open(os.path.join(a.out, "libc.map"), "w").write(text)
    with open(os.path.join(a.out, "compat.txt"), "w") as f:
        f.write("\n".join(sorted(compat)) + "\n")
    for lib, i in info.items():
        if lib in ("libc.so.6", "ld-linux-x86-64.so.2"):
            continue
        ns = [(d["name"], d["parent"]) for d in i["verdefs"]]
        stub_syms = {}
        for d in i["verdefs"]:
            if not d["name"].startswith("GLIBC_ABI"):
                stub_syms[d["name"]] = {"__stub_" + d["name"].replace(".", "_")}
        open(os.path.join(a.out, lib + ".stub.map"), "w").write(script(ns, stub_syms, comment="/* generated by tools/gen_versions.py */"))
    li = info["ld-linux-x86-64.so.2"]
    lnodes = [(d["name"], d["parent"]) for d in li["verdefs"]]
    lby = {}
    for s in li["symbols"]:
        if s["version"] and s["default"]:
            lby.setdefault(s["version"], set()).add(s["name"])
    extra = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "crates", "rusty-libc-ldso", "exports.txt")
    if os.path.exists(extra):
        for line in open(extra):
            line = line.split("#")[0].strip()
            if line:
                lby.setdefault("GLIBC_PRIVATE", set()).add(line)
    open(os.path.join(a.out, "ld.map"), "w").write(script(lnodes, lby, comment="/* generated by tools/gen_versions.py: what ld-linux-x86-64.so.2 exports */"))
    dyn = set()
    for lib, i in info.items():
        if lib == "ld-linux-x86-64.so.2":
            continue
        for s in i["symbols"]:
            if s["version"] and (s["type"] in ("OBJECT", "TLS") or (s["default"] and s["name"] in INTERPOSE)):
                dyn.add(s["name"])
    with open(os.path.join(a.out, "libc.dynlist"), "w") as f:
        f.write("{\n" + "".join("  %s;\n" % n for n in sorted(dyn)) + "};\n")
    nd = sum(len(v) for v in by_node.values())
    print("libc.map: %d nodes (%d added), %d default symbols, %d compat symbols, %d interposable" % (len(nodes), len(added), nd, len(compat), len(dyn)))


main()
