#!/usr/bin/env python3
import os

LO, HI = -342, 308


def entry(q):
    if q >= 0:
        p = 5 ** q
        bl = p.bit_length()
        v = p >> (bl - 128) if bl > 128 else p << (128 - bl)
    else:
        n = 5 ** (-q)
        z = (n - 1).bit_length()
        if q >= -27:
            v = (1 << (z + 127)) // n + 1
        else:
            v = (1 << (2 * z + 128)) // n + 1
            while v >= 1 << 128:
                v >>= 1
    assert v.bit_length() == 128
    return v >> 64, v & ((1 << 64) - 1)


def main():
    rows = [entry(q) for q in range(LO, HI + 1)]
    out = ["//! 128-bit powers of five for the Eisel-Lemire conversion (generated by tools/gen_pow5.py; do not edit).",
           "//! Entry `i` is 5^(i + SMALLEST_POW5) as (high word, low word), normalised so the top bit is set.",
           "",
           f"pub const SMALLEST_POW5: i64 = {LO};",
           f"pub const LARGEST_POW5: i64 = {HI};",
           "",
           f"pub static POW5_128: [(u64, u64); {len(rows)}] = ["]
    for i in range(0, len(rows), 3):
        out.append("    " + " ".join(f"(0x{h:016x}, 0x{l:016x})," for h, l in rows[i:i + 3]))
    out.append("];")
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "crates", "rusty-libc-core", "src", "pow5.rs")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.normpath(path), len(rows), "entries")


main()
