#!/usr/bin/env python3
import math

P = 700
ONE = 1 << P


def atanh_inv(n, prec=P):
    one = 1 << prec
    x = one // n
    n2 = n * n
    s = 0
    k = 1
    while x:
        s += x // k
        x //= n2
        k += 2
    return s


def ln_ratio(num, den):
    a, b = num - den, num + den
    sign = 1
    if a < 0:
        a, sign = -a, -1
    x = (a * ONE) // b
    x2 = (x * x) >> P
    s = 0
    k = 1
    t = x
    while t:
        s += t // k
        t = (t * x2) >> P
        k += 2
    return sign * 2 * s


LN2 = 2 * atanh_inv(3)
LN10 = 3 * LN2 + ln_ratio(5, 4)


def atan_inv(n, prec):
    one = 1 << prec
    x = one // n
    n2 = n * n
    s = x
    k = 1
    sign = -1
    while x:
        x //= n2
        k += 2
        s += sign * (x // k)
        sign = -sign
    return s


def pi_fp(prec):
    return 4 * (4 * atan_inv(5, prec + 16) - atan_inv(239, prec + 16)) >> 16


PI = pi_fp(P)


def atan_fp(num, den):
    x = (num * ONE) // den
    for _ in range(5):
        s = math.isqrt(ONE * ONE + x * x)
        x = (x * ONE) // (ONE + s)
    x2 = (x * x) >> P
    t = x
    s = 0
    k = 1
    sign = 1
    while t:
        s += sign * (t // k)
        t = (t * x2) >> P
        k += 2
        sign = -sign
    return s << 5


def ext(f):
    assert f > 0
    L = f.bit_length()
    sh = L - 128
    m = (f + (1 << (sh - 1))) >> sh
    e = L - 1 - P
    if m >> 128:
        m >>= 1
        e += 1
    return e, m


def fmt(f):
    e, m = ext(f)
    return "Ext::c(false, %d, 0x%032x)" % (e, m)


def recip(f):
    return (ONE * ONE) // f


out = ["// Generated by gen_consts.py. Do not edit.", "use super::ext::Ext;", ""]
consts = {
    "LN2": LN2, "LN10": LN10, "LOG2E": recip(LN2), "LOG10E": recip(LN10),
    "LOG2_10": LN10 * ONE // LN2, "LOG10_2": LN2 * ONE // LN10,
    "PI": PI, "PIO2": PI // 2, "PIO4": PI // 4, "TWO_PI": PI * 2,
    "SQRT2": math.isqrt(2 * ONE * ONE), "INV_PI": recip(PI), "THREE_PIO4": PI * 3 // 4,
}
for n, f in consts.items():
    out.append("pub const %s: Ext = %s;" % (n, fmt(f)))
out.append("/// ln(1 + j/128) for j = 1..=128 (entry j - 1).")
out.append("pub static LOG_TAB: [Ext; 128] = [")
for j in range(1, 129):
    out.append("    %s," % fmt(ln_ratio(128 + j, 128)))
out.append("];")
out.append("/// atan(j/32) for j = 1..=32 (entry j - 1).")
out.append("pub static ATAN_TAB: [Ext; 32] = [")
for j in range(1, 33):
    out.append("    %s," % fmt(atan_fp(j, 32)))
out.append("];")
NB = 16900 + 128
pi_big = pi_fp(NB + 64)
two_over_pi = (((1 << (NB + 64)) * 2) << (NB + 64)) // pi_big >> 64
words = []
nwords = NB // 64
v = two_over_pi
for w in range(nwords):
    words.append((v >> (NB - 64 * (w + 1))) & ((1 << 64) - 1))
out.append("/// The bits of 2/pi after the binary point (word 0 holds bits 1..=64).")
out.append("pub static TWO_OVER_PI: [u64; %d] = [" % len(words))
for i in range(0, len(words), 4):
    out.append("    " + ", ".join("0x%016x" % w for w in words[i:i + 4]) + ",")
out.append("];")

from fractions import Fraction


def bernoulli(n):
    B = [Fraction(0)] * (n + 1)
    B[0] = Fraction(1)
    for m in range(1, n + 1):
        B[m] = -sum(math.comb(m + 1, k) * B[k] for k in range(m)) / (m + 1)
    return B


BERN = bernoulli(80)


def fp_frac(fr):
    return (fr.numerator * ONE) // fr.denominator


def ln_real(v):
    k = 0
    while v >= (3 * ONE) // 2:
        v >>= 1
        k += 1
    while v < (3 * ONE) // 4:
        v <<= 1
        k -= 1
    neg = v < ONE
    z = (abs(v - ONE) * ONE) // (v + ONE)
    z2 = (z * z) >> P
    t = z
    r = 0
    n = 1
    while t:
        r += t // n
        t = (t * z2) >> P
        n += 2
    return (-2 * r if neg else 2 * r) + k * LN2


BERN_FP = [fp_frac(b) for b in BERN]


def zeta_fp(k, N=60):
    s = sum(ONE // (n ** k) for n in range(1, N))
    s += ONE // ((k - 1) * N ** (k - 1)) + ONE // (2 * N ** k)
    for j in range(1, 40):
        rf = 1
        for i in range(2 * j - 1):
            rf *= (k + i)
        s += (BERN_FP[2 * j] * rf) // (math.factorial(2 * j) * N ** (k + 2 * j - 1))
    return s


def gamma_euler_fp(N=100):
    h = sum(ONE // n for n in range(1, N + 1))
    s = h - ONE // (2 * N)
    for k in range(1, 40):
        s += BERN_FP[2 * k] // (2 * k * N ** (2 * k))
    return s - ln_real(N * ONE)


def fmts(f):
    return ("Ext::c(true, %d, 0x%032x)" % ext(-f)[:1] + "") if False else None


def fmt_signed(f):
    e, m = ext(abs(f))
    return "Ext::c(%s, %d, 0x%032x)" % ("true" if f < 0 else "false", e, m)


SQRT_PI = math.isqrt(PI * ONE)
special = {
    "GAMMA_E": gamma_euler_fp(),
    "SQRT_PI": SQRT_PI,
    "INV_SQRT_PI": (ONE * ONE) // SQRT_PI,
    "TWO_OVER_SQRT_PI": (2 * ONE * ONE) // SQRT_PI,
    "LN_PI": ln_real(PI),
}
special["HALF_LN_2PI"] = (LN2 + special["LN_PI"]) // 2
for n, f in special.items():
    out.append("pub const %s: Ext = %s;" % (n, fmt(f)))
out.append("/// B_2k / (2k (2k - 1)) for k = 1..=24 (Stirling series of ln Gamma).")
out.append("pub static STIRLING: [Ext; 24] = [")
for k in range(1, 25):
    out.append("    %s," % fmt_signed(fp_frac(BERN[2 * k] / (2 * k * (2 * k - 1)))))
out.append("];")
out.append("/// zeta(k) for k = 2..=130 (entry k - 2).")
out.append("pub static ZETA: [Ext; 129] = [")
for k in range(2, 131):
    out.append("    %s," % fmt(zeta_fp(k)))
out.append("];")


out.append("/// 1/n for n = 1..=1100 (entry n - 1): dividing by a small integer is a multiplication.")
out.append("pub static RECIP: [Ext; 1100] = [")
for n in range(1, 1101):
    out.append("    %s," % fmt(ONE // n))
out.append("];")

def q126(f):
    return (f * (1 << 126) + (ONE >> 1)) // ONE


def fact_inv(n):
    return ONE // math.factorial(n)


def fmtq(name, vals):
    out.append("pub static %s: [u128; %d] = [" % (name, len(vals)))
    for v in vals:
        out.append("    0x%032x," % q126(v))
    out.append("];")


out.append("/// Q126 coefficients (value * 2^126) of the series evaluated in fixed point by `fx::horner`.")
out.append("/// 1/(k+1)!, k = 0..=15: expm1(r)/r = sum r^k/(k+1)!")
fmtq("E1COEF", [fact_inv(k + 1) for k in range(16)])
out.append("/// 1/(2k+1)!, k = 0..=17: sin(r)/r = sum (-1)^k r^(2k)/(2k+1)!")
fmtq("SINCOEF", [fact_inv(2 * k + 1) for k in range(18)])
out.append("/// 1/(2k)!, k = 0..=17: cos(r) = sum (-1)^k r^(2k)/(2k)!")
fmtq("COSCOEF", [fact_inv(2 * k) for k in range(18)])
out.append("/// 1/(2n+1), n = 0..=11: atanh and atan series")
fmtq("ODDRECIP", [ONE // (2 * n + 1) for n in range(12)])


def exp_fp(xf):
    t = ONE
    s = ONE
    n = 1
    while t:
        t = (t * xf >> P) // n
        s += t
        n += 1
    return s


out.append("/// 2^(j/32), j = 0..=31")
out.append("pub static EXP2_32: [Ext; 32] = [")
for j in range(32):
    out.append("    %s," % (fmt(exp_fp(LN2 * j // 32)) if j else "Ext::c(false, 0, 1 << 127)"))
out.append("];")
print("\n".join(out))
