#!/usr/bin/env python3
from fractions import Fraction
import math

P = 500
ONE = 1 << P


def atanh_inv(n):
    x = ONE // n
    n2 = n * n
    s = 0
    k = 1
    while x:
        s += x // k
        x //= n2
        k += 2
    return s


LN2 = 2 * atanh_inv(3)


def fp_mul(a, b):
    return (a * b) >> P


def ln_ratio(num, den):
    a, b = num - den, num + den
    sign = 1
    if a < 0:
        a, sign = -a, -1
    x = (a * ONE) // b
    x2 = fp_mul(x, x)
    s, k, t = 0, 1, x
    while t:
        s += t // k
        t = fp_mul(t, x2)
        k += 2
    return sign * 2 * s


def ln_int(n):
    k = max(0, n.bit_length() - 1)
    m = Fraction(n, 1 << k)
    return fp_ln_frac(m) + k * LN2


def fp_ln_frac(m):
    num, den = m.numerator, m.denominator
    return ln_ratio(num, den)


def ln_frac(m):
    k = 0
    while m >= 2:
        m /= 2
        k += 1
    while m < 1:
        m *= 2
        k -= 1
    return fp_ln_frac(m) + k * LN2


def exp_fp(x):
    s = ONE
    t = ONE
    k = 1
    while t:
        t = fp_mul(t, x) // k if t > 0 else -((-fp_mul(t, x)) // k)
        s += t
        k += 1
        if k > 400:
            break
    return s


def exp2_frac(num, den):
    return exp_fp(num * LN2 // den)


def frac(v):
    return Fraction(v, ONE)


def dd(v):
    hi = float(v)
    lo = float(v - Fraction(hi))
    return hi, lo


def trunc_bits(v, nbits):
    e = 0
    t = v
    while t >= 2:
        t /= 2
        e += 1
    while t < 1:
        t *= 2
        e -= 1
    scaled = v * Fraction(2) ** (nbits - 1 - e)
    return Fraction(int(scaled)) / Fraction(2) ** (nbits - 1 - e)


def pieces(v, n, bits=30):
    out = []
    r = v
    for i in range(n - 1):
        c = trunc_bits(r, bits)
        out.append(c)
        r = r - c
    out.append(r)
    return [float(c) for c in out]


def fmt(x):
    return repr(float(x))


def emit_pair_table(name, rows, doc):
    print(f"/// {doc}")
    print(f"pub const {name}: [[f64; 2]; {len(rows)}] = [")
    for hi, lo in rows:
        print(f"    [{fmt(hi)}, {fmt(lo)}],")
    print("];")
    print()


def emit_const(name, v, doc):
    print(f"/// {doc}")
    print(f"pub const {name}: f64 = {fmt(v)};")


def emit_dd(name, v, doc):
    hi, lo = dd(v)
    print(f"/// {doc}")
    print(f"pub const {name}: (f64, f64) = ({fmt(hi)}, {fmt(lo)});")


print("//! Tables and constants of the double-double fast paths (fast.rs). Generated by gen_fast.py; do not edit.")
print("#![allow(clippy::approx_constant, clippy::excessive_precision, clippy::unreadable_literal)]")
print()

ln2 = frac(LN2)
emit_pair_table("EXP2_256", [dd(frac(exp2_frac(j, 256))) for j in range(256)], "2^(j/256), j = 0..255, as (hi, lo).")
emit_const("INV_LN2_256", float(Fraction(256) / ln2), "256 / ln 2.")
for i, c in enumerate(pieces(ln2 / 256, 4)):
    emit_const(f"LN2_256_{i + 1}", c, f"Piece {i + 1} of ln2/256 (pieces 1-3 have 30 significant bits, so k times them is exact for |k| < 2^22).")
emit_dd("LN2_DD", ln2, "ln 2.")
LN10 = ln_int(10)
emit_dd("LOG2_10_DD", frac(LN10) / ln2, "log2(10).")
emit_dd("LOG2_E_DD", 1 / ln2, "1 / ln 2.")
emit_dd("LOG10_E_DD", 1 / frac(LN10), "1 / ln 10.")


def log_table():
    rows = []
    for j in range(512):
        m = Fraction(1) + Fraction(2 * j + 1, 1024)
        if j >= 212:
            m = m / 2
        c = float(1 / m)
        lc = -frac(ln_frac(Fraction(c)))
        hi, lo = dd(lc)
        rows.append((c, hi, lo))
    return rows


rows = log_table()
print("/// Log table: [c_j, hi, lo] with c_j = 1/m for the centre m of bin j of the fraction (m in [1, 1.414) for")
print("/// j < 212, m/2 for the other bins) and hi + lo = -ln(c_j).")
print(f"pub const LOG_TAB: [[f64; 3]; 512] = [")
for c, hi, lo in rows:
    print(f"    [{fmt(c)}, {fmt(hi)}, {fmt(lo)}],")
print("];")
print()
for i, c in enumerate(pieces(ln2, 2, 38)):
    emit_const(f"LN2_P{i + 1}", c, f"Piece {i + 1} of ln 2 (piece 1 has 38 significant bits: E times it is exact for |E| < 2^15).")
emit_dd("ONE_THIRD_DD", Fraction(1, 3), "1/3.")


def atan_inv(n):
    x = ONE // n
    n2 = n * n
    s = x
    k = 1
    sign = -1
    while x:
        x //= n2
        k += 2
        s += sign * (x // k)
        sign = -sign
    return s


PI = 4 * (4 * atan_inv(5) - atan_inv(239))


def atan_fp(num, den):
    x = (num * ONE) // den
    h = 0
    for _ in range(6):
        sq = math.isqrt(ONE * ONE + x * x)
        x = (x * ONE) // (ONE + sq)
        h += 1
    x2 = fp_mul(x, x)
    term = x
    s = x
    k = 1
    sign = -1
    while term:
        term = fp_mul(term, x2)
        k += 2
        s += sign * (term // k)
        sign = -sign
    return s << h


emit_pair_table("ATAN_TAB", [(0.0, 0.0)] + [dd(frac(atan_fp(j, 256))) for j in range(1, 257)], "atan(j/256), j = 0..=256, as (hi, lo).")
emit_dd("PI_DD", frac(PI), "pi.")
emit_dd("PIO2_DD", frac(PI) / 2, "pi/2.")
emit_dd("ONE_SIXTH_DD", Fraction(1, 6), "1/6.")


def sincos_fp(num, den):
    x = (num * ONE) // den
    x2 = fp_mul(x, x)
    s = x
    c = ONE
    ts = x
    tc = ONE
    k = 1
    while ts or tc:
        tc = -fp_mul(tc, x2) // ((k) * (k + 1)) if tc >= 0 else fp_mul(-tc, x2) // ((k) * (k + 1))
        ts = -fp_mul(ts, x2) // ((k + 1) * (k + 2)) if ts >= 0 else fp_mul(-ts, x2) // ((k + 1) * (k + 2))
        c += tc
        s += ts
        k += 2
        if k > 300:
            break
    return s, c


print("/// [sin hi, sin lo, cos hi, cos lo] of j/128, j = 0..=101.")
print("pub const SINCOS_TAB: [[f64; 4]; 102] = [")
for j in range(102):
    sv, cv = sincos_fp(j, 128)
    sh, sl = dd(frac(sv))
    ch, cl = dd(frac(cv))
    print(f"    [{fmt(sh)}, {fmt(sl)}, {fmt(ch)}, {fmt(cl)}],")
print("];")
print()
for i, c in enumerate(pieces(frac(PI) / 2, 4, 30)):
    emit_const(f"PIO2_P{i + 1}", c, f"Piece {i + 1} of pi/2 (pieces 1-3 have 30 significant bits: k times them is exact for |k| < 2^22).")
emit_const("TWO_OVER_PI", float(2 / frac(PI)), "2 / pi.")
emit_dd("TWO_OVER_PI_DD", 2 / frac(PI), "2 / pi.")
emit_dd("INV_PI_DD", 1 / frac(PI), "1 / pi.")
emit_dd("LN_PI_DD", frac(ln_frac(frac(PI))), "ln(pi).")
