#!/usr/bin/env python3
import os, subprocess, sys, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "composedata")
SPECS = {"CP1255": "CP1255//", "CP1258": "CP1258//", "TCVN5712_1": "TCVN5712-1//"}

def probe(mode, iname, inp=None):
    exe = os.path.join(tempfile.gettempdir(), "mbprobe")
    subprocess.check_call(["gcc", "-O1", "-w", os.path.join(HERE, "mbprobe.c"), "-o", exe])
    return subprocess.run([exe, mode, iname], input=inp, capture_output=True, check=True).stdout.decode().split("\n")

def run(inp, iname):
    out = {}
    for line in probe("decf", iname, inp.encode()):
        f = line.split()
        if len(f) >= 2 and f[1] == "ok":
            out[bytes.fromhex(f[0])] = [int(x, 16) for x in f[2].split(",")] if len(f) > 2 else []
    return out

def build(name, iname):
    singles = run("".join("%02x\n" % b for b in range(256)), iname)
    dec = {k[0]: v[0] for k, v in singles.items() if len(v) == 1}
    pairs_in = "".join("%02x%02x\n" % (a, b) for a in dec for b in dec)
    pairs = run(pairs_in, iname)
    comp = {}
    for k, v in pairs.items():
        if len(v) == 1:
            comp[(dec[k[0]], dec[k[1]])] = v[0]
    marks = sorted({m for (_, m) in comp})
    bases = sorted({b for (b, _) in comp})
    mark_bytes = [b for b in dec if dec[b] in marks]
    base_bytes = [b for b in dec if dec[b] in bases]
    trip = "".join("%02x%02x%02x\n" % (a, b, c) for a in base_bytes for b in mark_bytes for c in mark_bytes)
    for k, v in run(trip, iname).items():
        if len(v) == 1:
            x = comp.get((dec[k[0]], dec[k[1]]))
            if x is not None and (x, dec[k[2]]) not in comp:
                comp[(x, dec[k[2]])] = v[0]
    enc = {}
    for line in probe("enc", iname):
        f = line.split()
        if len(f) >= 2:
            enc[int(f[0], 16)] = bytes.fromhex(f[1])
    enc1 = sorted((cp << 8 | b[0]) for cp, b in enc.items() if len(b) == 1 and cp < 0x10000)
    decomp = sorted((cp, b) for cp, b in enc.items() if len(b) > 1)
    assert all(len(b) <= 3 for _, b in decomp)
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name.lower() + ".rs"), "w") as f:
        f.write("// Generated by tools/gen_compose.py from the host's glibc (%s); do not edit.\nuse crate::compose::Comp;\n\n" % iname)
        f.write("static DEC: [u16; 256] = [\n")
        for i in range(0, 256, 16):
            f.write("    " + ", ".join("0x%04x" % dec.get(b, 0xffff) for b in range(i, i + 16)) + ",\n")
        f.write("];\nstatic ENC1: [u32; %d] = [\n" % len(enc1))
        for i in range(0, len(enc1), 12):
            f.write("    " + ", ".join("0x%x" % x for x in enc1[i:i+12]) + ",\n")
        cl = sorted((m, b, c) for (b, m), c in comp.items())
        f.write("];\nstatic COMP: [(u16, u16, u16); %d] = [\n" % len(cl))
        for i in range(0, len(cl), 6):
            f.write("    " + ", ".join("(0x%x, 0x%x, 0x%x)" % (m, b, c) for m, b, c in cl[i:i+6]) + ",\n")
        f.write("];\nstatic DECOMP: [(u16, u8, [u8; 3]); %d] = [\n" % len(decomp))
        for i in range(0, len(decomp), 5):
            f.write("    " + ", ".join("(0x%x, %d, [%s])" % (cp, len(b), ", ".join("0x%02x" % x for x in b.ljust(3, b"\0"))) for cp, b in decomp[i:i+5]) + ",\n")
        f.write("];\n\npub static COMP_%s: Comp = Comp { dec: &DEC, enc1: &ENC1, comp: &COMP, decomp: &DECOMP };\n" % name)
    sys.stderr.write("%s: %d bytes, %d compositions, %d decompositions, %d single-byte encodes\n" % (name, len(dec), len(comp), len(decomp), len(enc1)))

if __name__ == "__main__":
    for n in sys.argv[1:]:
        build(n, SPECS[n])
