#!/usr/bin/env python3
import os, subprocess, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
SETS = [("J0208", "3042"), ("J0212", "02d8"), ("GB2312", "2236"), ("KSC5601", "ac00")]
with tempfile.TemporaryDirectory() as d:
    exe = os.path.join(d, "jpprobe")
    subprocess.check_call(["gcc", "-O1", "-w", os.path.join(HERE, "jpprobe.c"), "-o", exe])
    print("// Generated by tools/gen_jp_extra.py from the host's glibc; do not edit.")
    print("// (character, two-byte code) for the characters up to U+00FF and U+203E, per set.\n")
    for name, seed in SETS:
        out = subprocess.check_output([exe, "ISO-2022-JP-2//", seed]).decode().split("\n")
        ent = sorted((int(l.split()[0], 16), int(l.split()[1], 16)) for l in out if l.strip())
        print("pub static %s: [(u16, u16); %d] = [" % (name, len(ent)))
        for i in range(0, len(ent), 8):
            print("    " + ", ".join("(0x%x, 0x%04x)" % e for e in ent[i:i+8]) + ",")
        print("];\n")
