#!/usr/bin/env python3
import ctypes, struct, sys

libc = ctypes.CDLL(None, use_errno=True)
libc.iconv_open.restype = ctypes.c_void_p
libc.iconv_open.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
libc.iconv.restype = ctypes.c_size_t
libc.iconv.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t), ctypes.POINTER(ctypes.c_char_p), ctypes.POINTER(ctypes.c_size_t)]


def run(to, frm, data):
    cd = libc.iconv_open(to, frm)
    assert cd != ctypes.c_void_p(-1).value and cd, (to, frm)
    ibuf = ctypes.create_string_buffer(data, len(data))
    obuf = ctypes.create_string_buffer(64)
    ip = ctypes.c_char_p(ctypes.addressof(ibuf))
    op = ctypes.c_char_p(ctypes.addressof(obuf))
    il, ol = ctypes.c_size_t(len(data)), ctypes.c_size_t(64)
    r = libc.iconv(cd, ctypes.byref(ip), ctypes.byref(il), ctypes.byref(op), ctypes.byref(ol))
    if r == ctypes.c_size_t(-1).value:
        libc.iconv_close(ctypes.c_void_p(cd))
        return None
    r2 = libc.iconv(cd, None, None, ctypes.byref(op), ctypes.byref(ol))
    libc.iconv_close(ctypes.c_void_p(cd))
    if r2 == ctypes.c_size_t(-1).value:
        return None
    return obuf.raw[: 64 - ol.value]


def dec(b):
    o = run(b"UTF-32LE", b"TSCII", bytes(b))
    if o is None:
        return None
    return list(struct.unpack("<%dI" % (len(o) // 4), o))


def enc(cps):
    o = run(b"TSCII", b"UTF-32LE", b"".join(struct.pack("<I", c) for c in cps))
    return None if o is None else list(o)


SPECIAL = {0x82, 0x87, 0x8A, 0x8B, 0x8C, 0xA6, 0xA7, 0xA8}
to_ucs4 = []
for b in range(0x80, 0x100):
    if b in SPECIAL:
        to_ucs4.append([0, 0])
        continue
    r = dec([b])
    if r is None:
        to_ucs4.append([0, 0])
    else:
        assert 1 <= len(r) <= 2, (hex(b), r)
        to_ucs4.append((r + [0])[:2])
from_tab = []
for c in range(0xB80, 0xC00):
    r = enc([c])
    from_tab.append(r[0] if r is not None and len(r) == 1 else 0)
cons = [b for b in range(0xB8, 0xCA)]
inv = {}
for c in range(0xB80, 0xC00):
    if from_tab[c - 0xB80] in cons:
        inv[from_tab[c - 0xB80]] = c
assert len(inv) == 18, inv


def comb(sign):
    out = []
    for b in cons:
        r = enc([inv[b], sign])
        assert r is not None and len(r) == 1, (hex(b), sign, r)
        out.append(r[0])
    return out


cu, cuu, cv = comb(0xBC1), comb(0xBC2), comb(0xBCD)
for i, b in enumerate(range(0x80, 0x100)):
    if to_ucs4[i][0] and to_ucs4[i][1] == 0 and to_ucs4[i][0] >= 0xB80 and b not in cons:
        pass


def arr(name, ty, vals, per, fmt):
    s = "pub static %s: %s = [\n" % (name, ty)
    for i in range(0, len(vals), per):
        s += "    " + ", ".join(fmt % v if not isinstance(v, list) else "[0x%04x, 0x%04x]" % tuple(v) for v in vals[i:i + per]) + ",\n"
    return s + "];\n"


print("// Generated by tools/gen_tscii.py from the host's iconv; do not edit.")
print(arr("TO_UCS4", "[[u16; 2]; 128]", to_ucs4, 4, "%s"))
print(arr("UCS4_TO_TSCII", "[u8; 128]", from_tab, 16, "0x%02x"))
print(arr("CONSONANT_WITH_U", "[u8; 18]", cu, 9, "0x%02x"))
print(arr("CONSONANT_WITH_UU", "[u8; 18]", cuu, 9, "0x%02x"))
print(arr("CONSONANT_WITH_VIRAMA", "[u8; 18]", cv, 9, "0x%02x"))
