#!/usr/bin/env python3
import ctypes, os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "mbdata", "isoir165.rs")

lib = ctypes.CDLL("/usr/lib64/gconv/libISOIR165.so")
to = (ctypes.c_uint16 * (94 * 94)).in_dll(lib, "__isoir165_to_tab")
gbase = ctypes.addressof(ctypes.c_char.in_dll(lib, "__isoir165_from_idx"))
fbase = ctypes.addressof(ctypes.c_char.in_dll(lib, "__isoir165_from_tab"))
gaps = []
i = 0
while True:
    s, e, idx = struct.unpack("<HHi", ctypes.string_at(gbase + 8 * i, 8))
    gaps.append((s, e, idx))
    i += 1
    if e == 0xffff:
        break


def enc(ch):
    if ch > 0xffe5:
        return None
    for s, e, idx in gaps:
        if ch <= e:
            if ch < s:
                return None
            b = ctypes.string_at(fbase + (ch + idx) * 2, 2)
            return None if b[0] == 0 else b
    return None


dec = {}
for r in range(94):
    for c in range(94):
        v = to[r * 94 + c]
        if v:
            dec[(r, c)] = v
rev = {}
for ch in range(0xffe6):
    b = enc(ch)
    if b:
        rev[ch] = (b[0] - 0x21, b[1] - 0x21)
assert len(set(dec.values())) == len(dec), "two codes share a character"
assert all(dec.get(rc) == ch for ch, rc in rev.items()) and len(rev) == len(dec), "tables are not inverse"

base = 256
data = [dec.get((k // 94, k % 94), 0) for k in range(94 * 94)]
pairs = sorted((ch, base + r * 94 + c) for ch, (r, c) in rev.items())


def arr(n, ty, v, per, fmt):
    s = "pub static %s: [%s; %d] = [\n" % (n, ty, len(v))
    for k in range(0, len(v), per):
        s += "    " + ", ".join(fmt % x for x in v[k:k + per]) + ",\n"
    return s + "];\n"


with open(OUT, "w") as f:
    f.write("// Generated by tools/gen_isoir165.py from the host's libISOIR165.so; do not edit.\nuse crate::mb::{Mb, Set};\n\n")
    f.write("pub static D0: [u16; 256] = [0; 256];\n")
    f.write(arr("D1", "u16", data, 16, "0x%04x"))
    f.write("pub static WIDE: [(u32, u32); 0] = [];\n")
    f.write(arr("ENC_CP", "u16", [p[0] for p in pairs], 16, "0x%04x"))
    f.write(arr("ENC_POS", "u16", [p[1] for p in pairs], 16, "0x%04x"))
    f.write("pub static EXTRA: [(u32, u32, u8); 0] = [];\n")
    f.write("pub static RDEC: [(u32, u32, u32); 0] = [];\npub static RENC: [(u32, u32, u32); 0] = [];\n")
    f.write("\npub static MB: Mb = Mb {\n    sets: &[\n")
    f.write("        Set { prefix: &[], lead_lo: 0x0, lead_hi: 0xff, trail_lo: 0x0, trail_hi: 0x0, nbytes: 1, base: 0, data: &D0 },\n")
    f.write("        Set { prefix: &[], lead_lo: 0x21, lead_hi: 0x7e, trail_lo: 0x21, trail_hi: 0x7e, nbytes: 2, base: 256, data: &D1 },\n")
    f.write("    ],\n    wide: &WIDE,\n    enc_cp: &ENC_CP,\n    enc_pos: &ENC_POS,\n    extra: &EXTRA,\n    runs_dec: &RDEC,\n    runs_enc: &RENC,\n};\n")
sys.stderr.write("isoir165: %d characters\n" % len(dec))
