#!/usr/bin/env python3
import os, subprocess, tempfile
HERE = os.path.dirname(os.path.abspath(__file__))
exe = os.path.join(tempfile.gettempdir(), "mbprobe_conv")
subprocess.check_call(["gcc", "-O1", "-w", os.path.join(HERE, "mbprobe.c"), "-o", exe])

def conv(to, frm, seqs):
    inp = "".join(s + "\n" for s in seqs)
    out = subprocess.run([exe, "conv", to, frm], input=inp.encode(), capture_output=True, check=True).stdout.decode().split("\n")
    res = {}
    for line in out:
        f = line.split()
        if len(f) == 3 and f[1] == "ok": res[f[0]] = f[2]
    return res

def arr(name, ty, vals, per=12, fmt="0x%04x"):
    s = "pub static %s: [%s; %d] = [\n" % (name, ty, len(vals))
    for i in range(0, len(vals), per): s += "    " + ", ".join(fmt % v for v in vals[i:i+per]) + ",\n"
    return s + "];\n"

print("// Generated by tools/gen_direct.py from the host's glibc; do not edit.\n")
seqs = ["%02x%02x" % (a, b) for a in range(0xa1, 0xf8) for b in range(0xa1, 0xff)]
r = conv("BIG5//", "EUC-CN//", seqs)
print(arr("GB_TO_BIG5", "u16", [int(r.get(s, "0"), 16) for s in seqs]))
cols = list(range(0x40, 0x7f)) + list(range(0xa1, 0xff))
seqs = ["%02x%02x" % (a, b) for a in range(0xa1, 0xfa) for b in cols]
r = conv("EUC-CN//", "BIG5//", seqs)
print(arr("BIG5_TO_GB", "u16", [int(r.get(s, "0"), 16) for s in seqs]))
seqs = ["%02x" % b for b in range(256)]
r = conv("IBM420//", "IBM1008//", seqs)
print(arr("IBM1008_TO_420", "u8", [int(r.get(s, "0"), 16) for s in seqs], 16, "0x%02x"))
r = conv("IBM1008//", "IBM420//", seqs)
print(arr("IBM420_TO_1008", "u8", [int(r.get(s, "0"), 16) for s in seqs], 16, "0x%02x"))
