#!/usr/bin/env python3
import glob, os, re, subprocess, sys, tempfile

GCONV = "/usr/lib64/gconv"
HERE = os.path.dirname(os.path.abspath(__file__))

SPECIAL = {
    "ISO-10646/UCS4/": 0, "UCS-4LE//": 1, "ISO-10646/UTF8/": 2, "ISO-10646/UCS2/": 3, "UNICODEBIG//": 4,
    "ANSI_X3.4-1968//": 5, "UTF-16//": 6, "UTF-16LE//": 7, "UTF-16BE//": 8, "UTF-32//": 9,
    "UTF-32LE//": 10, "UTF-32BE//": 11, "UNICODE//": 12, "UTF-7//": 13, "UTF-7-IMAP//": 14, "INTERNAL": 15,
    "EUC-KR//": 16, "EUC-CN//": 17, "EUC-JP//": 18, "UHC//": 19, "GBK//": 20, "SJIS//": 21,
    "CP932//": 22, "BIG5//": 23, "JOHAB//": 24, "EUC-TW//": 25, "GB18030//": 26,
    "EUC-JP-MS//": 27, "ISO_6937//": 28, "ISO_6937-2//": 29, "T.61-8BIT//": 30, "ANSI_X3.110//": 31, "IBM932//": 32, "IBM943//": 33,
    "ISO-2022-JP//": 40, "ISO-2022-JP-2//": 41, "ISO-2022-KR//": 42, "ISO-2022-CN//": 43, "BIG5HKSCS//": 44, "ISO-2022-CN-EXT//": 63, "TSCII//": 64,
    "CP1255//": 45, "CP1258//": 46, "TCVN5712-1//": 47,
    "IBM930//": 48, "IBM933//": 49, "IBM935//": 50, "IBM937//": 51, "IBM939//": 52,
    "IBM1364//": 53, "IBM1371//": 54, "IBM1388//": 55, "IBM1390//": 56, "IBM1399//": 57,
    "EUC-JISX0213//": 60, "SHIFT_JISX0213//": 61, "ISO-2022-JP-3//": 62,
}
BUILTIN_ALIASES = [
    ("UCS4//", "ISO-10646/UCS4/"), ("UCS-4//", "ISO-10646/UCS4/"), ("UCS-4BE//", "ISO-10646/UCS4/"), ("CSUCS4//", "ISO-10646/UCS4/"),
    ("ISO-10646//", "ISO-10646/UCS4/"), ("10646-1:1993//", "ISO-10646/UCS4/"), ("10646-1:1993/UCS4/", "ISO-10646/UCS4/"),
    ("OSF00010104//", "ISO-10646/UCS4/"), ("OSF00010105//", "ISO-10646/UCS4/"), ("OSF00010106//", "ISO-10646/UCS4/"),
    ("WCHAR_T//", "INTERNAL"),
    ("UTF8//", "ISO-10646/UTF8/"), ("UTF-8//", "ISO-10646/UTF8/"), ("ISO-IR-193//", "ISO-10646/UTF8/"),
    ("OSF05010001//", "ISO-10646/UTF8/"), ("ISO-10646/UTF-8/", "ISO-10646/UTF8/"),
    ("UCS2//", "ISO-10646/UCS2/"), ("UCS-2//", "ISO-10646/UCS2/"), ("OSF00010100//", "ISO-10646/UCS2/"),
    ("OSF00010101//", "ISO-10646/UCS2/"), ("OSF00010102//", "ISO-10646/UCS2/"),
    ("UNICODELITTLE//", "ISO-10646/UCS2/"), ("UCS-2LE//", "ISO-10646/UCS2/"), ("UCS-2BE//", "UNICODEBIG//"),
    ("ANSI_X3.4//", "ANSI_X3.4-1968//"), ("ISO-IR-6//", "ANSI_X3.4-1968//"), ("ANSI_X3.4-1986//", "ANSI_X3.4-1968//"),
    ("ISO_646.IRV:1991//", "ANSI_X3.4-1968//"), ("ASCII//", "ANSI_X3.4-1968//"), ("ISO646-US//", "ANSI_X3.4-1968//"),
    ("US-ASCII//", "ANSI_X3.4-1968//"), ("US//", "ANSI_X3.4-1968//"), ("IBM367//", "ANSI_X3.4-1968//"),
    ("CP367//", "ANSI_X3.4-1968//"), ("CSASCII//", "ANSI_X3.4-1968//"), ("OSF00010020//", "ANSI_X3.4-1968//"),
]

def read_conf():
    aliases, charsets = {}, []
    files = [GCONV + "/gconv-modules"] + sorted(glob.glob(GCONV + "/gconv-modules.d/*.conf"))
    for f in files:
        for line in open(f):
            p = line.split("#")[0].split()
            if not p: continue
            if p[0] == "alias":
                aliases[p[1].upper()] = p[2].upper()
            elif p[0] == "module":
                a, b = p[1].upper(), p[2].upper()
                if a != "INTERNAL" and b == "INTERNAL" and a not in charsets: charsets.append(a)
                elif b != "INTERNAL" and a == "INTERNAL" and b not in charsets: charsets.append(b)
    return aliases, charsets

def canon(name, aliases):
    seen = 0
    while name in aliases and seen < 10:
        name = aliases[name]; seen += 1
    return name

def probe(names, exe):
    out = subprocess.check_output([exe] + names).decode().split("\n")
    res, other, cur = {}, {}, None
    for line in out:
        p = line.split()
        if not p: continue
        if p[0] == "SIMPLE":
            cur = p[1]; res[cur] = ([], [])
        elif p[0] == "D": res[cur][0].append(int(p[1]))
        elif p[0] == "E": res[cur][1].append((int(p[1]) << 8) | int(p[2]))
        elif p[0] == "OTHER": other[p[1]] = p[2] if len(p) > 2 else ""
    return res, other

def ident_name(name):
    return re.sub(r"[^A-Z0-9]", "_", name.rstrip("/").upper())

def main():
    aliases, charsets = read_conf()
    for k, v in BUILTIN_ALIASES: aliases[k] = v
    with tempfile.TemporaryDirectory() as d:
        exe = os.path.join(d, "sbprobe")
        subprocess.check_call(["gcc", "-O1", "-w", os.path.join(HERE, "sbprobe.c"), "-o", exe])
        cand = [c for c in charsets if c not in SPECIAL and canon(c, aliases) == c]
        res, other = probe(cand, exe)
    sb_names = sorted(res)
    meta = {}
    sb_index = {n: i for i, n in enumerate(sb_names)}
    print("// Generated by tools/gen_charsets.py from the host's gconv configuration and iconv; do not edit.")
    print("use crate::unicode::Sb;\n")
    total_blocks = 0
    for n in sb_names:
        dec, encl = res[n]
        enc = {e >> 8: e & 255 for e in encl}
        blocks, hi, zero = [], [0] * 256, []
        for cp in sorted(enc):
            if cp >= 0x10000: continue
            if enc[cp] == 0:
                zero.append(cp); continue
            h = cp >> 8
            if hi[h] == 0:
                blocks.append([0] * 256); hi[h] = len(blocks)
            blocks[hi[h] - 1][cp & 255] = enc[cp]
        ident = 0
        while ident < 256 and enc.get(ident) == ident: ident += 1
        dec_ident = 0
        while dec_ident < 256 and dec[dec_ident] == dec_ident: dec_ident += 1
        total_blocks += len(blocks)
        print("static D_%s: [u16; 256] = [" % ident_name(n))
        for i in range(0, 256, 16): print("    " + ", ".join("0x%04x" % (0xffff if x < 0 else x) for x in dec[i:i+16]) + ",")
        print("];")
        print("static H_%s: [u8; 256] = [" % ident_name(n))
        for i in range(0, 256, 32): print("    " + ", ".join("%d" % x for x in hi[i:i+32]) + ",")
        print("];")
        print("static B_%s: [[u8; 256]; %d] = [" % (ident_name(n), len(blocks)))
        for b in blocks:
            print("    [")
            for i in range(0, 256, 32): print("        " + ", ".join("%d" % x for x in b[i:i+32]) + ",")
            print("    ],")
        print("];")
        print("static Z_%s: [u16; %d] = [%s];" % (ident_name(n), len(zero), ", ".join("0x%x" % z for z in zero)))
        meta[n] = (ident, dec_ident)
    print("\npub static SBS: [Sb; %d] = [" % len(sb_names))
    for n in sb_names:
        i = ident_name(n)
        print('    Sb { name: "%s", dec: &D_%s, hi: &H_%s, blocks: &B_%s, zero: &Z_%s, ident: %d, dec_ident: %d },' % (n.rstrip("/"), i, i, i, i, meta[n][0], meta[n][1]))
    print("];\n")
    table = {}
    def code_of(c):
        if c in SPECIAL: return 0x8000 + SPECIAL[c]
        if c in sb_index: return sb_index[c]
        return None
    allnames = set(aliases) | set(charsets) | set(SPECIAL)
    for n in allnames:
        c = canon(n, aliases)
        code = code_of(c)
        if code is not None: table[n] = code
    items = sorted(table.items())
    print("/// Every name (as normalised by `names::strip`) with its charset code: an index into `SBS`, or\n/// 0x8000 + the number of a hand-written charset.")
    print("pub static ALIASES: [(&str, u16); %d] = [" % len(items))
    for k, v in items: print('    ("%s", 0x%x),' % (k, v))
    print("];")
    print("\n/// (code, name) of the hand-written charsets, sorted by code.")
    print("pub static SPECIAL_NAMES: [(u8, &str); %d] = [" % len(SPECIAL))
    inv = sorted(SPECIAL.items(), key=lambda kv: kv[1])
    display = {"ISO-10646/UCS4/": "UCS-4", "ISO-10646/UTF8/": "UTF-8", "ISO-10646/UCS2/": "UCS-2", "UNICODEBIG//": "UCS-2BE"}
    for k, v in inv: print('    (%d, "%s"),' % (v, display.get(k, k.rstrip("/"))))
    print("];")
    sys.stderr.write("single-byte tables: %d\nnot simple (%d): %s\n" % (len(sb_names), len(other), " ".join(sorted(k.rstrip('/') for k in other))))
    sys.stderr.write("table bytes: dec %d, encode index %d (%d blocks)\n" % (len(sb_names) * 512, total_blocks * 256 + len(sb_names) * 256, total_blocks))

main()
