#!/usr/bin/env python3
import os, subprocess, sys, tempfile

C_SRC = r"""
#define _GNU_SOURCE
#include <langinfo.h>
#include <stdio.h>
#include <stdint.h>
#define W(i) ((uint32_t)(uintptr_t)nl_langinfo(i))
int main(void) {
    uint32_t n = W(_NL_CTYPE_TRANSLIT_TAB_SIZE);
    uint32_t *fi = (uint32_t *)nl_langinfo(_NL_CTYPE_TRANSLIT_FROM_IDX);
    uint32_t *ft = (uint32_t *)nl_langinfo(_NL_CTYPE_TRANSLIT_FROM_TBL);
    uint32_t *ti = (uint32_t *)nl_langinfo(_NL_CTYPE_TRANSLIT_TO_IDX);
    uint32_t *tt = (uint32_t *)nl_langinfo(_NL_CTYPE_TRANSLIT_TO_TBL);
    uint32_t dl = W(_NL_CTYPE_TRANSLIT_DEFAULT_MISSING_LEN);
    uint32_t *dm = (uint32_t *)nl_langinfo(_NL_CTYPE_TRANSLIT_DEFAULT_MISSING);
    if (W(_NL_CTYPE_TRANSLIT_IGNORE_LEN) != 0) { fprintf(stderr, "ignore ranges present\n"); return 1; }
    printf("N %u\n", n);
    /* from table length: up to the NUL of the last entry */
    uint32_t fl = fi[n - 1]; while (ft[fl]) fl++; fl++;
    uint32_t tl = ti[n - 1]; while (!(tt[tl] == 0 && tt[tl + 1] == 0)) tl++; tl += 2;
    printf("FL %u\nTL %u\nDL %u\n", fl, tl, dl);
    for (uint32_t i = 0; i < n; i++) printf("FI %u\n", fi[i]);
    for (uint32_t i = 0; i < fl; i++) printf("FT %u\n", ft[i]);
    for (uint32_t i = 0; i < n; i++) printf("TI %u\n", ti[i]);
    for (uint32_t i = 0; i < tl; i++) printf("TT %u\n", tt[i]);
    for (uint32_t i = 0; i < dl; i++) printf("DM %u\n", dm[i]);
    return 0;
}
"""

def main():
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "t.c"); exe = os.path.join(d, "t")
        open(src, "w").write(C_SRC)
        subprocess.check_call(["gcc", "-O1", "-w", src, "-o", exe])
        out = subprocess.check_output([exe]).decode().split("\n")
    vals = {k: [] for k in ("FI", "FT", "TI", "TT", "DM")}
    for line in out:
        p = line.split()
        if len(p) == 2 and p[0] in vals:
            vals[p[0]].append(int(p[1]))
    def arr(name, ty, v):
        s = "pub static %s: [%s; %d] = [\n" % (name, ty, len(v))
        for i in range(0, len(v), 16):
            s += "    " + ", ".join("0x%x" % x for x in v[i:i+16]) + ",\n"
        return s + "];\n"
    print("// Generated by tools/gen_translit.py from the host glibc's C locale; do not edit.")
    print(arr("FROM_IDX", "u16", vals["FI"]))
    print(arr("FROM_TBL", "u32", vals["FT"]))
    print(arr("TO_IDX", "u16", vals["TI"]))
    print(arr("TO_TBL", "u32", vals["TT"]))
    print(arr("DEFAULT_MISSING", "u32", vals["DM"]))

main()
